### ISSUE TITLE
Proposal: Allow CustomElements and AttachedBehaviors to expose API on Elements

### ISSUE THREAD

**Issue by RichiCoder1** [aurelia/templating#10]
To sum:
```javascript
import {Behavior} from 'aurelia-templating';

export class ExampleAttachedBehavioer {
    static metadata() {
        return Behavior
            .attachedBehavior("example")
            .exposeClass("example");
    }

    static inject() { return [Element]; }

    constructor(element) {
        this.element = element;
    }

    doThing() {
        this.element.classList.add("thing");
    }

    undoThing() {
        this.element.classList.remove("thing");
    }
}
```
Usage:
```javascript
// ...stuff....
var elem = $("#myElement")[0];
elem.example.doThing();
```

**Comment by EisenbergEffect** [comment]
Love it love it love it. What if we name the api a bit different. LIke this `exposeAs("excample")` Thoughts?

**Comment by RichiCoder1** [comment]
I'm up for better names. Maybe even `exposeApi` or `exposeInterface` to make it clear what's being exposed.

Random thought: Allow a second parameter that is something like
```javascriptimport {Behavior} from 'aurelia-templating';

export class ExampleAttachedBehavioer {
    static metadata() {
        return Behavior
            .attachedBehavior("example")
            .exposeClass("example", "api");
    }

    static inject() { return [Element]; }

    constructor(element) {
        this.element = element;
    }

    private doThing() {
        this.element.classList.add("thing");
    }

    private undoThing() {
        this.element.classList.remove("thing");
    }

   get api() {
       return {
           doThing: this.doThing.bind(this),
           undoThing: this.undoThing.bind(this),
       };
   }
}
```
Though I may be overthinking at this point.

**Comment by EisenbergEffect** [comment]
That's an interesting idea. Need to think about it.

On Thu, Jan 29, 2015 at 4:33 PM, Richard Simpson <notifications@github.com>
wrote:

> I'm up for better names. Maybe even exposeApi or exposeInterface to make
> it clear what's being exposed.
>
> Random thought: Allow a second parameter that is something like
> ```javascriptimport {Behavior} from 'aurelia-templating';
>
> export class ExampleAttachedBehavioer {
> static metadata() {
> return Behavior
> .attachedBehavior("example")
> .exposeClass("example", "api");
> }
>
> static inject() { return [Element]; }
>
> constructor(element) {
>     this.element = element;
> }
>
> private doThing() {
>     this.element.classList.add("thing");
> }
>
> private undoThing() {
>     this.element.classList.remove("thing");
> }
>
> get api() {
> return {
> doThing: this.doThing.bind(this),
> undoThing: this.undoThing.bind(this),
> };
> }
> }
>
> Though I may be overthinking at this point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/templating/issues/10#issuecomment-72108571>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by RichiCoder1** [comment]
My thinking is that you man not always want to expose the custom behavior/element directly since it'll have a lot of element/specific items that aren't otherwise relevant to something publicly exposed but are necessary for Aurelia to do it's convention thing.

**Comment by EisenbergEffect** [comment]
Right. I think it's probably a good idea and probably not much more
difficult at all.

On Thu, Jan 29, 2015 at 4:38 PM, Richard Simpson <notifications@github.com>
wrote:

> My thinking is that you man not always want to expose the custom
> behavior/element directly since it'll have a lot of element/specific items
> that aren't otherwise relevant to something publicly exposed but are
> necessary for Aurelia to do it's convention thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/templating/issues/10#issuecomment-72109249>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by EisenbergEffect** [comment]
One thing we can do is...instead of letting them name it, we can just automatically surface it for each behavior based on the behavior name. Then, if they want to expose a special api, we can let them do that.

**Comment by EisenbergEffect** [comment]
Ok, I didn't add the custom api creation callback. I want to keep this simple for now. But, we will now automatically camel-case the name of the behavior and set that on the element. As an example, from the navigation skeleton, the `nav-bar` custom element now has a `navBar` property on it which is the instance of the custom class. This works automatically for all behaviors so they are now all accessible following the same pattern.

**Comment by RichiCoder1** [comment]
Cool. Do we want to add a separate item for adding a api creation callback and just stick it in the backlog?

**Comment by EisenbergEffect** [comment]
Let's wait until some actually needs it and asks for it ;)

**Comment by RichiCoder1** [comment]
I guess we can :P

**Comment by stoffeastrom** [comment]
This is awesome!
