### ISSUE TITLE
An 'include' custom element. (Possible enhancement)

### ISSUE THREAD

**Issue by csaloio** [aurelia/templating#101]
I think it would be handy to be able to refer to an external snippet of html from within a template for frequently used pieces of markup.

Something perhaps like:
```
<template>
   <div>Normal template markup....</div>
   <include path='./footer.html'/>
</template>
```

**Comment by EisenbergEffect** [comment]
You can do this today with compose.

`<compose view="./footer.html"></compose>`

Compose is very powerful and can choose arbitrary combinations of views,
view-models and models.

**Comment by csaloio** [comment]
I see. Sorry, I didn't realize compose could be used in that way. Looks great.
