### ISSUE TITLE
Add @callable decorator

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/templating#102]
For *custom attributes* it would be nice to be able to do

```
@customAttribute("some-behavior")
@callable({
  name: "someFunction",
  defaultFunction: function() {}
})
export class SomeBehavior {}

<div some-behavior="someFunction.call: whatever();"r></div>
```

Then I always know i have a function reference in my *custom attribute* and doesn't have to check if the function exists..

Thoughts?

**Comment by EisenbergEffect** [comment]
Hmm. So, for custom attributes, you want to be able to define a default value, basically. Is that correct? You can do that already with options attributes, just not with simple attributes. We could add that. Here's an example of what you can do today with options attributes:

```
@customAttribute("some-behavior")
export class SomeBehavior {
  @bindable foo = function(){};
  @bindable bar = 'some value';
}
```

So, you can provide the default. Here's what we could do for simple attributes:

```
@customAttribute({ name: "some-behavior", defaultValue: function(){} })
export class SomeBehavior {

}
```

We could provide a standard `noop` for use in this scenario as well:

```
@customAttribute("some-behavior")
export class SomeBehavior {
  @bindable foo = noop;
  @bindable bar = 'some value';
}
```

```
@customAttribute({ name: "some-behavior", defaultValue: noop })
export class SomeBehavior {

}
```

I'm trying not to introduce an additional concept if we don't have to. Thoughts on this?

**Comment by stoffeastrom** [comment]
@EisenbergEffect I have this but it will evaluate to a value not a function

```
@bindable({
  name: "moved",
  defaultValue: function() {}
})
```
if you don't bind it will be `undefined`. I thought that was as designed. Maybe I'm missing something but for my *custom attribute* I want to be able to have a optional function bind. Does that makes sense?

**Comment by stoffeastrom** [comment]
I just double checked. If I don't bind the move

```
<div my-custom-attribute="moved.call: someFunc();"></div>
```
It will throw an expection saying that moved is not a function.

**Comment by stoffeastrom** [comment]
Also if I do like this

```
@bindable({
  name: "allowDrag",
  defaultValue: function() { return false; }
})
```
Then this.allowDrag will be false not a function.

So I wonder if there is something to support this? How do we define a callable optional function for custom attribute?

**Comment by stoffeastrom** [comment]
Ok so I fiddled a bit more with this and as you say if I add a @bindable as a property initializer it works as expected. Is this as designed? Kind of weird that it works different.

**Comment by stoffeastrom** [comment]
I agree on not introducing additional concept! As long as we can support the different use cases in an understandable way.

**Comment by stoffeastrom** [comment]
Since I can achieve what I want I'm gonna close this.
