### ISSUE TITLE
Use ref attribute with Content element

### ISSUE THREAD

**Issue by shanonvl** [aurelia/templating#105]
I’m just playing around with `<content select=“…”>` and custom elements and have a 
question:

I'd like to use `ref` with `<content>`.. something like the below example:

Custom element in parent vm's html template:
```
<template> 
...
<custom-el custom-el.ref="customElViewModel">
  <header>
  </header>
  <main>
  </main>
</custom-el>
...
</template>
```

Binding `customElViewModel` to parent view model works great, but I'm wondering if 
it's possible to bind the sub-elements to the custom element's view model in the same way.

e.g. in `custom-el`'s template, I have something like this:
```
<template>
  <div>
    <content ref="header" select="header"></content>
  </div>
  <div>
    <content ref="body" select="main"></content>
  </div>  
</template>
```

I was hoping that the `ref` would maybe bind those properties to the `custom-el` view model, but it didn't seem to work.  Note that if I use `ref` on the top-level `header` or `main` elements, that it *does* bind correctly to the parent vm.

I hope this makes sense.   This isn't a big deal for me as there are other ways to update the content.  I'm really just wondering if `ref` should work on `<content>` as described above.  Thanks!

**Comment by shanonvl** [comment]
Another workaround would be to put the `ref` on the wrapping `<div>`'s and walk down... maybe this is a better idea as I believe this is selecting the *content* in `header` and `main` vs. the node?

**Comment by EisenbergEffect** [comment]
I'm not entirely following what you are trying to do. However, you can't use ref on `content` elements.

**Comment by shanonvl** [comment]
:)  Sorry for the confusing use case.   Thanks for confirming no ref on `content` elements.
