### ISSUE TITLE
Possible for a CustomElement to manipulate a template part?

### ISSUE THREAD

**Issue by csaloio** [aurelia/templating#106]
From within a CustomElement I would like to be able to manipulate a template part provided by the consumer of the CustomElement. For example I'd like to be able to add classes to the elements within the template part so the consumer doesn't have to.

Anyway to accomplish this?

**Comment by csaloio** [comment]
One way I've manged to do this is by specifying `@skipContentProcessing` on the customer element, modifying the contained template and then injecting/compiling back into the custom element at the correct location during bind().

Would this be the recommended way or is there a better way to go about it?

**Comment by kevmeister68** [comment]
It sounds like @processContent was designed for cases like this, so you might want to take a look at that. You can manipulate the content before the aurelia template compiler deals with it?

**Comment by jdanyow** [comment]
@csaloio are you still looking for a solution for this issue? If so, could you provide some more info about your use-case? I agree, manually compiling the template sounds a little heavy-handed.

**Comment by csaloio** [comment]
I haven't worked on this in some time, but the scenario was for a datagrid custom element that had user supplied columns. The consumer of the control specified each column like this: (syntax may be outdated now):

```
<cs-grid src.bind="rows" multiple cs-grid.ref="grid">
   <template replace-part="columns">
      <div h-label='ID' h-sort="id">${i.id}</div>
      <div h-label='Full Name'>${i.firstname + ' ' + i.lastname}</div>
   </template>
</cs-grid>
```
As the author of the grid control it is useful to be able to modify the `divs` specified by the consumer within the template part for example to add css classes so the consumer does't have to.

**Comment by EisenbergEffect** [comment]
You can accomplish this with the `processContent` hook.
