### ISSUE TITLE
Unable to remove event listener during detached()

### ISSUE THREAD

**Issue by csaloio** [aurelia/templating#107]
I have a CustomElement.
During attached() I create an `<object>`  (of type text/html) as a child of this CustomElement. I also add an event listener to the` <object>` like this:
```
obj.contentDocument.defaultView.addEventListener('resize', resizeListener);
```

Now I expected to be able to remove the resizeListener in detached() however by the time detached is called  `obj.contentDocument` is null.
Not sure if this will cause a memory leak or not. Anything earlier than detached I can use to remove this event listener?

**Comment by jdanyow** [comment]
You could try `unbind` instead of `detached`.  It would be nice to have a `detaching` hook though- @EisenbergEffect thoughts?

Another thing you could do is during attached, grab a reference to contentDocument.defaultView to enable calling removeEventListener in the detached method.

**Comment by csaloio** [comment]
Thank you for the suggestions. Unfortunately `unbind` has the same problem. 

I'm not sure I can grab a reference to defaultView very easily because it is not available at the time the object is created. I think it may 1st be available when its onload event runs. The code that I'm using to generate the object is outside my CustomElement, so while probably possible, it would be pretty awkward to get the reference back to my CustomElement when it finally becomes available.

**Comment by jdanyow** [comment]
>I have a CustomElement.
During attached() I create an `<object>`  (of type text/html) as a child of this CustomElement. I also add an event listener to the` <object>` like this:
```javascript
obj.contentDocument.defaultView.addEventListener('resize', resizeListener);
```

-------------------
Could you add another couple of lines that do this:
```javascript
var defaultView = obj.contentDocument.defaultView;
this.unsubscribeResize = () => defaultView.removeEventListener('resize', resizeListener);
```

Then in detached you could do this:
```javascript
detached() {
  if (this.unsubscribeResize) {
    this.unsubscribeResize();
    this.unsubscribeResize = null;
  }
}
```
