### ISSUE TITLE
Select binding and templating values

### ISSUE THREAD

**Issue by shanonvl** [aurelia/templating#108]
See [this plunker](http://embed.plnkr.co/H9Hdf8Y5Fu8yCPwlyquG/preview) for an example, albeit contrived, which illustrates my question.

I'd like to have a `terms` array in the view model which is bound to a `repeat.for` in the view.   Each `term` has dependent values e.g. `term.favoriteSubTitle` is dependent on the selection for `term.item`.  The number of terms is dynamic which is why I have the "Add Term" button.  

Right above the "Add Term" button there are two JSON outputs of *the same object* - one via templating and one via direct reference ( using `setInterval` to update the value ).  

While the binding system is working correctly ( as evidenced by the `setInterval` output ), I'm hitting the following issues and wondering if I'm doing something wrong / this is unsupported / there's a bug.

1.  The templating value `${terms | json}` does not update when `terms` is changed.

2.  The `termsChanged` listener is not fired ( I don't see the console.log ) when any of the following occurs:
    i.  "Add Term" clicked
    ii.  Any top-level selection is made ie. `terms[..].item` is changed
    ii.  Any secondary-level selection is made ie. `terms[..].favoriteSubTitle` is changed.
 
Please let me know if I can provide any other info.  Thanks!

**Comment by jdanyow** [comment]
The interpolation binding will be updated when the viewmodel's `terms` property changes (when a different array instance is assigned to the property).  Mutating the array instance (via `.push`) or mutating the objects within the array will not cause the termsChanged handler to be invoked or the interpolation binding to update.

As a workaround you could change the addTerm method to something like this:
```javascript
addTerm() {
  var terms = this.terms.slice(0);
  terms.push({});
  this.terms = terms;
}
```

**Comment by EisenbergEffect** [comment]
I think we should try to find a solution to this in the long term...but need to wait until after the binding refactoring. Perhaps when we detect that there's an array input to a filter, we re-run the filter when the array's members change. Not sure, but we can address it after the core improvements.

**Comment by akircher** [comment]
+1
