### ISSUE TITLE
Binding to datetime attribute of <time>

### ISSUE THREAD

**Issue by shanonvl** [aurelia/templating#109]
[Here's the example](http://embed.plnkr.co/X58jdmr1L7t6AbFU47YC/preview) on Plunker.

```html
<!-- iso is simple date.toISOString() -->
<time datetime="${timestamp | iso}" data-foo="${timestamp | iso}" ref="timestampEl">
 ${timestamp | iso}
</time>
```
results in the following markup:
```html
<time datetime="${timestamp | iso}" data-foo="2015-06-23T22:08:05.549Z" 
      ref="timestampEl" class="au-target">2015-06-23T22:08:05.549Z</time>
```
- The `datetime` attribute is bound directly to the `time` element vs. set as an attribute.   Other attributes e.g. `foo`, `bar` also behave in this manner.
- `data-*` attributes work properly.

Please let me know if I can provide any other info.  Thanks!

**Comment by EisenbergEffect** [comment]
@jdanyow I'm not sure, but I'm wondering if there's a custom mapping we need here. Maybe a difference in casing from the attribute to the property?

**Comment by jdanyow** [comment]
@EisenbergEffect I think you're right:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLTimeElement/dateTime

Chrome and Internet Explorer don't have `HTMLTimeElement` support yet so adding the map will only work in Firefox.

@shanonvl - you can add the attribute mapping right away, without waiting for a new build of aurelia templating-binding by doing this:

```javascript
import {BindingLanguage} from 'aurelia-framework';  // <--- this

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging();

  aurelia.start().then(a => {
    var language = a.container.get(BindingLanguage);  // <--- and this
    language.attributeMap.datetime = 'dateTime';      // <--- and this
    a.setRoot();
  });
}
```

**Comment by shanonvl** [comment]
Thanks, guys!  :+1:

**Comment by shanonvl** [comment]
@jdanyow, that actually didn't work -- [see updated Plunker](http://embed.plnkr.co/X58jdmr1L7t6AbFU47YC) with your recommended changes in [main.js](http://embed.plnkr.co/X58jdmr1L7t6AbFU47YC/main.js).

**Comment by jdanyow** [comment]
@shanonvl did you see my comment about Chrome and IE?  They don't support the DOM interface for the time element (HTMLTimeElement) so adding the attribute map will only work in Firefox.

Using firefox, with the main.js changes described above, you can do this:

```html
<time datetime.bind="test">hello world</time>
```
```javascript
export class App {
  test = '2013-12-25 11:12';
}
```

**Comment by shanonvl** [comment]
@jdanyow gotcha, I misunderstood before.   Please go ahead and close this unless you'd like to use it for tracking the aurelia-templating-binding update... Thanks again.

**Comment by tjad** [comment]
I am wondering about the status of this issue as I seem to still be running into the problem a year later. Yes I am using chrome browser and yes it does work in firefox.

Example:
```{html}
<time datetime="${article.published_at}"> ${article.published_at} </time>
```

Yields:
```{html}
<time class="au-target" au-target-id="21">19th July 2016</time>
```
