### ISSUE TITLE
Attached Behavior in Custom Element gets Shadow DOM injected

### ISSUE THREAD

**Issue by tyrsius** [aurelia/templating#11]
So this appears to be happening only to a Custom Element inside another Custom Element. The top level is having styles applied just fine, but the inner element has a `show` behavior on it, and as you can see it only gets applied to the shadow DOM.

![image](https://cloud.githubusercontent.com/assets/1187432/5971366/c8daed06-a7f8-11e4-9573-7f3f792e739f.png)

Debugging confirms that the Attached Behavior receives the shadow DOM element, not the light dom one. This is done using the Tab Control / Tab Item that @EisenbergEffect shared in Gitter.

**Comment by EisenbergEffect** [comment]
I'm not sure I entirely understand what is happening. What element was the attached behavior put on in code? What element did it get injected? What element did you expect to get injected?

**Comment by tyrsius** [comment]
Here is the tab-control
```lang-javascript
<template>
  <ul class="nav nav-tabs">
    <li repeat.for="item of items" class="${item.isSelected ? 'active' : ''}">
      <a href="#" click.trigger="$parent.selectItem(item)">${item.title}</a>
    </li>
  </ul>

  <content select="tab-item"></content>
</template>
```

Here is the tab-item
```lang-javascript

<template>
  <div class="tab-pane" show.bind="isSelected">
    <content></content>
  </div>
</template>
```

This *should* produce a tab-item container that hides itself when `isSelected` is false. The element that is injected into the `show` behavior is the element inside the shadow DOM, and you can see the hide class being applied to it.

Although, I am now realizing another problem might be at work. I was so focused on debugging `show` that I just noticed that there is a `content` tag in the light DOM from the tab-control. That shouldn't be there, it should have been replaced by the tab-item. I need to go back and look at that tonight.

**Comment by EisenbergEffect** [comment]
Content tab should be there unless the tab control itself uses shadow dom.

**Comment by EisenbergEffect** [comment]
The attached behavior appears to work correctly to me. The attached behavior is on the div...therefore it is applied to the div.

**Comment by tyrsius** [comment]
Perhaps I misunderstood. When you introduced this in gitter you said that Aurelia uses the shadow DOM spec for custom elements, which should use the `content` element as a transclusion point. The `content` tab isn't replaced? Here is how I am using it.

```
 <tab-control>
      <tab-item repeat.for="tab of tabs" title="${tab.header}">
        <h4>${tab.header} Content</h4>
        Things and stuff
       
      </tab-item>
    </tab-control>
```

**Comment by EisenbergEffect** [comment]
When we have our shadow dom fallback, the content tag becomes an "anchor" for the transclusion point. I can't remember what code I gave you for sure, but I think only one of the elements was using actual shadow dom. So, that would only remove the content tag if you were in Chrome or using the Polymer polfill for shadow dom.

**Comment by tyrsius** [comment]
I am using Chrome

**Comment by EisenbergEffect** [comment]
Ok, But are both custom elements set up to use shadow dom?

On Fri, Jan 30, 2015 at 12:04 PM, Timothy Moran <notifications@github.com>
wrote:

> I am using Chrome
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/templating/issues/11#issuecomment-72233876>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by tyrsius** [comment]
I don't think so, because I don't know what setup that requires. You can see the full code for them [here](https://github.com/tyrsius/tuner/tree/master/src/tabs)

**Comment by tyrsius** [comment]
Nevermind, it looks like the tab-item is setup to use shadow dom. I missed that. I bet it will work if i take that off. I'll try that tonight. This is probably a non-issue

**Comment by EisenbergEffect** [comment]
Yep. Notice that TabItem says useShadowDOM in metadata.


On Fri, Jan 30, 2015 at 12:06 PM, Timothy Moran <notifications@github.com>
wrote:

> I don't think so, because I don't know what setup that requires. You can
> see the full code for them here
> <https://github.com/tyrsius/tuner/tree/master/src/tabs>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/templating/issues/11#issuecomment-72234195>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by tyrsius** [comment]
Yep, removing shadowDom from the tab-item fixed the problem. Sorry.
