### ISSUE TITLE
Cannot access view-model property in repeat for

### ISSUE THREAD

**Issue by jw56578** [aurelia/templating#110]
Plunkr here 
http://plnkr.co/edit/7LzCTr7BaH42KGnHXByK?p=preview
Should you be able to use a view-model computed property in the repeat for. It does not render it.

**Comment by jdanyow** [comment]
change:
```html
<li repeat.for="row of 5" >
  ${fullName}
</li>
```

to:
```html
<li repeat.for="row of 5" >
  ${$parent.fullName}
</li>
```

In a future release, `$parent` will not be needed because binding scopes will work like they do in js.

Please hit up the gitter with questions like these, there are a ton of community members ready to help you out:  https://gitter.im/Aurelia/Discuss
