### ISSUE TITLE
add extra animation events for the `animate` method

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating#111]
some events should be added for the `animate` method of the base animator.

- `animation:animate:begin`
- `animation:animate:active`
- `animation:animate:done`

**Comment by zewa666** [comment]
as discussed with you @Aaike I've added the sequence events, along the missing timeout events for add/removeClass as well. All the other discussed events can be added later as we need them

**Comment by EisenbergEffect** [comment]
It's in now :)
