### ISSUE TITLE
repeat.for with Value Converters

### ISSUE THREAD

**Issue by shanonvl** [aurelia/templating#113]
[Here's the plunker](http://embed.plnkr.co/tZCLEMIPIDzE1V0bwEHh/preview) which has a single view model, App, with the following template:
```html
<!-- max length is a simple value converter which slices when > passed val -->
<div repeat.for="i of items | maxLength: 5">${i}</div>
```
When App is constructed, `items` is `[]` and a `setInterval` appends 1..10 to `items` every 1.5 seconds.   

Expected Result after 15 seconds:
```
1
2
3
4
5
```

Actual:
```
1
2
3
4
5
6
7
8
9
10
```

After inserting a breakpoint in the `toView` of the value converter, I noticed that it's only called once, when the template is initially rendered.

**NOTE** this same value converter works correctly when using on a bound attribute e.g. `foo.bind="items | maxLength:5"`.

Please let me know if I can provide more info.  Thanks!

**Comment by jdanyow** [comment]
This is another variation of https://github.com/aurelia/templating/issues/108

The `repeat` is observing the array instance returned by the `items | maxLength: 5` expression.  The instance is never replaced with a new instance so the converter is never re-evaluated.  In other words no property-change occurs.  Mutating the array via `.push` doesn't cause a property change.

The same workaround described in https://github.com/aurelia/templating/issues/108 could be used.

**Comment by shanonvl** [comment]
Thanks, @jdanyow.  Applying the workaround here fixed the issue.

**Comment by jdanyow** [comment]
nice- hopefully we can figure something out to make this more intuitive without sacrificing perf
