### ISSUE TITLE
html attribute interpolation

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating#114]
Using interpolation in an ad-hoc html attribute has a confusing result in the current build.  

Example:

```html
<span ref="el" foo="${bar}"></span>
```
```javascript
export class App {
  bar = 'xyz';

  attached() {
    console.log(this.el.foo); // "xyz"
    console.log(this.el.getAttribute('foo')); // "${bar}"
  }
}
```

To make things more consistent with `.bind`ing an html attribute we are removing the interpolated attribute when compiling the template:  https://github.com/jdanyow/templating/commit/cbff88687c4328b78865d755f4f95652218bf92c

The result of this change can be seen in scenario 2, under the "getAttribute" column:

![result](http://i.imgur.com/glfW84g.png)

Here's a plunkr demonstrating the current behavior:
http://embed.plnkr.co/oY5KNb91ghaaRZDjYhgW/preview

Code for the table of test cases above:
```javascript
import 'bootstrap/css/bootstrap.css!';

export class App {
  bar = 'xyz';
}

export class QuoteValueConverter {
  toView(value) {
    if (value === null) return 'null';
    if (value === undefined) return 'undefined';
    return `"${value}"`;
  }
}
```
```html
<template>
  <div class="container">
    <span  ref="a" style="display: none" foo.bind="bar"               ></span>
    <span  ref="b" style="display: none" foo="${bar}"                 ></span>
    <label ref="c" style="display: none" for="${bar}"                 ></label>
    <input ref="d" style="display: none" id="${bar}"                  ></input>
    <span  ref="e" style="display: none" class="test ${bar} testing"  ></span>
    <span  ref="f" style="display: none" data-foo="${bar}"            ></span>

    <h3>Result of binding to view-model's "bar" property (bar==="xyz")</h3>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Element Type</th>
          <th>Binding Expression</th>
          <th>getAttribute</th>
          <th>Property Access</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td><code>span</code></td>
          <td><code>foo.bind="bar"</code></td>
          <td><code>el.getAttribute('foo')===${a.getAttribute('foo')|quote}</code></td>
          <td><code>el.foo===${a.foo|quote}</code></td>
        </tr>
        <tr>
          <td>2</td>
          <td><code>span</code></td>
          <td><code>foo="\${bar}"</code></td>
          <td><code>el.getAttribute('foo')===${b.getAttribute('foo')|quote}</code></td>
          <td><code>el.foo===${b.foo|quote}</code></td>
        </tr>
        <tr>
          <td>3</td>
          <td><code>label</code></td>
          <td><code>for="\${bar}"</code></td>
          <td><code>el.getAttribute('for')===${c.getAttribute('for')|quote}</code></td>
          <td><code>el.htmlFor===${c.htmlFor|quote}</code></td>
        </tr>
        <tr>
          <td>4</td>
          <td><code>input</code></td>
          <td><code>id="\${bar}"</code></td>
          <td><code>el.getAttribute('id')===${d.getAttribute('id')|quote}</code></td>
          <td><code>el.id===${d.id|quote}</code></td>
        </tr>
        <tr>
          <td>5</td>
          <td><code>span</code></td>
          <td><code>class="test \${bar} testing"</code></td>
          <td><code>el.getAttribute('class')===${e.getAttribute('class')|quote}</code></td>
          <td><code>el.className===${e.className|quote}</code></td>
        </tr>
        <tr>
          <td>6</td>
          <td><code>span</code></td>
          <td><code>data-foo="\${bar}"</code></td>
          <td><code>el.getAttribute('data-foo')===<span textcontent.one-time="f.getAttribute('data-foo')|quote"></span></code></td>
          <td><code>f['data-foo']===<span textcontent.one-time="f['data-foo']|quote"></span></code></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
```

**Comment by jdanyow** [comment]
I'm not 100% sure this is the right approach.  Maybe interpolation binding expressions (`foo="${bar}"`) should be the method for binding html attributes (equivalent of `Element.setAttribute`) and regular binding expressions (`foo.bind="bar"`) should remain the syntax for binding DOM properties or creating new "ad-hoc" properties.

**Comment by EisenbergEffect** [comment]
One problem with switching that approach is that there is no equivalent for Aurelia's behaviors. Both standard bindings and interpolations would need to go through the property. (because it's a plain class that is bound) This would be a huge change in the binding system. I prefer for the binding system to use properties in all cases except where the DOM itself is broken and setAttribute is required. Is there some reason why we would need to sync the change back to the attribute? Note that some HTML properties sync to the attribute automatically and some do not. The DOM is not consistent on this point.

**Comment by jdanyow** [comment]
Makes sense- your comment in the gitter cleared things up for me, posting it here in case I need to refer back to it:

>Attributes are treated as initializers only. After template compilation, the binding system should use only DOM properties. The only exception would be for places where the DOM is broken/inconsisent, in which case we are forced to use get/setAttribute.

Closing this.
