### ISSUE TITLE
Extending existing html elements

### ISSUE THREAD

**Issue by levan1993** [aurelia/templating#116]
Hi, is it possible to extend existing elements like input, select ?

**Comment by EisenbergEffect** [comment]
Unfortunately no. Even with web components, the method of accomplishing that is still being debated.

**Comment by EisenbergEffect** [comment]
Consider wrapping them in a custom element or creating a custom attribute that attaches additional behavior to the built-in element. Something like this

`<input type="checkbox" custom-checkbox>` where `custom-checkbox` is your custom attribute that adds behavior to the input.

**Comment by levan1993** [comment]
If I create custom element for example <custom-checkbox ckecked="..." name="...">
how can I access these attributes in template to assign them to <input type="checkbox" checked="..." name="..."> ?
