### ISSUE TITLE
Expression in img src attribute

### ISSUE THREAD

**Issue by pszybiak** [aurelia/templating#119]
I have a problem with this code:

```
<img src="images/${type == 'Bug' ? 'Bug' : 'Task'}.png"/>
```

On console i have an error:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/images/$%7Btype%20==%20'Bug'%20?%20%27Bug%27%20:%20%27Task%27}.png
```
but rendered view looks fine. Maybe it's something similar to #99?

**Comment by jdanyow** [comment]
It's a bug caused by #99, but I don't think you want to use interpolation in an img src in case the browser eagerly loads the image prior to the binding evaluation- see https://github.com/aurelia/templating-binding/issues/47

try this instead:

```html
<img src.bind="'images/' + (type === 'Bug' ? 'Bug' : 'Task') + '.png'" />
```

**Comment by pszybiak** [comment]
Thanks for quick answer.
Now now everything works fine.
