### ISSUE TITLE
Bug using multiple instances of an custom element with different template parts

### ISSUE THREAD

**Issue by andrevlins** [aurelia/templating#120]
In the scenario bellow the two instances of `my-element` gets rendered using the later `template replace-part`declaration, resulting in this case in two lists with `red` as background color instead of one blue and one red.

fork with repro based on skeleton: https://github.com/andrevlins/skeleton-navigation

```html
<template>
	<require from="./my-element"></require>

	<h5>First my-element</h5>
	<my-element items.bind="blueItems">
		<template replace-part="title">
			<div style="background-color: blue;">
				${item}
			</div>
		</template>
	</my-element>

	<h5>Second my-element</h5>
	<my-element items.bind="redItems">
		<template replace-part="title">
			<div style="background-color: red;">
				${item}
			</div>
		</template>
	</my-element>

</template>
```

**Comment by andrevlins** [comment]
@EisenbergEffect this is the right way of make a repro on skeleton? doing a fork?
See some gitters using plunker, whats the best way?

**Comment by leosbrf** [comment]
@andrevlins , I´ve been trying a similar approach using `replace-part` but I stuck with the same problem. Any advances?

**Comment by andrevlins** [comment]
@leosbrf no luck with this yet but I think it will be handled now that Eisenberg is assigned, let's wait and see.

**Comment by EisenbergEffect** [comment]
Sorry for the delay on this. It's on my list for this week.

**Comment by EisenbergEffect** [comment]
Tracking down the issue now. It has to do specifically with repeaters that use replaceable parts... Normal parts replace just fine. Drilling in.

**Comment by EisenbergEffect** [comment]
The fix will go out in several patch releases tomorrow.
