### ISSUE TITLE
if.bind before repeat.for not working in chrome

### ISSUE THREAD

**Issue by ahallez** [aurelia/templating#123]
I noticed following behavior in Chrome.

I have a diff element with a repeat.for attribute and an if.bind attribute that uses the local variable created by the repeat.for.
When I add the if.bind attribute before the repeat.for it doesn't work in Chrome (allthough it works in Firefox). Putting the if.bind after the repeat.for solves the problem.

**Comment by EisenbergEffect** [comment]
Can you show me some sample html?

**Comment by ahallez** [comment]
Of course. I assembled a minimal example and discovered that it is even more strange.
This is my class file:
```javascript
export class Test {
    values = [1, 2, 3, 4];
}
```
My template:
```html
<template>
    <div if.bind="number == 2" repeat.for="number of values">
        <p>Test 1 : ${number}</p>
    </div>    
    <div repeat.for="number of values" if.bind="number == 2">
        <p>Test 2 : ${number}</p>
    </div>    
</template>
```
In Firefox this results in following output:
```html
<div>
    <p>Test 1 : 2</p>
</div>
```
In Chrome I get:
```html
<div>
    <p>Test 2 : 2</p>
</div>
```
The results are similar when I have only one of the divs in the template.

**Comment by ahallez** [comment]
BTW, In my application I avoided the issue by putting the repeat.for in a template tag.

**Comment by EisenbergEffect** [comment]
Ah. This makes sense. You cannot have more than one template controller on the same element. if and repeater are both template controllers. You need to nest them the same way you would in JS wither with the if inside the repeat or the repeat inside the if, depending on your scenario.

**Comment by mttmccb** [comment]
I have code like this but haven't experienced any bugs yet... would the solution be to move the if.bind or repeat.for into a template element ?
