### ISSUE TITLE
@bindable requires parameters in TypeScript.

### ISSUE THREAD

**Issue by Zoltu** [aurelia/templating#124]
https://github.com/aurelia/templating/blob/master/src/decorators.js#L60

The d.ts has a function like `export function bindable(nameOrConfigOrTarget: any, key: any, descriptor: any): any;`.  Unfortunately, this results in a compiler error if you try to do:
```ts
export class Foo {
	@bindable bar;
}
```
The problem is that the definition file function signature has 3 required arguments.  If they are supposed to be optional then it should look like this I believe:
```ts
export function bindable(nameOrConfigOrTarget?: any, key?: any, descriptor?: any): any;
```

Unfortunately, I don't know how to make it so the auto-generated d.ts knows the parameters are optional.  Also, I would not like it if every function had optional parameters for everything, so changing the auto-generator seems like the wrong approach.

I don't mind submitting a PR for this, I just don't know how to fix it.

**Comment by EisenbergEffect** [comment]
You can just change it in the ES6 source. The d.ts generator will understand that.
