### ISSUE TITLE
Templating engine gets confused by self-closing custom-element tags - should it?

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating#126]
The Aurelia templating engine screws up custom element substitutions if you use self-closing tags. For example, some dummy HTML I was playing around with:

<template>
<kdialog>
   <non-visual-element attrib="blah"/>
</kdialog>

<p>Some Text</p>
</template>

The templating engine will eliminate "Some Text" from the displayed content when a self-closing tag is used, but is fine if </non-visual-element> is used.

I know XHTML has particular rules on "void" elements that should use self-closing tags (eg. <br/>) but my question is whether custom elements should be subject to the same restrictions.

What is more concerning to me is that when the above situation occurs, it is extremely mysterious. There is no warning from Aurelia about mismatched tags.

I also found that it affected content selectors. For example, my kdialog.html file contained <content select="*"> and due to the self-closing tag, that "*" included elements all the way to the end of the template (eg. The <p>Some Text</p>) whereas when a conventional closing tag is used, it correctly only selected the <non-visual-element>tag.

**Comment by EisenbergEffect** [comment]
You are literally describing invalid HTML. There is no such thing as a self-closing custom HTML element. The only self-closing elements are those that are native built-ins, which are special cased by the HTML parser.
