### ISSUE TITLE
[FR] Imperative view creation?

### ISSUE THREAD

**Issue by gabor-farkas** [aurelia/templating#131]
Hi,
In some projects, imperative view creation can be more beneficial than html templates. With aurelia, if it would be possible to use js (typescript) to create the views, they would be more discoverable, compile-time checked and type-safe, including the binding expressions. Mithril is based on this concept for example. (I've summarized my point of view here https://medium.com/doctusoft-coding-style/benefits-of-imperative-type-safe-views-d9ca4707a48a)

Do you think it's possible in any way to hook into the template engine to make this possible with aurelia? (Somewhat the way JSF supports jsp, xhtml and imperative java code as well).

Thanks, Gábor

**Comment by EisenbergEffect** [comment]
Yes, it is possible. Every component is Aurelia is rendered by a view. What view to use is determined using a ViewStrategy. Most components use the ConventionalViewStrategy, but there are others that can be used instead, on a per component basis. You can even override what is used as the default. To integrate a system as you describe above, you would need to implement a custom ViewStrategy by inheriting and implementing the single method `loadViewFactory`. This would allow you to create a ViewFactory for the component in any way you desire, including loading a JS module that exported a custom model based on a view DSL, for example.
