### ISSUE TITLE
containerless composition fails in IE

### ISSUE THREAD

**Issue by arkon** [aurelia/templating#135]
When using `containerless` in a custom element, IE throws the following error:

```
TypeError: Assignment to read-only properties is not allowed in strict mode
```

This is due to the line

```JavaScript
anchor.attributes = element.attributes;
```

in the `makeElementIntoAnchor` method. If it's removed, everything works, but I'm not really sure why that line was there in the first place. `anchor` is a comment element, so why would you set any attributes in the first place? It doesn't even have an `attributes` field.

EDIT: seems related to https://github.com/aurelia/router/issues/162#issuecomment-122752504

**Comment by EisenbergEffect** [comment]
Fixed in 7764774cf6621d25a111759cbe1217dfae64812d
