### ISSUE TITLE
Failure in contentSelectorRemoveAll when using multiple views that are assigned to a single content selector

### ISSUE THREAD

**Issue by myellen42** [aurelia/templating#136]
I have a custom element with another custom element inside it using a repeat.for binding:
````html
<outer-component>
    <inner-component repeat.for="data of datasets"></inner-component>
</outer-component>
````
The template for this element uses a single component selector like this:
````html
<template>
    <content select="inner-component"></content>
</template>
````
When "datasets" in the ViewModel is first assigned everything works as expected, but when it is later updated with a new array of objects an exception is thrown from ViewSlot.contentSelectorRemoveAll().  The problem appears to be here:
````javascript
    for(i = 0; i < ii; ++i){
      view = children[i];

      for(j = 0; j < jj; ++j){
        contentSelectors[j].removeAt(i, view.fragment);
      }
    }
````
And ContentSelector.removeAt() looks like this:
````javascript
  removeAt(index, fragment){
    var group = this.groups[index],
        i, ii;
    [snip]
    this.groups.splice(index, 1);
  }
````
Initially there are 3 "datasets" and thus 3 views and one contentSelector.  First time through the loop (i=0,j=0) works fine.  However each time through the loop the "groups" array is getting smaller, but the index is also being incremented so eventually it overruns the array and throws an exception.

**Comment by EisenbergEffect** [comment]
If I understand correctly, the always passing an index of 0 to removeAt instead of passing i should work to fix the problem. Is that correct in your thinking?

**Comment by myellen42** [comment]
I believe so.  I tried that locally and it seemed to fix the problem.

**Comment by EisenbergEffect** [comment]
Great. I'm pushing a fix and it will go out in today's release. Thank you for catching this!
