### ISSUE TITLE
Template part replacement within repeat "leaks" to other instances of custom element

### ISSUE THREAD

**Issue by Vlemert** [aurelia/templating#137]
Hi,

I have a custom element, with a simple repeat construction inside. Within the repeat is a replaceable template. When I place multiple instances of this custom element on a page, and replace the template in some of those instances, the template gets replaced in all instances. The version of the replaced template is the one in the last instance of my custom element.

This only occurs within a repeat. Any replaceable template outside of repeats behaves like expected.

[Plunkr example here](http://embed.plnkr.co/O72uMw/preview), showing how templates within a repeat are affected, those outside the repeat are not.

[Alternative plunkr example](http://embed.plnkr.co/UCafIh/), showing that if I swap everything around and put the instance that does not define a replace template last, none of the instances will have a replaced template.

Let me know if you need any more info!

**Comment by EisenbergEffect** [comment]
I'm happy to tell you that this is already fixed in master. Release going out in the next day or two I hope.

**Comment by Vlemert** [comment]
Nice, thanks!

Guess I just learned that checking all open issues doesn't always cut it...
