### ISSUE TITLE
readonly binding

### ISSUE THREAD

**Issue by davismj** [aurelia/templating#138]
readonly.bind="!editing"

**Comment by jdanyow** [comment]
No DOM API backing the `readonly` html attribute.  Will need to create some sort of read-only observer in the binding repo that calls `element.setAttribute('readonly', 'readonly')` when the value is truthy and `element.removeAttribute('readonly')` when the value is falsy.

Should support textarea as well, which has a `readOnly` DOM API property.

**Comment by EisenbergEffect** [comment]
Got to love the "consistency" of the DOM.
