### ISSUE TITLE
[Addon] Utilise `.jade` files using custom `JadeView` and `JadeConventionView` classes

### ISSUE THREAD

**Issue by Craga89** [aurelia/templating#14]
I've developed a custom `ViewStrategy` that allows the user to utilise the SystemJS `jade` plugin to load `.jade` and pre-compiled `.jade.js` files just as you would normal `.html` files.

Examples and the code for which can be seen at my repo: https://github.com/Craga89/aurelia-jade-viewstrategy

Can I get your thoughts on this? Is this the best way to achieve this?

**Comment by Craga89** [comment]
Small update, I've removed the need for passing the ViewModel instance through to `JadeConventionView` and instead use the `moduleID` of the ViewStrategy` defined by the `static:getDefault` method to resolve it by convention instead.

Is this a reliable way of doing this? I noticed you explicitly pass this moduleId annotation to `ConventionView` in `static:getDefault`, so presuming it's fine!

**Comment by EisenbergEffect** [comment]
Looks fantastic. You are using it correctly. The moduleId is set for this purpose. Do keep an eye on the templating and loader-default repos though. We are probably going to be making some changes around view loading. I'm not sure yet if it will affect the work you've done here.
