### ISSUE TITLE
@containerless custom element gets Comment node from injector

### ISSUE THREAD

**Issue by atsu85** [aurelia/templating#140]
Currently when asking for element to be injected into @containerless custom element, such as
``` TypeScript
@autoinject
@containerless
export class Customelement {
  constructor(element: Element) {
    this.element = element;
    console.log("Customelement element:");
    console.log(this.element);
  }
}
```
then the result is Comment node:
`Comment { attributes=NamedNodeMap, primaryBehavior=BehaviorInstance, driverlicense=Driverlicense, more...}`

My current workaround is to use
`this.element = this.element.previousElementSibling`
As i'm adding single root element inside template tag then it looks like it is working as expected, but I'm wasn't aware if there might be cases where this workaround screws things up for me. @EisenbergEffect said it is safe to use previousElementSibling.

My initial thought was to suggest a change in Aurelia templating that would check if there was exactly one html element in template tag and pass that to the user (maybe even throw an error when single element can't be detected).

@EisenbergEffect had some other ideas - let's discuss them here.

@EisenbergEffect:
> Hmm. I wonder if we could create a “fake” element to inject. There could be a lot of work in that though. Maybe we could define a minimal dom surface to define in that case?

Can You elaborate what would be the benefit of passing fake element instead of element.previousElementSibling? I hope that when the "fake element" route is taken then I could use the injected element the same way without having to worry if the class is regular or @containerless custom element (so that the interface for the fake element would match ES6 element: https://github.com/Microsoft/TypeScript/blob/master/bin/lib.es6.d.ts#L7722 )

---------------
Original discussion in gitter: https://gitter.im/Aurelia/Discuss?at=55b8dec5b49857ca22384a40

**Comment by EisenbergEffect** [comment]
So, let's start with some use case. Creating that entire api, might be a lot of work, but maybe we can have a subset of it that is reasonable, but always give you access to the original comment node, just in case it isn't. But if we can handle the majority of use cases, then we can make it so it's transparent for developers. So, can you share some details of what you are trying to do with the element?

**Comment by atsu85** [comment]
I'm using it to locate DOM element from that custom element, by passing it as a context to jQuery:
```
$("input[type='file']", this.element).fileupload({...
```

**Comment by atsu85** [comment]
Oh, after thinking about it, i came to the conclusin, that aurelia can't just pass `element.previousElementSibling` to the constructor (as it would reference worong dom element before that custom element content is resolved and attached to the DOM). It doesn't work before attached() method is invoked, so my initial proposal of just passing  `element.previousElementSibling` wouldn't work. So basically proxy instance to `element.previousElementSibling` would act exactly the same way that i initially thought.

**Comment by jdanyow** [comment]
@atsu85 / @EisenbergEffect what's the status on this one

**Comment by EisenbergEffect** [comment]
The challenge is that containerless elements don't actually have a single element that can be injected. So, currently we inject the comment node that serves as the placeholder. We dress is up a little so that it has a couple dom apis that pass through to the original removed container. I'm interested in any recommendations that people might have. On the whole, I want to discourage people from using this since it's not possible with web components and I want people to tend towards writing things that will work both with Aurelia and Web Components.

**Comment by atsu85** [comment]
I'm using @containerless a lot, because i had to work with HTML/CSS provided by visual team - they were not happy to hear me taking about future standards when i was discussing possibility to redo the CSS ;) I guess it would have been less of an issue if they had known in advance, that I'd like to create lots of containers that they have no idea about ;)

Anyway, my current solution (that doesn't annoy me much and that also works with IE as well) is following:
```TypeScript
  attached(){
    this.element = CustomElementUtil.getRealElement(this.element);
    // use the element without worrying about using @containerless
  }
```
see the [source of CustomElementUtil.getRealElement(this.element)](https://gist.github.com/atsu85/03b1d053d9467e227dd5#file-customelementutil-ts-L7)

**Comment by EisenbergEffect** [comment]
Closing this. I'm not sure we can make this any better for containerless scenarios.

**Comment by atsu85** [comment]
Fair enough. Just for the record I had no isssues with the workaround I described [above](https://github.com/aurelia/templating/issues/140#issuecomment-167689212) - it was trivial to use in the project that required `@containerless` custom elements.
