### ISSUE TITLE
@containerless causes issues with event delegation

### ISSUE THREAD

**Issue by shanonvl** [aurelia/templating#141]
On the latest build, I using the following delegation on a `@containerless` view model stopped working ( handlerFn isn't called ):

```html
<div repeat.for="a of arr">
   <div click.delegate="$parent.$parent.handlerFn($index,$event);">hi</div>
</div>
```

[Full Plunker Example](http://embed.plnkr.co/Exaj2F/preview)

All of the references are set correctly; this code worked prior to upgrading.   Using the Plunker, if I remove `@containerless` from custom-element.js, the code starts working again.   

Please let me know if I can provide other info -- I'm assuming this is still supported ?

**Comment by EisenbergEffect** [comment]
I just pushed a new release out for templating which I believe shold fix your bug. Please try it out and let me know.

**Comment by shanonvl** [comment]
Working again!  Huge thanks for resolving this so quickly!

**Comment by EisenbergEffect** [comment]
Sorry about that. We fixed some issues related to shadow dom..but a few cases got missed in the change we made to handle that. Glad this was an easy fix ;)
