### ISSUE TITLE
@processContent(false) not working

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/templating#142]
Updated to latest release. Changed the deprecated decorator `skipContentProcessing` to `processContent(false)`. However it still seems to compile it. Debugged it and saw this https://github.com/aurelia/templating/blob/master/src/view-compiler.js#L394
setting `elementInstruction.type.skipContentProcessing` this to true in the debugger and it worked.

**Comment by EisenbergEffect** [comment]
Ah....sorry. I'll get it fixed. Hopefully today if not by tomorrow.

**Comment by stoffeastrom** [comment]
No hurry :)

**Comment by EisenbergEffect** [comment]
Just pushed a new release. Give it a shot and let me know if the issue is fixed.

**Comment by stoffeastrom** [comment]
Fixed!

**Comment by EisenbergEffect** [comment]
Sorry about that. I tried to sneak a feature in at the last moment...and failed to get it right ;)

**Comment by EisenbergEffect** [comment]
Glad it's working now.

**Comment by stoffeastrom** [comment]
hehe np ;)
