### ISSUE TITLE
template parts latest update causes TypeError: Cannot read property 'behaviorInstructions' of undefined

### ISSUE THREAD

**Issue by devmondo** [aurelia/templating#143]
i have updated to latest to fix this issue https://github.com/aurelia/templating/issues/139 and followed the docs example, now i get this error : 

TypeError: Cannot read property 'behaviorInstructions' of undefined

if i remove ```replaceable``` error goes away, but naturally templates wont be replaced.

**Comment by EisenbergEffect** [comment]
Can you attach a simplest possible sample for me? I will need to see it, possibly reproduced on the nav skeleton. Also, make sure you have the latest...latest. There were several patches for different edge cases released in the last day or two.

**Comment by devmondo** [comment]
@EisenbergEffect 
i downloaded the skeleton per your suggestions and added the sample, hope i am not doing something wrong!

http://www.megafileupload.com/dh7C/replaceParts.zip

thanks in advanced.

**Comment by EisenbergEffect** [comment]
Got it fixed in master. Will go out in the next release either today or tomorrow I hope. Thanks for catching this!

**Comment by devmondo** [comment]
you rock Rob :)
