### ISSUE TITLE
using multiple instances of an custom element with template parts does not work properly

### ISSUE THREAD

**Issue by uwascan** [aurelia/templating#148]
While trying out Template Parts, following the example in the Aurelia documentation, I encountered an inconsistent behavior. Using the custom-element below as an example (copied from Aurelia documentation)

##example.js
```
export class Example {
  constructor(){
    this.items = [1,2,3,4,5];
  }

  bind(context){
    this.$parent = context;
  }
}

```

##example.html

```
<template>
  <ul>
    <li class="foo" repeat.for="item of items">
      <template replaceable part="item-template">
        Original: ${item}
      </template>
    </li>
  <ul>
</template>

```
I placed two instances of the above custom-element on the welcome page of the skeleton-navigation as shown below

```
<template>
  <require from="example"></require>

  <section class="au-animate">
      --------------
      
    <div>
      <h2>Original</h2>
      <example></template>
    </div>
    
    <div>
      <h2>Replace-Part</h2>
      <example>
        <template replace-part="item-template">
          Replacement: ${item} ${$parent.$parent.fullName} 
            <button click.delegate="$parent.$parent.welcome()">Test</button>
        </template>
      </example>
    </div>
  </section>
</template>
```

only the first instance renders, but if I switch them as shown below

```
<template>
  <require from="example"></require>

  <section class="au-animate">
      --------------
        
    <div>
      <h2>Replace-Part</h2>
      <example>
        <template replace-part="item-template">
          Replacement: ${item} ${$parent.$parent.fullName} 
            <button click.delegate="$parent.$parent.welcome()">Test</button>
        </template>
      </example>
    </div>
    
    <div>
      <h2>Original</h2>
      <example></template>
    </div>
  </section>
</template>
```

both instances renders correctly. Is this the intended behavior or a bug?

**Comment by EisenbergEffect** [comment]
This is a strange bug. I will look into it. I have confirmed it is reproducible using the above code.

**Comment by EisenbergEffect** [comment]
I'm happy to tell you that this is easy to fix :) You have a typo in your html which results in html parser issues in the browser. Your second example has the incorrect closing tag. It should be `</example>` but you have `</template>` instead.

**Comment by uwascan** [comment]
@EisenbergEffect thank you for the catch.

**Comment by annlopez** [comment]
i am experiencing this as well. it seems like i can only use the custom element once. which is weird

**Comment by bigopon** [comment]
If you are experiencing a bug, please open a new issue with a repro. Its not possible to guess / help based on your comment @annlopez .
