### ISSUE TITLE
Error: Permission denied to access property "delegatedCallbacks"

### ISSUE THREAD

**Issue by valichek** [aurelia/templating#150]
Getting this error when clicking into form text inputs
Error: Permission denied to access property "delegatedCallbacks"
Replacing `click.delegate="reset()"` with `click.trigger="reset()"` fixes error
You can get the example here https://github.com/valichek/skeleton-navigation/blob/delegatedCallbacks-error/src/welcome.html

**Comment by JoshHarris** [comment]
We are also experiencing the same issue, but only in Firefox and not in Chrome

**Comment by alexmills** [comment]
I concur with @JoshHarris, seeing this issue in Firefox but not chrome.

**Comment by gavinaiken** [comment]
I'm also seeing this issue in Firefox only when clicking on text inputs.

**Comment by aozisik** [comment]
Same here. It's working in Chrome.

**Comment by tareqimbasher** [comment]
Yes I have this problem when clicking on any text input, data bound or not.

**Comment by EisenbergEffect** [comment]
I've identified the issue. It will be fixed in the next release.

**Comment by EisenbergEffect** [comment]
Fixed and going out in latest release.
