### ISSUE TITLE
Interpolation binding expression in custom attribute

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating#154]
[Plunker](http://plnkr.co/edit/KYYQVqw6Cw4u49mnBh2Z)

**Run the plunker... correct result: `div.getAttribute('data-t')` returns the result of the interpolation expression:**

![result](http://i.imgur.com/TwsCPO1.png)

**Open app.js and uncomment DataTCustomAttribute, re-run the plunker:**

- `div.getAttribute('data-t')` remains `${message}`.
![result](http://i.imgur.com/eQD9mIP.png)

- `div['data-t']` is an object:
![data-t](http://i.imgur.com/nRHk6tu.png)

**Comment by zewa666** [comment]
Thanks for the detailed description @jdanyow :+1:

**Comment by jdanyow** [comment]
@EisenbergEffect is this a bug?

**Comment by jdanyow** [comment]
updated to latest aurelia:  https://gist.run/?id=d55b3ef835c615b81038

**Comment by jdanyow** [comment]
not an issue- custom attribute value is not supposed to sync back to the dom element attribute
