### ISSUE TITLE
Events not being consumed in parent of custom element

### ISSUE THREAD

**Issue by emcga** [aurelia/templating#155]
Sorry if the title is slightly misleading. I'm new to JavaScript and Aurelia. 

Ok, to get to the point, I have a view and view-model named main.html and main.js, and another view and view-model named custom-element.html and custom-element.js that represent a custom element. I'm trying to fire an event from the custom element, catch the event in the parent of the custom element, and call a method in the parents view-model(main.js) named customEventFired. I would like to catch the event in the DOM like the example below...
```html
<!--I would like to catch the event like buttons do-->
<button click.delegate='buttonClicked()'></button>

<!--But instead with my custom element and event like this-->
<custom-element customEvent.delegate = 'customEventFired()'></custom-element>
```
Here is the code I have and it does not work...

```html
<!--main.html-->
<template>
   <require from='./custom-element'></require>
   <custom-element customEvent.delegate='customEventFired()'></custom-element>
</template>
```
```javascript
//main.js
export class Main{
   customEventFired(){
      alert('Custom Event Fired!');
   }
}
```
```html
<!--custom-element.html-->
<template>
   <button type='button' click.delegate='fireEvent()'>Fire Event!</button>
</template>
```
```javascript
//custom-element.js
import{inject} from 'aurelia-framework';

@inject(Element)
export class CustomElement{

   constructor(element){
      this.element = element;
   }

   fireEvent(){
      let e = new CustomEvent('customEvent', {bubbles: true}); //create the event
      this.element.dispatchEvent(e);//dispatch the event
   }
}
```

I tried multiple variations of the code above and cannot get the parent view-model to consume the event produced by the custom element! I have been working on this for days without success. Any help would be appreciated. 

Also, I have tried multiple versions of the aurelia-skeleton including versions 15, 16 and 17 without success. 

Thank you in advance for your help.

**Comment by emcga** [comment]
I finally discovered a solution! For those who have this problem, this is what I did to correct the issue.

When you create a custom event, the event type, or the first parameter of the CustomEvent constructor, can not be uppercase. Example below...

```javascript
let e = new CustomEvent('customEvent', {bubbles: true}); //This is wrong!

let e = new CustomEvent('customevent', {bubbles: true}); //This is right!
```
Also, don't forget to change the event delegate binding in the parent view.
```html
<!--main.html-->
<template>
   <require from='./custom-element'></require>
   <custom-element customevent.delegate='customEventFired()'></custom-element>
</template>
```

 I'm not sure if this is a bug in the framework or just the nature of how events function, but this definitely solved my problem!

Also, this is such an intuitive framework and I absolutely love working with aurelia. Keep up the excellent work!

**Comment by EisenbergEffect** [comment]
Ah. Yes. This has to do with the fact that html doesn't understand case and the parser basically lowercases all html element names and attributes before any 3rd party code can see them. So, when you wire for the event like this `customEvent.delegate` Aurelia actually sees this: `customevent.delegate`. And unfortunately, there's nothing we can do about it since this is coming from the browser itself. Hopefully that explains why your solution works. In general, I think all biult-in events, are lowercase, so using that same naming convention for your own, also gives you the added benefit of being consistent with the underlying platform.
