### ISSUE TITLE
Loading a view into a bootstrap popover

### ISSUE THREAD

**Issue by dpinart** [aurelia/templating#157]
Hi,

First of all I'm not sure this is the right place for this question, if not, my apologizes.

Well, I'd like to dinamically show an aurelia view into a popover. Is there any way I can compile a view and set it as a popover content?

Thanks

**Comment by EisenbergEffect** [comment]
Have you looked at using the `<compose></compose>` element?

**Comment by dpinart** [comment]
Hi
Yes I did though... I guess I'm missing something. Any idea or advice?

**Comment by EisenbergEffect** [comment]
I would need some more information about how you are going about it. Can you share any code?

**Comment by dpinart** [comment]
yes sure. I'm building an Esri app to show issues in a map. Often, many issues are placed in the same point so I'd like to show a popover on the map marker with a list with the issues.

Right now, I just want to show an aurelia view as the popover content. I have created a single view
<template><h1>Hello from popover</h1> called popover-view

then, in order to show the popover I'm doing something like:
showPopover(element: any, model: any, viewModel: string){
    var vm = 'model="\'hello from popover\'" view-model="\'popover-view\'"';
    $(element).popover({
      container: 'body',
      html: true,
      placement: 'auto',
      content: function () {
        return "<div><span>Hi</span>" +
          "<compose " + vm + "></compose></div>"
      }

    }).popover('show');
  }

I can see the popover showing hi, but popover-view is not instantiated

html for the popover looks like:
<div class="popover fade top in" role="tooltip" id="popover731643" style=top: 328px; left: 1470px; display: block;">
   <div class="arrow" style="left: 67.5555555555556%;">
       ::after
    </div>
    <h3 class="popover-title" style="display: none;"></h3>
    <div class="popover-content">
       <div>
          <span>Hi</span>
         <compose model="'hello from popover'" view-model="'popover-view'"></compose>
      </div>
    </div>
</div>

**Comment by dpinart** [comment]
As you can see from previous post, compose element inside popover content misses the class au-target so it seems aurelia is not enhancing the html content of the popover

**Comment by dpinart** [comment]
Any insight about how I can show an aurèlia view in a bootstrap popover? May be I'm missing something in order to force aurèlia framework to enhance the popover?

**Comment by EisenbergEffect** [comment]
There is an api on the ViewEngine class called `enhance`. It can be used to progressively enhance html that was not processed by the templating engine. There's no docs on it yet because it is subject to change in the next few weeks, but if you look in the ViewEngine class in the templating repo, you will see it. You can then also look in the framework repo at the enhance method of the aurelia class. That uses the view engine api. Hopefully that will give you some ideas in the mean time. I can provide some more insight if you can share a bit more of your code, related to the class that you have for showing popups.

**Comment by dpinart** [comment]
Thanks rob for your interest. 
Sure I can share more details. I just created a class in order to show a popover on an element. The class, right now, i as simple as:
<code>
```javascript
export class PopoverExtension{
  public static showPopover(element: any, model: any, viewModel: string){
    var vm = 'model="\'hello from popover\'" view-model="\'src\\fron-end\\core\\html-components\\popover-view\'"';
    $(element).popover({
      container: 'body',
      html: true,
      placement: 'auto',
      template: '<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div><compose model="\'aa\'" view-model="\'src\\fron-end\\core\\html-components\\popover-view\'"></compose></div></div>',
      content: function () {
        return "<div><span>Hi</span>" +
          "<compose " + vm + "></compose></div>"
      }

    }).popover('show');
  }
}
</code>

As you can see showPopover just takes as arguments an element, the one to place the popover on, and the model and view-model to compose the popover content

If you pay attention to the implementation, right now, I'm omitting the last two parameters and just statically setting the compose model and view.model attibutes.

I then have a popover-view template that looks like
<code>
```html
<template>
  <h1>${model}</h1>
</template>
</code>

and the popover view model looks like 
<code>
```javascript
export class PopoverViewModel{
  public model:any;
  public activate(model){
    this.model = model;
  }
}
</code>

**Comment by EisenbergEffect** [comment]
Try something like this:

```
import {ViewEngine, Container, ViewResources, inject} from 'aurelia-framework';

@inject(Container, ViewEngine, ViewResources)
export class Popover{
  constructor(container, viewEngine, viewResources){
    this.container = container;
    this.viewEngine = viewEngine;
    this.viewResources = viewResources;
  }

  public show(element: any, model: any, viewModel: string){
    var vm = 'model="\'hello from popover\'" view-model="\'src\\fron-end\\core\\html-components\\popover-view\'"';
    $(element).popover({
      container: 'body',
      html: true,
      placement: 'auto',
      template: '<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div><compose model="\'aa\'" view-model="\'src\\fron-end\\core\\html-components\\popover-view\'"></compose></div></div>',
      content: function () {
        return "<div><span>Hi</span>" +
          "<compose " + vm + "></compose></div>"
      }

    }).popover('show');

    let view = this.viewEngine.enhance(this.container.createChild(), element, this.viewResources);
    view.attached();
  }
}
```

Note that at this level you are managing the view lifecycle yourself, so you will need to call view.detached() and view.unbind() whenever the popup is closed.
