### ISSUE TITLE
Error when removing item from Map that is binded to custom element

### ISSUE THREAD

**Issue by michalru3ch** [aurelia/templating#158]
Let's assume that we have a following markup in a view:

```html
<ul>
      <customLi repeat.for="[id, item] of items" item.bind="item"></customLi>
</ul>
```

`customLi` is a containerless custom element and `items` is a Map. Following works fine when displaying or adding items. When I try to remove an item I get following error:

`message: "Cannot read property 'source' of undefined"
stack: "TypeError: Cannot read property 'source' of undefined↵ at Repeat.getViewIndexByKey (http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.14.0/repeat.js:411:30)↵ at Repeat.handleMapChangeRecords (http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.14.0/repeat.js:387:32)↵ at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.14.0/repeat.js:187:16)↵ at ModifyMapObserver.call (http://localhost:9000/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:591:23)↵ at TaskQueue.flushMicroTaskQueue (http://localhost:9000/jspm_packages/github/aurelia/task-queue@0.6.2/aurelia-task-queue.js:107:16)↵ at MutationObserver.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/task-queue@0.6.2/aurelia-task-queue.js:48:24)"`

If I wouldn't use custom element (`customLi`) but `li` instead, it would work - I've already tried. When debugging attached lifecycle hook of `customLi` I've noticed that even if the item was already removed from items Map, this method was still called for this item. It seems to me that custom elements displayed on the view are listed in some variable/observable that is not updated so Aurelia does not know that the item bound to that custom element does not exist anymore, and still tries to render it.

Any thoughts? Am I missing something?

**Comment by jdanyow** [comment]
Hi @michalru3ch, thank you for your bug report- would you be able to put together a minimal repro of this issue in the [aurelia plunker](http://bit.ly/aurelia-plunker) so we can debug it?

Thanks!

**Comment by michalru3ch** [comment]
Hi @jdanyow. This is [a plunk](http://plnkr.co/edit/9khkd6ON41DrPPP2p5gz) I've created.

Unfortunately I was not able to even get the binding of a map working. It throws ```Object in "repeat" must be of type Array, Map or Number``` which is quite strange because it's a map and it's definitely working on my project - maybe I'm using different versions of Aurelia libraries locally. Could you please try to fix the issue?

The rest should be prepared for reproducing the original issue. I've also added itemsArray to prove that removing items from Arrays works correctly. Just uncomment line 6 in app.html and comment 5.

**Comment by jdanyow** [comment]
@michalru3ch thanks for the Plunker, I was able to reproduce the issue you reported after changing `itemsMap = new Map();` to `itemsMap = new window.Map();` (apparently there are two versions of the Map polyfill being used by the plunker which I will look into separately).

When pressing the "remove item with id 3" button an error occurs in the repeat component:
![repeat error](http://i.imgur.com/flczWCC.png)

**Comment by michalru3ch** [comment]
@jdanyow thanks for the fix! I've already updated my plunker.

Not sure whether it will be of some help, but when I'm debugging my local project debugger hits attached hook of `CustomLi` element after item is removed from Map and I see that aurelia loops through all items - even over removed one. In plunker I do not have this behaviour - but the error is the same.

**Comment by jdanyow** [comment]
@michalru3ch are you still having issues with this?

**Comment by michalru3ch** [comment]
Hi jdanyow.

I've just updated aurelia and babel (babel-core@5.8.25, babel-runtime@5.8.25) as well, but I still have the issue. Even the proposed workaround
```javascript
import regeneratorRuntime from 'babel-runtime/regenerator';
window.regeneratorRuntime = regeneratorRuntime;
```
didn't solve it.

Current error:

`
message: "Cannot read property 'source' of undefined"
stack: "TypeError: Cannot read property 'source' of undefined?    at Repeat.getViewIndexByKey (http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.16.0/repeat.js:403:30)?    at Repeat.handleMapChangeRecords (http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.16.0/repeat.js:376:32)?    at Repeat.call (http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.16.0/repeat.js:58:20)?    at ModifyMapObserver.callSubscribers (http://localhost:9000/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:167:19)?    at ModifyMapObserver.call (http://localhost:9000/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:649:14)?    at TaskQueue.flushMicroTaskQueue (http://localhost:9000/jspm_packages/github/aurelia/task-queue@0.8.0/aurelia-task-queue.js:110:16)?    at MutationObserver.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/task-queue@0.8.0/aurelia-task-queue.js:60:22)"
`

**Comment by michalru3ch** [comment]
@jdanyow 

Today I've installed the latest version of babel (5.8.30) and its runtime, but still same error...

From pure curiosity I gave it a try to debug the repeat.js and these are my findings:

- it crashes in method `getViewIndexByKey` when accessing the first binding of viewSlot.children `child.bindings[0].source[this.key]`. Strange thing is that none of the children ever had the list of bindings filled in (length is always zero) so this method would never find the index this way.

- the failing method is called by `handleMapChangeRecords` which tries to get the index of viewSlot child (of removed item from the map) so it could then remove it.

```javascript
case 'delete':
  if (!record.oldValue) {
    return;
  }
  removeIndex = this.getViewIndexByKey(key);
  viewSlot.removeAt(removeIndex, true);
  break;
```

If I just prevent the code from calling the `getViewIndexByKey` and call `viewSlot.removeAt(removeIndex, true)` directly by providing the correct index it works as expected - coresponding element is removed from the view.

I do belive that if you would invest couple of minutes to just take a look at `getViewIndexByKey` and review its implementation, you'd probably know what to change.

PS: if someone wants to overcome this issue without waiting for the fix, you could do something like this...

```javascript
let mapCopy = new Map(this.itemsMap);
mapCopy.delete(3);
this.itemsMap = mapCopy;
```

It's dirty, but it works. Drawback is that all items are rendered again.

**Comment by michalru3ch** [comment]
Ok, I have it.


Replace this line (repeat.js:404)

```javascript
child.bindings[0].source[this.key] === key
```

by this one

```javascript
child.bindingContext[this.key] === key
```

**Comment by martingust** [comment]
@michalru3ch Great, That implementation was not right, will get this fix in by next release, thanks.
