### ISSUE TITLE
Add an option to have containerless by default

### ISSUE THREAD

**Issue by eyalsk** [aurelia/templating#159]
Currently, you can add the 'containerless' attribute to elements, the issue with that is that you can find yourself in places where you need to add this attribute every single time which can be tedious, repetitive and very annoying but most importantly it can make the view unreadable.

So we need a way to tell Aurelia that we want containerless to be the default for all elements and to reverse that option locally we would use something like the following: 
```html
<element containerless=false></element>
```

**Comment by EisenbergEffect** [comment]
Hmm. I actually thought when you first stated this that you were referring just to making the `compose` element containerless by default. I'm not sure doing this for all elements would be a good idea. That would break a lot of things. 3rd party elements would function incorrectly, it wouldn't be very compatible if you wanted to re-use your aurelia element as a web component, etc.

If what you mean is that for a *particular* element, you want *it* to always be containerless when *it* is used, you can actually do that today by decorating the class with the `@containerless` decorator. Is that what you want?

**Comment by eyalsk** [comment]
@EisenbergEffect, yeah! that's what I wanted/meant! ;)

**Comment by EisenbergEffect** [comment]
Excellent.
