### ISSUE TITLE
ViewSlot::getAnimatableElement causes error : Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by sylvain-hamel** [aurelia/templating#160]
I have this bug where `ViewSlot.prototype.removeAt()` throws with `Cannot read property 'firstChild' of undefined` inside `getAnimatableElement` at line

    function getAnimatableElement(view) {
        var firstChild = view.firstChild;

because `view` is `undefined`.

The stack trace shows it's processing a `if`
```
getAnimatableElement (aurelia-templating.js:792)
removeAt (aurelia-templating.js:929)
remove (aurelia-templating.js:910)
valueChanged (if.js:28)
bind (if.js:22)
bind (aurelia-templating.js:2102)
bind (aurelia-templating.js:544)
valueChanged (if.js:44)
BindableProperty.createObserver.selfSubscriber (aurelia-templating.js:2269)
call (aurelia-templating.js:2419)
flushMicroTaskQueue (aurelia-task-queue.js:107)
(anonymous function) (aurelia-task-queue.js:48)
```

I can reproduce it at will in my applicaton but I'm not able to isolate this problem.

**Comment by sylvain-hamel** [comment]
I can temporarily fix this by adding the 2nd line here

```
    ViewSlot.prototype.remove = function remove(view) {
      var index = this.children.indexOf(view);
      if(index === -1) return;
      return this.removeAt(index);
    };
```

But I can't explain why I end up in this situation.

**Comment by simonfox** [comment]
Possibly related to aurelia/templating-resources#103

**Comment by EisenbergEffect** [comment]
@sylvain-hamel Can you provide some instructions for me that would enable me to reproduce this issue?

**Comment by sylvain-hamel** [comment]
@EisenbergEffect As I wrote in my first post, I'm not able to isolate this problem in a separate project. FYI: I'm not use animations (at least not intentionally) and the error is in `getAnimatableElement`.

**Comment by EisenbergEffect** [comment]
@martingust Is this issue fixed?

**Comment by martingust** [comment]
@EisenbergEffect Not that I know of. Haven't looked into this, let me know if you want me to.

**Comment by EisenbergEffect** [comment]
@martingust If you can take a look, that would be great. Thanks! I thought you recently made a fix to the view slot for this, but I may be incorrect.

**Comment by sylvain-hamel** [comment]
I can no longer reproduce this bug with 0.15.3. I think it was fixed by some other change.
