### ISSUE TITLE
Feature request: Get reference to view model with DOM node

### ISSUE THREAD

**Issue by hschmidt99** [aurelia/templating#165]
There was a convenience feature that I used in Durandal like
```knockout.dataFor(<referenceToDomElement>)``` that allowed me to get a reference to the underlying view model in the development console of my browser and enabled me to play around with it without having to reload anything,

I'd love to be able to do the same thing with Aurelia.

**Comment by CharlesPockert** [comment]
You can get a viewmodel (the binding context) via the `primaryBehavior` property that's attached to an element:

```
element.primaryBehavior.bindingContext
```

It should be present on any custom element

**Comment by EisenbergEffect** [comment]
Now it is `element.au.controller.model` for any custom element.

**Comment by davismj** [comment]
The real use case here is for drag and drop. In the common use case for Aurelia, you would want to drag one model into another model, yet you only have access to the view through the drag-and-drop API. It would be excellent if there was a way to signal Aurelia to expose an object directly onto an element in the exact same way it does for custom elements. For example, the following html element might have `element.au.controller.model` defined as `item`.

```
<div repeat.for="item of list" model.bind="item"></div>
```

**Comment by EisenbergEffect** [comment]
If you do as above, Aurelia will place a model property directly on the div element with the value of item.

**Comment by stevenvachon** [comment]
The information here seems to be outdated. I'm having difficulty finding the model from either the element or from a `StageComponent` instance.
