### ISSUE TITLE
Infinite recursion on bound view factory

### ISSUE THREAD

**Issue by CharlesPockert** [aurelia/templating#168]
https://github.com/aurelia/templating/blob/10cdc2f7f7fc6016d4e5c4beecc5ffb296a534a7/src/view-factory.js#L238

Seems to call itself...

I get max call stack size exceeded when opening a page in my app, it appears to be when the `if` behavior checks to see if the view is caching

Here's a screenshot of the offending caller and the stack (not sure if you can see it due to the crash overlay in Chrome but there's the getter called on `isCaching` first followed by the `if` attribute and so on up the stack)

![image](https://cloud.githubusercontent.com/assets/9073518/9700736/59b465be-5406-11e5-91d1-00f0fd0dcb11.png)

**Comment by EisenbergEffect** [comment]
Release coming...hang on.

**Comment by EisenbergEffect** [comment]
Templating patch release is out. You should be able to get 0.15.1 with `jspm update`.

**Comment by CharlesPockert** [comment]
Thanks for the quick fix, I will try to break more things in the interest of progress!
