### ISSUE TITLE
[Feature] Databind to custom data-* attributes

### ISSUE THREAD

**Issue by robotnoises** [aurelia/templating#17]
Assuming an object `obj` is equal to `{ name: "one", value: "1" }`

I would like to databind `obj` properties to a custom data-* attribute in my template so that:

    <div data-value.bind="obj.value">${obj.name}</div>

... renders as

    <div data-value="1">one</div>

**Comment by yelvert** [comment]
Would `<div data-value="${obj.value}">${obj.name}</div>` not work?

**Comment by EisenbergEffect** [comment]
We got this in binding now. It will go out in the next release, probably tomorrow. This also includes support for aria- attributes.

**Comment by robotnoises** [comment]
Thank you!

**Comment by EisenbergEffect** [comment]
Thanks to @jdanyow He did the work on this.
