### ISSUE TITLE
Render custom element from a custom attribute

### ISSUE THREAD

**Issue by Vheissu** [aurelia/templating#172]
I have a need for being able to render a custom element using a custom attribute. Dynamically creating my custom element and being able to pass values to the custom element.

My custom element allows for styled select elements. Using it in the form of ``<au-select>`` is fine and works as expected. However, I want the option for users to be able to decorate an existing select with a custom attribute and then convert that into a custom element. Essentially replacing the element with a custom element (and parsing any options).

I am not too well-versed in how the view engine stuff works, this seems like something that many people would want to do. Being able to use an attribute to render custom a View (with support for custom elements in that view). Is this currently possible? If not, would be a great feature.

**Comment by EisenbergEffect** [comment]
It's not possible and definitely won't be added for v1. Sorry. We are trying to keep element and attribute scenarios clearly separated. Adding this would require probably a major re-working in the compiler if any attribute can just turn the hosted element into something else...

If you really want to do this, I would recommend creating a custom element and a custom attribute. They can both be registered with the same name and share some infrastructure. The attribute would just inject Element and manipulate the DOM manually.

**Comment by Vheissu** [comment]
No worries Rob. I actually have made some ground exploring this concept since posting this issue. It isn't ideal however I think it will work. Basically it involves removing the element that the custom attribute is wrapping, then I render a custom element using the view compiler and then insert it into the ViewSlot. It is almost there.  I've got it inserting the custom element, parsing the options and pass them through is another thing entirely. I'll let you know how I go.

**Comment by EisenbergEffect** [comment]
Maybe marking it as a template controller could help?
