### ISSUE TITLE
support passing content given to custom element to other custom elements

### ISSUE THREAD

**Issue by atsu85** [aurelia/templating#173]
<b>Support  passing tag content given to first custom element to another custom element in first custom element   tag like this:</b>

file my-custom-elem-wrapper.html:
```html
<template>
  <inner-tag>
    <!-- 
      pass content given to <my-custom-elem-wrapper> to <inner-tag> custom element
     -->
    <content></content><!-- content DOESN'T WORK HERE -->
  </inner-tag>
  <!-- content WOULD WORK HERE -->
</template>
```
Originally I asked about it in Gitter chat and initially @CharlesPockert said he can't see a reason why it shouldn't work.

So i created a Plnkr demo of the problem:
http://plnkr.co/edit/KzhVDUWMzpf3zbMsgbP3?p=preview

Later @CharlesPockert said:
> maybe it doesn't work because the content selector is processed as part of the parent template but is done after the inner custom element, so the content hadn't been selected/injected yet and the inner element gets a content selector which selects nothing...

> The only thing I can think of that's clean is to defer the processing, but that would probably screw with lifecycle, the other option would be to have all content selectors run before custom elements were processed. It looks like the issue is that the content selector is treated as part of the nested custom element instead of as part of the parent

>Wonder if a framework tweak could be made to account for this and if it would break anything

If in reality i wouldn't have much more markup in the wrapper tag i could just pass inner-tag as a content to my-custom-elem-wrapper, but in my case it would mean a lot of copy-paste for each place where i want to use <my-custom-elem-wrapper>

**Comment by EisenbergEffect** [comment]
It isn't a matter of whether or not it could work...but it's rather a matter that it's not allowed to work. The `content` tag comes from the Shadow DOM and as far as I understand isn't specified to work that way. So, we can't change that.

However, the content tag is being removed. The new shadow dom spec is quite different and uses a named slot model. I think that the new model might support the pattern you are asking for. This is going to be a breaking change in Aurelia, but it's something we can't help because it's a change in the spec. I'm reviewing it all now and hope to implement the new shadow dom fallback next week maybe.

**Comment by atsu85** [comment]
Hi @EisenbergEffect ,
what is the status of this feature request?

> The new shadow dom spec is quite different

...
>  think that the new model might support the pattern you are asking for.

As i understand new shadow dom spec is out by now. What are Your thoughts on that? 

It is very limiting to be unable to pass custom element content through second custom element to third custom element.

I've had several scenarios where i've been crying for this feature to avoid code duplication - i think it is one of the most significant pieces missing from Aurelia by now.

**Comment by Cedware** [comment]
+1

**Comment by EisenbergEffect** [comment]
We'll be working on the new shadow dom over the next few weeks. The spec has changed significantly, and frankly, this is the most complex part of the entire framework, so it will take a bit of time. But it's high priority and next up on the list.

**Comment by EisenbergEffect** [comment]
It's part of the new shadow dom update.

**Comment by atsu85** [comment]
Fantastic news, so I guess this issue could be reopened until it is actually implemented in Aurelia? What do You think, when will it get implemented?

**Comment by EisenbergEffect** [comment]
We are preparing to do the shadow dom update now. Please bear with us...it's extremely complicated and may take a few weeks.
