### ISSUE TITLE
Compile string markup without root element

### ISSUE THREAD

**Issue by jods4** [aurelia/templating#174]
Say you want to compile markup `Aurelia ROCKS!` (by simply calling `ViewCompiler.compile("Aurelia ROCKS!")`).

It won't work because those lines in `createTemplateFromMarkup` will throw in a browser without `<template>` support (don't know for others):
https://github.com/aurelia/templating/blob/02606f53de32481632d5ef539d612ab7fb08aa5c/src/dom.js#L16-L21

`temp` will be null because there is no Element child. Then `temp.content = ...` throws.

**Comment by EisenbergEffect** [comment]
You have to include a template wrapper for any markup you compile. Are you saying that that doesn't work on IE?

**Comment by jods4** [comment]
Didn't know that... It works with a wrapper of course.
Am I supposed to add the wrapper to inline views as well? It _seemed_ I had the same problem when using `@inlineView("Aurelia 4ever")`.

**Comment by EisenbergEffect** [comment]
Yes, you have to add it there too. This was a breaking change we made a month or so back because we realized that without enforcing that we couldn't reliably support surrogate behaviors. Something that would be a nice PR would be some error handling that told the developer when they made this mistake. Any interest in PRing that?

**Comment by jods4** [comment]
Sorry, really no time for a PR at the moment :(

I was mislead by using old code fragments I found on the web. If you are supposed to always pass a wrapper `<template>` then everything works as intended.

**Comment by EisenbergEffect** [comment]
Can you send me links to where you found the old examples? I may be able to
fix those or add some comments to help others not fall into that issue.

On Wed, Sep 16, 2015 at 11:36 AM, jods <notifications@github.com> wrote:

> Closed #174 <https://github.com/aurelia/templating/issues/174>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/templating/issues/174#event-411291421>.
>



-- 
Rob Eisenberg,
President - Blue Spire
aurelia.io

**Comment by jods4** [comment]
I guess my inspiration was essentially #35

**Comment by EisenbergEffect** [comment]
Thanks. I put an update there.

On Wed, Sep 16, 2015 at 11:39 AM, jods <notifications@github.com> wrote:

> I guess my inspiration was essentially #35
> <https://github.com/aurelia/templating/issues/35>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/templating/issues/174#issuecomment-140837223>.
>



-- 
Rob Eisenberg,
President - Blue Spire
aurelia.io

**Comment by shanonvl** [comment]
@EisenbergEffect I just submitted #175 which adds the requested error handling.

**Comment by EisenbergEffect** [comment]
Excellent :) I am traveling but will review soon. Thanks!
