### ISSUE TITLE
IE 11/Edge: injecting scoped styles using require tag for custom element is not wokring

### ISSUE THREAD

**Issue by lares83** [aurelia/templating#176]
Hi,
I'm testing your framework and I noticed issue for custom elements that are using shadow dom namely scoped styles that are beeing injected through require tag in template is not working on IE11/Edge. (On IE <= 10 templates are not even being loaded in body tag)
Here is an example:
http://plnkr.co/edit/uMIe2H?p=preview
As you can see on Chrome and FF button is blue and on IE/Edge it has default background.
Styles are visible in inspector but for some reason IE is not taking them into consideration.

**Comment by EisenbergEffect** [comment]
Fixed in master and releasing tomorrow-ish.
