### ISSUE TITLE
problem with replaceable parts and lifecycle of custom elements

### ISSUE THREAD

**Issue by andrevlins** [aurelia/templating#177]
I created a fork to demonstrate the problem on https://github.com/andrevlins/skeleton-navigation.

I have a __layout__ custom element with a replaceable part, when I use an __input__ custom element in that replaceable part the lifecycle is broken as the BIND method of __layout__ is called after BIND of __input__. That way __input__ has no access to $parent during BIND.

Please help me as this is across all my application as we use layout custom elements for master template of application.

**Comment by danylocampos** [comment]
I'm having this problem too and can't figure how to solve. Any updates on this @EisenbergEffect @andrevlins ?

**Comment by EisenbergEffect** [comment]
Fixed in master. Going out in next release, hopefully tomorrow or Tuesday.
