### ISSUE TITLE
"For" attibute bug 

### ISSUE THREAD

**Issue by lares83** [aurelia/templating#178]
Hi,
When I try to add variable from view-model  to "for" attribute in "ul" tag
<ul for="${variable}"></ul>
it's being removed.

I put example on Plunker
http://plnkr.co/edit/zcxd9o94r69miEoF2Xrb?p=preview

Everything is in users template.
As you can see in in inspector when I put hardcoded value in "for" attribute everything works fine but when I try to add value from view-model Aurelia removes whole attribute.

**Comment by EisenbergEffect** [comment]
Yes, the attribute is removed because if it contains and interpolation expression, then it actually has an invalid value. The binding engine then takes over controlling setting up the `for` property on the actual instance of the UL itself.

**Comment by lares83** [comment]
Thanks for explanation. I noticed this behaviour when I wanted to add context menu from "Material Design Lite" library (http://www.getmdl.io/components/index.html#menus-section). They are using "for" attribure for "ul" tag to localize which context menu should be displayed. What do you think would be the best solution to have this functionality working in Aurelia? Creating cutom attribute?

**Comment by PWKad** [comment]
I wonder if the same issue is reproducible using a label with interpolation...

**Comment by EisenbergEffect** [comment]
Hmm. I think that in the case of the label, `for` actually maps to `htmlFor` so maybe that is what is happening with the ul. Perhaps it's actually setting `htmlFor` instead.

@jdanyow Can you look into this? Is there some way to only map the attribute to htmlFor when its on the label element?

**Comment by darren-gibson** [comment]
I've also encountered this issue whilst attempting to use the MDL menu.  I've worked around with a simple hack in the custom mdl attribute

``` javascript
        if(element.getAttribute('for') == null && "htmlFor" in element) {
            element.setAttribute('for', element['htmlFor']);
        }
```

However, I notice that the MDL team are looking to support `data-mdl-for` as the `for` attribute is not allowed at this point for the `UL` element (see (https://github.com/google/material-design-lite/issues/1556)), so maybe there's no change required on the Aurelia side?

**Comment by jdanyow** [comment]
@darren-gibson thanks for the update and submitting a workaround.  We're planning on fixing this issue in an upcoming release, there's more info in https://github.com/aurelia/templating-binding/issues/64
