### ISSUE TITLE
Route params with wildcard question

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/templating#180]
This is a super nit picky question, i'd figured i'd just mention it anyways.

If i have a route defined as such
order/:id*

Then in the activate function i need to access the id as such

activate(params) {
 params["id*"]
}

shouldn't the * be ignored and it should just be id or is that done for a reason.

**Comment by zewa666** [comment]
It seems like you wanted to combine a route using a parameter as well as a wildcard. Those two don't work together and normally you'd terminate the parameter declaration with a trailing slash. In your case Aurelia thinks that the parameter is named `id*`. Take a look at the possible scenarios in the [router docs](http://aurelia.io/docs#routing)

**Comment by devteamexpress** [comment]
I tried with a trailing slash as such 
order/:id/*
but if i tried to go to a route called

order/112/summary it gave me route not found, using the * like i did worked perfectly

**Comment by zewa666** [comment]
hm actually you're right, that's strange. Would you mind creating the issue in the router repository as it fits better over there, and close this one here. You can then reference this closed one from the new location. That way we get the proper people to look at the issue
