### ISSUE TITLE
css class au-animate breaks repeat.for re-rendering

### ISSUE THREAD

**Issue by coderasm** [aurelia/templating#181]
See this plunker for css class au-animate breaking repeat.for re-rendering.
http://plnkr.co/edit/F65cUaS7qFxgETSf5Wjn

**Comment by EisenbergEffect** [comment]
@zewa666 @martingust Can you guys look into this?

**Comment by martingust** [comment]
This will get fixed with https://github.com/aurelia/templating-resources/issues/112
