### ISSUE TITLE
Why is the bind(context) of a <compose view-model="x" model.bind="item"> the viewmodel itself?

### ISSUE THREAD

**Issue by sickboy** [aurelia/templating#188]
~~~
bind(context) { }
~~~

context will be the viewModel itself ("this"), instead of it's parent.

And how to otherwise refer to the $parent ?

**Comment by jdanyow** [comment]
Here's a related question on stackoverflow:
http://stackoverflow.com/questions/32777303/custom-elements-binding-context-what-is-it-exactly-how-to-access-parent-vm/32781324#32781324
