### ISSUE TITLE
Global suscription event to a loaded view 

### ISSUE THREAD

**Issue by leon-andria** [aurelia/templating#189]
There is a way that we are able to subscribe to an event when a view is attached for exemple.
My use case is that, I would update some href attribute dynamically after that the binding is applied.
Today, having a custom attribute with a DIV wrapper can fit that but when you have more than 100 views, we can't do that manually.
There is a way, it should be good to have something like in ASP.NET a PreRender method and can be subscribed globally.

http://bp0.blogger.com/_poAbnIVuAzE/RngicyuzscI/AAAAAAAAAA8/vnU1l-I_ut8/s1600-h/asppagelifecycle.jpg

regards,

**Comment by zewa666** [comment]
you can either leverage Router events (https://github.com/aurelia/router/issues/24) or implement a BaseVM which the others would inherit. In there create your custom logic for all VMs. Personally I'd prefer the first way though.

**Comment by leon-andria** [comment]
@zewa666 We share the same feeling, the first one is more better for less dependencies.
As you put in the link, this is the kind of details that we need absolutely, this is why i put the poster as an idea that i did for asp.net few years ago.
What is really frustrating today is that with Aurelia, it's really hard for "basic" developers to find out some details. With a good overview like this, we can make easier many people onboard to love Aurelia platform.

**Comment by zewa666** [comment]
Those things should and will happen in tge docs app which were working on nowas part of the beta release
