### ISSUE TITLE
Firefox: Performance Issue

### ISSUE THREAD

**Issue by lares83** [aurelia/templating#190]
Hi, 
I prepared code in Plunker in which I would like to display 3 opinions
http://plnkr.co/edit/hiZ7GW?p=preview

As you can see on Firefox "Opinions" header is animated first and after few seconds opinions are being displayed. In Chrome/Edge header and opinions are being animated at the same time.

Second issue I noticed is that when I want to display opinions that have only uuid and put in opinion tag if.bind="opinion.uuid" it doesn't work on Firefox and nothing is being displayed.
In Chrome/Edge everything works fine.

**Comment by EisenbergEffect** [comment]
@zewa666 Can you take a look into the animation issue.
@jdanyow If you get a chance, can you look into the "if.bind" issue?

**Comment by jdanyow** [comment]
@lares83 are you still hitting an issue with `if.bind`?  I've updated your plunker to the latest aurelia bits, it's working in firefox now:

http://plnkr.co/edit/uRFQwi?p=preview

**Comment by lares83** [comment]
@jdanyow Hi, yes I still have it.  When you put 

<opinion repeat.for="opinion of opinions" if.bind="opinion.uuid" opinion.bind="opinion" class="opinion card-container au-animate"></opinion>

opinions are not being displayed in firefox but on chrome they are.

**Comment by jdanyow** [comment]
@lares83 - thanks for the additional info.  We're tracking the firefox issue with `if` and `repeat` on the same element in https://github.com/aurelia/templating-resources/issues/111.
