### ISSUE TITLE
Support full CSS selectors with @sync decorator

### ISSUE THREAD

**Issue by charlespockert** [aurelia/templating#191]
At the moment, the `@sync` decorator only supports the most simple scenario when selecting child elements to track.

This is limiting to framework users as it means that certain control scenarios are not possible.

Take this nested tab control example:

```
<tabs>
  <tab title="Tab 1">
    <p>Hello World</p>
  </tab>
  <tab title="Tab 2">
    <tabs>
      <tab title="Nested tab 1">
        <p>This is nested</p> 
      </tab>
      <tab title="Nested tab 2">
        <p>This is nested</p> 
      </tab
    </tabs>
  </tab>
</tabs>
```

With this `@sync` decorator tracking the children:

```
@sync({ name: "tabs", selector: "tab" })
```

Leads to this undesirable situation as the selector is not specific enough to ignore the nested children:

![image](https://cloud.githubusercontent.com/assets/9073518/10563806/e4465cf4-7590-11e5-8520-dbe1bd1d81ac.png)

### Potential solution

A `:scope` selector exists, which you can use with `element.querySelector/All` which selects the current element. This allows you to pick direct children using `:scope > ...`, which would solve the above problem

The `@sync` decorator would then look more like:

```
@sync({ name: "tabs", selector: ":scope > tab" })
```

It has support in Chrome/FF with a shim to polyfill others.

https://github.com/lazd/scopedQuerySelectorShim

Without changing the API, the `@sync` decorator could support simple selectors or upgrade to full support when a more complex selector was used.

You could detect if the selector was complex using regex, and automatically switch between the likely more performant `node.matches()` and `querySelectorAll()`.

Then plug this into the mutation observer callback e.g. here:

https://github.com/aurelia/templating/blob/master/src/children.js#L65

```javascript
  onChange(mutations){
    var items = this.behavior[this.property],
        selector = this.selector;

    // If the selector is complex, use querySelectorAll before looping the DOM mutations to grab the current DOM state and slice it into an array
    if(!this.isSimple)
      var results = Array.prototype.slice.call(this.target.querySelectorAll(this.selector));
...
```

Then in the loops here (and others):

https://github.com/aurelia/templating/blob/master/src/children.js#L78

```javascript
   // If the selector is complex, check if the mutated item is in the results of the above query, otherwise just use node.matches()
   if(node.nodeType === 1 && ((this.isSimple && node.matches(selector)) || (!this.isSimple && results.indexOf(node) !== -1))) {
          primary = node.primaryBehavior ? node.primaryBehavior.executionContext : node;
```

**Comment by EisenbergEffect** [comment]
Here's what we did: We replace `sync` with two decorators `children` for selecting a collection, and `child` for referencing a single element. The selectors will now only match immediate child content of the element. I think this is better for encapsulation and it also makes things more performant.

If that does not work for you, you should know that these decorators are build on an extensible system, so you could add back the old sync behavior or create your own. Just take a look at how the child/children decorators are written in the source if you are interested.

**Comment by charlespockert** [comment]
Sounds cool

:thumbsup:
