### ISSUE TITLE
Cannot use getter on repeat.for loop

### ISSUE THREAD

**Issue by LordZardeck** [aurelia/templating#194]
`this` is undefined in the following getter when running `repeat.for`:

**JavaScript:**
```js
get validZones(): Array<string> {
    // We need to exclude the card's current zone
    return this._zoneManager.zones.filter((zone: ZoneBase) => zone.zoneId != this.parentCard.parentZone.zoneId);
}
```

**HTML**
```html
<li repeat.for="zone of validZones">
	<a href="javascript:void(0)">${zone.zoneName}</a>
</li>
```

Is there something i'm doing wrong when implementing the `repeat.for` loop that is causing `this` to be undefined?

**Comment by martingust** [comment]
@LordZardeck It looks correct to me, I can't reproduce this. Would you mind creating example project with minimal steps to replicate? Thanks!

**Comment by LordZardeck** [comment]
@martingust Sorry about the late reply, I'll try to get a full example to you soon.

**Comment by LordZardeck** [comment]
@martingust So when I use a simple example on plunker ([example](http://plnkr.co/edit/9DVHuORLdCQe1Izbslr1?p=preview)), it does indeed work. I will have to re-try this again tonight as I used a different method in the mean time.
