### ISSUE TITLE
How to bind to the current bindingContext

### ISSUE THREAD

**Issue by LordZardeck** [aurelia/templating#195]
I'm wanting to pass the current binding context in to a custom element. This custom element could be contained in a variety of places inside a zone. Since I have a variety of implementations of the zone, sometimes the zone isn't the direct parent context of the custom element. Therefore I want to be able to pass the context in, injecting a specific context in. However, `this` doesn't work, like shown:

```html 
<card is-draggable.bind="false" parent-zone.bind="this"></card>
```

where `parent-zone` is the property i want to bind the context onto. It does work with `$parent` for repeat loops like shown: 

```html
<ul>
    <li repeat.for="card of zoneCards">
        <card is-draggable.bind="false" parent-zone.bind="$parent" id.bind="card.id" name.bind="card.name"></card>
    </li>
</ul>
```

My issue is that I cannot find a way to pass the current binding context to a bound property when I'm not in a repeater. Is there something available that I can use similar to `$parent`?

**Comment by EisenbergEffect** [comment]
Custom elements automatically gain access to the current binding context via the bind callback. So, if your element want to do that, simply implement a method on the custom element class with the following signature: `bind(bindingContext)`.

**Comment by LordZardeck** [comment]
@EisenbergEffect The problem is, the context can vary. I do use the `bind(bindingContext)` on some of my elements, but that provides the immediate parent. I need to control what context is given to the child custom element. is there a way to change what is passed to `bind(bindingContext)`?

**Comment by LordZardeck** [comment]
@EisenbergEffect Essentially I need to provide a specific binding context, not the immediate parent's context.

**Comment by EisenbergEffect** [comment]
There isn't a way to build that into an element. We do have a `with` behavior that lets you specify a binding context for a "section" of the DOM. You could use that. We are however going to be removing that in the next release due to the fact that it has some issues as a general behavior and we want to wait to add it officially until we can make it perfect. However, it might work for you and it's very small and easy to add to your own project. You can see the source for it here: https://github.com/aurelia/templating-resources/blob/master/src/with.js

**Comment by LordZardeck** [comment]
@EisenbergEffect So essentially there is not way to reference the current bindingContext? In angular you can set a `controllerAs: 'ctrl'` property, which you can then reference inside the views. Is there nothing similar in Aurelia?

**Comment by EisenbergEffect** [comment]
Nothing is built in at the moment. In your view model, you could create a property like this:

```
this.currentContext = this;
```

and then you could bind to `currentContext`.

**Comment by LordZardeck** [comment]
@EisenbergEffect yeah, I was thinking about that. seemed redundant, but I guess it's what I have to do.

**Comment by EisenbergEffect** [comment]
You can do that for now...then create an issue for us to build what you want ootb. If you have an inclination, you could look at adding the feature via a PR. If you have any questions on how that might work: @jdanyow is our binding guru and he can assist.

**Comment by LordZardeck** [comment]
@EisenbergEffect Will do. Thanks!

**Comment by dkent600** [comment]
Did this capability ever get improved (to where one can direclty reference the current bindingContext within a view, without having to grab it in viewmodel.bind()?  What if one is using an html-only view, relying on the template `bindable` attribute?  

Thanks

**Comment by jdanyow** [comment]
Use $this in your template

**Comment by dkent600** [comment]
@jdanyow  cool, thanks
