### ISSUE TITLE
Embedding javascript within templates doesn't seem to work?

### ISSUE THREAD

**Issue by BruceL33t** [aurelia/templating#196]
First for all I really love Aurelia so far. I'm super happy that I left Angular and React behind.

However I do have a slight problem I can't find a solution for when looking in the docs.

A client of mine was requesting a small change - in addition to the standard scrollbar at the bottom of a table, he would like me to add a scrollbar at the top.

Normally this would be fairly easy (although it sucks that browsers have no native way to achieve this).

We'd usually have to use some javascript like eg:
```
<div class="table-responsive">
    <table class="table table-bordered table-striped" id="doublescroll">
        // ...
    </table>
</div>

<script type="text/javascript">
    function DoubleScroll(element) {
        var scrollbar= document.createElement('div');
        scrollbar.appendChild(document.createElement('div'));
        scrollbar.style.overflow= 'auto';
        scrollbar.style.overflowY= 'hidden';
        scrollbar.firstChild.style.width= element.scrollWidth+'px';
        scrollbar.firstChild.style.paddingTop= '1px';
        scrollbar.firstChild.appendChild(document.createTextNode('\xA0'));
        scrollbar.onscroll= function() {
            element.scrollLeft= scrollbar.scrollLeft;
        };
        element.onscroll= function() {
            scrollbar.scrollLeft= element.scrollLeft;
        };
        element.parentNode.insertBefore(scrollbar, element);
    }

    DoubleScroll(document.getElementById('doublescroll'));
</script>
```
But I can't even get a simple

```
<script>alert("test")</script>
```

to work, regardless if I place it inside or just outside a template tag. It seems like i gets ignored completely.

I've created this thread http://stackoverflow.com/questions/33317278/the-aurelia-way-of-adding-a-horizontal-top-scrollbar-to-a-table, in hopes that anyone would know how to solve this "the aurelia way", because I do see a glimpse of hope, using ref and attach but still I can't seem to get all the way to the finish line on this.

If code inside a script tag would only execute, it would make this sooo much easier.

I'm a little astonished I seem to be the only one raising this issue.

**Comment by jdanyow** [comment]
create a custom attribute for this- here's an example:

```javascript
import {inject} from 'aurelia-framework';

@inject(Element)
export class DoubleScrollCustomAttribute {
  constructor(element) {
    this.element = element; // this is the element the double-scroll attribute appears on.
  }

  attached() {
    let element = this.element;
    // contents of your DoubleScroll function from your original post
  }

  detached() {
    let element = this.element;
    // optional:  tear-down double scroll (unsubscribe events, etc)
  }
}
```

Then change your markup to:

```html
<div class="table-responsive">
    <table class="table table-bordered table-striped" double-scroll>
        // ...
    </table>
</div>
```

(the custom attribute class was exported as `DoubleScrollCustomAttribute`... aurelia strips the `CustomAttribute` and hyphenates the name resulting in the `double-scroll` attribute you see on your table element above.

For more info on custom attributes check out the docs at aurelia.io
