### ISSUE TITLE
can't test a `@bindable` callback function with `createModelForUnitTest`

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/templating#199]
There isn't an example of how to test a simple `@bindable` function. It's not possible to stub since it's added with an `Object.defineProperty` with `writable = false`.

**Comment by EisenbergEffect** [comment]
What about this?  https://github.com/aurelia/templating/blob/master/test/behavior-testing.js#L44

**Comment by stoffeastrom** [comment]
Not the same thing. That only spies on the `valueChanged` which is a different thing. If you want to control what a @bindable function returns it needs to be possible to stub it somehow

**Comment by EisenbergEffect** [comment]
You mean you want to change the property implementation itself? Change the value that the getter of the property returns?

**Comment by stoffeastrom** [comment]
Silly example but maybe makes it more understandable
```
<div custom-attribute="get-random.call: getRandom();"></div>

export class CustomAttribute {
  @bindable getRandom = () => { return Math.random(); }
}
```
Now I want to control what the bound `getRandom();` function returns but that doesn't seem possible right now?

**Comment by EisenbergEffect** [comment]
Ok. Gotcha. Have tried getting the property descriptor, and then re-defining it with your own getter that wraps the old one but returns your value?

**Comment by stoffeastrom** [comment]
No, good idea.. will try that out!

**Comment by stoffeastrom** [comment]
So, to be able to do that this pseudo code was needed

```
let getRandom = sandbox.stub();
let vm = templatingEngine.createModelForUnitTest(Foo);
vm = Object.create(Foo, {
  'getRandom': {
    value: stubFn
  }
});
```

Maybe not the nicest but it works!
