### ISSUE TITLE
create properties in controller class for typescript definitions

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/templating#202]
[these properties](https://github.com/aurelia/templating/blob/master/src/controller.js#L14-L20) are missing from the [typescript definitions](https://github.com/aurelia/templating/blob/master/dist/aurelia-templating.d.ts#L1000-L1043)

I need this for my custom implementation of aurelia-dialog. It is giving me an error [here](https://github.com/aurelia/dialog/blob/master/src/dialog-service.js#L51) because it doesn't know of a `view` property in the `Controller` class

**Comment by EisenbergEffect** [comment]
Can you describe what you are doing that requires you to use those
properties on the Controller class?

**Comment by JeroenVinke** [comment]
I have used bits and pieces of aurelia-dialog in my own dialog helper, and I need the `view` property in the `Controller` class so that I can add it to a viewslot. I am using a custom dialog solution because I wasn't able to get aurelia-dialog to play nicely with [material-bootstrap](https://fezvrasta.github.io/bootstrap-material-design/), and this custom solution also contains logic I use within all my modals. I may reconsider this approach if [this pr](https://github.com/aurelia/dialog/pull/50) fixes my issues with aurelia-dialog though. Until then I am sticking with my custom implementation in which I am getting an error because the `view` property is not in the typescript definitions.

**Comment by EisenbergEffect** [comment]
I can expose the view and viewModel properties. That makes sense to me. Hang on a bit and we'll get a patch release with the TS update shortly today.

**Comment by EisenbergEffect** [comment]
Committed to master. Hang on a bit longer for the release. Going to fix a few other things too.

**Comment by EisenbergEffect** [comment]
Released fix.

**Comment by JeroenVinke** [comment]
Thanks!
