### ISSUE TITLE
Regression: @bindable raises TS1236

### ISSUE THREAD

**Issue by jods4** [aurelia/templating#203]
Code using `@bindable property` now raises Typescript error 1236: _"The return type of a property decorator function must be either 'void' or 'any'."_

I am unsure why TS has this restriction (no time to look it up for now), the fact is that previous `.d.ts` had decorators typed as `bindable(...): any`. Now they are typed `bindable(...): Function`, which is probably more precise but trips up TS.

**Comment by marwijn** [comment]
I've tried to look into the problem and it seems that e.g. containerless should be written like:

```
export function containerless<TFunction extends Function>(TFunction?: any) : TFunction
```

**Comment by EisenbergEffect** [comment]
Released fix.
