### ISSUE TITLE
Make .d.ts interface members optional

### ISSUE THREAD

**Issue by niieani** [aurelia/templating#205]
It would be great to get code completion for Views/Templates when using TypeScript. One way to do it now is to make those classes implement some interfaces, like `ViewNode`.
Unfortunately the implementations are marked as obligatory, while they're really not (at least not for building on top of Aurelia). 
Perhaps instead of this:
```ts
  export interface ViewNode {
    bind(bindingContext: Object, overrideContext?: Object): void;
    attached(): void;
    detached(): void;
    unbind(): void;
  }
```
We could have this:
```ts
  export interface ViewNode {
    bind?(bindingContext: Object, overrideContext?: Object): void;
    attached?(): void;
    detached?(): void;
    unbind?(): void;
  }
```
Then we could:
```ts
export class Welcome implements ViewNode {
    ///...
}

**Comment by EisenbergEffect** [comment]
Your view model is not a ViewNode. Examples of ViewNodes are the View and ViewSlot classes of Aurelia, which require implementations of all those methods. I'm not sure what implementing an interface would buy you in this case. If you place the method on your class, you will have intellisense for it.

**Comment by niieani** [comment]
Yes, I realize that a view model is not a ViewNode (but doesn't it also implement it, along with other possible methods?).
You say "If you place the method" -> this assumes that you have all those methods in hour head already, e.g. memorized from the documentation or source. I realize that proper docs are coming next week, but wouldn't it be even better to have intellisense/autocompletion with built-in descriptions for all the possible methods that a view model can have - already there, in the IDE, as we're writing the code for our apps? Full-blown documentation has it's place naturally, but quickly referencing what methods I could implement on a view model would be very beneficial too. Perhaps a separate, generic ViewModel interface could be written for this case? I'd be happy to contribute as soon as the docs are ready, but I'm not a `d.ts` expert.
