### ISSUE TITLE
ChildObserverBinder & ChildObserver

### ISSUE THREAD

**Issue by zebrooks** [aurelia/templating#207]
http://plnkr.co/edit/tWileZUIMLuKlxctWDrX?p=preview
https://github.com/aurelia/templating/blob/master/src/child-observation.js#L199

`selector is undefined`
Earlier in the same method `this.selector` was used. Typo?

Happens when using the `@children` decorator and adding children in the view with a repeat.for (as in the plunker). Works fine if the children are static.

If I change it to `this.selector` on that line I get a different error from this line:
https://github.com/aurelia/templating/blob/master/src/child-observation.js#L103
`TypeError: key.changeHandler is undefined`

**Comment by EisenbergEffect** [comment]
@zebrooks Can you provide a repro for me? I've got the first issue fixed but would like to investigate the second.

**Comment by EisenbergEffect** [comment]
Never-mind...I found the problem ;) Release coming in a few minutes.
