### ISSUE TITLE
Feature Request: @cacheStrategy decorator (or @view-cache decorator)

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/templating#209]
I'm running into a problem (which is somewhat related to #140), documented in this StackOverflow question: http://stackoverflow.com/questions/33674752/disable-view-caching-for-a-custom-element

I believe that, in this instance, the view caching is causing problems (due to `if.bind` in a parent context). I think it would be nice to be able to opt-out of view caching on a per-element basis, depending on that element's needs.

I'm not sure if there's already a way to do this. There's a blog post on durandal.io from September documenting the `view-cache` attribute, but I don't think that applies here.

It might be nice to be able to do something like this:

	@customElement('my-element')
	@containerless()
	@inlineView('<template><input type="text" ref="proxy" class.bind="class" /></template>')
	@cacheStrategy(cacheMode.none) // or something
	export class MyElement {
		...
	}

Thoughts?

**Comment by EisenbergEffect** [comment]
There is no view caching unless you turn it on.

**Comment by EisenbergEffect** [comment]
Can you describe your problem in more detail? Also, make sure you have the latest releases. We made some patch releases last night that fixed some issues with `if` and `repeat`.

**Comment by jedd-ahyoung** [comment]
I thought view caching was on by default for the `if` binding - my mistake. I updated on Tuesday, I'll try updating again and see if that fixes the issue.

**Comment by jedd-ahyoung** [comment]
I've updated and it hasn't fixed the issue. I'm attempting to create a Plunker to identify the issue, here: http://embed.plnkr.co/yqmPVJ/preview

It seems as though the base use case is working, but this isn't working in my application. Are there any known issues with having a `router-view` inside of an enclosing `if` binding, like so?

	<div id="application" class="au-animate" if.bind="isLoggedIn">
		<nav-bar router.bind="router"></nav-bar>
		<div class="page-host">
			<router-view></router-view>
		</div>
	</div>

**Comment by EisenbergEffect** [comment]
I don't imagine that's going to work....the router-view really needs to be statically present in the DOM. Instead, consider using show.bind.

**Comment by jedd-ahyoung** [comment]
Final question. I'd done it that way because I didn't want unused information in the DOM if the user isn't logged in or if they log out. Do I need to create an empty viewmodel or is there a way to clear the router-view? In past attempts I've always had to use `if.bind` or `show.bind`.

**Comment by EisenbergEffect** [comment]
What displays if they aren't logged in? Couldn't you use a router pipeline step to redirect to a login page any time someone wasn't logged in? Then you don't have to worry about hiding UI.

**Comment by jedd-ahyoung** [comment]
A login form displays if they aren't logged in, but that's also driven by
the show.bind. The reason I wanted to do it this way was to implement (in
the longer run) a login overlay in case of a timeout or something (so as
not to disrupt a current route or cause any untoward redirects). I may just
be able to use an empty view for the initial login.

Sorry to take your time on this - I definitely appreciate your efforts. The
ball's squarely in my court now. I think I'll be able to figure out a
logical design pattern.

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect I've created a working example of the bug here: http://jedd-ahyoung.github.io/if-bind-test/. Should I create a new issue for this, or is this something that you guys would flag as a wontfix?

**Comment by EisenbergEffect** [comment]
Can you describe what I should be seeing in the demo above vs. what you are expecting to see?

**Comment by jedd-ahyoung** [comment]
Sorry - just saw this. I made updates to the issue in
http://stackoverflow.com/questions/33674752/custom-element-issue-ref-element-is-null-in-viewmodel
- if you open the console and toggle the router-view, you'll see the
binding error. (Unfortunately, due to lack of style, nothing really looks
different as this is a stripped-down version. The autocomplete
functionality wouldn't work, though.)
