### ISSUE TITLE
string interpolation does not respect skipContentProcessing

### ISSUE THREAD

**Issue by Alxandr** [aurelia/templating#21]
I created a custom element (named `resource-pooled`) that has the `skipContentProcessing` metadata added. However, in the constructor of the `ResourcePooled` behavior class, if I inspect the node, I see the following:

![node](http://i.imgur.com/Tlme1xD.png)

The original html:

```html
  <resource-pooled>
    <div>I am so testing pooling here...</div>
    <div>Title (bound value): ${post.title}</div>
  </resource-pooled>
```

I would expect the html to maintain the interpolation-string (so that I can compile it myself), rather than having injected a value.

**Comment by EisenbergEffect** [comment]
I think I've got this fixed now. Going out in next release. Soon.
