### ISSUE TITLE
Scrolling to the bottom of the page when changing views

### ISSUE THREAD

**Issue by mikeobrien** [aurelia/templating#211]
I'm having a problem where after navigating to a new view the page is always scrolled to the bottom. It appears that when the new view is rendered, its rendered after the last view. In the screenshot below you can see the top of new view (Databases) and the bottom of the last view. When this new view is rendered you are scrolled down to it (As shown in the screen shot). The nodes in the old view are then removed causing the page content to shift up, but the scroll position remains the same, leaving you at the bottom of the page after it's all said and done.

![image](https://cloud.githubusercontent.com/assets/187817/11165982/8a74edde-8aef-11e5-85a2-79a7d16426ed.png)

The content that being scrolled is in a router view, so like this (Not sure if that makes a difference):

index.html

```html
<body aurelia-app="main">
</body>
```

app.html

```html
<template>
    <router-view></router-view>
</template>
```
I'm on the latest bits AFAIK, updated yesterday.

Is this a bug or am I doing something wrong?

Thx!

**Comment by mikeobrien** [comment]
Ok, just figured out what was going on right after I posted this. I am setting the focus of a textbox when the view is attached and that is what is causing it to scroll down:

```js
export class Dashboard {
    ...
    attached() {
        this.search.focus();
    }
}
```

I tried to set the focus at `bind` and `activate` but no dice. So a few questions:

1. Is there any way to set the focus of a control the way it currently renders, some time after the old view is completely gone? I guess I could do `setTimeout`, yuk.
2. Is the current rendering strategy (where it adds the new view after the old, then removes the old, see image below) a good one? Seems like it would end up causing problems as one would expect the content to be at the top of the container when it's attached to the DOM. Also, you'd expect it to be the only content in the container. Would it be better to remove the old view completely before rendering the new one? 
3. If there is some reason its rendering the way it does, could `attached` be called after the old view is removed?

Anyways, I know nothing about the view engine so I am probably just missing something.

This is what the DOM looks like when `attached` is called, notice the two views, old first, new second:

![image](https://cloud.githubusercontent.com/assets/187817/11166143/ff1a9ffc-8af5-11e5-8ec2-6a16bf0b0386.png)


Thx!

**Comment by mikeobrien** [comment]
Found [this](https://github.com/aurelia/router/issues/170#issuecomment-134948900). Counteracts the scrolling but prevents scroll restoration. Anyways, answers question one for now, but is definitely a hack.

**Comment by ZapMyR** [comment]
If you want to do something after the old view is removed <code>detached</code> (counterpart to <code>attached</code>) could help you.

I think if scroll restoration is supported by the browser api this would make a good feature to be shielded by the aurelia framework. This would give an uniform way of handling the scrolling without having to think about the actual browser implementation.

**Comment by mikeobrien** [comment]
I actually want to do something when the new view is attached, but the old view is still there when `attached` is called so it interferes.

**Comment by ZapMyR** [comment]
I think I found what you're looking for. The router-view offers swap strategies to determine how to handle the swap. The reason the old view is still present is that the default strategy aims to animate it out.
But there's a 'with'-strategy that might behave as you like.
Have a look [here](https://github.com/aurelia/templating-router/blob/master/src/router-view.js) to see the full mechanism.

**Comment by mikeobrien** [comment]
Bingo! Thx!

```html
<router-view swap-order="after"></router-view>
```
