### ISSUE TITLE
content tag not working with form elements in custom element

### ISSUE THREAD

**Issue by bemon** [aurelia/templating#213]
When trying to use 
```html
<custom-select>
    <option value="1">foo</option>
</custom-select>
```
Where custom-select is:

```html
<select>
   <content select="option"></content>
</select>
```
Custom select is not filled with option tag.
Example code: http://plnkr.co/edit/MseLZf9bSB2GwNQMlm3K?p=preview

Related Aurelia docs on this topic: http://blog.durandal.io/2015/04/24/aurelia-custom-elements-and-content-selectors/

**Comment by bemon** [comment]
@RWOverdijk

**Comment by EisenbergEffect** [comment]
I believe this is invalid HTML. @jdanyow Can yo confirm?

**Comment by jdanyow** [comment]
yep:
https://github.com/aurelia/framework/issues/192#issuecomment-150809310
