### ISSUE TITLE
Support for IE9/10 not working..

### ISSUE THREAD

**Issue by SorenMuller** [aurelia/templating#217]
Hi,

I'm not sure if this is the right place, but here goes..

I'm running Aurelia beta 1 and have added  
github:webreflection/es6-collections@master and github:polymer/mutationobservers.
also added script references in index.html..

But when I run i IE9/10, I get several errors (IE11 works fine)..

    Out of stack space
	Evaluating http://localhost/Webfragt2.Webclient/jspm_packages/npm/core-js@1.2.6/modules/es6.map.js

    Potentially unhandled rejection [2] Error: Expected object
    Error loading http://localhost/Webfragt2.Webclient/jspm_packages/npm/core-js@1.2.6/modules/es6.map.js
    Unhandled promise rejection Error: Out of stack space
    Error loading http://localhost/Webfragt2.Webclient/jspm_packages/npm/aurelia-loader-default@1.0.0-beta.1.0.1.js

Please let me know if you need more info..

**Comment by martingust** [comment]
@SorenMuller Load core-js instead of es6-collections

**Comment by SorenMuller** [comment]
@martingust I have the core-ls@1.2.6 in my solution
But which .js file should I add in index.html ??

**Comment by zloirock** [comment]
@SorenMuller [you should remove `es6-collections` from your solution](https://github.com/WebReflection/es6-collections/issues/40#issuecomment-157691113).

**Comment by zewa666** [comment]
@SorenMuller you don't need to import any .js file manually, System.js will do so. Please follow the configuration for old browsers mentioned in the new docs http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/cheat-sheet

```
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script>
  System.import('core-js').then(function() {
    return System.import('polymer/mutationobservers');
  }).then(function() {
    System.import('aurelia-bootstrapper');
  });
</script>
```

**Comment by SorenMuller** [comment]
Awesome :-)... solved it :-) Thx m8
