### ISSUE TITLE
<template repeat.for="" /> is not rendering in IE11

### ISSUE THREAD

**Issue by bennage** [aurelia/templating#22]
I have a view that looks like 
``` html
<template repeat.for="item of collection">
  <!-- some stuff -->
</template>
```
Here's the [actual template](https://github.com/bennage/pundit/blob/61e9ed1878d38f2ba8901e512b192404f80b4077/client/document.html#L15-L53).

In Chrome (and Safari) this is render as expected, however it does not render correctly in IE11.
Instead, it renders the `template` once, even if the collection is empty.

Here's a [live example](https://github.com/bennage/pundit/blob/61e9ed1878d38f2ba8901e512b192404f80b4077/client/document.html#L15-L53), please compare this in Chrome with it in IE11.

**Comment by bennage** [comment]
@EisenbergEffect I'm willing to look into this problem, but I'd like know where to start. :-)

**Comment by EisenbergEffect** [comment]
You might see if there's something going wrong in the html template element polyfill first. If there's nothing going wrong there, have a look inside the TemplateController class in the templating repo. There may be an issue there. Third place I would look is in the repeat implementation itself, in the templating-resources repo.

**Comment by EisenbergEffect** [comment]
@bennage We've identified an issue with templates in IE11. Not sure if it's your issue yet, but we found one and have a fix. It's going out in the next release.

**Comment by bennage** [comment]
Groovy

-----Original Message-----

**Comment by bennage** [comment]
When are you expecting the next release? I'm assuming this fix will be in 0.8.13?

**Comment by EisenbergEffect** [comment]
The plan is to release today. I've got to do some repo maintenance first, then I'm going to do a fresh release of all libraries. After that, you should be able to run `jspm update` to get all the latest versions.

**Comment by bennage** [comment]
I updated to 0.8.14 for templating (and everything else to the latest), however I am still seeing the problem.
Here's the [live example](http://pundit.cloudapp.net/#/bennage/pundit/0e6d64473f7a53693ac3faea5d980fbadc0b185f/README.md). (I just realized that I never pasted in the correct link above.)

**Comment by jdanyow** [comment]
In IE 11, using the live example app, when I click the "sample repository" link I hit this error:

![error](http://imgur.com/hBBhcAz)

**Comment by bennage** [comment]
Sorry, the "sample repository" link on the welcome page won't work because that is a private repo. (Though this does expose the need for better UX.)

Here's a direct link to a publicly accessible repo:
http://pundit.cloudapp.net/#/bennage/pundit/0e6d64473f7a53693ac3faea5d980fbadc0b185f/README.md

After you authenticated, it just redirected back to the home. Apologies for the confusion. Can you try the link above after you are signed in?

**Comment by jdanyow** [comment]
that worked- no errors at all this time.  Is this the right result?
![result](http://i.imgur.com/fg3YCWM.png)

**Comment by bennage** [comment]
That is what I see in IE11 as well, however that is not the expected behavior. In Chrome and Safari, it renders as expected:
![image](https://cloud.githubusercontent.com/assets/118161/6450248/6e65e802-c0db-11e4-8dbc-477fc129d920.png)

**Comment by jdanyow** [comment]
took another look- in terms of the network tab it looks like all your aurelia components are up to date except for the http-client.  Probably unrelated.

Nothing really stood out- other than the DOM Explorer clearly showed things were kind of screwy.  I wish I had a better answer for you but you might try dialing back the complexity of this view to the minimum necessary bindings/behaviors/templates necessary to reproduce the issue.  Once you get to the point where you know "adding this behavior/binding/markup breaks this in IE" we'll probably be able to help you more.

Maybe someone else will have a better idea-  in any case, let us know if you have something else you want us to take a look at- your app looks pretty cool by the way.

**Comment by sorenhoyer** [comment]
We're still facing this issue with ie11 and edge. repeat.for on the template tag doesn't refresh the page as the data changes, however when removing the template tag, it works :/

**Comment by EisenbergEffect** [comment]
@sorenhoyer Would the solution I describe in that issue work for you if we added `template-start` and `template-dend`?

**Comment by sorenhoyer** [comment]
I guess, however prefer the "repeater on the tbody tag" solution which is proposed in that other thread - just didn't think it was valid html with multiple tbody tags within one table. It works just fine in ie, edge too though :-)
