### ISSUE TITLE
ElementConfigResource ReferenceError

### ISSUE THREAD

**Issue by StrahilKazlachev** [aurelia/templating#220]
I'm trying to figure out what `@elementConfig` can do for me, but I get the following error `Uncaught ReferenceError: Target is not defined`. [This](https://github.com/aurelia/templating/blob/1.0.0-beta.1/src/element-config.js#L33) seems to be the problem, but I have no idea what `Target` should be.

**Comment by EisenbergEffect** [comment]
That is used to configure web components so that Aurelia knows how to two-way bind to them. It allows you to link properties to update events.
