### ISSUE TITLE
If I use @bindable properties called width or height they default to zero rather undefined

### ISSUE THREAD

**Issue by timfish** [aurelia/templating#224]
I've got a simple custom element which I hope to eventually use inline SVG but I've fallen well before that hurdle:

```
@customElement('inline-svg')
export class InlineSVGElement {
  @bindable src;
  @bindable width;
  @bindable height;

  attached(){
   // I will eventually inline svg here using JavaScript
  }
}
```

```
<template>
  <img src.bind="src" width.bind="width" height.bind="height" />
</template>
```
If I don't set width or height they default to zero and the attributes are added. However, if I use another name for my @bindable properties they default to undefined and the attributes are not added. So the following doesn't display as the height gets set to zero:

```
<inline-svg show.bind="!connected" src="images/no-connection.svg" width="25" />
```

I had assumed any bindable property names were fair game! Should I just be avoiding the standard HTML ones?

**Comment by jdanyow** [comment]
works for me:  http://plnkr.co/edit/nH1jUt?p=preview

Maybe the issue you're seeing was due to the missing `</inline-svg>` tag?  According to the spec, custom elements cannot be self-closing.

**Comment by timfish** [comment]
Thanks Jeremy! I thought it was more likely that I'd got something wrong.
