### ISSUE TITLE
HierarchyRequestError in IE10/9 when using nested repeat.for

### ISSUE THREAD

**Issue by Andreas-Hjortland** [aurelia/templating#225]
Hi,

When I updated from the mid-october release (aurelia-templating@0.16.0) to the beta, I encountered a problem with nested repeat statements in IE9 and IE10.

I whenever I try to open a view with a nested repeat.for I don't get any error messages, but the view won't render. When I did some digging I managed to extract the exception which was `HierarchyRequestError` and originated from the `insertNodesBefore` method of the `View` class (https://github.com/aurelia/templating/blob/HEAD/src/view.js#L177).

I managed to reproduce this issue in the skeleton navigation project (you can find it at http://hjortland.org/files/aurelia/). What I did was to append a nested repeat clause in the welcome view, and a model in the controller

welcome.html
 ```
    ...
    </form>
    <hr/>
    <div repeat.for="item of test">
      <h3>
        ${item.name}
      </h3>
      <div class="col-sm-6 col-xs-12" repeat.for="child of item.children">
        ${child}
      </div>
      <hr/>
    </div>
  </section>
</template>
```

welcome.js
```
  ...
  previousValue = this.fullName;
  test = [
	  {
		  name: 'myname',
		  children: [
			  'myname-child1',
			  'myname-child2'
		  ]
	  },
	  {
		  name: 'second',
		  children: [
			  'second-child1',
			  'second-child2',
			  'second-child3'
		  ]
	  },
  ]

  //Getters can't be directly observed, so they must be dirty checked.
  ...
```

It works fine in IE11, chrome and firefox, but in IE9 and 10 it will just swallow an error. If set a break point in the insertNodesBefore, you can get the exception.

**Comment by Andreas-Hjortland** [comment]
It seems this has been fixed in one of the releases since this issue was filed. I retried an update today and was unable to reproduce the issue.

**Comment by martingust** [comment]
Great that latest solved the issue for you. Closing this.
