### ISSUE TITLE
Animations issue

### ISSUE THREAD

**Issue by lares83** [aurelia/templating#226]
Hi,
I noticed animation issue after last update (1.0.0-beta.1.0.2).
In skeleton-navigation-app when you switch e.g. from Welcome page to Github users, users are being animated and after that "Welcome page" is disappearing.
What I've noticed is, that in the new version copy of tag ```<section class="au-animate">``` is being made, and and classes ```au-enter au-enter-active``` are being added to this copy.
In previous version copy was not being made and classes were added to an existing 'section' tag

**Comment by EisenbergEffect** [comment]
Ah yes. This was a change in the beta related to how the router view swaped out views. It was done to allow more robust animation scenarios. To make things work correctly with animation in the skeleton, add `swap-order="after"` to all `router-view` elements. I'm adding some notes to the skeleton for future developers.
