### ISSUE TITLE
Edge Browser (Windows 10) 

### ISSUE THREAD

**Issue by philcarbone** [aurelia/templating#228]
I'm not sure if the issue is actually happening with the templating or not, but I don't want to hold back from posting in case it isn't known yet. When I go to http://aurelia.io/docs.html in Edge (as an example), the page is blank. When I open the browser dev tools the page shows up fine. 

I am planning at looking at this further tonight or tomorrow, but wanted to post in case someone wanted to get a head start ;)

**Comment by philcarbone** [comment]
Also, It does show the loader but goes blank after that. It seems to be after/during the **activate** event for the view.

**Comment by jdanyow** [comment]
https://github.com/aurelia/framework/issues/227
