### ISSUE TITLE
css attribute not compiled by view-compiler or enhance

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/templating#229]
The `css` attribute on HTML elements are not compiled into a `style` attribute when compilation is done by the `view-compiler` or by `enhance`

[enhance plunkr](http://plnkr.co/edit/lrAvKL1N5N0butHKqW0R?p=info), [view-compiler plunkr](http://plnkr.co/edit/Xwk6lO82OP5o33X7wKfH?p=info)

**Comment by JeroenVinke** [comment]
ping @adriatic

**Comment by EisenbergEffect** [comment]
@jdanyow Am I correct in thinking that css isn't processed if it isn't used with .bind or a string interpolation? If that's the case, while I understand it, I think it might be an oversite on our part that leads to confusion. Let me know what you think.

**Comment by jdanyow** [comment]
Now that we use a text loader for the templates, can we automate the injection of the `css` attribute and tell people to use `style`?  I know [we cannot parse HTML with a regex](http://stackoverflow.com/a/1732454/725866)... but maybe just one specific attribute in conjunction with `${`?

For example, would something like `template = template.replace(/style=("[^"]*\$\{[^"]*")/g, 'css=$1')` introduce more problems than it solves?

**Comment by EisenbergEffect** [comment]
I'm not sure if it's a good idea or not. We would have to be sure it would work 100% correctly. That aside, we also have the "enhance" use case where there is already HTML in the DOM that we want to enhance. That means that we would still need to have support for the `css` property and document that use case. So, it's not something we could hide away.  But, maybe, with your regex, it can be used only for that one scenario? Then developers wouldn't need to think about it as much...and it can simply be pushed into a side note of the docs. Also, I just realized, that anyone using the html import loader would still need to use the `css` property.

I think we would need some more feedback.

**Comment by jdanyow** [comment]
rest of this can be tracked in https://github.com/aurelia/templating-binding/issues/23
