### ISSUE TITLE
$parent inside enhanced view

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/templating#230]
When we use the following [setup](http://plnkr.co/edit/9eaNTtSAzUsKR2Xm5BfY?p=preview), and click on the button, we get `test is not a function`.

If you rename `$parent` to `$parent1` on line 17 and 21, the button works.

Inside Kendo's Grid we have table rows. We run `enhance` on each `<tr>` and use the dataItem (which we get from Kendo) to run `bind()` on the `View` we get back from enhance. We'd like to use `$parent` to allow you to run functions on the view-model the Grid control is in. I've seen something about overrideContext, but i'm not sure if that's recommended over the $parent approach.

ping @adriatic

**Comment by EisenbergEffect** [comment]
overrideContexti is how you provide the $parent

**Comment by JeroenVinke** [comment]
Thanks, works great!
