### ISSUE TITLE
Setting style background-color fails in IE11

### ISSUE THREAD

**Issue by RalfJan** [aurelia/templating#232]
Trying to set the background-color on an input tag using a viewmodel attribute seem not to work on IE11, but works fine on Chrome.

in template html:
<p>This works in both Chrome and IE11</p>
<input style="background-color: #ff0000"/><br/>
<p>This only works on Chrome</p>
<input style="background-color:${redcolor}"/>

in Typescript viewmodel:
constructor() {
           this.redcolor = "#ff0000";
    }

**Comment by RalfJan** [comment]
First post failed since I inlcuded the html code. Sorry about that. 
The html template looked something like this:

			[input style="background-color:${redcolor}"/]

The above only work in Chrome and not in IE11. The background-color style is left out in the generated html.

**Comment by RalfJan** [comment]
We installed the Beta last week.

**Comment by jdanyow** [comment]
If you check the console, there should be a warning- IE doesn't like the `{` `}` brackets in the style attribute.

This will work:

```html
<input css="background-color:${redcolor}"/>
```

**Comment by RalfJan** [comment]
Tankyou!

Regards,

Ralf
