### ISSUE TITLE
Bootstrap tool tips not supported

### ISSUE THREAD

**Issue by Vaccano** [aurelia/templating#233]
Steps to Reproduce:

 * Fire up the skeleton navigation app (As per here:https://github.com/aurelia/skeleton-navigation)
 * Open welcom.html
      * Add the following code to the end of the first name input:  
                     `data-toggle="tooltip" data-placement="top" data-title="bootstrap tooltip" title="html tooltip"`

 * Run the app
     * Hover the mouse over the first name input.  The tool tip shows as a plain html tool tip (not bootstrap).
     * Expected: tool tip would have the back background and white text that is default for a bootstrap tooltip.

Just to be sure, I also added the following to the top the file (below `<template>`):  

     <script src="../../../jspm_packages/github/components/jquery@2.1.4/jquery.js"></script>
     <script src="../../../jspm_packages/github/twbs/bootstrap@3.3.6/js/bootstrap.js"></script>
     <script>
        $(function() { $("[data-toggle='tooltip']").tooltip(); });
     </script>

I also tried adding this to index.html 

I also added `import 'bootstrap'` to the welcome.js.  

Nothing I did could get a bootstrap styled tooltip to show.  Since other bootstrap classes work fine, I assume that this is an issue with the template's support for the popup that is in a tool tip.

**Comment by jdanyow** [comment]
Bootstrap's tooltip component requires javascript. Use a custom attribute to execute the tooltip javascript

```js
import {customAttribute, inject} from 'aurelia-framework';
import $ from 'jquery';
import 'bootstrap';

@customAttribute('bootstrap-tooltip')
@inject(Element)
export class BootstrapTooltip {
  constructor(element) {
    this.element = element;
  }

  bind() {
    $(this.element).tooltip();
  }

  unbind() {
    ${this.element).tooltip('destroy');
  }
}
```

Then on the element, add the `bootstrap-tooltip` attribute:

```html
<require from="./bootstrap-tooltip"></require>

<input bootstrap-tooltip data-toggle="tooltip" data-placement="top" data-title="bootstrap tooltip" title="html tooltip">
```

**Comment by Vaccano** [comment]
@jdanyow Thank you so very much for this code example!  I was stuck and about to have to make a hard design change on my app.  This opens it up again!  Thank you a ton!

**Comment by nomack84** [comment]
@Vaccano with Bootstrap4 which is developed on ES6, this will be even better.

**Comment by Jaans** [comment]
Thanks! For those who want to, you can also access the jQuery selector functionality from Bootstrap instead of from jQuery itself. Updated example below:

```
import {customAttribute, inject} from "aurelia-framework";
import $ from "bootstrap";

@customAttribute("bootstrap-tooltip")
@inject(Element)
export class BootstrapTooltip {
    constructor(element) {
        this.element = element;
    }

    bind() {
        $(this.element).tooltip();
    }

    unbind() {
        $(this.element).tooltip("destroy");
    }
}
```

**Comment by johnmanko** [comment]
This suggestion doesn't work, or perhaps I'm missing something.

Unhandled promise rejection TypeError: $(...).tooltip is not a function
Stack trace:
bind@http://localhost:3000/lib/attributes/bootstrap-tooltip.js!transpiled:28:13
bind@http://localhost:3000/vendor/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2774:9
bind@http://localhost:3000/vendor/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:847:9
bind@http://localhost:3000/vendor/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2766:9
automate@http://localhost:3000/vendor/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2712:7
swap/<@http://localhost:3000/vendor/npm/aurelia-templating-router@1.0.0-beta.1.1.0/router-view.js:116:9
notify/</run@http://localhost:3000/vendor/npm/core-js@2.0.3/modules/es6.promise.js:116:49
notify/<@http://localhost:3000/vendor/npm/core-js@2.0.3/modules/es6.promise.js:130:9
flush@http://localhost:3000/vendor/npm/core-js@2.0.3/modules/_microtask.js:25:7

**Comment by eliavmaman** [comment]
I m using
tooltip.js -
`import {customAttribute, inject, bindable} from 'aurelia-framework';
import $ from 'bootstrap';
@customAttribute('tooltip')
@inject(Element)
export class Tooltip {
    element: HTMLElement;
    @bindable title: any;
    @bindable placement: any;
    constructor(element) {
        this.element = element;
    }
    attached() {
        $(this.element).tooltip({
            title:this.title,
            placement:this.placement
        });
    }
}`

and view is 
` <p class="box-elipsis v-padder" data-toggle="tooltip" data-html="true" tooltip="placement:left; title:${offering}">
                    <label>Offering:</label>
                    <span class="label-value">${offering}</span>
                </p>`

the binding to ` tooltip="placement:left; title:${offering}"` not working...
any idea please?

**Comment by EisenbergEffect** [comment]
I believe there's a but with interpolation inside of an options attribute. Try `title.bind` instead and see if that fixes it for you.

**Comment by krostkowski** [comment]
With `tooltip="title.bind: ..."` it works. 
I suggest extending @jdanyow solution to sth that allows dynamic title change:

```
@customAttribute('bootstrap-tooltip')
@inject(Element)
export class BootstrapTooltip {
    $element:any;
    @bindable title:string;

    constructor(element) {
        this.$element = $(element);
    }

    bind() {
        this.$element.tooltip({title: this.title})
    }

    unbind() {
        this.$element.tooltip('destroy');
    }

    titleChanged() {
        this.$element.data('bs.tooltip', false)
        this.$element.tooltip({title: this.title});
    }
}
```
```
<i class="icon-attention" bootstrap-tooltip="title.bind: msgs"
```

**Comment by jpravetz** [comment]
@krostkowski I get a ```Uncaught Error: No method named "destroy"``` when I hide (```if.bind="show"```) a div that contains these tooltips. If I comment out the unbind method's body this goes away.

**Comment by logansgraphicd** [comment]
@jpravetz If you are using Bootstrap 4, "destroy" is now "dispose". So your code would look like: `this.$element.tooltip('dispose');`

**Comment by aurelia-next** [comment]
Bootstrap puts the content of the title attribute into data-original-title

So instead of using title.bind="..."
I used data-original-title.bind="..."

And worked a treat with dynamic changes to the title attribute.

**Comment by robscottnh** [comment]
What would this look like using Typescript?

**Comment by robscottnh** [comment]
Can anyone point me to a Typescript version of this?  I'm sure I'm making a simple mistake, but I'm new to this.  The compilation error is : Property 'tooltip' does not exist on type 'JQuery<HtmlElement>'.

The code looks like:
'''
import { customAttribute, inject } from "aurelia-framework";
import "jquery";
import "bootstrap";

@inject(Element)
export class BootstrapTooltipCustomAttribute
{
  constructor(element:any)
  {
    this.element = element;
  }

  bind()
  {
    $(this.element).tooltip();
  }

  unbind()
  {
    $(this.element).tooltip("destroy");
  }
  element:any;
}
'''

**Comment by nmocruz** [comment]
It look like a problem loading bootstrap+jQuery not Aurelia.
Typescript version be the same code, but if you are you using jspm, webpack
or other module system it can demand some configuration to use jQuery and
bootstrap together, see the bootstrap document if is this case

Em 01/12/2017 20:32, "robscottnh" <notifications@github.com> escreveu:

**Comment by nmocruz** [comment]
Sorry, I didn't saw that was a compilation error. You should install
bootstrap typings. Npm install @types/bootstrap (something like this)

Em 01/12/2017 20:32, "robscottnh" <notifications@github.com> escreveu:

**Comment by robscottnh** [comment]
Nuno,

Thank you so much.  It was a combination of needing to install the types
and updating the webpack config.  I appreciate you helping a newb out.

Regards,
Rob
