### ISSUE TITLE
Can not install aurelia-templating on Azure

### ISSUE THREAD

**Issue by jeremy-holt** [aurelia/templating#234]
(I also just posted this on SO)

Until the latest version of aurelia beta, I was happily deploying to Azure running `jspm update` as part of the deployment command.
However, since the latest beta, `update` fails with 

```
err  Error: EPERM: operation not permitted, rename 'D:\local\LocalAppData\.jspm\packages\npm\aurelia-templating@1.0.0-beta.1.0.2\dist\amd' -> 'D:\local\LocalAppData\.jspm\packages\npm\.tmp-aurelia-templating@1.0.0-beta.1.0.2'
         at Error (native)
```

In an attempt to resolve this myself I have used the following at the Kudu command prompt:

`jspm clean`

`jspm install aurelia-templating`

`jspm update aurelia-templating`

Needless to say running `jspm update` on my local machine works fine, which strongly suggests that this is a permissions problem in Azure in D:\Local\LocalAppData.

Is there some way to change the permissions in this folder, or is this a problem with the aurelia-templating package itself?

**Comment by EisenbergEffect** [comment]
It's not aurelia, but probably something with jspm. That's where I would ask the question.
