### ISSUE TITLE
Using <template replace-part="xxx"> via a <content> element does not work.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating#235]
Custom-Element "fred" template:

    <template>
        <div background="blue">
             <content></content>
        </div>
    </template>

Custom-Element "barney" template:

    <template>
       <require from="fred"></require>
 
        TITLE BANNER
         <fred>
            <template replaceable part="sub-heading-part">
               &nbsp;
            </template>
         </fred>
    </template>

User of custom-element "barney":

    <barney>
       <template replace-part="sub-heading-part">
          This is my sub-heading part.
       </template>
    </barney>

Aurelia will not replace the "sub-heading-part" template part in custom element "barney" seemingly on account of it either being inside <fred> or being injected via a <content> element within fred's template.

**Comment by EisenbergEffect** [comment]
New slot and content compilation mechanism should take care of this.
