### ISSUE TITLE
ViewEngine cannot be Dependency Injected

### ISSUE THREAD

**Issue by Vaccano** [aurelia/templating#236]
I have the following code that attempts to dependency inject ViewEngine:

        import {ErrorRenderer} from 'aurelia-breeze';
        import {ViewEngine} from 'aurelia-templating';
        import {autoinject} from 'aurelia-framework';

        @autoinject
        export class PopoverErrorRenderer extends ErrorRenderer {

            viewEngine: ViewEngine;

            constructor(viewEngine: ViewEngine) {
                super();
                this.viewEngine = viewEngine;
            }
            //....

When I do this, I hit the following error in aurelia-templating.js:

Error: A BindingLanguage must implement parseText(...) at

aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:547:13) at ViewCompiler._compileNode aurelia-templating.js:1930:79) at ViewCompiler._compileNode
aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1950:33) at ViewCompiler.compile 

Why does it think I want a new binding language?  I just want to be able to call `enhance` on my attribute I added when a validation failed.

SIDE NOTE: I am trying to do this because in https://github.com/aurelia/framework/issues/102 Rob says that "the ViewEngine has an enhance method that works for "activating" elements".  I am hoping that will work to make my custom attribute be recognized when it is added dynamically.

**Comment by EisenbergEffect** [comment]
Are you manually resolving your PopoverErrorRenderer from the container before `aurelia.start()` has completed?

**Comment by Vaccano** [comment]
You are absolutely correct.  Once I moved it inside the `aurelia.start`, it worked fine.

Thank you for the help!
