### ISSUE TITLE
How to have a parameter in function in a repeat.for

### ISSUE THREAD

**Issue by stphdenis** [aurelia/templating#239]
How can we get `x` as a parameter of `getYs()` ?
```
      <div repeat.for="x of xs">
        <tr repeat.for="y of getYs(x)">
           ...
```
`getYs()` is in the same controler as `xs`.

**Comment by EisenbergEffect** [comment]
Please ask questions at gitter.im/aurelia/discuss
The GitHub issues are a place for bugs and feature requests.
