### ISSUE TITLE
Loading html files dynamically.

### ISSUE THREAD

**Issue by shivajiraot** [aurelia/templating#240]
I need to load html files dynamically that use the same view model as the parent. (Do NOT have their own view model). Example: I have files named file1.html, file2.html etc.. Looking to achieve something like the below.
```
<require from='sections/file1.html'></require>
<require from='sections/file2.html'></require>
<div repeat.for="section of sections">
<file${section.id}/>
</div>
```
Can someone point to a solution or correct way of doing this please?

**Comment by EisenbergEffect** [comment]
For this you want to use the `compose` element. It can dynamically compose view, view-models and models in any combination. If you compose only a view, it will bind to the view model of the containing view.

```html
<compose view="sections/file1.html"></compose>
```

**Comment by shivajiraot** [comment]
Thanks @EisenbergEffect  for the quick and perfect response.
