### ISSUE TITLE
too much recursion error when import package from three levels up

### ISSUE THREAD

**Issue by devmai** [aurelia/templating#243]
I got an error when I ``` import Highcharts from '../../../lib/highcharts';``` in my custom element chart class. 

Console log in FF43 says: 
```ERROR [app-router] InternalError: too much recursion```
and even Chrome47 says: 
```Unhandled promise rejection RangeError: Maximum call stack size exceeded
    at Container.elementContainerGet [as get] (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.0.2/aurelia-templating.js:1470:28)```

Stepping up to 10 parent folder level as default would be fine or it should be configureable with ```aurelia.use.maxRecursionLevel``` in export function configure(aurelia).

**Comment by EisenbergEffect** [comment]
Can you create a simple project that reproduces this error? I'd like to take a look at what is going on there.

**Comment by devmai** [comment]
As I tried to set up a blank aurelia-skeleton for reproducing I saw after "npm install" something like that. So it's not an error of Aurelia but Node and npm install won't work for now. Strange.

```C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targ
ets(355,5): error MSB6006: "CL.exe" wurde mit dem Code 5 beendet. [D:\skeleton-
navigation\skeleton-es2016\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\skeleton-navigation\skeleton-es2016\node_modules\bufferutil
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok```

**Comment by devmai** [comment]
The problem was not the templating engine. 
The view of the custom element (Custom Element View Declaration) had ```<mychart></mychart>``` instead pure html code. Also I used in another view (Custom Element Use ) with ```<require from="../widgets/mychart"></require>  
    <div class="container-fluid">
        <mychart></mychart>         
    </div>```
It wasn't a real issue of Aurelia templating.
