### ISSUE TITLE
Enhance not initializing custom elements/attributes imported via require

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/templating#245]
Plunker: http://plnkr.co/edit/7CyNhwEBharrG7vdbiYQ

In the plunker above, I have two buttons. The first button adds a `<red-square>` and a `<blue-square>` custom element to the DOM.

The second button calls enhance on the div containing the red and blue square. What I expect is `attached()` to be called on both custom elements (red and blue square custom element).

The blue square custom element is globalized via `globalResources('blue-square')` in `main.js`, and the red square custom element is imported via `<require>`. Enhance calls the lifecycle callbacks correctly on the blue square, but doesn't with the red square.

Should this work?

**Comment by EisenbergEffect** [comment]
You need to pass the ViewResources along so that it knows what is available to use to enhance with.

**Comment by EisenbergEffect** [comment]
I'm seeing that our api docs are missing some information. Apologies on that. Something is going wrong with the generation process. You can see what you pass to the enhance call here:

http://aurelia.io/docs.html#/aurelia/templating/1.0.0-beta.1.0.3/doc/api/interface/EnhanceInstruction

If you provide the ViewResources, it will work. You can have those injected into your view model to get the resources for its view.

**Comment by JeroenVinke** [comment]
Just tried this out, but it doesn't seem that `red-square` (which is imported via `<require>`) is on the ViewResources instance.

Plunker of this is here: http://plnkr.co/edit/Co2B4UBgr7v8qU5jQ7XL?p=preview

![image](https://cloud.githubusercontent.com/assets/2189477/12217555/7b65df56-b704-11e5-8736-8a6e66506605.png)

**Comment by JeroenVinke** [comment]
@EisenbergEffect can you help me out with the above question? Perhaps I'm doing something wrong. 

it would possibly allow us to do something like this:

``` 
  <require from="./my-custom-element"></require>
  <k-grid k-data-source.bind="datasource">
    <k-col title="Contact Name">
      <my-custom-element></my-custom-element>
    </k-col>
  </k-grid>
```

without having to globalize `my-custom-element` in `main.js`

**Comment by EisenbergEffect** [comment]
Enhance won't account for requires right now. Instead, when you call enhance, you can pass it a ViewResources instances that contains the resources the compiler should use. You can have ViewResources injected into any custom element to get the resources that are available where that element is defined. If you have your requires in the outer view and then pass this injected resources through to the enhance call, it should work. Does that make sense?

**Comment by JeroenVinke** [comment]
That makes sense yes, and I believe I'm doing that [in this plunker](http://plnkr.co/edit/Co2B4UBgr7v8qU5jQ7XL?p=preview). However, I don't see the `red-square` in the injected ViewResources.

**Comment by EisenbergEffect** [comment]
It doesn't work in that case because you will get injected the view resources of where the component is used. The app component isn't inside of any view with resources, so you get the global resources. You do not get the resources of your own view..it's the resources of the view that your element is used inside of.

**Comment by EisenbergEffect** [comment]
But you can get your own view's resource...implement the created callback and that will give you, as the second parameter,  your own View instance. From that you can get the viewFactory that produced the view...and from that you can get the resources available inside your own view.

**Comment by JeroenVinke** [comment]
you guys have really thought about everything :+1:  thanks

**Comment by EisenbergEffect** [comment]
Well...I had to really think about that and check the source code. I knew you could get it, but it's not an every day thing :)

**Comment by rockResolve** [comment]
FYI There is no typescript support for view.viewFactory
Wanting to use as suggested:

    created(owningView: View, myView: View) {
        let containingViewResources = owningView.viewFactory.resources;
        ...
