### ISSUE TITLE
No bindings between a <compose> view and the main application controller

### ISSUE THREAD

**Issue by yd021976** [aurelia/templating#248]
Hello,
don't know if it's a question, issue or request, but when testing aurelia framework i discover that there's no way to bind data between an application (main VM) and the underlying VM <compose>.

Let's make an exemple :
`main application view model`
```javascript
Export class mainApp {
  mainData : [];
  anEvent(newdata){
    this.mainData = newData;
  }
}
```
`main application view`
```html
<template>
  <div>
     <compose view='foo.html' view-model='foo.js' model.bind='mainData'></compose>
  </div>
</template>
```

In this example, when the `mainData`is changed there is no updates in the 'foo' view even if model is binded with `model.bind='mainData'`

Is it a bug or am i wrong doing this ?

Thank you

**Comment by EisenbergEffect** [comment]
The `activate` method on your `foo.js` class will be called whenever the value of `model` changes. If the array's items change, that is separate from the value of the `mainData` property changing.

**Comment by yd021976** [comment]
Thanks for your quick reply. But i'm not sure i get your second part "If the array's items change, that is separate from the value of the mainData property changing". In this case (array's items change), i understand that the `activate` method will not be called, and so i understand the value of `model` will not update.

In addition, in my example `mainData`is populated with an http request (with httpClient) that return a promise called in the `attached` method.
I think there is a problem with it because the `mainData` model binded to `foo.js` is not updated and the `activate` method is not called once the data are processed in the 'main' application.
