### ISSUE TITLE
Custom element and custom attribute both inheriting from the same superclass

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/templating#249]
In the plunker below I have a custom element (bar) and a custom attribute (foo), both inheriting from the same `SuperClass`.

When you add a @bindable property to the SuperClass, Aurelia starts to act weird. For example, it tries to load foo.html while that is a custom attribute (and custom attributes don't have html files)

Is something like this possible?

Plunker: http://plnkr.co/edit/9MMca6?p=preview

**Comment by EisenbergEffect** [comment]
We don't support inheritance for behaviors currently. There's an existing issue to incorporate that in the future.

(In general we actually want to discourage the use of inheritance. In the entirely of the Aurelia framework there are only one or two instances of inheritance at all.)

**Comment by adriatic** [comment]
The response of the Aurelia support team :-) is simply superb. Thanks Rob - as this issue caused some headaches today

**Comment by EisenbergEffect** [comment]
You're welcome! Apologies for the loss of time.

**Comment by sylvain-hamel** [comment]
@EisenbergEffect can you provide the link to that other issue please? We would use inheritance for custom elements if it were supported. Thanks
