### ISSUE TITLE
Possible problem with @children depending on location of <content>

### ISSUE THREAD

**Issue by csaloio** [aurelia/templating#250]
Please see this plunker:
http://plnkr.co/edit/0yEcM9eDlyaR5LnsjYZg?p=preview

If `<content>` is not nested the array created by `@children` is correct. WHen it is nested the array is always empty.

**Comment by EisenbergEffect** [comment]
Thanks for reporting this! We need to do some improvements how how `@children` works internally and those should fix this issue.

**Comment by charlespockert** [comment]
Was wondering when this would be fixed. Not a massive issue for me but it saves me having to use an extra div every time I want an instance of a certain control
  https://github.com/aurelia/templating/issues/218

**Comment by MikaelPorttila** [comment]
Any updates on this issue?

**Comment by EisenbergEffect** [comment]
Quick update on this. We are working on a solution. However, the fix is probably going to have to wait until we update to Shadow DOM v1 because the implementation details are strongly connected. We'll do a bit more research this week and see if there's a way we can address it before then.

**Comment by EisenbergEffect** [comment]
This issue is now fixed in our shadow dom v1 branch.
