### ISSUE TITLE
Default binding mode not obeyed of custom attributes on input tags

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/templating#253]
I have a bindable inside a custom attribute with two-way binding as default. When I put this attribute on an input tag and use `bind`, the default binding mode is ignored and one-way databinding is used.

plunker: http://plnkr.co/edit/aKqPmKlrRHXEu39BzJRV?p=preview

**Comment by jedd-ahyoung** [comment]
@jdanyow This may need to be tagged as a bug.

**Comment by Thanood** [comment]
This seems to apply to ```<select>``` elements, too.
http://plnkr.co/edit/g2i582ZL29bhLEiXobhG?p=preview

**Comment by Vaccano** [comment]
Not sure if it adds info for this bug, but I hit it while doing the "options" style binding too.

[http://stackoverflow.com/questions/35658280/two-way-binding-in-an-aurelia-custom-attribute](http://stackoverflow.com/q/35658280/16241)
