### ISSUE TITLE
Call `changed` callbacks after all bound properties are assigned during the initial bind phase

### ISSUE THREAD

**Issue by sylvain-hamel** [aurelia/templating#257]
This is a request to change the timing of when `changed` callbacks are called during the `bind()` phase.

**Current timing:** The `changed` callbacks are invoked progressively, as the bound properties are set. The order in which they are called is not guaranteed.

Therefore this code does not work because in one `changed` callback the _other_ property will not be bound yet:

```
@bindable attr1;
@bindable attr2;
attr1Changed(){
   this.DoSometingWith(this.attr1, this.attr2);
}
attr2Changed(){
   this.DoSometingWith(this.attr1, this.attr2);
}
```

**Proposed timing:** The `changed` callbacks should be invoked after all bound properties are set.

I have already discussed this with @EisenbergEffect.

**Comment by jdanyow** [comment]
@EisenbergEffect what were your thoughts on this ^^

**Comment by EisenbergEffect** [comment]
It's something we could do. I haven't looked into it to see how easy/hard it would be. The logic is in the Controller class's bind method. My only concern is that changing this might affect perf or memory negatively. I need to dig in though...

**Comment by EisenbergEffect** [comment]
@jdanyow This may not be that hard to change. See here: https://github.com/aurelia/templating/blob/master/src/controller.js#L107 We could remove the code related to self subscribers and then after the first loop, check to see if we aren't supposed to skip, and if so, loop again, invoking the callbacks. I think that would do it. I'm not sure if this would be a big perf change or not though, for scenarios where there were bindables and no bind callback. What do you think?

**Comment by jdanyow** [comment]
Sounds like a good plan to me. If I had to guess I'd bet that it doesn't impact the templating benchmarks.

**Comment by bigopon** [comment]
@EisenbergEffect We already have `bind` to handle this case. Does the plan mean we separate the logic call after all properties bound out of `bind` to `changed` ?

**Comment by EisenbergEffect** [comment]
It's about timing. In the event where someone does not have a `bind`, the first time the change callbacks are called as part of the binding phase, they would/should all be called together after all properties are bound. Right now each callback is fired after each property is bound.

**Comment by Alexander-Taran** [comment]
could not find the issue recently closed by @EisenbergEffect 
with a comment that a new lifecycle event 'bound' will be introduced in vNext

guess that would solve this

maybe can be closed

**Comment by EisenbergEffect** [comment]
This is a bit different. But, I don't think we're going to make the exact change proposed by this issue. Instead, we'll probably consistently fire a `bound` event and property change events.
