### ISSUE TITLE
Child Router view replacing element in the parent

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/templating#260]
I wanted to know if it's possible using replaceable parts to have a child router view define content that will be replace in it's parent upon render. I couldn't find any example of how to do this and I've been trying different ideas but to no luck. 

Basically in the parent view we have a couple of action buttons which change depending on the child view selected, we don't want to have to absolute position them and would rather they naturally fit into the flow.

**Comment by EisenbergEffect** [comment]
It's not possible to accomplish it in that way, no. However, it's not difficult to do it using other techniques. One idea is to use the EventAggregator. Have your parent view model subscribe to an event and then have the child view-model publish that event with any necessary information. The parent view-model, can then recieve the event data and use that to build up a UI in the parent's view.

**Comment by devteamexpress** [comment]
Ok i thought about that as well, thanks for the quick response!
