### ISSUE TITLE
repeat.for can't be used with nested compose tag in a table structure

### ISSUE THREAD

**Issue by jsobell** [aurelia/templating#261]
Trying to adapt the rows of a table based on a repeat.for variable, so the code goes something like this:
```
<tbody>
  <tr repeat.for="j of jobs">
    <compose view="./jobs_${j.jobType}.html"></compose>
  </tr>
</tbody>
```
The imported view is a simple sequence of valid `<td>data</td>` tags

Unfortunately, the templating engine seems to consider this invalid, presumably due to the presence of the `<compose>` tag, and after attempting to load a resource `./jobs_.html` it ignores the loop.
Replacing the above code with at least one set of `<td>` tags renders the content (but of course breaks the layout)
```
<tbody>
  <tr repeat.for="j of jobs">
    <td><compose view="./jobs_${j.jobType}.html"></compose></td>
  </tr>
</tbody>
```

**Comment by EisenbergEffect** [comment]
It's not an issue with templating issue per se. Rather the browser won't allow foreign elements inside the tr. The browser itself removes them before the framework has a chance to handle it. If you have the latest release of aurelia,  you could try this out

```
<tbody>
  <tr repeat.for="j of jobs">
    <td as-element="compose" view="./jobs_${j.jobType}.html"></td>
  </tr>
</tbody>
```

**Comment by jsobell** [comment]
This won't work, as it's essentially identical to the sample I showed that breaks the layout, because the `<td>` surrounds anything in side it, including other `<td>` elements.

**Comment by jsobell** [comment]
It's like we need a way of ordering the `<tr>` tag to inject the composed values. Like a `child-element='compose'` sort of thing

**Comment by EisenbergEffect** [comment]
Can't you remove the td from your template?

**Comment by jsobell** [comment]
The `TD`s, plural. Sorry, the example I gave was a simplification for testing. The actual content has about 6 columns, and there are 5 templates for different job types.  The only way to do that would be to remove the outer two, making the remaining html non-conformant, so unfortunately not.
This is a real sod of a problem for us. We can't even paste in all five sub-templates with `show.if` conditions, as we'd have to create 30 templates and interweave them in the middle of each `<td></td>`, as there's not a common tag that we can apply the condition to other than the `<tr>` tag itself. I first thought we could create five `<tr>` blocks with an if.bind, but that would mean injecting a tag between `<tbody>` and `<tr>` which is also invalid!

**Comment by jsobell** [comment]
Here's a similar solution in some appallingly unreadable framework that I can hardly bear to read, let alone develop on:
[http://plnkr.co/edit/pHTrlnRNYijjzQYlRjto?p=preview](http://plnkr.co/edit/pHTrlnRNYijjzQYlRjto?p=preview)
Do we have anything along the same lines?

**Comment by EisenbergEffect** [comment]
If you wouldn't mind providing a more extensive example of what you are trying to do in Aurelia, I'd like to help you find a solution. I think we could leverage the new as-element on the tr but I would need to see a bit more code that shows some more intricacies of your scenario.

**Comment by jsobell** [comment]
Sure, here's a plunker of the same concept I'm trying to apply: [http://plnkr.co/edit/Bdym9H?p=preview](http://plnkr.co/edit/Bdym9H?p=preview)
Essentially, this is a list of jobs. Each job type has its own properties and display template, so for each job in the list we want to display that template.
Because the data is tabular, it resides in a table, which means the contents of each row is its own template.
A workaround would be to replace all tables of this type with css columns, but for people using tables to display various items it's common to replace the row to avoid a huge number of conditional classes within each div.
Adding containerless to the `compose` tag lets us create valid HTML, but by then it's too late as the content has already been stripped.
Perhaps what we need is an attribute to indicate that a tag is simply their as an html framework placeholder, and it should be stripped at bind time?
e.g.
```
<tr repeat.for="r of ['A','B','A','B','A','B']">
   <td placeholder><compose view='./rowtype${r}.html' componentless></compose></td>
</tr>
```

**Comment by EisenbergEffect** [comment]
Why can't you just do something like this?

```
<table>
    <tr>
      <th>Code</th><th>Info</th><th>Index</th>
    </tr>
    <tr repeat.for="r of ['A','B','A','B','A','B']" es-element="compose" view='./rowtype${r}.html'>
    </tr>
  </table>
```

**Comment by jsobell** [comment]
Yes, that was the obvious solution I tried :)
[http://plnkr.co/edit/Bdym9H?p=preview](http://plnkr.co/edit/Bdym9H?p=preview)
The first issue appears to be that the binding of the view attribute doesn't get performed, so ${r} is never resolved (as shown in the console load errors).
However, even if you substitute a valid fixed view name, it still doesn't render, so it looks like there may be a couple of issues related to this.

**Comment by EisenbergEffect** [comment]
That plunkr probably doesn't have the as-element feature since it was just released a few days ago. I'll look into it locally.

**Comment by jsobell** [comment]
Yep, the latest version works fine, awesome stuff!
Can I suggest you ask someone to add that solution to the section in the cheat-sheet about using repeat to generate valid tables?  I'm not yet familiar enough with Aurelia to do write it up properly. Give me another month or so...
Thanks

**Comment by EisenbergEffect** [comment]
@jsobell Would you mind creating a separate issue for adding the docs on this? If so, we can probably get it in this week.

**Comment by bb-harlan** [comment]
I stumbled upon this thread while searching for how to do something that is conceptually like this:

     <my-component repeat.for="listItem of itemList"></my-component>

But **my-component** cannot see the repeat.for variable **listItem**. I haven't know about the **compose** element or the **as-element** attribute. I cannot find where they are documented. Can you point me to where I can read about them. I am wondering whether they might be a solution to what I need to do..

**Comment by EisenbergEffect** [comment]
You can read about the compose element in the cheat-sheet here: http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/cheat-sheet/6'

I'm not sure if the docs for `as-element` made it in yet, but you can just provide an element name to that attribute and it makes one element act like another.

**Comment by bb-harlan** [comment]
So I tried the following which did not work..

    <template repeat.for="listItem of dataProvider">
      <compose as-element="acct-view" view-model.bind="listItem"></compose>
    </template>

Any suggestions?

**Comment by bb-harlan** [comment]
Eureka! This works!

    <template repeat.for="listItem of dataProvider">
      <compose model.bind="listItem" view-model="./acct-view"></compose>
    </template>

**Comment by EisenbergEffect** [comment]
That's definitely not right..but I'd need more information to be able to advise you. A better place to get help is in our gitter chat room: gitter.im/aurelia/discuss

**Comment by jsobell** [comment]
@bb-harlan Here's a blog example of the as-element being used within a table:
http://www.sobell.net/dynamically-adding-row-templates-to-a-table-in-aurelia/

**Comment by EisenbergEffect** [comment]
Maybe whoever wrote that blog post wants to send a PR to the cheat sheet ;)

**Comment by jsobell** [comment]
OK, can do

**Comment by HojjatK** [comment]
Anyone has any idea how can I get a recursive template working?
The following doesn't work.

Here's what the **_tree-list_** template looks like:
```
<template>
    <require from='./tree-list-node'></require>
    <table>
        <tbody>
            <tr repeat.for="node of nodes" 
                             model.bind="node" 
                             columns.bind="columns" 
                            as-element="tree-list-node"></tr>            
        </tbody>
    </table>
</template>
```

and Here's what the **_tree-list-node_** template looks like:

```
<template>
    <tr show.bind="model.visible" style="display:flex;">
        <td>${model.title}</td>
        <td repeat.for="col of columns">${model.payload[col.name]}</td>            
    </tr>
    <tr repeat.for="node of model.children" 
                             model.bind="node" 
                             columns.bind="columns" 
                             as-element="tree-list-node"></tr>
</template>
```

Thank you
