### ISSUE TITLE
target isn't used in BindableProperty.registerWith, remove it?

### ISSUE THREAD

**Issue by jhoguet** [aurelia/templating#263]
I found myself trying to figure out what I was going to pass in as `target` only to discover that isn't actually used. 

https://github.com/aurelia/templating/blob/master/src/bindable-property.js#L46

Can I remove this?

**Comment by EisenbergEffect** [comment]
Why are you even using this api? What in the world are you doing?

**Comment by jhoguet** [comment]
experimenting ;)

**Comment by EisenbergEffect** [comment]
Gotcha. Well, we are trying not to make breaking changes in apis at this point, so we aren't going to remove that, even though it isn't used. Thanks for digging in though!
