### ISSUE TITLE
Documentation update request

### ISSUE THREAD

**Issue by jsobell** [aurelia/templating#264]
Can the cheat-sheet section `Templating Basics / Correct Table Code` have a section added to explain:

1. how the browser will strip invalid table structures, preventing Aurelia reading compose statements nested directly below `<table>`, `<thead>`, `<tbody>`, or `<tr>` tags
2. how use of the `as-element` attribute can be used to 'inject' a composed element into one of these restrictive elements, bypassing the browser's trimmer

```
<table>
   <tr repeat.for="r of ['A','B','A','B']" as-element="compose" view='./tpl_${r}.html'>
   </tr>
</table>
```
will inject templates named `tpl_A.html` and `tpl_B.html` into rows of a table.
Each template might be of the following format:
```
<template><td>Col 1</td><td>Col 2</td><td>Col 3</td></template>
```

**Comment by EisenbergEffect** [comment]
Got it :)
