### ISSUE TITLE
if.bind does not preserve order

### ISSUE THREAD

**Issue by Exsilium122** [aurelia/templating#265]
It looks like aurelia if binding is inserting elements into DOM in some random order.

View:

    template
        p.text-center(show.bind="type!=='login'")
            a(href="#login ", click.delegate="setType('login')") Remember password?
        p.text-center(show.bind="type!=='remind')
            a(href="#remind", click.delegate="setType('remind')") Forget password?
        p.text-center.text-muted(show.bind="type!=='register'")
            small Register
                a(href="#signup", click.delegate="setType('register')") Register

ViewModel:

    export class LoginDialog {
        type = 'login';
        setType = (type) => {
            this.type = type;
        }
    }

If I use show.bind every time I get the same result. I guess it is because if.bind removes and inserts DOM elements. show.bind only CSS hide them. So there must be some event concurrency and if.bind is always appending elements to parent?

**Comment by EisenbergEffect** [comment]
The `if` binding places a comment node anchor into the DOM at the same location as the conditional content. It then prepends the conditional content before the comment anchor node when the condition is truthy.
