### ISSUE TITLE
Feature request: support $this with enhance

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/templating#270]
I noticed that we can use $this in Aurelia templates to get a reference to the context, but it returns `undefined` when `enhance` is doing the compilation.

plunker: http://plnkr.co/edit/ZI88Uu?p=preview

**Comment by jdanyow** [comment]
Updated to latest Aurelia bits: https://gist.run/?id=7c8dc8af39bf26046e374abba409328f

@EisenbergEffect is this really a bug?  Is there any way for the templating engine to know what the binding context is in scenarios where a DOM element is passed to the `enhance` method instead of a `EnhanceInstruction` with a `bindingContext` property?

https://github.com/aurelia/templating/blob/master/src/templating-engine.js#L80

**Comment by EisenbergEffect** [comment]
Correct, it's not a bug if a binding context isn't passed in.

**Comment by JeroenVinke** [comment]
Passing the context to bindingContext allows $this to work, so that's great. But now it doesn't pick up the overrideContext: https://gist.run/?id=b9939a488d6158ebef4285eee1c1ebb8

Do I still need to call .bind() myself? How would we pass the overrideContext to the enhance call as [this line](https://github.com/aurelia/templating/blob/master/src/templating-engine.js#L94https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js) only passes one argument to .bind() which is the bindingContext. this);
    view.attached();
```

**Comment by EisenbergEffect** [comment]
Ah, well that's a bug. That must have been missed when we added the override context implementation. @JeroenVinke Any interest in submitting a PR to add overrideContext to the EnhanceInstruction as well as pass that through to the bind call?

**Comment by JeroenVinke** [comment]
Sure, I'll take a stab at it.

**Comment by JeroenVinke** [comment]
OK, so now I'm able to pass an overrideContext and enhance will pass that to bind(). But now the real issue is showing.

Check out this gist: https://gist.run/?id=cda6266d95db146fd58699cd3b27e043. Note that this gist doesn't use the latest aurelia-templating yet, so it doesn't pass a bindingContext or overrideContext to enhance(). Instead, a .bind() call is used on the View that's returned from enhance(). The issue is the same.

As you see in the gist I enhance two divs. With one I pass an overrideContext to bind() and with the other I don't. `$this` only works when you don't use an overrideContext. Strangely `$this.someVar` works both scenarios

**Comment by JeroenVinke** [comment]
Got it, it works when I wrap my overrideContext in a `createOverrideContext` call: https://gist.run/?id=69e65deae65bacfc4eb0928514ed5fbe

Important bit: `view.bind(ctx, createOverrideContext(ctx, this));` where `createOverrideContext` comes from `aurelia-binding`.

I guess the next question is: should `enhance()`  or the caller of `enhance` use `createOverrideContext`?

**Comment by EisenbergEffect** [comment]
This question is best answered by @jdanyow

**Comment by jdanyow** [comment]
If you're supplying the `overrideContext`, it's best to use `createOverrideContext` to create it.  This will ensure things are wired up correctly.

although this looks like it would work: `view.bind(ctx, createOverrideContext(ctx, this));`

To match how it would be modeled in non-enhance scenarios you might want to do this:

```js
const parentBindingContext = this;
const parentOverrideContext = createOverrideContext(parentBindingContext);
const bindingContext = { foo: 'bar' };
const overrideContext = createOverrideContext(bindingContext, parentOverrideContext);
view.bind(bindingContext, overrideContext);
```

**Comment by JeroenVinke** [comment]
Works like a charm, thanks :+1: 

![image](https://cloud.githubusercontent.com/assets/2189477/14940620/be091cfc-0f7d-11e6-91f5-68f731d64748.png)

**Comment by EisenbergEffect** [comment]
Do we need to change something in our enhance implementation to make this better?
