### ISSUE TITLE
Issues binding an InlineViewStrategy to a different binding context

### ISSUE THREAD

**Issue by mbroadst** [aurelia/templating#275]
I (perhaps stupidly) updated to the most recent releases, and this code which used to work:

```
<img class="ui middle aligned mini image" src.bind="someTransformMethodOnTheVM(data)">
```

No longer works, and no longer works silently. Instead I just get a bunch of errors in the console about not being able to access `http://localhost/blah/blah/undefined`, meaning that the expression is evaluating to undefined. `someTransformMethodOnTheVM` is a method defined on the VM backing the current view. Was there any relevant change in this area recently? This worked for me as recently as `aurelia-framework@^1.0.0-beta.1.0.5`. 

Thanks!

**Comment by jdanyow** [comment]
just a guess- this may not be the issue- but I'm betting the markup above is part of a custom element's template and the method you're binding to is not a property on the custom element's view model, it's a property in the outer scope- is that correct?

There was a bug in previous releases that broke custom element encapsulation and allowed a custom element template to bind to stuff it shouldn't have had access to, making the custom element not portable.

Apologies if I'm way off here.

**Comment by mbroadst** [comment]
@jdanyow yeah I think that's exactly what's going on here. I have an example plunker from a while back when I created this thing [here](https://plnkr.co/edit/LSmSiL?p=info). The use case for this would be to bind something inside the "second" column in app.html. Do you have any thoughts as to how I might emulate this behavior now that the bug has been fixed?

**Comment by mbroadst** [comment]
@jdanyow specifically, it seems that I already have the plumbing to explicitly provide a view model to the `column` component, however I'm not sure how to:
  a) specify `this` as the view model
  b) default to specifying `this` as the view model

Any sort of tips would be very much appreciated here, please let me know if I can clarify this at all

**Comment by mbroadst** [comment]
Sorry for all the updates, but I just wanted to add any clarifications I could as I worked through this:

So what seems to be happening here is that my "default" behavior is to take the `innerHTML` of the column and convert it to an `InlineViewStrategy`, then using it as a `view` (not `view-model`) with compose - which, according to do the docs "inherit[s] the parent binding context". In this case that "parent binding context" would in fact be the `grid` not the VM that's _using_ the grid, correct?

I _think_ the solution is to use that as the `view` and then to somehow pass the grid's parent in as the `view-model` in that compose. Does this sound correct? How exactly does one do that? :)

**Comment by jdanyow** [comment]
you could do something like this:

**my-component.js**
```js
export class MyComponent {
  @bindable dataContext;

  bind(bindingContext, overrideContext) {
    Object.assign(overrideContext, dataContext);
  }
}
```

Another thing you could try instead is something like this:


**my-component.js**
```js
export class MyComponent {
  @bindable dataContext;
}
```
**my-component.html**
```html
<template with="dataContext>
  ...
</template>
```

**Comment by mbroadst** [comment]
@jdanyow see the particular problem here is that the custom component is being created dynamically as an `InlineViewStrategy` and then popped into a `compose`, I'm not sure how I would override the binding context to be the parent VM of the view using the `Grid` this way.

**Comment by mbroadst** [comment]
@jdanyow I think taking a look at the plunker might make this more clear? It's a bit convoluted in terms of implementation, but it makes the actual user experience pretty fantastic

**Comment by mbroadst** [comment]
Okay I think I fixed this but perhaps not in the most optimal way. In `grid.js` I took your advice and saved off the binding context:

```
class Grid {
  @children('column') columns;
  @bindable dataContext;

...

  bind(bindingContext, overrideContext) {
    this.dataContext = bindingContext;
  }

....

}
```

and then in the `grid.html` did the following:

```
          <compose if.bind="!!column.template" view.bind="column.template" view-model.bind="dataContext"></compose>
```

Is that what you had in mind? Does anything look "off" about that (in particular since you chose to use `Object.assign` above)?

**Comment by mbroadst** [comment]
@jdanyow what I've noticed with this approach is that I now get debug messages for loading resources for the `dataContext` for every row in my `repeat.for`:
```
DEBUG [templating] importing resources for http://localhost:9000/dist/guests/guests.js []
```

**Comment by mbroadst** [comment]
Hey, so I've updated this plunker here to the code I'm currently running locally (and experiencing this duplication of resource loading with): https://plnkr.co/edit/RJezkP. Unfortunately, while you can definitely see that with the bound `dataContext` you get an import for the context for every row displayed, this example doesn't exactly work because the plunker isn't up to date (and therefore the bug hasn't been fixed, disallowing access to the parent context). 

Is there a way to force caching of that VM (`dataContext`) so it's not loaded for every displayed row?

**Comment by mbroadst** [comment]
Hm, well I've spent about 2 hours trying to track down why exactly this VM is loaded that many times (in fact in my case I have two other VMs inside some of my columns, so for a page of 20 entries I actually have this debug message ~100 times!).  Alas, I'm just not up to snuff enough on the binding/templating system.

@jdanyow if you have any hints to point me at were I should look at in the code it would be much appreciated, but for now it seems like this feature might be dead in the water and I'll have to use an alternate approach for my grid.

**Comment by jdanyow** [comment]
@mbroadst sorry for the late reply.  I took a look at the plunker and might have an approach for you. It will require more research to implement but will be vastly more performant than building the grid out of nested repeats, compose, if, etc.

Really the grid component you're building is a much more advanced `repeat` which is what's known as a "template controller" in the aurelia framework. The repeat has one template that it "controls" by repeating it over an array. In your grid's case each column has a header and cell template that need to be repeated in a couple different directions.

Currently template controllers have to be custom attributes but we have an open issue for enabling custom elements to be template controllers here: https://github.com/aurelia/templating/issues/171

Hopefully this is helpful, I know it's pretty high level. I haven't had a chance to try creating a grid element using this approach.  I'm guessing aurelia interface's grid will do something along those lines but not 100% sure.  Definitely not a trivial undertaking.

**Comment by mbroadst** [comment]
@jdanyow thanks for taking a look.

Your observations that this is like an advanced `repeat` ring loud and clear, and bring new insight into the problem indeed. There seem to be a few extra missing pieces in terms of converting this thing into a `@templateController` (on top of the pretty important lack of an ability to assign this to a custom component), specifically that the template controller only allows a single template where this grid wishes to allow a number of different view options:
 
   * the raw template (this would be handled by `@templateController` iiuc)
   * a custom element with bindings to the current row
   * a custom view (sans view-model) with bindings to the current row

I would love to dig into these (and absolutely will), however I wonder if there is any sort of method where I might get around the issue with the current implementation _today_? The code itself works the same as before, but where the view model bound to each row used to be shared (due to the bug referenced above) it no longer is.  Getting this fixed would free up a lot of time on my part towards refactoring the code into something like you've outlined above.

**Comment by jdanyow** [comment]
was talking with @mbroadst and put together a minimal repeat attribute to help illustrate what a template controller does:

https://gist.run/?id=60ee02d25797518a9330

**Comment by jdanyow** [comment]
@mbroadst can this be closed?

**Comment by mbroadst** [comment]
yep, sorry!
