### ISSUE TITLE
CustomEvent detail not getting passed

### ISSUE THREAD

**Issue by bhaeussermann** [aurelia/templating#277]
I created a custom element and added a custom event to it exactly as described [here](http://ilikekillnerds.com/2015/08/aurelia-custom-elements-custom-callback-events-tutorial/).

When the event triggers my function is called, but the event parameter does not contain the detail property.

On Firefox the event is `{"isTrusted":false}`.  
On Chrome the event object is empty: `{}`

The blog post suggests that this has worked before. I'm using `aurelia-framework@1.0.0-beta.1.1.3`

**Comment by EisenbergEffect** [comment]
This shouldn't have anything to do with Aurelia since it's just a standard DOM event. Can you share some code with me or a sample project we can test?

**Comment by bhaeussermann** [comment]
I don't what I've been doing wrong, but it's working now. Thanks! :)
