### ISSUE TITLE
attribute.createBinding is not a function on Firefox

### ISSUE THREAD

**Issue by SPARTAN563** [aurelia/templating#281]
# What Happens
Running Aurelia (`aurelia-templating@1.0.0-beta.1.1.1`) on Firefox (tested on 44.0.2) results in an unrecoverable exception being thrown when launching - preventing the application from loading its views correctly. This manifests as the application bootstrapping but displaying no content in its `<router-view>`.

This issue is not present when running the application under Chrome (tested on 48.0.2564.116) and was not present in older versions of the `aurelia-templating` library (tested against `aurelia-templating@1.0.0-beta.1.0.3`).

# Suspected Line
[src/bindable-property.js@L177](https://github.com/aurelia/templating/blob/master/src/bindable-property.js#L177)

# Stack Trace

```
TypeError: attribute.createBinding is not a function
Stack trace:
_initialize@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js:3165:65
Controller@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js:2800:9
create@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js:3490:24
applyInstructions@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js:1693:20
create@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js:1917:9
create@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.1/aurelia-templating.js:3501:29
process/<@http://localhost:9000/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.1.1/router-view.js:96:42
notify/</run@http://localhost:9000/jspm_packages/npm/core-js@2.1.3/modules/es6.promise.js:87:49
notify/<@http://localhost:9000/jspm_packages/npm/core-js@2.1.3/modules/es6.promise.js:101:9
flush@http://localhost:9000/jspm_packages/npm/core-js@2.1.3/modules/_microtask.js:25:7
```

Please let me know if there is any additional information I can give you which will assist in rectifying this as quickly as possible.

**Comment by EisenbergEffect** [comment]
To fix this, we will need a reproduction. Please create a simplest possible repro of the bug on the nav skeleton project. You can attach the src folder here. That will enable us to drop it into our test environment and see what is happening.

**Comment by SPARTAN563** [comment]
I'll see what I can do - unfortunately I'm very time constrained at the moment on both this and another project, so no promises.

**Comment by SPARTAN563** [comment]
That being said, I have an externally available instance on which you can reproduce this - it's not particularly simple but it's the best I can offer right now.

http://beta.farmtracksa.com

**Comment by EisenbergEffect** [comment]
I loaded the app and everything seems to work fine. Is there something I should be doing to trigger the error?

**Comment by SPARTAN563** [comment]
Busy deploying a build now which allows you to enable Aurelia's diagnostic output (using `localStorage.setItem('debug', true)`). Issue currently manifests as no content appearing on screen.

Just noticed that the build has bundling enabled, if you'd like me to remove that I can do so (may make debugging easier).

**Comment by EisenbergEffect** [comment]
Sure...but I can't actually reproduce the bug. It runs fine in FF for me. What version are you running? What OS?

**Comment by SPARTAN563** [comment]
That's very curious indeed, running Firefox 44.0.2 on Windows 10 x64 - and the issue was brought to my attention by one of our testers (also Firefox 44.0.2, but Windows 8.1 x64 in that case).

**Comment by EisenbergEffect** [comment]
I'm running the same version, but on OSX. It takes a sec to load, but does appear to work. @AshleyGrant Can you try out the link above on FF on Windows?

**Comment by SPARTAN563** [comment]
Just to confirm, this is what we're expecting to see:

![image](https://cloud.githubusercontent.com/assets/1760260/13519516/0e8f521a-e1e1-11e5-9263-4a51d50e2d15.png)

While this is what we're seeing on Firefox

![image](https://cloud.githubusercontent.com/assets/1760260/13519521/1bdcfc88-e1e1-11e5-8025-742badfccad6.png)

**Comment by EisenbergEffect** [comment]
Ah, well, that's different. Yes. I can confirm the erratic behavior.

**Comment by SPARTAN563** [comment]
Perhaps my description could be a bit clearer - Aurelia does seem to start correctly, however fails during initialization of its initial view. Let me quickly update the description to clarify that.

**Comment by EisenbergEffect** [comment]
I don't see any errors in the console though. Are you seeing errors? Or is it just failing silently for you?

**Comment by SPARTAN563** [comment]
I do see errors, provided I enable debug logging with `localStorage.setItem('debug', true)` - also seeing them come through on our Sentry backend.

**Comment by EisenbergEffect** [comment]
Is there a chance you can create a simple repro? Or do you have no idea where the scenario is that causes this? Also, are you using the latest Aurelia libs. We've had some fixes, even a few minutes ago. On a long shot...try running jspm update to see if the problem goes away.

**Comment by SPARTAN563** [comment]
I'm not entirely certain, I suspect it's got something to do with a complex interaction somewhere - though I can certainly try and debug it from my side as well.

It should be running the latest libs as of 1h ago - but let me update them again and see if it has an effect.

**Comment by EisenbergEffect** [comment]
I literally just released a couple of fixes. So, on an off chance, see if that makes any difference.

**Comment by SPARTAN563** [comment]
Latest update (ran `jspm update` again right now) seems to have made some progress - getting the following error now, unfortunately the internal error doesn't provide much in the way of detail (aside from a line number).

Looking at that line, it's adding a custom router pipeline step to run during the `loading` step:

```typescript
config.addPipelineStep('authorize', createRouteFilterStep('loading'));
```

```
Error: Error invoking RouterView. Check the inner error for details.
------------------------------------------------
inner error: App</App.prototype.configureRouter@http://localhost:9000/dist/app.js:20:49
registerViewPort/_ret5</_ret6</<.v.v<@http://localhost:9000/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.3/aurelia-router.js:1483:30
configure@http://localhost:9000/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.3/aurelia-router.js:706:18
registerViewPort/_ret5</_ret6<@http://localhost:9000/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.3/aurelia-router.js:1482:24
registerViewPort/_ret5<@http://localhost:9000/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.3/aurelia-router.js:1477:28
registerViewPort@http://localhost:9000/jspm_packages/npm/aurelia-router@1.0.0-beta.1.1.3/aurelia-router.js:1473:22
RouterView@http://localhost:9000/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.1.2/router-view.js:70:1
invokeWithDynamicDependencies@http://localhost:9000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:359:12
invoke@http://localhost:9000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:339:155
invoke@http://localhost:9000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:587:16
get@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1624:64
get@http://localhost:9000/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1.1.5/aurelia-dependency-injection.js:524:14
elementContainerGet@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1681:12
create@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:3555:48
applyInstructions@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1759:20
create@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:1983:9
create@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:3567:29
createController/<@http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.4/aurelia-templating.js:3954:16
```

**Comment by AshleyGrant** [comment]
@SPARTAN563 can you provide some sense of what `createRouteFilterStep` looks like. If you don't want to share it publicly, you can PM me on Gitter. Maybe we can figure this out!

**Comment by SPARTAN563** [comment]
Hi @AshleyGrant, that is (/was) being imported from `aurelia-router` - I'm trying to figure out why that was present previously but isn't now, as well as why that is now not present (ran a `jspm update` again just now).

The function, to my understanding (and I implemented it a while ago, so this may be off) was responsible for creating a new pipeline step category which executed as part of the provided step.

This allowed us to construct a pipeline as follows:

```typescript
config.addPipelineStep('authorize', createRouteFilterStep('loading'));
config.addPipelineStep('loading', LoadingIndicatorStep);
config.addPipelineStep('authorize', AuthorizeStep);
config.addPipelineStep('authorize', NotAuthorizedStep);
config.addPipelineStep('authorize', PermissionStep);
config.addPipelineStep('analytics', GoogleAnalyticsStep);
config.addPipelineStep('modelbind', createRouteFilterStep('analytics'));
```

Obviously, having an `authorize` step which executed as part of the loading step, as well as an `analytics` step which executed during the `modelbind` phase.

**Comment by AshleyGrant** [comment]
Did you get it from here originally? https://github.com/cmichaelgraham/spike-aurelia-ts-port-dts-gen/blob/master/aurelia-ts/router/route-filters.ts

**Comment by EisenbergEffect** [comment]
OH! You are using `createRouteFilterStep`! That was removed in the latest release. That was never intended to be a public API and we didn't know that anyone was using it. Our apologies! The internals of the pipeline step configuration have been reworked but the high level API is the same. There are now strongly typeed methods for each phase of the pipeline. Here's the link to the API: http://aurelia.io/docs.html#/aurelia/router/1.0.0-beta.1.1.3/doc/api/class/RouterConfiguration

Also, you can see how the steps are arranged here: https://github.com/aurelia/router/blob/master/src/pipeline-provider.js#L21

If you update to use the new methods or step slot names, that may solve your problem.

**Comment by SPARTAN563** [comment]
Haha, that would explain it - I'm afraid I don't recall where I got it from originally, have been on Aurelia since 0.13.0 with this project, so it's gone through a lot of changes over that time.

Will quickly update everything to the new API and check whether that fixes the issue we were seeing with `attribute.createBinding` (it may simply have been hidden as a result of the other).

**Comment by SPARTAN563** [comment]
Right, new version is up (<http://beta.farmtracksa.com>) and unfortunately we're back to the original `attribute.createBinding` issue. Just confirmed that I've got no errors in Edge either, so specific to Firefox.

**Comment by SPARTAN563** [comment]
Finally have had some time to track down the cause of this - in our case it was related to the `@bindable` decorator in which the `attribute` property was specified. Specifically, if there was an existing property on the view model whose name matched the `attribute` then it would be called [here](https://github.com/aurelia/templating/blob/master/src/bindable-property.js#L179) as `attribute` and things would break.

## Example Component

```typescript
import {bindable} from "aurelia-framework"

@bindable({
  name: "testAttribute",
  attribute: "test",
  defaultValue: "testing"
})
export class TestComponent {
  testAttribute: string;
  
  test() {
    console.log(this.testAttribute);
  }
}
```

We were also using the component something like this (relying on the default value).

```html
<require from="test-attribute"></require>

<test-attribute></test-attribute>
```

Curiously, this wasn't an issue in IE Edge or Chrome, however it would reliably fail in Firefox until I renamed the `test()` function/property.

**Comment by EisenbergEffect** [comment]
The above sample usage doesn't seem to make sense. The element name doesn't match the component in any way. Are you sure the code provided here is correct?

**Comment by SPARTAN563** [comment]
Sorry about that, was intended to be `test-component` - in the specific case in which it occurred I had not provided the `test-attribute=""` attribute, however it may have failed if that were provided as well (not tested).

**Comment by EisenbergEffect** [comment]
So, if I copy/paste the code above into a project, I will see the error?

**Comment by SPARTAN563** [comment]
Not 100%, let me put together a repro - however I that was the only change required to get our project working. Give me 1h or so to get that to you

**Comment by SPARTAN563** [comment]
Now that's very curious - the code I gave you there doesn't reproduce it, however I just noticed that the specific component (which matches that structure, but uses different attribute names) does definitely do so.

Drilling down, I was able to reproduce it using `{ attribute: "watch" }` (which is what we have specified on our component).

So, to reproduce, the following will suffice:

```typescript
// create-binding-fail.ts
import {bindable} from "aurelia-framework";

@bindable({
  name: "watchAttribute",
  attribute: "watch"
})
export class CreateBindingFail {
  watchAttribute: string;
}
```

<template>
  <require from="create-binding-fail"></require>
  
  <create-binding-fail></create-binding-fail>
</template>

**Comment by EisenbergEffect** [comment]
Ah! Ok, so this is a bug we understand ;) Have you tried updating to the latest releases? I believe we have this issue fixed.

**Comment by EisenbergEffect** [comment]
Oh...wait it might not be in this case. Please let me know if you are on the latest release though. I do understand the issue here, which is good.

**Comment by SPARTAN563** [comment]
Just ran a `jspm install` from the latest skeleton-navigation project, so I suspect it should be the latest bits, however I'll quickly try again to make 100% certain.

**Comment by SPARTAN563** [comment]
Unfortunately no luck with the latest bits (`1.0.0-beta1.2.7` of `templating-binding`)

**Comment by EisenbergEffect** [comment]
Ok, I think I understand the cause. It is related to naming the property `watch` which conflicts with a non-standard Firefox API on objects.

**Comment by SPARTAN563** [comment]
I see, good to know and something I've worked around in our project, may be worth adding a warning about it if there isn't a good workaround (i.e. if `typeof attributes[this.attribute] !== 'string'`) which may also catch things like naming it `toString` (haven't tested, but I imagine you could cause trouble doing stuff like that).

**Comment by EisenbergEffect** [comment]
Fixed.
