### ISSUE TITLE
Compose-ref on a model-property in repeat.for-scope does not bind the reference to the property.

### ISSUE THREAD

**Issue by MikaelPorttila** [aurelia/templating#282]
Hi I'm trying to access child compose scopes hosted within a repeat.for scope from the parent using compose.ref on model property but the property will never bind to the ref.
```Javascript
<div repeat.for="model of models"> 
    <span>Repeat index: ${$index}, name: ${model.name}</span>
    <compose compose.ref="model.composeref" view-model="./myview" model.bind="cat"></compose>
</div>
```
from the parent I want to access the compose contexts something like this:
```Javascript
someMethod(){
this.models[0].composeref.somePropertyFromTheComposeViewModel.
}
```
I have built a working plunker of the issue:
http://plnkr.co/edit/timkNg2zBDz6x0qj9YY0?p 
any known fixes for this problem?

**Comment by EisenbergEffect** [comment]
The compose ref isn't going to give you access to your composed view model That gives you access to the instance of Compose (the view model that backs the compose element itself). Doing what you are doing isn't stricly using our public apis, so be ware. But if you want the instance of your own view model from that, you need to reference the `currentViewModel` of the Compose view model.

**Comment by dhanapalschandran** [comment]
@EisenbergEffect I have a scenario where i need to change the view after it has rendered which is  <compose view.bind="view" view-model.bind="viewModel" repeat.for="view of views"></compose> , when i try to reassign views[0] = "newview" , that is not rerendering the dom, could you help me to achieve this
