### ISSUE TITLE
Ability to import functions and data into templates

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating#287]
http://stackoverflow.com/questions/35889226/is-it-possible-to-make-a-function-or-class-available-to-all-views-in-aurelia

discussion: :point_up: [March 5, 2016 12:10 PM](https://gitter.im/aurelia?at=56db12eb68ddef776468dde9)

**Comment by EisenbergEffect** [comment]
Yes, I think we'll add a new api to ViewResources which will get invoked by the View during its bind phase. This would allow writing view engine plugins that add things to the override context, making them available to bind.

Basically, it would be an official way to do what @bryanrsmith did for his CSS Modules experiment and it would open up the door to a number of other possibilities as well.

**Comment by mikefills** [comment]
Can someone shed some info why a value converter or a custom attribute won't suffice for that scenario?

**Comment by EisenbergEffect** [comment]
For the scenario in the SO question, it probably would. But we are considering adding view local data that comes from other sources besides the view model. An example of this might be a set of constants that aren't needed in a view model at all, but that are needed across a bunch of views. A concrete example of this could be "theming" or customer "branding" for mulitenant sites. The demo our team member did was with CSS Modules, which allow private, modular styling of components through providing a special "styles" variable that is available in the view. Some of these scenarios would be very hard or impossible with value converters.

**Comment by mikefills** [comment]
thank you Rob, this helps a lot on learning Aurelia

**Comment by EisenbergEffect** [comment]
implemented.

**Comment by dabide** [comment]
@EisenbergEffect, how has this been implemented?
