### ISSUE TITLE
Strange behavior using repeat with compose inside

### ISSUE THREAD

**Issue by leosbrf** [aurelia/templating#289]
I'm trying to use compose inside repeat, but after a number of elements being repeated, the values of my input change unexpectedly (when attached). I have code sample ([here](https://github.com/leosbrf/aurelia)). Some screenshots:
![works](https://raw.githubusercontent.com/leosbrf/aurelia/master/screenshots/Ok%201.png)
![strange behavior](https://raw.githubusercontent.com/leosbrf/aurelia/master/screenshots/Not%20ok%201.png)

[Other images here](https://github.com/leosbrf/aurelia/tree/master/screenshots)

**Comment by andrevlins** [comment]
cc @jdanyow @EisenbergEffect 

This strange behavior is preventing us from updating the framework.

We have an application in production in a large hospital and so far this was the only case in which we did not get a clear upgrade.

BTW thanks for your excellent work!

**Comment by jdanyow** [comment]
@leosbrf / @andrevlins are you guys still seeing this behavior?

https://gist.run/?id=ee6f3c41825b329e2caa

**Comment by andrevlins** [comment]
Yes I'm. Even in your gist.run example after a few attempts with random values ​​the strange behavior happens.

**Comment by leosbrf** [comment]
Yep. I had to workaround using jQuery and, in this case, Im not using aurelia to bind the properties.

By the way, the framework is awesome!

**Comment by leosbrf** [comment]
Hi, @jdanyow . Any news on this?

**Comment by jdanyow** [comment]
@leosbrf it's a race condition- here's an updated gist where the issue is fixed:
https://gist.run/?id=0574a263a84a8219d81b49e235fe4e40

Click on the revisions tab to see the change that fixed the issue.

**Comment by leosbrf** [comment]
Thanks for the clarification, @jdanyow . I thought that putting the expression in the bind() method the result of it would be calculated before the element creation. Isn't that the expected behavior?

**Comment by jdanyow** [comment]
bind is called after the element is data-bound.  This meant that the `min` was assigned null first, then later assigned min-step, leading to the weird behavior you were seeing.
