### ISSUE TITLE
using a compose inside a manually compiled template

### ISSUE THREAD

**Issue by mbroadst** [aurelia/templating#290]
Can someone more familiar with the internals of the templating engine explain to me why the following code results in an error: https://gist.run/?id=b74bbe825d8e38927947

The code snippet in question is:
```
render() {
  let template =
    `<template><compose view="some-view.html"></compose></template>`;
  let viewFactory = this.viewCompiler.compile(template);
  let view = viewFactory.create();
  this.viewSlot.add(view);
}
```

Where I'm trying to manually compile a compose element (this is for the experimental grid component I've been working on). 

The error is `TypeError: Cannot read property 'createChild' of undefined` because on [this line](https://github.com/aurelia/templating/blob/master/dist/aurelia-templating.js#L2162) `containers` has a single member `root` whose value is `undefined`. I've been doing pretty well getting through templating the past few days, but don't fully grok it hence this error. 

Any help would be much appreciated!

**Comment by mbroadst** [comment]
Hmm it looks like if I inject `Container` and then use that as the first parameter of `viewFactory.create` it works. I'm still a little confused as to why `repeat` gets away without having to do something similar (it just calls `viewFactory.create()` with no arguments at all)

**Comment by EisenbergEffect** [comment]
The repeater gets its view factory as a BoundViewFactory, which is slightly different. That is a special view factory that is already "bound" to a particular template extracted from the DOM as well as a Container instance based on the hierarchy from where the template was extracted.
