### ISSUE TITLE
Conditional css require / dynamic css loading

### ISSUE THREAD

**Issue by b-barry** [aurelia/templating#293]
Hello,

I have a special use case where I have to load a specific css link based on the url.
I tried to perform a if.bind on a require template statement to change de loading but it is not working.
I tried to bind a value (saved in app.js)  to the "from" of a require template statement, it is not working.
Do you have a way to perform this kind of theming in aurelia ?

**Comment by EisenbergEffect** [comment]
`require` elements are statically analyzed and don't support binding, much like ES2015 `import` statements. If you can provide some more details we can help you find a solution.

**Comment by b-barry** [comment]
For your website, we would like to change the css loaded based on the sub domain. For example, when someone navigate to sub.domain.com , we would like to load the custom theme of sub in the fly. 
So during the loading time of aurelia, we would to be able to load the custom CSS link such as CDN.subcss.example. com

Thanks for the help

**Comment by StrahilKazlachev** [comment]
Couldn't you add an appropriate mapping in SystemJS before starting the app?

**Comment by b-barry** [comment]
I don't enough know System js to perform the mapping.
Could You provide a example/ sample ?

**Comment by b-barry** [comment]
After your question @StrahilKazlachev , I tried the code below in the index.html
```javascript
 <script>
    const hasSubdomain=window.location.host.split('.').length>2;
    if(!hasSubdomain){
      System.import('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css');
    }
    System.import('aurelia-bootstrapper');
  </script>
```
However I got a CORS error and I would prefer doing in the aurelia btw.
Is the mapping that you are speaking ?

**Comment by StrahilKazlachev** [comment]
No, this way you are loading it.
```
System.config({
  map: {
    styles: the_path/some_styles.css!text
  }
});
```
You will need the systemjs `text` plugin, you should have it btw, not sure at the moment if aurelia was using it to load the css. Also I'm not exactly sure if this is the correct way to map when using a plugin. Check it out in the systemjs repo, you may also want check the `paths` config. But this way you should be able to use one alias for the styles and map it to what you want before starting the application.
About the CORS, you will get it even if you mange to load it from the application.

**Comment by b-barry** [comment]
@StrahilKazlachev with this mapping, do you not override the basic config of Aurelia js ? How I can change it in the fly ?

**Comment by StrahilKazlachev** [comment]
You will override only if there are collisions. You can not make changes to the config after the app starts loading.

**Comment by b-barry** [comment]
@StrahilKazlachev It seems working but I always got the XHR errors.
@EisenbergEffect Do you know a other way to perform this dynamic loading by using aurelia ?

**Comment by EisenbergEffect** [comment]
Aurelia's startup mechanism is async, so you could always just add a script tag dynamically at startup. There are lots of ways it could be done...

**Comment by b-barry** [comment]
Thanks for the support. I will do it like this
