### ISSUE TITLE
Strange Rendering Behavior since 1.1.4 release

### ISSUE THREAD

**Issue by devteamexpress** [aurelia/templating#294]
I understand as part of the new aurelia release there was some work done on minimizing the visual popping

We have code which looks like this
    <i show.bind = "router.isNavigating"  class="fa fa-spinner fa-spin"></i>
    <div show.bind = "router.isnavigating"></div>

This has served us well in the past. Now we are experiencing that when the router.isNavigating becomes false meaning the view is shown it's the old view and it takes a noticeable amount of time till the new view comes into play. Is this a bug or is their a different way to code to support the scenario?

**Comment by EisenbergEffect** [comment]
I can't see your code, but first please run `jspm update` to make sure you have the latest. There were a few fixes in that area. If that doesn't fix the problem, then we will need you to create a simple reproduction on the skeleton repo and attach it here so we can run it, see the problem and identify a fix.

**Comment by devteamexpress** [comment]
I only ran the jspm update today so unless there were releases since then its still broken. I guess I will need to roll back till this is resolved since this is rather noticeable.

**Comment by EisenbergEffect** [comment]
It won't get fixed unless you can provide a repro. We need that to see the bug in action and track down the cause. If you can put that together, I can take a look at it myself early this week.

**Comment by devteamexpress** [comment]
I will try to get this to you this morning. If this helps it seems to happen whenever i navigate to a view which contains a compose element in which the acitvate function of that compose element returns a promise.

**Comment by devteamexpress** [comment]
I got it to happen

Basically i moved all the code from the users page into another view called additionalview and just used a component element instead. I added a promise delay to simulate a call.

If you start on the welcome page and switch to the users page you will see the loading sign comes on but when it finishes it first shows the welcome page again and then jumps to the user page. 

https://github.com/GrocerKey/skeleton-navigation

Meanwhile I have rolled back our code base. Please let us know when you have more information.

Thanks

**Comment by devteamexpress** [comment]
Any update on this?

**Comment by devteamexpress** [comment]
Anything guys over here? Still waiting to upgrade

**Comment by devteamexpress** [comment]
So after playing around with it a bit more this is what i find- the parent viewmodel waits for all composed elements to activate before rendering , but the router doesn't respect that and only waits for the parent viewmodel to activate. So as soon as the viewmodel activates the router shows the screen but since the children haven't activated yet the new view hasn't rendered
does this make any sense to anybody

**Comment by EisenbergEffect** [comment]
This is odd. It seems like you've got a mixture of new and old stuff happening. I'll take a look atyour example above shortly and see if we can get to the bottom of this.

**Comment by devteamexpress** [comment]
It seems to be related to a composition transaction. If a view has a
compose tag within it where the compose tags activate function takes time .
The router navigation complete event will not wait till all compose tags
activate. Using router.isNavigating doesn't work in this scenario because
it becomes false right away, but the view only actually shows up  once all
compose tags have activated.

I have tried on the latest aurelia and will provide a screen cast of the
issue shortly
On Apr 21, 2016 00:01, "Rob Eisenberg" <notifications@github.com> wrote:

This is odd. It seems like you've got a mixture of new and old stuff
happening. I'll take a look atyour example above shortly and see if we can
get to the bottom of this.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/aurelia/templating/issues/294#issuecomment-212604405>

**Comment by devteamexpress** [comment]
Here is a screencast of what happens

https://temp-temp-grocerkey.s3.amazonaws.com/Untitled%20Screencast%20%281%29.webm

**Comment by EisenbergEffect** [comment]
Ok, the issue is coming from the fact that the router.isNavigating is changing to false before the actual view has been swapped. The router is done with it's work but I think we aren't aggregating all the way through to the end of the view swap and its animation. @bryanrsmith Is there a way we can easily fix this?

**Comment by bryanrsmith** [comment]
@EisenbergEffect Sorry, I don't know how the animation is set up. Looks like the router runs the swap as part of the last pipeline step here: https://github.com/aurelia/router/blob/master/src/navigation-instruction.js#L215. `isNavigating` is updated after that step completes. Does `viewPort.swap()` kick off async work that should delay the completion of the pipeline? If so we can probably just `Promise.all()` the swap promises.

**Comment by EisenbergEffect** [comment]
We could fix up the swap an process methods of the router-view to return a promise. @bryanrsmith If we did that would it be an easy fix on your end to just drop a Promise.all? That should delay the update to the isNavigating flag, correct?

**Comment by bryanrsmith** [comment]
Yep

**Comment by EisenbergEffect** [comment]
Ok, i'll make some of the fixes in the templating router piece and then ping you here so you can fix up the router itself.

**Comment by devteamexpress** [comment]
Is their any update here. We received a report that this bug is always happening on the iphone.

**Comment by EisenbergEffect** [comment]
The issue hasn't been fixed yet but we believe we have a way to do it. It should be fixable for the Release Candidate.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/router #365](https://github.com/aurelia/router/issues/365) via [**ZenHub**](https://www.zenhub.com/)
