### ISSUE TITLE
owningView of App.created is null

### ISSUE THREAD

**Issue by doktordirk** [aurelia/templating#295]
```js
export class App {
  created(owningView, myView) {
    //owningView === null !?
  }
}
```
owningView is null on startup. i expected it to be `body`

-----
created(owningView: View, myView: View) 
- If the view-model implements the created callback it is invoked next. At this point in time, the view has also been created and both the view-model and the view are connected to their controller. *The created callback will recieve the instance of the "owningView". This is the view that the component is declared inside of*. If the component itself has a view, this will be passed second.

**Comment by EisenbergEffect** [comment]
`body` isn't a View. A `View` is an aurelia-specific structure. There is literally no `View` instance outside of the App. I suppose we could create a special null view to use in this type of scenario...I'm not sure though. What were you hoping to accomplish here?

**Comment by doktordirk** [comment]
basically i wanna fix something in my code which was never nice in the place. :)

anyways, i basically found now what changed with the last framework update

 in eg the skeleton app the order of events are:

* prior to last framework update:
a) app constructor/created
b) app attached
c) welcome constructor/created  <--- after app attached, thus save to use document.body (this includes the contructors of all first time injected classes)
d) welcome attached

* after last framework update:
a) app constructor/created
c) welcome constructor/created  <--- before app attached, thus NOT save to use document.body
b) app attached
d) welcome attached

now, whether it's a good idea to have used document.body is a different thing. it's just that change of the order which surprised me. i happily accept the new order of events, but persistent as i can be, i wanna make really really ;) sure, that this change isn't a bug

**Comment by EisenbergEffect** [comment]
No, this change isn't a bug. It's a result of our new ability to track nested compositions of UI and aggregate them into a single DOM render update.

**Comment by doktordirk** [comment]
@EisenbergEffect  ok, thanks, for the info (and aurelia :) )
