### ISSUE TITLE
Possible templating bug in IE11

### ISSUE THREAD

**Issue by oneillci** [aurelia/templating#296]
I am getting an 'out of stack space' error in IE11. I _think_ it's due to usage of a replaceable template-part with the `BindingEngine.enhance` method. My code runs fine in Chrome & FF.

I have a sample project with a simple reproduction at:
https://github.com/oneillci/templating-engine-possible-bug

Hopefully the README contains enough information to understand the issue.

**Comment by oneillci** [comment]
I have simplified the reproduction as I was originally using a kendo grid and templates. I have removed this usage and the behaviour still exists.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look at this?

**Comment by oneillci** [comment]
Have you had a chance to look at this yet @jdanyow?

**Comment by jdanyow** [comment]
@oneillci sorry for the wait. Did you get this resolved?  I gave it a quick look- lot going on in there!

**Comment by jdanyow** [comment]
@oneillci - let me know if this needs to be re-opened
