### ISSUE TITLE
Cannot use oneTime as the defaultBindingMode

### ISSUE THREAD

**Issue by sylvain-hamel** [aurelia/templating#298]
- See here http://plnkr.co/edit/d9EXNNoYixWB6J4bqomI?p=preview
- Open source tab
- search for this line : `this.defaultBindingMode = this.defaultBindingMode || _aureliaBinding.bindingMode.oneWay`;
- set a conditional breakpoint `nameOrConfig.name === "foo"`
- run

When the debugger stops, `this.defaultBindingMode` equals `0` which is the value for `bindingMode.oneTime`. Therefore the boolean expression returns the *OR* side because 0 is *falsy*.

**Comment by EisenbergEffect** [comment]
LOL Good catch. I think we can address this pretty easily. Thanks!

**Comment by EisenbergEffect** [comment]
Any interest in creating a PR and getting your name in the credits?
