### ISSUE TITLE
Should bound values of dashed "attributes" be assigned to dashed properties or camelCase 

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/templating#300]
@jpray commented on [Sat Mar 19 2016](https://github.com/aurelia/framework/issues/370)

Hi!

I have a bunch of vanilla custom elements that I'm working on using within an Aurelia app.  A standard interface for custom elements are HTML attributes, so I was a bit surprised to see that something like
```
  <my-vanilla-custom-element
    bar=${aValueForBar}
  </my-vanilla-custom-element>
```
would assign the value of aValueForBar to the bar property and not set the attribute.  But after reading more I came to accept that this was probably done for performance reasons, though I do think it would still be nice to have an option to have it set the attribute without having to declare a custom attribute.  I assume this is technically feasible?  I wouldn't mind taking a stab at implementing it if you all think it makes sense and could provide some direction.  Maybe an alternative syntax to have templating behave this way?

Also, during this exercise I noticed that when doing something like this

```
  <my-vanilla-custom-element
    foo-bar=${aValueForFooBar} 
  </my-vanilla-custom-element>
```
this['foo-bar'] will contain the value.  Here's a [plunker](http://plnkr.co/edit/y3BRrPOelHejTrTJZmXn?p=preview) illustrating this.

For my own vanilla custom elements, I set them up so that dashed attributes are automatically bound to camelCase properties, similar to Polymer.

from https://www.polymer-project.org/1.0/docs/devguide/properties.html
> Attribute names with dashes are converted to camelCase property names by capitalizing the character following each dash, then removing the dashes. For example, the attribute first-name maps to firstName.
 
 Currently it seems there is no easy way for me to set the foo-bar attribute nor the fooBar property of the element.  I can do it by defining customAttributes but I don't want to have to define dozens of customAttributes simply to achieve this behavior. 

Thoughts? Thanks!

**Comment by EisenbergEffect** [comment]
The dashed to camel case scenario is the default behavior for Aurelia's bindables so I'm a bit confused when you say that that isn't happening.

Regarding the properties being reflected to attributes, we have a plan to add that in the future.

**Comment by jpray** [comment]
Cool, glad to hear the ability to bind to a vanilla custom element's attributes is in the backlog.  

Regarding the dashed to camel case scenario, I've updated the [plunker](http://plnkr.co/edit/9BWmzXvCyrnqlha8tSuN?p=preview) to be a simple comparison between a vanilla custom element and an aurelia custom element.  It shows how the aurelia custom element does turn the dashed attribute into a camelCase property, but it turns the vanilla custom element's dashed attribute into a dashed property.

**Comment by jpray** [comment]
Looking to keep this conversation moving forward, I've drafted a couple potential tweaks here with inline comments. https://github.com/jpray/templating-binding/pull/1/files

If you think this is on the right track, I'll submit a real PR with tests, but there is one question I know I still need answered:

1. There doesn't seem to be a robust camelCase utility function available yet.  I would need direction on how you'd like it to be added (locally or pulled in from elsewhere)

Thanks!

**Comment by EisenbergEffect** [comment]
@jdanyow What do you think of this? It would make things a bit more consistent. Do you think there would be any negative side effects?

**Comment by kevmeister68** [comment]
I think the way it works *now* is quite sensible. I am talking about the default behaviour.

Yes, changing makes things more consistent from the perspective of Aurelia, but it actually makes things less consistent from the perspective of someone who is dipping their toe into the waters of Aurelia and trying to retrofit small parts of Aurelia into existing HTML. In other words, a user who originally had a standard custom element with a hyphenated attribute name will now find that if they apply an Aurelia binding expression to that attribute, their code may no longer work as expected.

So if you do provide a way to do this, I think the current way should remain as the default, and any "special behaviour" needs to be specifically requested by the developer. Should the behaviour be defined at the .bind level, at the custom element usage level eg. <my-custom-element au-bind-behaviour="camelCase">, at the custom element definition level, or some other way? The obvious first step would be to tell Aurelia about specific custom elements and define what their binding conventions should be, similar to how custom-elements are advised to the DOM through document.registerElement.

**Comment by EisenbergEffect** [comment]
I think I would agree with that. We have a way to map properties to events
for binding web components so we could add the attribute mailing eventually
too.

**Comment by jpray** [comment]
@EisenbergEffect for mapping properties to events for binding web components are you referring to Custom Attributes or something else?

@kevmeister68 regarding the following:
> In other words, a user who originally had a standard custom element with a hyphenated attribute name will now find that if they apply an Aurelia binding expression to that attribute, their code may no longer work as expected.

Yes, in some cases additional code will need to be written to inform Aurelia about how to interact with certain vanilla custom elements.  I'm arguing that that should be required for the 1% of outlier custom elements that don't follow best practices.  I'd like to summarize my findings below and get your feedback on whether or not   it makes sense to change the current default behavior.

Goal: to bind a value to either the foo-bar attribute or the fooBar property of a vanilla custom element.
Finding:
`<vanilla-element foo-bar="${something}">` sets the 'foo-bar' property on the element
`<vanilla-element fooBar="${something}">` sets the 'foobar' property on the element

The custom element specification doesn't provide a mechanism for syncing attributes to properties, but I think its safe to say that with Polymer and Aurelia both mapping dashed attributes to camelCase properties, that that is the best practice/industry standard. 

So shouldn't Aurelia be supporting this best practice out of the box and make someone who's trying to set the 'foo-bar' property on the element do the extra work of informing Aurelia about their element?

**Comment by EisenbergEffect** [comment]
I'm not referring to custom attributes. There's a mechanism inside Aureila that you can use to tell it what events to use when two-way binding to a property on an unknown element.

**Comment by jdanyow** [comment]
@jpray / @EisenbergEffect - Can this be closed?  If not- what's the current status?

**Comment by EisenbergEffect** [comment]
Let's not change this for now.

**Comment by jpray** [comment]
I was waiting for a response from @kevmeister68...   You guys haven't yet weighed in on my reasoning for why this should be changed... 

Aurelia templating blurs the lines between attributes and properties.  The default behavior works against Aurelia's and Polymer's best practices of having dashed attributes and camelCase properties.  When the templating engine sees an unknown dashed attribute, it should either apply it as a dashed attribute or a camelCase property, not a dashed property.  Nobody creates dashed properties and if they do, they can tell Aurelia more about their element to get the desired behavior.  The fact that I can't bind to a camelCase property out of the box with Aurelia is a big hassle.

**Comment by jpray** [comment]
To @kevmeister68 point
>In other words, a user who originally had a standard custom element with a hyphenated attribute name will now find that if they apply an Aurelia binding expression to that attribute, their code may no longer work as expected.

This isn't true since standard custom elements don't deal directly with properties, only attributes.  The only potential person this could affect is someone who's joining against the grain and syncing dashed attributes to dashed properties.  That's the exception.  I'm following the Aurelia and Polymer best practice and it's broken for me now.

**Comment by EisenbergEffect** [comment]
@jpray Sorry for closing this prematurely. I think we should evaluate. @jdanyow There's a good point here about dashed properties being almost universally never used. Can we reliably convert to camel cased? Are there any built-in attributes that may break which we need to account for before making this change? Wouldn't this be pretty straight forward to change in the binding language? I think what we would do is instead of simply using the attribute map, we would call a map function that would look up things in the attribute map...if they weren't found then it would apply the rule above. Thoughts? I doubt it will break anything and like @jpray mentions, it will probably improve compat with web components.

**Comment by jdanyow** [comment]
Just to make sure I'm on the same page- is the goal to make any kebab cased binding expression (`foo-bar.bind`, `foo-bar.trigger`, `foo-bar="${baz}"`, etc) result in assigning a camel cased property on the element (eg `fooBar`)?

Standard exceptions would be `data-*`, `aria-*` and things in the existing attribute map?  It's possible someone could do something like `@bindable({ name: 'foo-bar', attribute: 'foo-bar' })` but I'm guessing that would be a non-issue.

**Comment by EisenbergEffect** [comment]
@jdanyow Yes, that is correct.

**Comment by jdanyow** [comment]
Makes sense to me. Also switching to an attribute map function would enable fixing some other issues that have been reported.

**Comment by EisenbergEffect** [comment]
Cool. Do you have time to work on this?

**Comment by jdanyow** [comment]
yes- will start this after I finishing squashing the remaining binding bugs.

**Comment by jdanyow** [comment]
https://github.com/aurelia/templating-binding/issues/64

**Comment by jpray** [comment]
Many Thanks!!!!

**Comment by jdanyow** [comment]
https://github.com/aurelia/templating-binding/issues/32

**Comment by jdanyow** [comment]
implemented in https://github.com/aurelia/templating-binding/commit/4f3e91198a0102ca82fc791d5b69a77cfff94e43
