### ISSUE TITLE
Repeater won't run (sort)ValueConverter when item property is changed.

### ISSUE THREAD

**Issue by MikaelPorttila** [aurelia/templating#302]
Hi!
I'm running a list of items through a repeater with a sortValueConverter which sorts the items by a index-property on the items.

When I add or remove items the sort will run but if I just modify one of the items index-property the sort will not be called. 

Is there any way to signal the property change or set some sort of computedFrom('myIndexProperty') property on the the sortValueConverter? 

Plunker: http://plnkr.co/edit/wMci3LRPOFYEqDwSBIk1?p=preview

**Comment by EisenbergEffect** [comment]
@jdanyow Can you answer and also may7be put something in the docs for this since it's such a common scenario?

**Comment by jdanyow** [comment]
@EisenbergEffect sure

@MikaelPorttila the binding system doesn't observe all properties of all objects, it only observes the props used in the binding expression.  Here's some examples of how you could implement this feature:
https://gist.run/?id=0bdac28d000e80ecc026
https://gist.run/?id=637d1ece26efb425a9ca
