### ISSUE TITLE
repeat.for throwing Cannot read property get Collection Observe of null error

### ISSUE THREAD

**Issue by Tinadim** [aurelia/templating#305]
Hello. In my view model I have an array of objects, and in my view I have something like that:

`<div repeat.for="obj of data"> ... content ... </div>`

When my view loads, my view-model already have some data and the repeat works great. However, I have some AJAX that changes the content of data, and when that happen, the error 
`Cannot read property get Collection Observe of null error` is thrown. I have already checked and the new data that comes from ajax is correct, and is also an array of objects with the same properties.

What am I doing wrong?

**Comment by EisenbergEffect** [comment]
@martingust Can you look into this?

**Comment by martingust** [comment]
@Tinadim Are you sure it is still an array after you change the bound object? You will get that error when you bind to an object that `repeat` cannot iterate. The error message for this scenario improved in the latest release. Can you try update to latest and see if you still getting the same error? If so it would be great if you could provide some example repo on how to replicate this.

**Comment by Tinadim** [comment]
@martingust updating Aurelia clarified the error message, as you said, and I was able to solve the issue. Thanks a lot!
