### ISSUE TITLE
Composing custom element with a precreated view-model without manually specifying the path to the View via <compose>

### ISSUE THREAD

**Issue by niieani** [aurelia/templating#307]
There are times where I would prefer to create the ViewModels for my components in the app logic, not have them automatically created by Aurelia.

Currently I can do that like this:

_app.js_
```js
export class App {
  testInstance = new Test()
}
```
_app.html_
```html
<compose view="test.html" view-model.bind="testInstance"></compose>
```

But why should I need to type the path to the View? If I'm going to do it over and over again, would be nice if I could do it simply like this:

_app.html_
```html
<test view-model.bind="testInstance"></test>
```

It would simply mean the view-model does not need to be created by Aurelia, but we re-use the pre-existent one when creating the Custom Element.

**Comment by EisenbergEffect** [comment]
Have you tried it?

**Comment by niieani** [comment]
I have indeed. Didn't work, hence the issue :)

**Comment by EisenbergEffect** [comment]
Ok, it should have worked. Did you get an error? Can you provide some more information?

**Comment by niieani** [comment]
No error, it's as if it ignored the `view-model.bind` altogether. I'll post
a gistrun when I'm home.

**Comment by niieani** [comment]
Here you go: https://gist.run/?id=f6152812e3b3cfa41bba

**Comment by jdanyow** [comment]
From the gist:
```html
<template>
  <require from="./test"></require>
  compose: <compose view="test.html" view-model.bind="testInstance"></compose>
  <hr/>
  test: <test view-model.bind="testInstance"></test>
</template>
```

this part is not valid: `<test view-model.bind="testInstance"></test>`

A view model instance cannot be specified for a custom element.

**Comment by niieani** [comment]
@jdanyow Jeremy, I think you misunderstood. That's the point of this issue:

> A view model instance cannot be specified for a custom element.

I know that this syntax is not valid, but it would be nice if an instance could in fact be specified for a custom element, so that path to the View would not need to be necessary every time when composing a custom element with a preexisting ViewModel instance.

**Comment by alvarezmario** [comment]
@niieani this is valid syntax:
```html
<test view-model.bind="test"></test>
```
With current implementation you don't always need to write the view.

**Comment by EisenbergEffect** [comment]
We aren't going to change this...it would be to costly. Instead we provide the compose element, you should be able to specify only a view model with that, without needing to specify a view. If that doesn't work, then it's a bug and we can fix it.

**Comment by behzad888** [comment]
That does'n work,
`<compose if.bind="recursive.checked" view-model="./hello"></compose>`

**Comment by niieani** [comment]
@EisenbergEffect I didn't realize it works without specifying the view path, it's an undocumented feature. Awesome! That solves my problem then, thanks.

**Comment by niieani** [comment]
@EisenbergEffect Actually there's one scenario where this won't work: `as-element` attribute. Is there a way to combine the two? To use it while specifying the view-model at the same time? Not sure what the syntax would be in that case?

```
<div view-model.bind="testInstance"></div>
```

It would be awesome if that could work, composing the above div as element of the selected view-model. Would it be difficult to implement?

**Comment by EisenbergEffect** [comment]
Try this

```
<div as-element="compose" view-model.bind="testInstance"></div>
```

**Comment by niieani** [comment]
@EisenbergEffect Brilliant. A bit verbose, but works. Thanks. It would be great to add all of these examples to the cheat-sheet.

**Comment by EisenbergEffect** [comment]
If you submit a PR to add them, we could gladly accept :)

**Comment by niieani** [comment]
@EisenbergEffect I wanted to submit a PR for the docs already in the past, but I can't find which repo the docs are located at. 
https://github.com/aurelia/documentation/ doesn't seem to contain any of the docs from the website.

**Comment by EisenbergEffect** [comment]
The cheat sheet is on the framework repo.
