### ISSUE TITLE
View not rendered with self-closing require tag

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/templating#311]
This works:

```html
<template class="rendered">
	<require from="frontend/converters/newlines"></require>
	<p if.bind="toonNotitie && notitie">${notitie | newlines}</p>
	<a click.trigger="openDialog()" href="#">#{pakketoverview.maak.notitie}#</a>
</template>
```

but if I make the require-tag self-closing:

```html
<require from="frontend/converters/newlines" />
```

there's no error, but the view isn't rendered.

I spent a lot of time looking elsewhere until I found this. If this is expected behaviour, I suggest adding a note to the docs (Requiring Resource in the cheat sheet at least).

**Comment by EisenbergEffect** [comment]
Our upcoming custom element docs have a note on this. Basically, the browser doesn't support custom self-closing tags. It only recognizes an internal, hard-coded list of tags that support this. It's unfortunate and even the web components specification doesn't allow for this :cry:
