### ISSUE TITLE
Strategy to mock a dynamic dependency (custom resolver)

### ISSUE THREAD

**Issue by istrau3** [aurelia/templating#313]
I have a class with the following signature:

```javascript
@inject(DependencyFactory.of(CrudResource))
export default class StaticDataCache {
```

and I am looking to write a unit test for it. I can't seem to figure out how to do this. I placed a breakpoint in the container.get and it doesn't seem to match any key (if it did I could registerResolver using a mocked up resolver).

Here is DependencyFactory for completeness's sake:
```javascript
import {resolver} from 'aurelia-framework';

@resolver
export class DependencyFactory {
    constructor(Type) {
        this.Type = Type;
    }

    get(container) {
        let self = this;
        return function(...rest) {
            return container.invoke(self.Type, rest);
        };
    }

    static of(Type) {
        return new DependencyFactory(Type);
    }
}
```

So what should my strategy be to mock this dependency?

I tried something like this:
```javascript
container = new Container();

container.registerResolver('DependencyFactory.of(CrudResource)', DependencyFactory.of(CrudResourceMock));

templatingEngine = container.get(TemplatingEngine);

cdc = templatingEngine.createViewModelForUnitTest(StaticDataCache);
```
but it didn't work (and I didn't think it would to be honest).

Thanks in advance.

**Comment by jdanyow** [comment]
Try doing `container.registerHandler(CrudResource, CrudResourceMock)` and replacing all `DependencyFactory.of` with the new built-in `Factory.of` resolver (this second part might not be necessary).
