### ISSUE TITLE
Custom Attributes with options don't allow camelCase on bindable properties

### ISSUE THREAD

**Issue by 5ebastianMeier** [aurelia/templating#314]
I discovered that the syntax is a bit limited in this example.

```
@customAttribute('some-attribute')
export class SomeAttribute {
  @bindable doeswork;
  @bindable doesNotWork;

  doesworkChanged(newValue, oldValue) { console.log('foo'); }
  doesNotWorkChanged(newValue, oldValue) { console.log('bar'); }
}
```

If you're busy I might have enough time to look into this next week.

**Comment by jdanyow** [comment]
bindable properties with mixed casing are hyphenated, even in custom attributes:

`<div some="doeswork.bind: 'something'; does-not-work.bind: 'this will work'">`

**Comment by 5ebastianMeier** [comment]
@jdanyow Now that you mention it this seems kinda logic considering the overall convention.

Is there a way for me to contribute this as an example to the cheatsheet in the docs? 

That's the only real documentation on typical use cases for the moment and although this convention seems logic I doubt I am the only one running into that issue.

I couldn't find any explicit hint to this in the docs.

**Comment by 5ebastianMeier** [comment]
Another thing, although that concerns databinding:
I discovered the (not yet documented) feature to select binding modes (like one-time) in string interpolation. But the keyword in the syntax is expected in camel case:
```
${boundValue & oneTime}
```
The hyphenated version of this (one-time) is not working.
Although I like the camel case approach better this seems inconsistent.

The camel case version in this example in my opinion looks better, because bound variables will mostly be named in camel case, but it is not easily identifiable as a keyword since its the same case.

**Comment by EisenbergEffect** [comment]
The cheat sheet is in the doc folder of the framework repo. We would love any PRs you think are valuable for the community.
