### ISSUE TITLE
Very low performance of repeat.for repaint with ArrayValueConverter

### ISSUE THREAD

**Issue by dilvish4ever** [aurelia/templating#315]
List: 20-70 rows, 8-10 columns with twbs inputs & selectpikers (3-5 each row). Every row - composed replaceble part 
```html
<list .....>
  <template replace.part=...>
    <compose ...></compose>
  </template>
</list>
```
List:
```html
<div class="list-group">
  <div class="list-group-item repeat.for="item of items | arrayFiler"...............>
    <template replaceble part=.....
    </template>
  </div>
</div>
```
After adding dummy ArrayFilterValueConverter 
```javascript
toView(arr, filter) {
  console.debug('array filtered'); 
  return arr;
}
```
initial loading and any array operations (push, splice,...) become 10-20 times slower (10-20 seconds only for repaint). Debug message from filter appears immediately after array mutation.

**Comment by jdanyow** [comment]
@dilvish4ever if you want to put together an example of what you're doing using the aurelia gist we could provide some performance suggestions:  https://gist.run/?id=1ae985e6c943885496e8

Here's our dbmonster in case that's helpful... 

https://github.com/jdanyow/aurelia-dbmonster

**Comment by dilvish4ever** [comment]
Sorry for a long answer, but I can't access gist due to local proxy policy :(
Just to explain: with filter adding or removing elements from array forces to recreation of all element's views. Without filter - view created just for added element. So, what I'm thinking... May be there is any chance to force `repeate` to know, that new array returned by applied filter is the "same" array just because all elements, except one (some), are the same and there is no need to recreate views for them.
