### ISSUE TITLE
Enhance click.delegate

### ISSUE THREAD

**Issue by dbrezoev** [aurelia/templating#318]
I cannot enhance `click.delegate` when applied on a table. For example `<table click.delegate="clickAnywhereOnTheTable($event)"> ...</table>`. The same if used on a div etc.

**Comment by oneillci** [comment]
I have found when using the bindingEngine enhance that only simple interpolation ${blah} works on the element you target.

However, if you wrap your table or div in a container (div/span or whatever), and enhance the container, things work as expected.
i.e.

`<div class='enhance-this-element-instead'><table click.delegate="clickAnywhereOnTheTable($event)"...</table></div>`

I'm not sure if this is a bug or intended behaviour

**Comment by dbrezoev** [comment]
Thanks, it really works. I don`t know if it is intended behavior too. Thanks again.

**Comment by JeroenVinke** [comment]
We're also hitting this issue and I think that [this gist](https://gist.run/?id=3d30ea5e7172de4eb5c622b231fabfee) demonstrates it

**Comment by JeroenVinke** [comment]
I was able to trace it back to [this line](https://github.com/aurelia/templating/blob/master/src/view-factory.js#L415) where only child elements of the target element are seen as instructables, not the root element. Does this have anything to do with the fact that templates should be wrapped in ` <template></template>`  tags? What are those template tags for anyway?
