### ISSUE TITLE
template if.bind= doesn't work

### ISSUE THREAD

**Issue by bushuyev** [aurelia/templating#32]
Documentaion (http://aurelia.io/docs.html#if) has sample showing if.bind used with template. This doesn't work. If.bind seems to be working with other tags (h, div, secrion) but not with template. To reproduce, clone 	https://github.com/aurelia/skeleton-navigation.git,  in src/welcome.js add:
```javascript
this.showTemplate = false; //in constructor

 toggle(){
    this.showTemplate = !this.showTemplate;
  }
```

in welcome.html, add if.bind="showTemplate" to template and h2 (title) tags, and button somewhere in the form:
```html
 <button click.trigger="toggle()">Toggle</button>
```
When button is clicked title is being hidden/shown as expected, but template content remains visible.

**Comment by EisenbergEffect** [comment]
It appears to work as expected with the following markup:

```markup
<template>
  <section>
    <h2 if.bind="showTemplate">${heading}</h2>

    <form role="form" submit.delegate="welcome()">
      <div class="form-group">
        <label for="fn">First Name</label>
        <input type="text" value.bind="firstName" class="form-control" id="fn" placeholder="first name">
      </div>
      <div class="form-group">
        <label for="ln">Last Name</label>
        <input type="text" value.bind="lastName" class="form-control" id="ln" placeholder="last name">
      </div>
      <div class="form-group">
        <label>Full Name</label>
        <p class="help-block">${fullName | upper}</p>
      </div>
      <button type="submit" class="btn btn-default">Submit</button>

      <template if.bind="showTemplate">
        This is some conditional text.
      </template>

      <button click.trigger="toggle()">Toggle</button>
    </form>
  </section>
</template>
```

**Comment by tomalec** [comment]
For me 
```html
<template if.bind="deeper.scopes.showme">
    <em>${deeper.scopes.conditional.data}</em>
</template>
```
Still does not work.
Should I register some kind of Binding Behavior or attribute? (I'm trying to use `aurelia-templating` standalone

**Comment by martinolsson** [comment]
I have the same issue, but only when using Internet Explorer 11 - <template if.bind=... works in Chrome.

**Comment by geea789** [comment]
I have a workaround 
you can use one parent template
then use compose to get your conditional template

example:

<template>

<compose if.bind="deeper.scopes.showme" view-model="deeperScopesModel"></compose>

</template>
