### ISSUE TITLE
Provide an ability for component templates to identify which template-parts have been provided by the user of that component.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating#321]
We have a "title-bar" component that we are using for a data-centric application. The title bar component has a template part called "status part" into which a user of the component can provide some markup to represent "status information" (whatever it is). The default content of this "status part" is empty.

Depending on the presence or absence of status markup, the layout of the remainder of the title bar component differs.

It would be nice if the component's <template> markup could directly identify what template parts the user of the component had supplied, or not, so the markup could be conditionalised accordingly.

I'm not exactly sure what this might look like, syntactically, but I would recommend that the presence of a template-part is another "boolean" kind of value that can be used in an if.bind or show.bind expression similar to a regular property.

Some possible ways of achieving this (I assuming it is *not* currently possible):

1. Extend <template> to have an attribute that names a property which is used to identify the supply or non-supply of the template part by the component user. eg. <template part="status-part" presence="hasStatusPart"> whereby "hasStatusPart" becomes a property of the ViewModel. The property can then be referenced by bind expressions. Obviously this won't work for "HTML-only" templates.

2. Extend the binding expression syntax to include an expression like $haspart(part-name) to test for part-presence, eg.

&lt;div if.bind="$haspart('status-part')"&gt;

**Comment by jdanyow** [comment]
Quick workaround: you could throw a `ref` binding on the standard part and use that to determine whether it's been replaced.

https://gist.run/?id=5268c30976b8a503ea6ef36f996080e4

**Comment by kevmeister68** [comment]
Cool. We'll give that a try.

**Comment by EisenbergEffect** [comment]
I'm going to close this for now. I don't think we're going to make any special apis for this. The ref idea is a great solution in this case.

There's another hack, but I wouldn't use it. Current the container that the component is created from has a replacementParts property on it. So, if you inject Container, you can see what is actually being replaced.

**Comment by EisenbergEffect** [comment]
If we get more requests for this, we could make the part replacements injectable in the future.
