### ISSUE TITLE
getter called before constructor

### ISSUE THREAD

**Issue by doktordirk** [aurelia/templating#326]
in the skeleton navigation welcome.js:
```js
export class Welcome {
  heading = 'Welcome to the Aurelia Navigation App!';
  firstName = 'John';
  lastName = 'Doe';
  previousValue = this.fullName;

  x = {};

  constructor() {
    console.log('Constructor');
    this.x.y = 'z';
  }

  get fullName() {
    console.log('fullName', this.x);  // <-- this.x === undefined. neither x= {} nor constructor has been called yet
    return `${this.firstName} ${this.lastName}`;
  }
```

**Comment by stsje** [comment]
Try changing your logging line to `console.log(this.x.y);`

**Comment by doktordirk** [comment]
right. had some typos. i've update the sample

**Comment by stsje** [comment]
Seems to be working fine for me https://gist.run/?id=e30321988c8f08ab6fb5af37a3f91b56

**Comment by doktordirk** [comment]
yeah, but who knows, whats different with gist, run-time transpilation, bundled ...

try the same in the skeleton and it'll be

welcome.js:22 fullName undefined
welcome.js:12 Constructor

**Comment by doktordirk** [comment]
wrong button, so again:

yeah, but who knows what happens with gist, run-time transpiled, bundled ...

try with the skeleton and it'll be
```
welcome.js:22 fullName undefined
welcome.js:12 Constructor
```

**Comment by EisenbergEffect** [comment]
Not a bug with Aurelia. If anything, it's a transpiler issue.

**Comment by doktordirk** [comment]
@EisenbergEffect 
hmm. i tried the same with es6 bundled, typescript and webpack. it's always the same. that doesn't hint at a transpiler issue

ps: one can remove the fullName 'call' in the view. still the same. 

in case it says anything. following calls the fullName getter before the constructor

```
at Container.invoke (webpack:///./~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:565:13)
    at StrategyResolver.get (webpack:///./~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:126:35)
    at Container.get (webpack:///./~/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js?:500:21)
    at eval (webpack:///./~/aurelia-templating/dist/commonjs/aurelia-templating.js?:3831:71)
  ```

**Comment by EisenbergEffect** [comment]
It shouldn't be possible to call a getter before the ctor has been run unless it is detached from the constructor somehow. @jdanyow Do you know anything about this?

**Comment by doktordirk** [comment]
ah, stupid me. found the error.

that's run before the constructor:
`previousValue = this.fullName;`

so, it's not a bug, it's a feature :smile: for real though

issue closed. sorry for the confusion
