### ISSUE TITLE
possibility of require decorator on the view model as an alternate to require element in html??

### ISSUE THREAD

**Issue by ppn2** [aurelia/templating#327]
Is it possible to introduce a require decorator on the view model, instead of importing the view models through require element in HTML?

before
```
//parent.html
<template>
   <require from="./child"></require>
   <child x.bind='y'></child>
</template>

//parent.ts
export class Parent {
  private y: string;
}

//child.ts
export class Child {
...
...  
}
```

After
```
//parent.html
<template>
    <child x.bind='y'></child>
</template>

//parent.ts
import {Child} from "./child";
@require([Child])    //This is array so multiple ViewModel can be specified.
export class Parent {
  private y: string;
}

//child.ts
export class Child {
...
...  
}
```

We are developing in typescript. The typescript compiler cannot statically recognize the require element in the html file and obviously cannot provide the benefit of the static compilation during development and build.

**Comment by EisenbergEffect** [comment]
This would break separation of concerns by mixing view specific implementation details into the view-model, creating a coupling which doesn't currently exist in Aurelia today. I don't think that's a good idea. 

Additionally, I don't see what benefit this would provide or how this would have anything to do with TypeScript. What "new" capability would this provide which doesn't exist today?

Note that Aurelia's HTML `require` element is not without precedent. It's based on and designed as an improvement on the Web Component's proposal of HTML Imports.

**Comment by atsu85** [comment]
@ppn2
> compiler cannot statically recognize the require element in the html file

If You want to detect bugs at build-time, then I've opened [separate issue](https://github.com/aurelia/tools/issues/31) for that. I'd really like to know what @EisenbergEffect thinks about it

**Comment by ppn2** [comment]
@atsu85  I read your issue and i like it. I like @EisenbergEffect will like to implement this kind of functionality (though sometime in future).

@EisenbergEffect wrote
> This would break separation of concerns by mixing view specific implementation details into the view-model, creating a coupling which doesn't currently exist in Aurelia today. I don't think that's a good idea.

@EisenbergEffect as I understand aurelia already have @containerless decorator. My request is not about implementation details but about locating the dependencies. If there is a require decorator, the view-model could pass the dependencies to the view using view-models types (not string) and the view could load those dependencies from there in addition to the dependencies it find from "require". Also please note this recommendation is for view-models only not for static resources.

> Additionally, I don't see what benefit this would provide or how this would have anything to do with TypeScript. What "new" capability would this provide which doesn't exist today?

Yes there is a benefit when using typescript. Since we are passing the dependent view-models in strongly typed way, If file name is changed or deleted or there is typo, typescript compiler will catch that. In addition to that it will help in bundling. While using JSPM, today in aurelia world, when we use jspm bundler we have supply whole src folder. That mean if you have any junk or unwanted file in the folder, that get bundled too. If all the files are statistically linked, than you can tell JSPM to bundle the root file and JSPM will find all the dependencies and bundle all the relevant file.
