### ISSUE TITLE
Creating templates dynamically via javascript ?

### ISSUE THREAD

**Issue by ab34** [aurelia/templating#33]
In the Aurelia blog "[Q&A](http://blog.durandal.io/2015/02/03/aurelia-qa/)" , there is an example of generating a custom element via the React.JS library and bypassing aurelia templating engine.

Is there also a way to create aurelia templates dynamically via javascript ?

Let's say one creates an aurelia template via es6 templates strings functionality, is it possible to bind that template into the view class directly into javascript ? That is, inlining the template into the view class ?

**Comment by EisenbergEffect** [comment]
Can you provide a few more details?

**Comment by ab34** [comment]
Yes, sure... What I was thinking is the ability to define for example an "app" module in app.js only instead of both app.js and app.html. I'm not sure if the construct already exists internally for being used like that. Basically, there would be a function that would take a template string, compiles it, interprets it and binds it to the DOM.

For example:

app.js
```javascript

var template = `<template>  
First Name:<input type="text" value.bind="firstName">
Last Name:<input type="text" value.bind="lastName">
Full Name: ${fullName}
</template>`

export class MyApp{  
  constructor(template){
    this.firstName = 'John';
    this.lastName = 'Doe';
  // Some function compiling, interpreting and binding the template string to the DOM
    templateCompile(template);
  }
  get fullName(){
    return `${this.firstName} ${this.lastName}`;
  }
}
```

For example, in Angular 2 there is the following annotation construct for templates:

```javascript
@Template({
inline: '<div>...</div>'
})
```

The idea here is to have the ability to inline templates directly into the component class.

One could also imagine, in Aurelia, the possibility to define/construct a template inside a module and inject it into the constructor of another one via the dependency injection mechanism...

something like:

anotherModule.js
```javascript
//Template string generated inside another module
import {Template} from './someModule';

export class AnotherModule{
    static inject() { return [Template]; }
    constructor(template){
        templateCompile(template);
    }
}
```

**Comment by ab34** [comment]
Another interesting use case would be for internationalization of an application.

We could have a template defined as a string in a module which can then be imported by another module doing some processing on it, for example via regex expressions, for then serving it into the view.

```Javascript
import {Template} from './englishModule';

export class chineseTranslation{
    static inject() { return [Template]; }
    constructor(template){
        this.template=template;
    }
    get translatedTemplate(){
       //SOME PROCESSING 
       return translatedTemplate;
   }
    activate(){
        templateCompile(`${this.translatedTemplate}`);
    }
}
```

**Comment by ab34** [comment]
For further investigation into the question, see #35.

Closing this one.
