### ISSUE TITLE
Aurelia does not log an error if a processContent( ) functor throws an exception.

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating#330]
Fairly self-explanatory. I had an exception in my processContent functor, and Aurelia did not log anything to the browser console to indicate the call had failed.

This in turn seems to destroy the whole view loading process within Aurelia as nothing gets displayed.

**Comment by EisenbergEffect** [comment]
@kevmeister68 We can add some logging around this scenario, no problem. But, shouldn't it still fail? What would be the alternative for the component if it's content process logic fails?

**Comment by atsu85** [comment]
> But, shouldn't it still fail?

I guess so - probably just debugging took too much time without any hints(errors) from browser console.
