### ISSUE TITLE
Attaching a component from ViewModel

### ISSUE THREAD

**Issue by DiegoGallegos4** [aurelia/templating#332]
I dont know if this is the right library but my question is: Is there any way to insert a component from the ViewModel? For example, whenever you fetch data from the server then pass that data to the component       and inserted into the View. 

I don't have a clear repro of this because it would require to fetch data from a real server because whenever I try it with static data it works but the structure is pretty common. I have a service injected into the screen, then the data is fetched(on the canActivate method), then the data is passed to the custom element(but this custom element receives an empty object). 

Service --> MainScreen --> CustomElement

Here I created a small repro: https://gist.github.com/DiegoGallegos4/9fea07fd56fa6972fc7d0ab3cc203006

DepartmentService injected in Department. From Department's View, CustomTable Element is called.

**Comment by kevmeister68** [comment]
Some suggestions, which may or may not make a difference.

1. Change the name of your attribute in &lt;custom-table&gt; from data to a hyphenated name like table-data.
2. Modify your @bindable to specify the attribute name.
3. There is no require for &lt;custom-table&gt; in departments.html. Is this a global resource?
