### ISSUE TITLE
Using a value converter in a ternary breaks parser

### ISSUE THREAD

**Issue by easyt** [aurelia/templating#333]
The following two uses of a value converter with a ternary in a binding expression fail:

```${myDate ? myDate | dateFormat : "N/A"}```
breaks with: Error: Parser Error: Conditional expression myDate ? myDate  requires all 3 expressions at column 17 in [myDate ? myDate | dateFormat : "N/A"]

```${myDate ? (myDate | dateFormat) : "N/A"}```
breaks with: Error: Parser Error: Missing expected ) at column 18 in [myDate ? (myDate | dateFormat) : "N/A"]

**Comment by EisenbergEffect** [comment]
It's because your syntax is incorrect. The value converter must go at the end of the expression, not in the middle.

**Comment by easyt** [comment]
What would you recommend if we want to display "N/A" when there is no date in this one case?

**Comment by EisenbergEffect** [comment]
Consider parameterizing the formatter so you can supply a fallback value.

`${myDate | dateFormat : "N/A"}`

**Comment by easyt** [comment]
Thanks, Rob.
