### ISSUE TITLE
ViewSlot firstChild null not being checked

### ISSUE THREAD

**Issue by cmichaelgraham** [aurelia/templating#34]
i'm getting an exception when i run a `todo` sample.  it looks like `ViewSlot` is not checking if .firstChild is null before referencing its properties.

[typescript repo containing sample](https://github.com/cmichaelgraham/aurelia-typescript)
[todo project within repo](https://github.com/cmichaelgraham/aurelia-typescript/tree/master/todo-require-vs-ts)
[running code illustrating exception](http://cmichaelgraham.github.io/aurelia-typescript/todo-require-vs-ts/index-latest.html)
[no check for firstChild null](https://github.com/aurelia/templating/blob/master/src/view-slot.js#L142)

**Comment by cmichaelgraham** [comment]
if i edit the [code](https://github.com/aurelia/templating/blob/master/src/view-slot.js#L142) like this, the sample works:

```javascript
      removeAll: {
        value: function removeAll() {
          var _this = this;

          var children = this.children,
              ii = children.length,
              i;

          var rmPromises = [];

          children.forEach(function (child) {
            if (child.firstChild !== undefined && child.firstChild !== null && child.firstChild.nodeType === 8 && element !== undefined && element.nodeType === 1 && element.classList.contains("au-animate")) {
              var element = child.firstChild.nextElementSibling;
              rmPromises.push(_this.animator.leave(element).then(function () {
                child.removeNodes();
              }));
            } else {
              child.removeNodes();
            }
          });
```

**Comment by zewa666** [comment]
Hey Mike would you mind sending in a PR for your fix? Also thanks for the detailed explanation and showcase of the error

**Comment by cmichaelgraham** [comment]
i thought about that, but i'm worried i don't know what should happen when it is actually null or why its null in my case.  can you give me a little guidance? :)

**Comment by cmichaelgraham** [comment]
like could it be because there's only one route?

or something specific to the view?  i don't know...

**Comment by zewa666** [comment]
we had something similar before with other parts. It was my mistake to think that elements/siblings could be `undefined`, as I was expecting. Seems though most of the time they are `null`.

The way you did it, testing for both of them, is definitely the safest route.

**Comment by cmichaelgraham** [comment]
ok - so just look for those places in ViewSlot and add some checks?  i'll give it a go :)

**Comment by cmichaelgraham** [comment]
i can validate within the typescript world.  how would you suggest validating out in the `real` world?  just a couple of suggestions if you have em
