### ISSUE TITLE
Suggestion: decorator for removing original textContent and injecting it 

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/templating#340]
I'm not sure, but I think this may be a fairly common scenario: wanting to pass data to a custom element through the element content, rather than any attribute. E.g.:

```html
<my-note-editor>Lorem ipsum

This is my current note.</my-note-editor>
```

I'm having this scenario come up multiple times in my current project. I've implemented it in a decorator by storing the original content on the element reference:

```ts
import {processContent} from "aurelia-framework";

export function saveElementTextContent() {
	return processContent(function(compiler: any, resources: any, element: Element) {
		(<any>element).originalTextContent = element.textContent;
		element.textContent = "";
		return false;
	});
}
```

and then picking it up in my component constructor:

```ts
@autoinject
@saveElementTextContent()
export class MyNoteEditor {
	constructor(element: Element) {
		this.note = (<any>element).originalTextContent;
	}
}
```

I'm fairly happy with this. I'd like it even better if the original `textContent` could be directly injected through some custom Type, but I haven't looked into implementing that yet.

If there's interest, and the Aurelia team likes it, I'd like to put a PR together for getting this into core.

**Comment by EisenbergEffect** [comment]
I'm hesitant to add it to the framework because we want to be careful not to make things bigger particularly if there's an existing plugin point. However, I do think this would be a great example to have in the advanced templating docs. Can you create a docs issue for this?
