### ISSUE TITLE
aurelia with bootstrap tooltip

### ISSUE THREAD

**Issue by eliavmaman** [aurelia/templating#342]
I m using
tooltip.js -
`import {customAttribute, inject, bindable} from 'aurelia-framework'; import $ from 'bootstrap'; @customAttribute('tooltip') @inject(Element) export class Tooltip { element: HTMLElement; @bindable title: any; @bindable placement: any; constructor(element) { this.element = element; } attached() { $(this.element).tooltip({ title:this.title, placement:this.placement }); } }`

and view is 
`<p class="box-elipsis v-padder" data-toggle="tooltip" data-html="true" tooltip="placement:left; title:${offering}"> <label>Offering:</label> <span class="label-value">${offering}</span> </p>`

the binding to tooltip="placement:left; title:${offering}" not working...
any idea please?

**Comment by jdanyow** [comment]
closing - this question was answered here:  https://github.com/aurelia/templating/issues/233#issuecomment-217735162
