### ISSUE TITLE
Percieved lag when img elements are reused.

### ISSUE THREAD

**Issue by lukechilds** [aurelia/templating#349]
When you update an image src many browsers will continue showing the old src until the new src has loaded. In Aurelia, elements are often reused, when image elements are reused it appears very laggy (even through the Aurelia side is fast) due to the way the browser updates the images.

Take this example:

https://gist.run/?id=50b5af249b57d1f18577bdd6cc4bfe33

(example works best if you open dev tools in chrome and disable cache in network tab)

If you append a new item to the array a new DOM node is created and appended for the new image element, this works fine.

However if you **prepend** an item to the array a new DOM node is **appended** and all the attributes are shifted along. This means the prepended image is wrong until the new one loads. This makes the app _appear_ very laggy.

I think a better default behaviour would be for the prepended image to not show any image until the src has loaded. This would make the behaviour of appending and prepending consistent.

I think this could be achieved by inserting new DOM nodes to the correct place by doing a deep compare on the objects to see if any new elements have been added and if so where (probably not very performant).

Alternatively removing an img elements src attribute before reusing it may stop the default browser behaviour (untested).

**Comment by lukechilds** [comment]
Can confirm removing the src attribute before updating it resolves the issue. If you think this is a valid bug I'm happy to work on a PR.

**Comment by EisenbergEffect** [comment]
I'd like to get some feedback from @jdanyow and see what he thinks.

**Comment by jdanyow** [comment]
looks like another condition that would rule out using [`_inPlaceProcessItems`](https://github.com/aurelia/templating-resources/blob/master/src/array-repeat-strategy.js#L124).  This optimization is getting to be more and more specific to a certain benchmark :)

**Comment by EisenbergEffect** [comment]
One thing I'm curios about is how that benchmark runs without this optimization, given that we have the recent optimization for item re-use.

**Comment by jdanyow** [comment]
We tested it, what we found was the recent optimization didn't help because of the way the benchmark replaces the whole array instance as well as all the objects within.

**Comment by EisenbergEffect** [comment]
Gotcha.

**Comment by lukechilds** [comment]
Removing the `src` attribute before setting it wouldn't affect any benchmarks significantly though would it?

**Comment by vegarringdal** [comment]
In my grid I just set src to "" before setting the new value(on valuechanged), to make old image go away before it loads
```
this.content.src = "";
this.content.src = value;
```

Does seam to slow it down in any way, just gets rid of the weird behavior of old image showing in a row it should not be in.
this.content.src = "";
http://vegarringdal.github.io/vGrid/viewSlotsDemo001/

Dunno if this was any usefull information at all, but figure I could at least tell you guys.
I do a lot of weird in my grid while Im learing aurelia :-)

**Comment by lukechilds** [comment]
Do you want a PR for this?

**Comment by EisenbergEffect** [comment]
@jdanyow How should we proceed on this?

**Comment by jdanyow** [comment]
this will be fixed by the changes for https://github.com/aurelia/framework/issues/408#issuecomment-215380065
