### ISSUE TITLE
Add support for instanceof operator

### ISSUE THREAD

**Issue by zakjan** [aurelia/templating#352]
I use TypeScript for model classes with polymorphism. In HTML templates I display a different template based on model type.

Currently I can do this with comparing constructor property. Can you add support for instanceof operator?

```
<li repeat.for="model in models">
    <dog-row if.bind="model.constructor === DogModel"></dog-row>
    <cat-row if.bind="model.constructor === CatModel"></cat-row>
</li>
```

**Comment by EisenbergEffect** [comment]
Please see answer in the other issue. If instanceof is still required, please consider opening an issue on the binding repo where the binding parser and ASTs capabilities are defined.
