### ISSUE TITLE
Template uses undefined value or property?

### ISSUE THREAD

**Issue by bleevo** [aurelia/templating#353]
Is there anyway to make Aurelia error/log when the template tries to access a value that doesnt exist?

${doesntExist}

${does.doesnt}

**Comment by EisenbergEffect** [comment]
Closing this as a duplicate. @jdanyow can update you on the status of this.

**Comment by jdanyow** [comment]
https://github.com/aurelia/binding/issues/30

**Comment by bleevo** [comment]
Thanks All.
