### ISSUE TITLE
custom bindings on custom element template tag should get hoisted to the custom element tag

### ISSUE THREAD

**Issue by davismj** [aurelia/templating#359]
I have the following line in my custom element template file.
```
<template element.ref="element" interact-drop.delegate="add($event)" interact-droppable=".tool">
```
When Aurelia composes the custom element, the `interact-droppable=".tool"` does not get hoisted onto the custom element itself. I would expect that all attributes, including custom bindings, would get hoisted onto the custom element.

**Comment by EisenbergEffect** [comment]
Investigating now. This should work.

**Comment by EisenbergEffect** [comment]
Cannot reproduce. I tested multiple attribute combinations very similar to what you have above but it all seems to work.

**Comment by davismj** [comment]
Sorry, you're correct. Gist example here:

https://gist.run/?id=99d17daddb3ac649939fec2c6d821844
