### ISSUE TITLE
getViewStrategy isn't called for a custom element

### ISSUE THREAD

**Issue by meggle** [aurelia/templating#360]
Overview: I'd like to be able to choose which template a custom widget I've made uses based off of what parameters are bound to it. So, I tried getViewStrategy. However, I found it never got called if I had a custom element, though it does get called if I compose it in.

Motivation: I'd like the element to display the same data and has the same behavior, but just displays in different formats. I'd like for it to be the same element (so I can use it in a selector) and viewmodel rather than building a new version of this for each possible variation.

Browsers: I've run the gist in the latest Chrome and Firefox

Here's a gist I wrote up to try and demonstrate:

https://gist.run/?id=58c81b5c6d31ddd2201aa40ac4764a97&sha=e9e2ef94e4d12aed704d49cc3e178440db133b5a

**Comment by EisenbergEffect** [comment]
`getViewStrategy` is only available for dynamic composition scenarios such as using the `compose` element or the `router. It's not available for static composition scenarios, such as custom element. This is for performance reasons.

One solution you may want to consider is creating a custom element view that contains a `compose` element. Then you can switch the views out internally based on data or any mechanism you desire.
