### ISSUE TITLE
Feature request: DOM manipulation on initial propChanged method call

### ISSUE THREAD

**Issue by akircher** [aurelia/templating#361]
I find myself writing the following a lot in my custom elements (based on mdl-lite) which is a minor inconvenience.

```
checkedChanged() {
    this.label && this.label.MaterialCheckbox.checkToggleState()
  }

  disabledChanged() {
    this.label && this.label.MaterialCheckbox.checkDisabled()
  }

  attached() {
    this.checkedChanged()
    this.disabledChanged()
  }
```

This is because the checkedChanged and disabledChanged properties are initially called before the view is attached. So you can't do any DOM manipulation yet. For this first call, I need to skip the DOM manipulation, hence the `this.label &&`.  Once the view is attached I need to manually call the methods to ensure the proper initial state.

Is there a way to make this more elegant?  Maybe make the `propChanged()` method not fire until after `attached()` is called on the initial call.  Or maybe a `propChangedAfterAttached()` with similar functionality.

**Comment by levan-g** [comment]
just add empty 'bind' method and change handlers will be skipped on the initial call

**Comment by Gheoan** [comment]
@akircher Why are you manually calling MaterialCheckbox.[checkToggleState(), checkDisabled()] instead of calling `componentHandler.upgradeElement()` (provided by `material-design-lite`) on the element of the custom element?

**Comment by akircher** [comment]
@levan-g that is great to know.  I didn't realize that would skip the initial call.  I believe that only prevents half the problem since I would still need to call the `propChanged` method from `attached` when the view is ready.

@Gheoan Unfortunately even after being upgraded mdl inputs don't respond to data binding.  You need to call methods like `checkDirty()` manually.  See https://github.com/google/material-design-lite/issues/903

**Comment by EisenbergEffect** [comment]
We aren't going to change the ordering of events here. The reason that the initial prop changed callbacks and bind lifecycle methods are called before attached it to enable optimized work in a disconnected dom. It material design requires that the dom be attached to the document, then you just have to wait until the attached event to do that work.

**Comment by akircher** [comment]
Got it.  Thanks for the explanation!
