### ISSUE TITLE
Template markup must be wrapped in a <template> element  for resources registered by config.globalResources after bundling

### ISSUE THREAD

**Issue by Ma3yTa** [aurelia/templating#362]
I have issue with loading resources registered by config.globalResources 
``Template markup must be wrapped in a <template> element e.g. <template> <!-- markup here --> </template>`` [https://gyazo.com/ef5c5cd64d4b3a59f2b3a6910aa35204](https://gyazo.com/ef5c5cd64d4b3a59f2b3a6910aa35204)

This happened after bundling

**Comment by EisenbergEffect** [comment]
This error happens when you've got a view somewhere that isn't wrapped in a template tag. Have a look at all your views and make sure they have a template as their root.

**Comment by Ma3yTa** [comment]
I looked in all views and all are wrapped in `` <template> `` tag. This error happened only for plugins registered by `` aurelia.use.feature('plugins') `` after bundle. Before bundle all works fine.

**Comment by Cedware** [comment]
I have nearly the same problem without using config.globalResources.
I think the problem exists in this peace of code in the app-build.js:

```
createTemplateFromMarkup: function(a) {
	var b = document.createElement("div");
	b.innerHTML = a;
	var c = b.firstElementChild;
	if (!c || "TEMPLATE" !== c.nodeName)
		throw new Error("Template markup must be wrapped in a <template> element e.g. <template> <!-- markup here --> </template>");
	return k.ensureHTMLTemplateElement(c)
}
```

The parameter a contains a Object with the property default. a.default contains an correct template. Shouldn't it be `b.innerHTML=a.default;` instead of `b.innerHTML = a;`

**Comment by EisenbergEffect** [comment]
No, the problem is in the change to the text plugin itself which should be accounted for at an earlier stage in the pipeline to this. That would fix both the css and html scenarios. The system.js text plugin must have had a breaking change. We'll work on fixing up our implementation to account for either the old or new versions.

**Comment by luminaxster** [comment]
Having the same issue, the problem appears only after deployment: 
![image](https://cloud.githubusercontent.com/assets/6577822/15895123/9be751be-2d57-11e6-8c70-a2a12617e54f.png)

**Comment by EisenbergEffect** [comment]
It's definitely a breaking change to jspm's text plugin.

**Comment by Cedware** [comment]
Can you tell me which version of the text plugin should work?

**Comment by Ma3yTa** [comment]
0.0.3 works for me

**Comment by luminaxster** [comment]
Yup, 0.0.3 is working for me too.

**Comment by MaximBalaganskiy** [comment]
Even works with 0.0.7. 0.0.8 does not

**Comment by luminaxster** [comment]
Thanks @MaximBalaganskiy. Working on 0.0.7, confirmed =)

**Comment by EisenbergEffect** [comment]
Check master of loader-default and let me know if this resolves the issue. Based on examining the source of multiple different loader text plugins and versions, I think this should handle the differing approaches.

**Comment by Ma3yTa** [comment]
Not resolved.
```

"jspm": {
    "dependencies": {
      .......
      "aurelia-bootstrapper": "npm:aurelia-bootstrapper@^1.0.0-beta.1.1.4",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@^1.0.0-beta.2.1.1",
      "aurelia-dialog": "npm:aurelia-dialog@^1.0.0-beta.1.0.2",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@^1.0.0-beta.1.2.1",
      "aurelia-fetch-client": "npm:aurelia-fetch-client@^1.0.0-beta.1.1.1",
      "aurelia-framework": "npm:aurelia-framework@^1.0.0-beta.1.1.4",
      "aurelia-history-browser": "npm:aurelia-history-browser@^1.0.0-beta.1.1.4",
      "aurelia-http-client": "npm:aurelia-http-client@^1.0.0-beta.1.2.2",
      "aurelia-loader-default": "github:aurelia/loader-default@^0.12.0",
      "aurelia-logging-console": "npm:aurelia-logging-console@^1.0.0-beta.1.1.4",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@^1.0.0-beta.1.1.4",
      "aurelia-polyfills": "npm:aurelia-polyfills@^1.0.0-beta.1.0.3",
      "aurelia-router": "npm:aurelia-router@^1.0.0-beta.1.1.3",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@^1.0.0-beta.1.1.2",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@^1.0.0-beta.1.1.3",
      "aurelia-templating-router": "npm:aurelia-templating-router@^1.0.0-beta.1.1.2",
      "aurelia-validatejs": "npm:aurelia-validatejs@^0.5.2",
      "aurelia-validation": "npm:aurelia-validation@^0.9.2",
       .......
       "systemjs/plugin-text": "github:systemjs/plugin-text@^0.0.8",
      "text": "github:systemjs/plugin-text@^0.0.8",


```

**Comment by MaximBalaganskiy** [comment]
Downgrade text plugin to 0.0.7

**Comment by EisenbergEffect** [comment]
I need more details of your problem. How can I reproduce it? Bear in mind, this isn't released. You would have had to pull down the repo, build it and copy the files over into your project.

**Comment by Ma3yTa** [comment]
https://github.com/Ma3yTa/au-bundle-tst

**Comment by EisenbergEffect** [comment]
I've confirmed with your sample that the bug is fixed. The dependencies you have are old, but if you update loader-default to the latest release, the bug will be fixed.

**Comment by vladyn** [comment]
I have the same issue when I'm trying to run tests on components. 
`Error: Template markup must be wrapped in a <template> element e.g. <template> <!-- markup here --> </template>`
I have no idea how to resolve this as this way no component could be rendered and respectively tested.
