### ISSUE TITLE
replace-part of a parent view

### ISSUE THREAD

**Issue by cosminonea** [aurelia/templating#364]
Consider a view with the following template
```html
<template>
  <template replaceable part="navigation">
    BEFORE
  </template>

  <router-vew></router-vew>
</template>
```

Is it possible for the router-view rendered to replace the navigation part in the "master" template?
```html
<template>
  <template replace-part="navigation">
    AFTER
  </template>
</template>
```

If not how would you achieve something like this? The only thing I can think of is events and event aggregator, but something like above would be cleaner I guess.

**Comment by alvarezmario** [comment]
@cosminonea this will be possible on the upcoming RC with https://github.com/aurelia/templating-router/pull/25 and the new Shadow Dom V1 slot implementation. Just way a bit

**Comment by EisenbergEffect** [comment]
@alvarezmario is correct. We have the new slots model coming for RC. We've also had some awesome community contributions to enable it with routing.

**Comment by cosminonea** [comment]
Is the RC happening in days or weeks from now?

**Comment by EisenbergEffect** [comment]
During the month of June.
