### ISSUE TITLE
[Question] In page templates

### ISSUE THREAD

**Issue by tszarzynski** [aurelia/templating#365]
Hey guys,

I was wondering you could give me some tips on implementing "in-page" templates. What i mean by that is a piece of markup returned by a server that's turned into a reusable Aurelia template?

Let me explain what i'm talking about using a simple example. Let's say a sever renders a page with a list of products for a category. Once a page is loaded i'd like to reuse the markup representing a single product and render a list of products for another category using Aurelia's repeater. I'm looking for a way to enhance a page behaviour without duplicating a markup on client side.

I have few ideas how to implement it i.e. extracting the markup from loaded page and passing it to custom-element implementing InlineViewStrategy. 

I'm just curious if Aurelia has some functionality that could make the process easier / smarter? What would be your approach to solve problem like that? 

Any help highly appreciated!

**Comment by EisenbergEffect** [comment]
Please ask questions at gitter.im/aurelia/discuss

**Comment by tszarzynski** [comment]
Sorry for posting it here, but I find it difficult to get any answers on a non-standard questions on Gitter channel.

**Comment by alvarezmario** [comment]
@tszarzynski then SO should be a better option. Issues are for bug, featureds, etc. There is an aurelia tag on SO, use it and then post the link on gitter.
