### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by levan-g** [aurelia/templating#366]
Is it possible to implement something like "Polymer Behaviors" https://www.polymer-project.org/1.0/docs/devguide/behaviors in aurelia?

**Comment by EisenbergEffect** [comment]
You can do this using plain decorators.

**Comment by levan-g** [comment]
How can I mixin bindable properties by plain decorators?

**Comment by EisenbergEffect** [comment]
A decorator is just a function applied to a target. You can invoke the
bindable decorator on the target from inside another decorator.
