### ISSUE TITLE
view-model.ref cannot be bound

### ISSUE THREAD

**Issue by ggrimbert** [aurelia/templating#367]
Hi,

Sorry if this have already been reported  but I am experiencing an issue, if I define a view-model.ref into a component, the value is inevitably taken as a string, so i can't bind this.

example : 
```
<compose if.bind="hasViewModelTemplate"  view-model.bind="element.template" view-model.ref="element.viewmodelref" model.bind="previousmodel"></compose>
```

In this case, I can't access to this.myviewmodel from the parent.

```
<compose if.bind="hasViewModelTemplate"  view-model.bind="element.template" view-model.ref="toto" model.bind="previousmodel"></compose>
```

I have access to this.toto.

Is it normal or is there a problem ?

**Comment by EisenbergEffect** [comment]
Using `view-model.ref` on a custom element gets you the view model of that custom element. So, in this case, you are going to get the view-model for the `compose` element itself.
