### ISSUE TITLE
Projected conditional content is not in correct order

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/templating#369]
I'm not sure how this works with the new Shadow DOM implementation, but with `<content></content>` the order of content is not preserved when some of it has `if.bind`. E.g.:

*app.js*
```js
export class App {
  showTwo = true;
}
```

*app.html*
```html
<require from="myparent"></require>
  <h2>Not projected</h2>
  
  <mychild>One</mychild>
  <mychild if.bind="showTwo">Two</mychild>
  <mychild>Three</mychild>
  
  <h2>Projected</h2>
  
  <myparent>
    <mychild>One</mychild>
    <mychild if.bind="showTwo">Two</mychild>
    <mychild>Three</mychild>
  </myparent>
```

*myparent.html*
```html
<template>
  <content></content>
</template>
```

Result:
![result](http://i.imgur.com/GW8Rfi9.png)

See https://gist.run/?id=674a44c193b5d7b78a09b0be7eca1728

**Comment by EisenbergEffect** [comment]
Fixed in the new version.
