### ISSUE TITLE
Cannot read property 'nextSibling' of null when using jQuery.DataTable

### ISSUE THREAD

**Issue by komenixx** [aurelia/templating#372]
attached() {
		this.dataTable = $(this.tableEl).DataTable({});
	}

	detached() {
		this.dataTable.destroy();
	}

dataTable loads successfully.

Everything looks great, but when i want to show another view by router, there is a error;

aurelia-templating.js:997 Uncaught (in promise) TypeError: Cannot read property 'nextSibling' of null
    at View.removeNodes (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating.js:997:23)
    at http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.7/aurelia-templating.js:1428:17

**Comment by photomoose** [comment]
@komenixx Did you ever resolve this? I'm having the same issue - and it looks like it is the same as this issue:

https://github.com/aurelia/templating/issues/343

**Comment by komenixx** [comment]
No

**Comment by EisenbergEffect** [comment]
My guess is that this particular jQuery widget was written in such a way that it cannot actually destroy unless it is in the DOM. It's an unfortunate characteristic of some legacy JavaScript libraries. I've only seen it in one other library (CKEditor).

For the future, we will consider a pre-detached event, but we have to be careful how we add that or else we can create significant performance issues in Aurelia. In the mean time, try something like this and see if it works for you:

```
export class YourComponent {
  created(owningView) {
    let original = owningView.removeNodes;
    let that = this;
    
    owningView.removeNodes = () => {
      this.dataTable.destroy();
      original.call(owningView);
    };
  }

  attached() {
    this.dataTable = $(this.tableEl).DataTable({});
  }
}
```

**Comment by komenixx** [comment]
Thanks for the explanation. Unfortunately the problem persisted and error message is same.
