### ISSUE TITLE
Tests not working after Shadow DOM v1 Slots Implementation

### ISSUE THREAD

**Issue by Gheoan** [aurelia/templating#375]
Tests make use of `_ContentSelector` which was removed by #357.

https://github.com/aurelia/templating/blob/9c602dd477c10ce671d593be2f21e2cfefbe72d8/test/view-slot.spec.js#L8

**Comment by bdenham** [comment]
Any update on this?

**Comment by EisenbergEffect** [comment]
It will get fixed this week.

**Comment by Gheoan** [comment]
Fixed by 10ccb740597fee8a42a40c70201c0cacab2fb47f I guess.
