### ISSUE TITLE
Create a helper api for dispatching custom events

### ISSUE THREAD

**Issue by Alxandr** [aurelia/templating#38]
It would probably be a good idea to have a simple way to dispatch custom DOM events, given how easy it is to consume them in Aurelia. This could greatly improve the way components communicate instead of simple pub/sub patterns.

**Comment by davismj** [comment]
We were actually talking about this in the Aurelia internal chat the other day. I'd like to get some feedback about how this ought to work.

**Comment by Alxandr** [comment]
I'm just thinking a simple function that takes an element, an event name, and an option object, creates a `CustomEvent` (if I remember how this should work correctly) and just fires it from the element. Basically just `$.trigger` (or whatever it's called) from jQuery, but using proper DOM dispatching.

**Comment by davismj** [comment]
Sure, but for listening?

**Comment by Alxandr** [comment]
No. Listening is done declaratively in the DOM, right.

So, say for instance I create a custom element named `foo-bar`, and I use it like this:

```html
<foo-bar baz.trigger="doBaz()"></foo-bar>
```

This would be a normal aurelia custom element, not a fullblown web component one.

This custom element, or rather it's template, can have whatever in it, but among the content is a button. I want to trigger `doBaz` whenever that button is clicked.

In other word, what I've created is proper (as far as I understand at least) separation of concerns. The `click` event from the button may or may not be leaked from the `foo-bar` element, depending on whether or not it does a `stopPropagation`, but that's beside the point. What it does do however, is trigger a `baz` custom event, that originates in the `foo-bar` element. Aurelia picks this up thanks to `baz.trigger` attribute, and runs the event handler.

A better example of something useful one could actually create would be something like this:

```html
<login-form login.trigger="performLogin($event)"></login-form>
```

Now, the point here is simply to simplify the creation of the click-handler of the button inside the `foo-bar` element.

A quick google-search would show something of how the method could be implemented. `CustomEvent` constructor should probably be used when available though. Might even be reasonable to pull in a small polyfill for it.

**Comment by jdanyow** [comment]
```js
import {DOM} from 'aurelia-pal';

// create event:
let event = DOM.createCustomEvent('my-event');
// dispatch:
element.dispatchEvent(event);
// or:
DOM.dispatchEvent(event);
```
