### ISSUE TITLE
Lifecycle hook "events"

### ISSUE THREAD

**Issue by bblazely** [aurelia/templating#382]
Hi,

I've been playing around with replicating Angular 1's $on.$destroy() functionality in my project, mainly to streamline the process of creating/destroying propertyObservers and listeners for i18n locale changes. I couldn't find a documented method to accomplish the same thing (is there one beyond the hook functions?), so I decided to make it a learning exercise in building ES7 decorators and came up with the code shown below.

The reason I like being able to register 'onEvent' handlers for the lifecycle hooks is that it lets me simplify my component set up / tear down. 

i.e.
Before:
```javascript
@inject(BindingEngine, UserSession, LanguageLoader, Element)
export class ExampleComponent {
    sessionObs = null;
    llObs = null; 
    
    bindingEngine = null;
    userSession = null;
    languageLoader = null;
    element = null;

    constructor(bindingEngine, userSession, languageLoader, element) {
        this.bindingEngine = bindingEngine;
        this.userSession = userSession;
        this.languageLoader = languageLoader;
        this.element = element;
    }

    bind() {
        this.sessionObs = this.bindingEngine.propertyObserver(this.userSession, 'valid')
            .subscribe((session_state) => {
                // ...
            });
        
        this.llObs = this.languageLoader.get(LanguageLoader.TYPE.COMPONENT, 'example-component', this.element)
    }

    unbind() {
        this.sessionObs.dispose();
        this.llObs.dispose();
    }
}
```
 
After (verbose):
```javascript
@viewEvents
@inject(BindingEngine, UserSession, LanguageLoader, Element)
export class ExampleComponent {
    constructor(bindingEngine, userSession, languageLoader, element) {
        let sessionObs, llObs;

        this.onBind(
            () => {
                sessionObs = bindingEngine.propertyObserver(userSession, 'valid')
                    .subscribe((session_state) => {
                        // ...
                    });
                llObs = languageLoader.get(LanguageLoader.TYPE.COMPONENT, 'example-component', element)
            }
        );

        this.onUnbind(
            sessionObs.dispose, llObs.dispose
        );
    }
}
```

Or: (More succinct, less readable)
```javascript
@viewEvents
@inject(BindingEngine, UserSession, LanguageLoader, Element)
export class ExampleComponent {
    constructor(bindingEngine, userSession, languageLoader, element) {
        this.onBind(
            () => {
                this.onUnbind(
                    bindingEngine.propertyObserver(userSession, 'valid')
                    .subscribe((session_state) => {
                        // ...
                    }).dispose,

                    languageLoader.get(LanguageLoader.TYPE.COMPONENT, 'example-component', element).dispose
                )
            }
        )
    }
}
```

The decorator is as follows:
```javascript
export function viewEvents(target) {
    let hookEvents = ['onBind', 'onUnbind', 'onDetached', 'onAttached'];

    for (let event of hookEvents) {
        let hook = event.substr(2).toLowerCase();

        // target.prototype needs all hooks not present in the class itself to be defined early or
        // the wrappers for the hooks won't be triggered at all (but why?)
        if (!target.prototype[hook]) {
            target.prototype[hook] = ()=>{};
        }

        // Add onEvent handlers to target prototype
        target.prototype[event] = function (...fn) {
            // Check for instance storage, create it if missing
            if (!this._auViewEvents) {
                this._auViewEvents = {
                    hooks: {},
                    on: {}
                }
            }

            if (!(hook in this._auViewEvents.on)) {
                this._auViewEvents.on[hook] = [];
            }

            // Add Listeners contained in 'fn' for this hook
            for (let i = 0; i < fn.length; i++) {
                this._auViewEvents.on[hook].push(fn[i]);
            }

            // Make sure the hook is only wrapped the first time...
            if (!(hook in this._auViewEvents.hooks)) {
                this._auViewEvents.hooks[hook] = this[hook];    // this[hook] is either the placeholder above, or an actual hook in the class
                this[hook] = function() {
                    // Call listeners
                    for (let i = 0; i < this._auViewEvents.on[hook].length; i++) {
                        this._auViewEvents.on[hook][i].apply(this);
                    }
                    // Call wrapped hook
                    if (this._auViewEvents.hooks[hook]) {
                        this._auViewEvents.hooks[hook].apply(this);
                    }
                }.bind(this);
            }
        };
    }
}
```
Note: It's my first decorator, so please let me know if I've done something odd/broken/leaky/dangerous! :-)

Note that the solution above still allows me to define bind/unbind/attach/detach methods. These get 'wrapped' by the decorator and executed once all the operations registered with the handlers are all done.

Known Issues / Concerns:

- It needs to register all the hook functions in the target.prototype if they're not already there or the new wrappers don't get called at all. 
- Also, even though it's unlikely to clash with something else.I'm also not fond of storing everything in _auViewEvents in the class instance.

(I believe that both these issues could be overcome if the solution was more closely integrated with aurelia-templating though - and not a decorator)

- Can't currently 'deregister' listeners. I haven't thought of a use case yet where i'd need it, but It would be doable with a minor change and would probably need to remove the support for adding multiple callbacks at once. (the handler could then return a disposal function). Maybe.

What do you think?

**Comment by atsu85** [comment]
This looks cool - less code when writing ES7 :)

I'm also adding my 2 cents from TypeScript perspective (as opposed to ES7):
As I understand it probably won't help much when writing TypeScript. (Based on my small experience with decorators) it seems to me, that TypeScript compiler doesn't recognize fields and methods added through decorators. To overcome this, i think the easiest thing to do would be to create an interface with methods added by the decorator and cast `this` to that interface type before calling methods added by the decorator. Also the "Before" version of the class You listed above will be much shorter with TypeScript, so (if i calculated correctly) that TypeScript version of the class without `@viewEvents` decorator will be just 1 line longer than the "After (verbose)" version ;)

@bblazely, thanks for sharing :+1:

**Comment by EisenbergEffect** [comment]
Nice extension! This would make a nice little plugin for people that prefer this over method hooks.
