### ISSUE TITLE
Get Template HTML Reflection?

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/templating#384]
I'm looking to use Aurelia's template parsing in order to get a simple reflection object (bindings, locations, nodes). Any chance someone could point me to class/service where I can pass a template in a string and retrieve back the reflection info on the bindings/expressions/custom-elements/etc?  

I found the expression parser in aurelia-binding; I just wondering if there is a more generalized entry-point for parsing the template whole?

**Comment by EisenbergEffect** [comment]
You can use the ViewCompiler to compile a template. It will return a ViewFactory capable of creating instances. The structures inside the factory contain all the info you need.

**Comment by MeirionHughes** [comment]
Nice, thank you.

**Comment by MeirionHughes** [comment]
@EisenbergEffect  hmm, it is possible to run this in node.js environment? It seems I'm blocked needing stuff from aurelia-pal, and it seems https://github.com/aurelia/pal-nodejs is just a placeholder. 

I don't really need to "create" a view per-se. I just need to intersect the bit that parses the file for bindings. Is there something a bit closer to the grain to do this?

**Comment by EisenbergEffect** [comment]
The intent is to implement pal-nodejs on top of something like jsdom and then enable all of Aurelia to run on the server. Then you just need a server-side bootstrapper that loads the correct pal and you can directly run the compiler to get what you want.

**Comment by EisenbergEffect** [comment]
We'd love for you to help out with this, it would also help with our server-side rendering story. @martingust

**Comment by MeirionHughes** [comment]
I guess I guess if its a near 1-to-1 mapping exercise to implement against jsdom, then I may give it a try.

**Comment by EisenbergEffect** [comment]
It would be an awesome contribution :)

**Comment by MeirionHughes** [comment]
slight hick-up: jsdom doesn't have MutationObserver https://github.com/tmpvar/jsdom/issues/639

**Comment by EisenbergEffect** [comment]
I think we could emulate it. It's not needed much for server-side stuff.

**Comment by MeirionHughes** [comment]
yeah, I guess in principle its not super difficult to keep track of observed nodes and dirty check.
