### ISSUE TITLE
empty view template throws TypeError: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by jrigsby** [aurelia/templating#385]
I have a custom element with an empty view template 

        <template></template>

.  Work is done in the viewmodel class to build a progress bar.  When I go to a page that includes it (stripped page down to just the require tag) it throws the following error.  This didn't happen in prior version (just updated today to latest via jspm update).  If I add a single space to the file it will work fine.  

aurelia-logging-console.js?bust=1465942700016:54 ERROR [app-router] TypeError: Cannot read property 'nodeType' of null
    at ViewCompiler.compile (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js?bust=1465942700016:2462:21)
    at eval (http://localhost:43436/dist/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.2/aurelia-templating.js?bust=1465942700016:3109:50)

**Comment by EisenbergEffect** [comment]
Just curious...why would you have an empty template?

**Comment by shanonvl** [comment]
Getting the same thing, it's [here in the code](https://github.com/aurelia/templating/blob/master/src/view-compiler.js#L130):

```javascript
...
   let firstChild = content.firstChild;
    if (firstChild.nodeType === 1) {   // <--- when empty template, firstChild is null
      let targetId = firstChild.getAttribute('au-target-id');
      if (targetId) {
...
```

@EisenbergEffect I have empty templates b/c I'm using them as placeholders for optional markup arguments to a custom element.    I'm about to submit a PR which includes a fix + unit test for this -- feel free to merge if it's implemented properly.

**Comment by EisenbergEffect** [comment]
Yes, PR is welcome :)

**Comment by jrigsby** [comment]
Because I dont need the view.  Everything Im doing is in the view model.

        import {customElement, inject, bindable} from "aurelia-framework";
import * as $ from "jquery";
import "bootstrap";

//https://github.com/aurelia/templating/issues/233

@customElement("progressbar")
@inject(Element)
export class ProgressBar {
    element: Element;
    @bindable value: number = 0;
    @bindable max: number = 100;
    @bindable min: number = 0;
    @bindable role: string;
    @bindable style: string;

    constructor(element) {
        this.element = element;
    }

    bind() {
        //$(this.element).collapse();
        //class="progress-bar progress-bar-success"
        $(this.element).removeClass("progress-bar").addClass("progress-bar");
        $(this.element).css("width", this.value + "%").attr("aria-valuenow", this.value).attr("aria-valuemax", this.max).attr("aria-valuemin", this.min); 
        if (this.role) {
            $(this.element).attr("role", this.role);
        }
        if (this.style) {
            $(this.element).attr("style", this.style);
        }
    }

    valueChanged(newValue) {
        $(this.element).css("width", newValue + "%").attr("aria-valuenow", newValue); 
    }

    maxChanged(newValue) {
        $(this.element).attr("aria-valuemax", newValue);
    }

    minChanged(newValue) {
        $(this.element).attr("aria-valuemin", newValue);
    }

    roleChanged(newValue) {
        $(this.element).attr("role", newValue);
    }

    styleChanged(newValue) {
        $(this.element).attr("style", newValue);
    }

    unbind() {

    }
}

**Comment by EisenbergEffect** [comment]
If you don't need a view, put a `@noView()` decorator on your view model. That will turn off view loading and compilation for that component, which is much more efficient.

**Comment by jrigsby** [comment]
Cool.  It may be in some documentation somewhere but whats available is horrible to go through.  So I make do.

**Comment by atsu85** [comment]
@EisenbergEffect, I'm wondering if instead of allowing empty templates, the error message could be changed to smth more informative, so it could contain instructions about `@noView`?

**Comment by EisenbergEffect** [comment]
That would seem to make sense to me.

**Comment by sapiens** [comment]
I was having the same problem, but for an empty view used for a default child route. `@noView` doesn't solve the problem, the only solution is to have an empty tag inside.

**Comment by shanonvl** [comment]
@EisenbergEffect my use case is no longer valid given that `<slot>`s will be used moving forward.  I'll  close the PR.

**Comment by Thanood** [comment]
Please don't close it. Consider html-only components like this:

```html
<template bindable="isActive" class="${ isActive ? 'is-active' : '' }"></template>
```

Btw: it works if there is at least a character between the tags. Like a newline.

**Comment by valichek** [comment]
@EisenbergEffect I got similar issue with latest update

My code is:
```html
<template replaceable part="top"></template>
```

I get error
```
TypeError: firstChild is null
    compile@http://localhost:3000/1.bundle.js:19393:1
    _compileElement@http://localhost:3000/1.bundle.js:19588:22
    _compileNode@http://localhost:3000/1.bundle.js:19421:17
    _compileElement@http://localhost:3000/1.bundle.js:19713:25
    _compileNode@http://localhost:3000/1.bundle.js:19421:17
    _compileElement@http://localhost:3000/1.bundle.js:19713:25
    _compileNode@http://localhost:3000/1.bundle.js:19421:17
    _compileNode@http://localhost:3000/1.bundle.js:19443:27
    compile@http://localhost:3000/1.bundle.js:19390:6
    loadViewFactory/</registryEntry.onReady<@http://localhost:3000/1.bundle.js:20040:28
```

The issue can be fixed by just adding some comment inside:

```html
<template replaceable part="top">
  <!--comment here-->
</template>
```

Maybe related to https://github.com/aurelia/templating/issues/388#issuecomment-226280474
