### ISSUE TITLE
Binding context of component is not reachable when using slots

### ISSUE THREAD

**Issue by valichek** [aurelia/templating#390]
Following approach worked when replace parts used. 
If it is not a bug would be nice to get some suggestions on how to solve the issue.

```javascript
export class Custom {
  
  doSmth() {
    alert("doSmth");
  }
  
}
```

```html
<template>

  <slot>
    <button click.delegate="doSmth()">Default</button>
  </slot>
  
</template>
```

```html
<custom>
    <button click.delegate="doSmth()">First slot</button>
  </custom>
  
  <custom>
    <!--comment here-->
  </custom>
```
Here is a Gist example:
https://gist.run/?id=ed38d664a94f3192698c8bbb959004ae

**Comment by levan-g** [comment]
It's not a bug. it's default behavior. 

This should work for you:
```html
<custom view-model.ref="custom">
    <button click.delegate="custom.doSmth()">First slot</button>
</custom>
```

**Comment by EisenbergEffect** [comment]
We added back the `replaceable` attribute in the latest release to enable this scenario. It's not how slots work though.
