### ISSUE TITLE
template replaceable not working in 1.0.0-beta.3+

### ISSUE THREAD

**Issue by danfma** [aurelia/templating#391]
Hey guys,

Did the change to the new slot system affected the template replaceable parts? I had a composition here that worked before and after the change it is not working anymore.

I already changed all the content to the new slots and that are working again, but I have a component called *list-on-demand* which has the following part:

```html
<template> 
  <ul class="ui middle aligned divided list">
      <li repeat.for="item of listSrc" class="item">
        <template replaceable part="list-item-template">
          ${item}
        </template>
      </li>
  </ul>
</template>
```

and its usage as 

```html
<list-on-demand>
  <template replace-part="list-item-template">
    <div class="territory-item" click.delegate="$parent.$parent.selectTerritory(item)">
      <span>${item.name | lowercase}</span>
      <i class="icon angle right"></i>
    </div>
  </template>
</list-on-demand>
```

**Comment by EisenbergEffect** [comment]
Hmm. We removed the replaceable attribute because it can be handled by slot fallback...but this might be an exception. We can certainly add it back today. I take it you don't want the li to re replaceable. You want the content inside it to be repaceable, is that correct?

**Comment by danfma** [comment]
Thanks, Rob for the quick reply!

Yes, in this case, I want to define the template of each item when using the `<list-on-demand>` element, because I need that `item.name` to be at the context of the `repeat` there and not at the parent context.

I could create some custom elements to overcome this problem, but I just need to know the correct way to do that, by the Aurelia team. :)

**Comment by EisenbergEffect** [comment]
I think the best solution is for us to add that attribute back. It was really simple anyway. We thought it was redundant, but this particular scenario requires it.

**Comment by danfma** [comment]
Ok, I'll wait for this. You said that it will be back at night, don't you?

**Comment by EisenbergEffect** [comment]
It's already released :)

**Comment by danfma** [comment]
Thank you, Rob! I just check it now and it's working again! 👍
