### ISSUE TITLE
Propose: contextual children custom elements

### ISSUE THREAD

**Issue by danfma** [aurelia/templating#392]
# Scenario

Suppose that you have two custom elements for lists: _list-a_ and a _list-b_. If you have a list, then you must have items too, so at the current specification, we have to create two custom element types _item-a_ and _item-b_, each defined for each list.

That will have the following impact in the usage:

``` html
<list-a>
  <item-a>...</item-a>
  <item-a>...</item-a>
  <item-a>...</item-a>
</list-a>

<list-b>
  <item-b>...</item-b>
  <item-b>...</item-b>
  <item-b>...</item-b>
</list-b>
```
# Problem

While this is a reasonable and simple example, for most complex scenarios, where we have more long names for elements it will cause some ugly html element definition and usage, like `something-list` and `something-list-item`...
# Propose

If for this kind of element we could define a custom element that has semantic meaning only at the parent element, then we can write:

``` html
<list-a>
  <item>...</item> 
  <item>...</item> 
</list-a>

<list-b>
  <item>...</item> 
  <item>...</item> 
</list-b>
```

The `item` in `item-a` will be rendered as the `item-a` element and the `item` from `list-b` will be rendered as the `item-b` element.
## Definition

The definition could be done at the parent (most logical) **or** at the children;
## Definition at the parent as one alias

``` typescript
import { ItemA } from "./item-a";

@childrenAlias({ alias: "item", element: ItemA })
export class ListA {

}
```
## Definition at the children

``` typescript
@parentAlias({ parentTag: "item-a", alias: "item" })
export class ItemA {
}
```

or 

``` typescript
@parentAlias({ parent: ListA, alias: "item" })
export class ItemA {

}
```

**Comment by levan-g** [comment]
+1

**Comment by jdanyow** [comment]
another example I've seen mentioned:

```html
<layoutgrid>
  <row></row>
  <col></col>
</layoutgrid>
```

```html
<datagrid>
  <col></col>
</datagrid>
```

**Comment by levan-g** [comment]
Hi, for now you can use this hack:
```js
import {processContent, customElement} from 'aurelia-framework';

export function childrenAlias(tagName: string, alias: string) {
	return function (target) {
		let deco = processContent((compiler, resources, element, instruction) => {
			for (let i = 0; i < element.children.length; i++) {
				let node = node.children[i];
				if (node.tagName.toLowerCase() === tagName) {
					let newNode = document.createElement(alias);
					newNode.innerHTML = node.innerHTML;
					for (let ii = 0; ii < node.attributes.length; ii++) {
						newNode.setAttrubute(
							node.attributes[ii].name,
							node.attributes[ii].value
						);
					}
					node.parentNode.replaceChild(newNode, node);
				}
			}
			return true;
		});

		deco(target);
	}
}

@customElement('list-a')
@childrenAlias('item', 'item-a')
export class ListA {

}

@customElement('list-b')
@childrenAlias('item', 'item-b')
export class ListB {

}
```
Note: you still need to register "item-a" and "item-b" as custom elements.

**Comment by Alexander-Taran** [comment]
This one can be closed. I think.
for semantics `as-element` would do

**Comment by EisenbergEffect** [comment]
Closing this since it clashes with the web component specification and is therefor something we're not likely to do.
