### ISSUE TITLE
Typescript: need to declare class variables.

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/templating#396]
the typings for the instructions aren't great. Most of the fields are missing. It would appear it is because the instructions don't declare the field in the class, they are simply assigned in the constructor. Then presumably that doesn't get included in the typings. 

example: https://github.com/aurelia/templating/blob/master/src/instructions.js#L146

**Comment by EisenbergEffect** [comment]
Yes, we can certainly improve all of that. It's mostly internal details though. If you were using that I'd probably be concerned ;) But in your case, knowing what you are doing, I'll make an exception :) Let me know if you have any questions in the mean time.

**Comment by MeirionHughes** [comment]
Would you accept a PR if I define the variables through-out? I _really_ like intellisense...  :D

**Comment by EisenbergEffect** [comment]
What do you mean by "variables throughout"?

**Comment by MeirionHughes** [comment]
well basically defining the variables explicitly in the class, and raising PRs when I spot (need) them. 

So for ViewCompileInstruction 
```ts
constructor(targetShadowDOM?: boolean = false, compileSurrogate?: boolean = false) {
    this.targetShadowDOM = targetShadowDOM;
    this.compileSurrogate = compileSurrogate;
    this.associatedModuleId = null;
}
```
I guess it needs;

```ts
export class ViewCompileInstruction
{
    targetShadowDOM: boolean ;
    compileSurrogate: boolean;
    associatedModuleId: string;
    ...
```

unless there is some trickery you can do when you generate the `d.ts` typings?

**Comment by EisenbergEffect** [comment]
Oh, gotcha. Yes, absolutely. If you want to move those to fields and define the types, that's fantastic. We're happy to take PRs like that.

**Comment by MeirionHughes** [comment]
Btw, do you need me to sign anything for contributions?

**Comment by EisenbergEffect** [comment]
Stock message ;)

We noticed that you haven't yet signed our CLA. We would appreciate it if you would consider doing that for us. Before signing, please take a few minutes to read [our contributing guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md). These guidelines will help get you up to speed on how our community likes to operate and how the pull request process works. Once you have read that, assuming you are in agreement, simply [sign our online CLA](https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1).

After you've signed, please ping this issue.

**Comment by jods4** [comment]
+1 was about to open an issue for that.
Most classes lack public fields in `aurelia-templating` type defs. For example `TargetInstruction`, `ViewSlot`, etc.

This is not a problem for most users but when trying to do advanced stuff that manipulates instructions / `View` / `ViewSlot` directly, the experience with TS is not good :(

A downside is that it is unclear which fields are considered internal implementation details and which fields are public supported API.

**Comment by EisenbergEffect** [comment]
PR merged. We've opened up more apis as public in templating. We're being careful about this because if we open up the wrong things, we prevent ourselves from making future optimizations. If there's something you need specifically, make a request and we can consider it.
