### ISSUE TITLE
Support Typing in ViewOnly Templates?

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/templating#399]
Will Aurelia support typing of variables created in View-Only Templates?

I'm currently flirting with the idea of doing something like, one of these:

```html
<require symbols="{Item}" from="./path/to/item"></import>
<require symbols="{Foo}" from="./foo"></import>
<template bindable="items:Item[], foo:Foo" >
   <table>
    <tr repeat.for="item of items">
      <td>${item.address.knock().result}</td>
    </tr>
  </table>
<template> 
```

```html
<template symbols="{Item}" from="./path/to/item"  bindable="items:Item[]">
     ...
```

```html
<template symbols="{Item}, {Foo}" from="./path/to/item,./foo"  bindable="items:Item[], foo:Foo">
     ...
```

```html 
<template bindable="items:Item[], foo:Foo" >
    <require symbols="{Item}" from="./path/to/item"></import>
    <require symbols="{Foo}" from="./foo"></import>
```

```html 
<!-- reference symbols="{Item}" path="./path/to/item" -->
<!-- reference symbols="{Foo}" path="foo" -->
<template bindable="items:Item[], foo:Foo" >
    ...
```

I could quite easily then [lint this and check type usage is correct](https://github.com/MeirionHughes/aurelia-template-lint) at build time. 

Having the require inside the the template is a little more difficult for me to because the linter currently doesn't look ahead; it analysis based on previous state changes. 

Now I technically could just simply do any of these above, then strip out the extra html, as a gulp task, and you'd be left with 
```html
<template bindable="items, foo">
     ...
```
However, I would prefer to come to a consensus on how you'd want to do it. Then have aurelia deal with the syntax even if that means ignoring it for the foreseeable future.

**Comment by EisenbergEffect** [comment]
I don't think we're going to add tyings into the html templates.
