### ISSUE TITLE
Enable CustomElement to handle content manually

### ISSUE THREAD

**Issue by RichiCoder1** [aurelia/templating#4]
Problem
=======
Currently there is no way to pass raw content into the innerHtml of a CustomElement and have it manually processed.
ex:
```html
<x-markdown>
    Title
    ======
    
    # Items
    ....
</x-markdown>
```

Attempted to consume the markdown within the CustomElement is impossible, as Aurelia will attempt to process it.

Solution
=======
Add a Metadata extension which allows you to signal Aurelia that the CustomElement will parse it's inner content it's self.

Recommendations:
```
Metadata.handlesContentManually();
Metadata.skipProcessingContent();
```

**Comment by t3hprofit** [comment]
`Metadata.skipContentProcessing();` rolls off the tongue a little easier or `Metadata.deferContentCompilation();` possibly

**Comment by RichiCoder1** [comment]
Defer makes it seem like the engine will still do it at some point. We want complete control with the CustomElement. 
Agreed on `skipContentProcessing();`

**Comment by EisenbergEffect** [comment]
Use `.skipContentProcessing()`. You  may also want to use this in conjunction with `.noView()`. It will go out in the next templating release, today or tomorrow.

**Comment by RichiCoder1** [comment]
Yay :D
