### ISSUE TITLE
@child-annotated field is 'undefined'

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/templating#400]
Some of my components broke after upgrading to the RC. If I try this:

```ts
import {autoinject, child} from 'aurelia-framework';

@autoinject
export class Childtester {

	@child("h1")
	title: Element;

	constructor(private element: Element) {
	}

	dump() {
		console.log(this.title);
		console.log(this.element.querySelector("h1"));
	}
}
```

```html
<template>
  <h1 click.trigger="dump()">Lorem Ipsum</h1>
</template>
```

then when I click the h1 it logs `undefined` for `this.title` and the `<h1>` element for `this.element.querySelector("h1")`. The same happens if I use `@children`.

**Comment by EisenbergEffect** [comment]
We will investigate.

**Comment by shabalin** [comment]
Hi, we are experiencing the same issue after upgrade aurlia libs to 1.0.0-rc.1.0.0

**Comment by DerAlbertCom** [comment]
me, to but only on navigation to the view, works in f5. see also #403

**Comment by DerAlbertCom** [comment]
it seems a timing issue, if i "encapsulate" the access to the property in `setTimeout(()=>....,0)` the property is assigned.

**Comment by RomkeVdMeulen** [comment]
This issue is blocking our upgrade to the RC. I'm hoping somebody will have a chance to look at it soon.

**Comment by EisenbergEffect** [comment]
Ok, now that I've had a look at this, I think it's a misunderstanding of `@child` and `@children`. These decorators allow an element to select its *content* child or children. That's the content placed inside the custom element by the consumer. If you want to select the view's own elements, you would use `ref`.

**Comment by RomkeVdMeulen** [comment]
I see. Thanks for clearing that up!

Is there something I missed in the docs? Or just misunderstood?
