### ISSUE TITLE
Copying over array doesn't seem to trigger view update

### ISSUE THREAD

**Issue by silverbucket** [aurelia/templating#404]
I've successfully had an array displayed in the view using the following:

```html
<div id="files">
  <ul>
    <li repeat.for="file of files">
      <span>[${file.uid}] ${file.name} - ${file.generatedChecksum || file.checksum}</span>
      <button click.trigger="playMedia(file)">play</button>
      <div if.bind="!file.existsLocally"><button click.trigger="startTransmission(file)">download</button></div>
    </li>
  </ul>
</div>
```

Where I used to always just `push` elements onto the array, I had to alter the code and now - in order to ensure there are no duplicate entries - I'm copying/processing the array and then re-assigning this.test with a new array.

```javascript
   // ... process array and create a new one
   this.files = newArray;
```

Since I've done this, the UI doesn't seem to update any longer. It usually works for the first entry, but when I add a second, or third entry, the UI still just lists the first. No errors are present, and when I debug the code I can verify that the `this.files` array has more entries than what is being displayed in the UI.

Is there some property or step I need to take to ensure that the UI updates?

**Comment by jdanyow** [comment]
could you put together a gist that demonstrates this issue? https://gist.run/?id=7542e061bc940cde506b

We have extensive tests that cover this use-case- would be surprising if re-assigning the array didn't work.

**Comment by silverbucket** [comment]
@jdanyow sure will attempt to do this now.

**Comment by silverbucket** [comment]
@jdanyow - Alright here's what I've been able to produce: https://gist.run/?id=9538acd77d0403da3c691fad6149c63a

This uses a library I use called "ArrayKeys" which I included in the source. It essentially manages an internal array but lets you look up it's elements using keys. During it's management of it's internal array `_store`, it appends the entry using the `length` value of the existing array.

So perhaps it's not that the array is being overridden each time, but that I'm not using traditional `.push()`?

**Comment by silverbucket** [comment]
ping @jdanyow - have you had a chance to take a look at this issue?

**Comment by jdanyow** [comment]
@silverbucket right- aurelia observes array mutation by intercepting calls to splice, push, pop, shift, etc.  If you circumvent those methods the change won't be observed.  This approach is extremely lightweight in terms of memory usage and eliminates the need for dirty-checking but it does have this limitation you're seeing around indexed-assignment.

**Comment by silverbucket** [comment]
@jdanyow thanks for the clarification, not ideal - but it makes sense as to why.
