### ISSUE TITLE
au-target-id

### ISSUE THREAD

**Issue by dredzone** [aurelia/templating#405]
I have more of a question rather then issue, when inspecting DOM (runtime) I see many au-target-ids attributes with the same values on different elements, what is the purpose of au-target-id?

**Comment by EisenbergEffect** [comment]
The view compiler tags elements which have bindings, custom attributes or custom element behavior. Each gets an id so that it can be looked up in the compiled view's internal compilation instruction list whenever a new view instance needs to be created.

**Comment by dredzone** [comment]
so If I use <compose view-model='widget'> element inside the loop (repeat), shouldn't au-target-id be different for each resulting widget's view? I expect new widget instance on each iteration.

**Comment by EisenbergEffect** [comment]
No. Those aren't instance ids, they are definition ids.

**Comment by dredzone** [comment]
understood, thank you.

**Comment by Muditr93** [comment]
how can console.log() these IDs for that particular custom element ?
