### ISSUE TITLE
@useShadowDOM does not work

### ISSUE THREAD

**Issue by srollinet** [aurelia/templating#407]
Using the RC1 version, when I decorate a custom element with @useShadowDOM nothing seems to happen.

```
import {useShadowDOM} from 'aurelia-framework';
@useShadowDOM
export class MyElement {
}
```

```
<template>
  <require from="./myelement.css" as="scoped"></require>
  <div></div>
</template>
```

![image](https://cloud.githubusercontent.com/assets/12350967/16466350/105e63e2-3e43-11e6-9a30-b5b074706730.png)

I should have a shadow-root in my-element, right? Am I missing something?

**Comment by EisenbergEffect** [comment]
You aren't missing anything but the browsers are. There is no browser that currently implements Shadow DOM v1. When the browser doesn't support it, our fallback kicks in.

**Comment by srollinet** [comment]
Ok, thanks for the answer.

So it won't be possible to have a local css in a custom element without having a browser that implements Shadow DOM v1? (Except using Firefox with a scoped css)

**Comment by EisenbergEffect** [comment]
Yes. However, there are probably better ways to handle the CSS because even Shadow DOM has issues (no sharing of styles, for example). You may want to look into CSS Modules.
