### ISSUE TITLE
slot does not seem to work with svg

### ISSUE THREAD

**Issue by caperavensoftware** [aurelia/templating#408]
`<template>
    <require from="./selection-highlight.css"></require>
    <svg class="highlight-item" ref="highlightElement"><slot></slot></svg>
</template>`

when using

`        <selection-highlight selected-item.two-way="selectedTab">
            <rect class="highlight-rect" />
        </selection-highlight>`

it does appear in the render tree in chrome dev tools but it does not draw.
if I edit the html in chrome and delete the slot comment element it renders fine.

is this a aurelia issue or something else?

**Comment by EisenbergEffect** [comment]
I don't believe the spec is designed to enable slot inside an svg. It's part of the HTML spec.
