### ISSUE TITLE
binding does not work, IE11, typescript transpiled to ES5

### ISSUE THREAD

**Issue by dkent600** [aurelia/templating#410]
In my Aurelia application, IE11, typescript transpiled to ES5, with the attached view and view-model ("test"), the following html is generated.  The problem I am reporting herein is that the view-model data has not been bound:

![capture](https://cloud.githubusercontent.com/assets/1821666/16534354/1d9267c8-3fad-11e6-8585-f06655c07d72.JPG)

The same binding works fine in Chrome.

Relevent code:  [views.zip](https://github.com/aurelia/templating/files/344177/views.zip)

**Comment by Gheoan** [comment]
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/4 Read the section about tables.

**Comment by dkent600** [comment]
I see, thanks, but those examples in the docs don't work for a more complicated template I am using in my app, where the template is not a simple `tr` element (see below for the code).  

See this section on containerless templates:  http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/6

According to that section  one can put the repeat.for in the `template` tag.  What, then, are the rules for when this is allowed and when it isn't?  It works in some cases and not others?  How can I create a containerless template that will work in the example given below? Thanks.

```
<template repeat.for="productType of productTypes">
                        <tr>
                            <th id="cat" colspan="7" scope="colgroup" style="background-color: lightgrey">${productType.ProductTypeName}</th>
                        </tr>
                        <tr repeat.for="order of productType.OrderProducts">
                            <td headers="cat Code">${order.Code_Internal & oneTime}</td>
                            <td headers="cat TX">${order.TX ? "TX" : "" & oneTime}</td>
                            <td headers="cat Desc">${order.Description & oneTime}</td>
                            <td headers="cat Unit">${order.Unit & oneTime}</td>
                            <td headers="cat UnitPrice" style="text-align: right">${order.UnitPrice | currency & oneTime}</td>
                            <td headers="cat Qty" style="text-align: center"><input style="width: 60px;" type="number" min="0" value.bind="order.Quantity"></td>
                            <td headers="cat TotalPrice" style="text-align: right">${order.TotalPrice | currency}</td>
                        </tr>
                    </template>
```

**Comment by Gheoan** [comment]
My understanding is that the html spec has rules about the permitted content of elements. For `table` the spec is very strict allowing only table related elements as content of `table`. In your case, IE11 removes the `template` element before Aurelia gets a look-in.

**Comment by dkent600** [comment]
Are you saying there is currently no way in Aurelia to accomplish this use case in IE11?

**Comment by levan-g** [comment]
@dkent600 ```table``` allows multiple ```tbody``` elements, so you can repeat ```tbody``` insted of template
```html
<table>
    <tbody repeat.for="productType of productTypes">
        <tr>
            <th id="cat" colspan="7" scope="colgroup" style="background-color: lightgrey">${productType.ProductTypeName}</th>
        </tr>
        <tr repeat.for="order of productType.OrderProducts">
            <td headers="cat Code">${order.Code_Internal & oneTime}</td>
            <td headers="cat TX">${order.TX ? "TX" : "" & oneTime}</td>
            <td headers="cat Desc">${order.Description & oneTime}</td>
            <td headers="cat Unit">${order.Unit & oneTime}</td>
            <td headers="cat UnitPrice" style="text-align: right">${order.UnitPrice | currency & oneTime}</td>
            <td headers="cat Qty" style="text-align: center">
                <input style="width: 60px;" type="number" min="0" value.bind="order.Quantity">
            </td>
            <td headers="cat TotalPrice" style="text-align: right">${order.TotalPrice | currency}</td>
        </tr>
    </tbody>
</table>

```

**Comment by dkent600** [comment]
Ah, I didn't know that multiple `tbody` would be allowed, thanks.  It works.

So, I am still a bit nervous about the lack of an explicit "virtual" binding ability (a la knockout), but maybe it'll work out fine.  So I will go ahead and close this.
