### ISSUE TITLE
Feature request: easily override binding context

### ISSUE THREAD

**Issue by jods4** [aurelia/templating#411]
I can't find a way to easily create an override context for a custom element or custom attribute.
Let's say you want to create this:
```html
<div magic-attribute>
${ $magic } was magically added in context.
</div>
<magic-element>
 ${ $magic } was magically added in context
</magic-element>
```

The intuition would be something like the following code: 
```js
bind(bindingContext, overrideContext) {
  bindingContext['$magic'] = 'Shazzam';
}
```

Now this works but it pollutes the external binding and so is broken in many situations. What you need is to create a new overrideContext. The problem is that `bind()` is too late for that. And you can't actually return a new context anyway, only modify the ones passed from above!

Looking at the source of `with` I figured that the only way to do so is to take control of your template and contents -- and bind them yourself. Which is way too complex and needs `ViewSlots`, `ViewFactory`, etc. Plus you loose many features that the templating engine can do for you if it manages your templates.

What would be nice is an early event like `beforeBind` or something, where you can manipulate the binding context, from top to bottom.

**Comment by EisenbergEffect** [comment]
Is there some reason you can't just add that property to the overrideContext?

**Comment by jods4** [comment]
I tried and it doesn't seem to work. How would you do that? `bind(c, o) { o.magic = 42 }`?

**Comment by EisenbergEffect** [comment]
Yes, just like that. That would give you a new property named `magic`.

**Comment by jods4** [comment]
Doesn't work. I _think_ it's because at this point the children have been bound already (right?) and since the `magic` property did not exist at that point, they observe the `bindingContext` for its creation.

**Comment by EisenbergEffect** [comment]
@jdanyow Will need to comment. If it is too late, we will need to document that. You could implement the created callback. You can access the override context from the view that is passed there and augment there.

**Comment by jods4** [comment]
I tried `created`. Not working either because at this point the views `bindingContext` and `overrideContext` are both `null`. From my understanding of the source code, they will be set when `View.bind()` is called.

It seems to me that the only point I could tap into would be this line inside `View.bind()`: 
```js
this.resources._invokeHook('beforeBind', this);
```
but I don't know where it goes. Not into your custom element `beforeBind()` at least, I tried!

**Comment by EisenbergEffect** [comment]
Well, you can implement a view resource hook to augment the binding context. If that's all you need to do, it's a better technique than using a custom attribute.

```javascript
@viewEngineHooks()
export class Magic {
  beforeBind(view) {
    //add the stuff you want here
  }
}
```

Then in your view

```html
<require from="./magic"></require>
```

@jdanyow Should we have a way for attributes and elements to do this? or should we make this explicit through the view engine hooks we have only.

**Comment by jods4** [comment]
This is a crazy rabbit hole.

The `ViewEngineHooks` solution is really dirty because of course, this is not all I'm doing and the actual values I want to inject are linked to my custom-elements, etc.

But I tried, because if I can create a `bindingContext` layer for my custom control with this then at least it would work.

Yet I couldn't get it to work. The `beforeBind()` hook grants me access to the bindingContext before it's bound... except that for a custom element that projects its contents into a `<slot>`, i.e. something like that: 
```html
<magic-wrapper>
  <div>Some content that would like to use $magic properties</div>
</magic-wrapper>

<!-- magic-wrapper template: -->
<template>
  <div> 
    Some stuff
    <slot></slot>
  </div>
```

Then in this case the view bindingContext is not the one used inside the slot... 

I tried to grab the correct bindingContext by using `__parentBindingContext` or `viewModelScope.bindingContext` but then I couldn't enhance the context properly.
It seems that at this point the `undefined` property had already appeared, so I guess it was too late.

**Comment by jods4** [comment]
OK I think I figured out the key problem here.

Consider this page:
```html
<template>
  <div>${title}</div>
  <magic-element>
    ${magicValue}
  </magic-element>
  <div>${footer}</div>
</template>
```

When aurelia binds this view, _it sees all bindings flat at the first level._
So when at the top level, it's going to evaluate `${title}`, `${magicValue}` and `${footer}`.
Then it's going to process all custom elements in a top-down fashion, but as you've guessed it's too late.
The trick here is that by default Aurelia makes no scope boundaries at custom element. For what I asked for to work, Aurelia would need to evaluate the contents of `<magic-element>` inside its own context, which it doesn't.

It seems that the only way to break the chain is to use a custom attribute that _lifts_ its content, i.e. decored with `@templateController`. This is how `with`, `repeat` and co. actually work.

For custom elements, another option would be to use `@processContent` to stop Aurelia processing at the element boundaries and then re-instantiate it yourself. Actually, this comes down to being able to say a custom element is `@templateController`, which is #171.

In conclusion these makes it very hard to create a custom element (or even a custom attribute, although it's a bit easier) that injects observable properties in its scope.

**Feature request**
I would love if aurelia had some `@overrideScope` attribute that would:
1. Create a view boundary at that custom element, so that its child bindings are evaluated inside its own context.
2. Automatically create an `overrideContext`.
3. Let me modify the `overrideContext` inside `bind()` _before_ the children are bound (or inside `beforeBind()` if it `bind()` cannot work).

**Example usages**
To motivate the feature, here are the kind of things we can do with it: create a `<my-form readonly.bind="true">` custom element that propagates a `$readonly` value inside it, which can then be bound: `<input readonly.bind='$readonly'>` (yeah, I wish HTML would work like that automatically...).

Something similar could be done for a validation context, that could be accessed by validated children.

Re-implement anything similar to the `with` attribute as a custom element. Or even re-implement `with` in a simpler way.

**Comment by jods4** [comment]
**Workaround** 
After a lot of code reading and debugging I finally found a useable work-around. 
For those interested, here it is (a word of caution: it's convoluted).

First I defined an `own-context` custom attribute. It basically works like a simplified `with` binding. 
This custom attribute will instantiate its content itself, and while doing so create an override context with an empty object.
```js
import { inject, templateController, BoundViewFactory, ViewSlot } from 'aurelia-framework';
import { createOverrideContext } from 'aurelia-binding';

@templateController
@inject(BoundViewFactory, ViewSlot)
export class ContextCustomAttribute {    
    constructor(factory, slot) {
        this.factory = factory; 
        this.slot = slot;
    }

    bind(bindingContext, overrideContext) {
        let newContext = { };
        overrideContext = createOverrideContext(newContext, overrideContext); 
        if (!this.view) {
            this.view = this.factory.create(); 
            this.view.bind(newContext, overrideContext); 
            this.slot.add(this.view); 
        } else { 
            this.view.bind(newContext, overrideContext); 
        } 
    }

    unbind() {
        if (this.view) this.view.unbind();
    }
}
````

This is most useful when used on a custom element, because then you can use the `bind()` method to enhance your local context with new data that will be bound by the children of your element, but not leak outside or be shared.

So now you can do this: 
```js
class MagicCustomElement {
  bind(context) {
    this.context = context; // for further manipulation by events, etc.
    context.$magic = 42;
  }
}
```
```html
<magic own-context>
  ${ $magic }
</magic>
```

Unfortunately you can't use this trick inside your custom element template, because the custom element would then loose track of the `<slot>`.
```html
<!-- magic.html, unfortunately we can't use own-context here, 
     because it would hide the slot from its parent -->
<template>
  <div>
    <h3>Magic frame</h3>
    <slot></slot>
  </div>
</template>
```

So you have to put it _on_ your custom element. But of course you don't want to do it explicitely like I did above... `@processAttributes` to the rescue! There is a catch, though: adding `own-context` attribute will lift the element into its own template for compilation... during which `processAttributes` is called again! So if we're not cautious we easily fall into an infinite compilation loop.
```js
@processAttributes(function(compiler, resources, node, attributes, instruction) {
    if (!node.hasOwnContext) {
        node.setAttribute('own-context', '');
        node.hasOwnContext = true;
    }
})
export class MagicCustomElement { /* ... */ }
```

And now we have a `<magic>` custom element that can inject its own variables into a private binding context! 🎆

**Comment by jdanyow** [comment]
re: https://github.com/aurelia/templating/issues/411#issuecomment-230329983

It's too late- the bindings are bound immediately before the view model's bind method is called.

https://github.com/aurelia/templating-resources/issues/171#issuecomment-166159327 is somewhat related, ignore my `<let>` element's implementation, it could potentially be done with view engine hooks now.

**Comment by jods4** [comment]
I have been reflecting on this a bit more and considered my use cases...
I am going to say that this is a bit of a niche API and if we get `@templateController` for custom elements then it'll be easy enough for both custom attributes and elements.

So feel free to decide if there's something you'd like to do here to make things easier -- like allowing an HTMLBehavior to break the context chain without requiring `templateController` -- or close this issue.

**Comment by EisenbergEffect** [comment]
We definitely want to be careful about adding new concepts. I think the element as template controller seems the most reasonable way to solve this while actually increasing consistency. I'll leave this open for now though.

**Comment by jdanyow** [comment]
tracking the rest of this in #171

**Comment by davismj** [comment]
`bindingContext['$magic'] = 'Shazzam';`

This was my favorite movie from the 90's.
