### ISSUE TITLE
replace parts don't work with embedded containers (ai-dialog for example)

### ISSUE THREAD

**Issue by gabor-farkas** [aurelia/templating#419]
Let's suppose we have a dialog that will be reused multiple times, but only a small part will differ. For the common parts, we created a base component that looks like:
```html
<!--base-dialog.html-->
<template>
    <ai-dialog>
        <ai-dialog-body>
            <div replaceable part="content">default content</div>
            <!--common content-->
        </ai-dialog-body>

        <ai-dialog-footer>
               <!-- common buttons -->
        </ai-dialog-footer>
    </ai-dialog>
```
And the actual dialog can use this like:
```html
<!-- actual-dialog.html-->
<template>
	<require from="./base-dialog"></require>
	<base-dialog dialog-model.bind="dialogModel" dialog-controller.bind="dialogController">
            <template replace-part="content">
                <!-- specific content -->
            </template>
	</base-dialog>
</template>
```

The problem here is that replacing don't work if the replaceable part is inside the ai-dialog or ai-dialog-body.
The problem I guess is that in viewfactory (https://github.com/aurelia/templating/blob/master/src/view-factory.js#L35) doesn't look in parent containers for partReplacements. (well of course I don't know if that would be a good solution for the problem).

I know that web component slots will soon replace this replaceable feature, so I don't know how long are you planning to maintain the replaceable feature here. I haven't yet had the chance to upgrade my project to the release candidate to check if this would work with slots.

Btw, I could work around this problem now by using a copy-paste of the replaceable attribute and modifying the constructor for this specific case:
```typescript
    constructor(viewFactory: any, viewSlot: any) {
        var container = viewFactory.parentContainer.parent.parent;
        var replacedFactory = container.partReplacements[viewFactory.viewFactory.part];
        viewFactory.viewFactory = replacedFactory;
        this.viewFactory = viewFactory;
        this.viewSlot = viewSlot;
        this.view = null;
    }
```

**Comment by EisenbergEffect** [comment]
This is probably fixed in the RC actually. But, that aside, this is best handled by slots.
