### ISSUE TITLE
Propose: Remove attribute `au-target-id`. Replace with property

### ISSUE THREAD

**Issue by bigopon** [aurelia/templating#422]
## Current State
Aurelia elements are marked with an id via attribute `au-target-id` in:
#### `line 53`:
```javascript
element.setAttribute('au-target-id', auTargetID);
```
Then usage of this attribute are in:
#### `line 131`:
```javascript
let targetId = firstChild.getAttribute('au-target-id');
```
and
#### `view-factory.js - line 436`
```javascript
if (createInstruction.enhance && fragment.hasAttribute('au-target-id')) {
  instructable = fragment;
  instruction = instructions[instructable.getAttribute('au-target-id')];
```

#### `line 53`:
```javascript
element.auTargetID = auTargetID
```
`Usage`:
#### `line 131`:
```javascript
let targetId = firstChild.auTargetID;
```
#### `view-factory.js -line 436`
```javascript
if (createInstruction.enhance && Object.hasOwnProperty.call(fragment, 'auTargetID')) {
  instructable = fragment;
  instruction = instructions[instructable.auTargetID]];
```

Optimize:
```javascript
let hasOwn = Object.hasOwnProperty; 
if (createInstruction.enhance && hasOwn.call(fragment, 'auTargetID')) // check like this
// or
let has = (el, prop) => hasOwn.call(el, prop); // cache somewhere
if (createInstruction.enhance && has(fragment, 'auTargetID')) // check like this
```

## Reason
It's unnecessary to use an attribute to mark/identify an element. Instead we can have cleaner DOM.

## Side Note
To ensure there won't be any conflicts with users' own props, we change `auTargetID` to `auTargetID__`

**Comment by EisenbergEffect** [comment]
This won't work because setting properties doesn't transfer when cloning the template. The only things that will be clones are actual HTML attribute values.
