### ISSUE TITLE
Weird issue with inheritance and typescript

### ISSUE THREAD

**Issue by dpinart** [aurelia/templating#424]
Hi
I usually code in typescript and till now I used to build typescript code with babel because it offers a polyfill for async/await pattern in ES5. I'm currentl getting rid of babel

I have a very simple ViewModelBase class that it's intendeed to implement basic behavior useful for most of view models along whole application. Therefore, most of view models in app extends this class. The issue is that depending the transpiler used-babelor typescrit- the application behaves differently. Below there's a very basic example
```
import {Subscription} from 'aurelia-event-aggregator';
export class ViewModelBase{
protected _subscriptions: Subscription[] = [];
public isBusy: boolean;
public busyContent: string;

protected addSubscription(subscription: Subscription){
    this._subscriptions.push(subscription);
  }

 protected removeSubscription(subscription: Subscription){
    subscription.dispose();
    let index = this._subscriptions.indexOf(subscription);
    if(index > -1)
      this._subscriptions.splice(index, 1);
  }
public deactivate() {
    for(var subscription of this._subscriptions)
      subscription.dispose();
    this._subscriptions = [];
  }
}

export class MyViewModel extends ViewModelBase{
publc attached(){
 alert('I'm on MyViewModel attached handler');
}
}
```

If code is transpiled by babel, 'attached' handler in MyViewModel class is invoked and I can see the alert but if code is transpiled by typescript I can't.

After some digging I found the reason is the way babel and typescript implements inehritance (extends) and how prototype is handled by both transpilers. In typescript, an instance of MyViewModel's prototype does not contain attached method while in babel it does.

In class HtmlBehaviorResource, in initialize method, there's
```
...
     var proto = target.prototype;
...
       this.handlesCreated = 'created' in proto;
      this.handlesBind = 'bind' in proto;
      this.handlesUnbind = 'unbind' in proto;
      this.handlesAttached = 'attached' in proto;
      this.handlesDetached = 'detached' in proto;
```
Threfore, if code is transpiled by babel, no problem, handlers defined in subclasses are always invoked becuase target (MyViewModel instance) prototype property contains all superclass and subclass memeber,  but if code is transpiled by typescript then we've got a big problem!: handlers defined only in subclasses are not being invoked!!

Right now, I have had to get back to babel transpiler although I'm no longer using async/await pattern bt I'd prefer to transpile with typescript in order to get better debug support from chrome.

I guess that looking for handles in target instead on looking them in target's prototype would fix the issue but I'm not 100% sure.

**Comment by EisenbergEffect** [comment]
This is a known issue with TypeScript. It doesn't handle inheritance in a spec compliant way and that causes problems in certain scenarios. I generally recommend developers to avoid inheritance anyway. You might consider creating a custom decorator that can apply the shared capabilities to any class that it decorates, instead of using a base class.

**Comment by dpinart** [comment]
thanks @EisenbergEffect. I did some reasearch before opening the issue but I couldn't find nothing about this known issue.

About creating custom decorators can you point to some link to get guidance?
