### ISSUE TITLE
processContent( ) setting instruction.enhance = true with DocumentFragment causes crash in ViewFactory.create

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating#426]
I need help with a crash that I am now getting after upgrading to Aurelia 1.0.0RC. Browser is IE11.

The failure is in this line of code in aurelia-templating.js:

```
function create(container, createInstruction, element) {
   -snip-
   if (createInstruction.enhance && *fragment.hasAttribute*('au-target-id')) {
```

The problem relates to the hasAttribute( ) method not being defined because the fragment is a DocumentFragment.

I have a tab control widget that I have built and it uses the processContent( ) method to process a logical definition of the "tabs" into a physical representation (ie. an @processContent decorator points to my processContent( ) method). The salient points of that code are (note: code is Typescript):

```
static processContent( compiler: ViewCompiler, resources: ViewResources, node: HTMLElement, instruction: ( BehaviorInstruction & any ) ): boolean
{
   // create the child elements that will hold our "processed" output
   let documentFragment: DocumentFragment = document.createDocumentFragment( );

   -snip-

   // use the instruction to hand back the number of tabs to the View Model
   instruction.tabPageCount = blah;

   // compile the document fragment
   instruction.enhance = true;
   instruction.viewFactory = compiler.compile( documentFragment, resources, instruction );

   // by returning true, we want Aurelia to post-process our "processed" result
   return true;
}
```

The above code could be wrong because I did not invent it and acquired it from sources on Gitter. But it did work correctly in the Beta, and now it does not.

If I set enhance to false, the "content" of my tab pages in this tab control are not "enhanced" by Aurelia anymore, so clearly I need enhance to be true.

(As an aside, the "enhance" property does not seem to be used by compiler.compile? Am I reading that correctly?)

I can't seem to find a workaround. I have tried:
- Converting my document fragment back into a string and passing that to compiler.compile. My bindings do not get attached.
- Taking the child nodes of my document fragment and replacing the content of the "node" passed into processContent( ) with my newly constructed content. In this case I don't call compiler.compile. Bindings do not get attached.

Any help _greatly_ appreciated.

**Comment by kevmeister68** [comment]
A small update:

It seems that when I pass in markup to compiler.compile, subordinate custom elements do get correctly instantiated by Aurelia, and _their_ bindings seem to work on face value. It is the bindings specifically of my tab control widget that are not getting wired up correctly.

**Comment by EisenbergEffect** [comment]
You cannot set the `enhance` property of the instruction when passing in a document fragment. Enhancement only works on live elements that are part of the document already.

**Comment by EisenbergEffect** [comment]
The code you acquired is incorrect and only worked "accidentally" previously.

**Comment by kevmeister68** [comment]
Okay, so the code I acquired is wrong. I had my suspicions anyway. Can you please tell me where I can find an example of the right way to do this? Even when I update the passed-in node "in situ", I still end up with non-functioning bindings for the custom element with the processContent decorator. If I compile a string, I get non-functioning bindings. I'm stuck.

Also, if you can't enhance a document fragment, for what specific user purpose would you pass a Document Fragment to compiler.compile?

**Comment by EisenbergEffect** [comment]
What you need to do is compile the fragment without the `enhance` setting. This will return a `ViewFactory` to you which you can still store on the instruction. Once you've done this, you are responsible for instantiating the the View for this content. You can have `TargetInstruction` injected into your element to gain access to the factory that you stored inside your component view model. You can then call `create` on the factory to create a `View`. You'll also want to have `ViewSlot` injected into your view model so that you can `add` the view.

**Comment by kevmeister68** [comment]
Okay, I shall give that a try. Do I create the view and add to the ViewSlot in the constructor, or via some other means?

**Comment by EisenbergEffect** [comment]
Take a look at this: https://github.com/aurelia/templating-resources/blob/master/src/replaceable.js

**Comment by kevmeister68** [comment]
Thanks for the help Rob. I've followed your instructions but when my bind( ) method attempts to perform the create( ) on the viewFactory, I am blowing up with:

ERROR [app-router] TypeError: Unable to get property 'createChild' of undefined or null reference
      stack: "TypeError: Unable to get property 'createChild' of undefined or null reference
    at createElementContainer (http://localhost/leb/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.1/aurelia-templating.js:2072:5)
    at applyInstructions (http://localhost/leb/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.1/aurelia-templating.js:2158:7)
    at create (http://localhost/leb/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.1/aurelia-templating.js:2383:9)
    at ViewElementFactoryBase.prototype.bind (http://localhost/leb/lebosi/hc-ui-base.js:139:17)
    at bind (http://localhost/leb/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.1/aurelia-templating.js:1427:9)
    at bind (http://localhost/leb/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.1/aurelia-templating.js:3369:9)
    at bind (http://localhost/leb/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.1/aurelia-templating.js:1433:9)
    at bind (http://localhost/leb/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.1/aurelia-templating.js:3369:9)
    at automa"

The "ViewElementFactoryBase" is my class that does the work. I think one of the following points is likely to be responsible for it not working.

- My processContent( ) function builds a DocumentFragment and passes that to compiler.compile( ) to get the viewFactory.
- My processContent( ) function deletes all existing children from "node" (passed in argument) and returns "false".
- My processContent( ) function stores the viewFactory in the instruction.viewFactory property passed into processContent, which my custom element view-model retrieves later. Should I use a different property name?
- I pass the "instruction" argument received by processContent( ) on to compiler.compile as its instruction arg -- or should I just pass NULL?
- My call to viewFactory.create( ) requires the first argument to be a "Container" (I'm using TS) - in the sample code you supplied you don't pass an argument to create( ) so I passed null.

Any ideas?

My instinct is the null container passed to create( ) is the culprit so I'll start seeing what effect passing the view-model's container might have.

**Comment by EisenbergEffect** [comment]
The sample code I showed was for a template controller which automatically binds itself to a Container based on its position in the view hierarchy. Sorry about not mentioning that! You need to supply a container to create the view from. You can do this by having `Container` injected into your class. Then create a child container to scope the component by calling `createChild()` on the container. Pass that child container to the view factory.

**Comment by kevmeister68** [comment]
Hi Rob, I am still stuck with this. My custom-element has the @processContent decorator but despite using your code example, and the modifications you suggest above (eg. inject Container, pass Container.createChild( ) to viewFactory.create( ), etc, the bindings for my custom-element do not get resolved, but everything else does.

I have tried passing "this" to view.bind( ) as the binding context. I have tried passing "bindingContext, overrideContext" (as passed into the bind( ) method) to view.bind( ). Nothing works for me.

My custom-element has the @noView decorator applied to it because there is no HTML file - could that cause a problem - if so what should I use if I don't have a HTML file?

I have traced into the bind code with a debugger and what seems to be happening is that two lots of bindings seem to occur - I have a "ref" in my custom-element and if I call view.bind( x ) using my view-model as x, the after the first bind I can see the correct value in the ref. But then it seems to get obliterated by another bind( ) operation on the same set of instructions, except the second set seems to try bind to something like my parent object (basically my main page view).

I am trying to get a Gist together but because I work in TS, that is proving to be just as much of a nightmare :-(

**Comment by EisenbergEffect** [comment]
Create a new project with the cli, change it to show your problem in the simples possible way. Exclude the npm modules, zip it and attach it here. I'll take a look.

**Comment by kevmeister68** [comment]
I hope you don't mind - I persevered with a Gist that runs in Gist.Run. If you need CLI let me know.

https://gist.run/?id=83b4831824d4b63ec7b9d4b344d9e05b

The two obvious failings at present are that no "tab" shows (only the headings). If you click on a tab you get an error about handleClickEvent not being found -- both of these are both caused by the bindings not attaching to the correct object or something.

The important files are hc-ui-tabcontrol.js and hc-ui-base.js. The tabcontrol file contains the processContent( ) method and DOM manipulation code (a comment at the top explains what it is doing). The practical reality of the tab definition is seen in app.html. The remaining guts of hc-ui-tabcontrol is basically manipulating various properties that control visibility of the tabs.

(You may recall a separate conversation we have had about avoid lifecyle commencement for tabs that have never been activated -- that's what all the rigmarole is here for).

hc-ui-base.js (look for ViewElementFactoryBase.bind) contains the bind code that creates the view from the view factory, adds it to the view-slot, and calls .bind on the view. Ultimately I have tried numerous various without success.

Thanks for your help. I have burned a bucket load of hours (incl. most of my weekend) trying to get this working.

**Comment by EisenbergEffect** [comment]
Would it be possible for you to create a more streamlined sample? perhaps one without code that's been emitted from a transpiler? That would really help me to identify the issue.

**Comment by kevmeister68** [comment]
Sure. I will get onto it.

**Comment by kevmeister68** [comment]
Hi Rob, is this one any better for you? hc-ui-tabcontrol.js is your main file.

https://gist.run/?id=0f5f449dd59b33d56dc7cfcf91c0034a

**Comment by kevmeister68** [comment]
Any luck with this one?

**Comment by EisenbergEffect** [comment]
Timing is pretty bad for us to take a detailed look now. We're prepping for 1.0 next week...

**Comment by kevmeister68** [comment]
No problems. Would appreciate if you can keep it on your radar for after 1.0 perhaps?

**Comment by EisenbergEffect** [comment]
Reopening so I make sure to get back to you once we're through this cycle.

**Comment by Nilz11** [comment]
As there is no update here, i had a similar problem and solved it like that:

It works like that, though not 100% sure if it is expected to work like that.

```
function compileTabs(compiler, resources, node, instruction)
{
    let tabs = node.getElementsByTagName('tab');
    let tabData = [];
    let viewFactories = [];

    for(let i = 0; i < tabs.length; i++) {

        let tab = tabs[i];

        //Get tab data we need to display tab headers (Bindings are not yet processed, so we need to use prefix)
        tabData.push({
            heading: tab.getAttribute('heading.bind') || tab.getAttribute('heading.one-time'),
            active: tab.getAttribute('active.bind') || tab.getAttribute('active.one-time'),
            if: tab.getAttribute('if.bind') || tab.getAttribute('if.one-time'),
        });

        //Wrap node in fragment, otherwise hiding does not work properly
        let fragment = document.createDocumentFragment();
        fragment.appendChild(tab.cloneNode(true));
        viewFactories.push(compiler.compile(fragment, resources));
    }

    instruction.tabData = tabData;
    instruction.viewFactories = viewFactories;

    //Remove remaining children
    while(node.lastChild) {
        node.removeChild(node.lastChild);
    }

}
```

```
bind(bindingContext, overrideContext)
    {
        this.bindingContext = bindingContext;
        this.overrideContext = overrideContext;

        let tabs = this.instruction.elementInstruction.tabData;
        let viewFactories = this.instruction.elementInstruction.viewFactories;

        let activeTab = 0;

        for (let i = tabs.length - 1; i >= 0; i--) {

            let tab = tabs[i];

            tab.heading = this.expressionEvaluator.evaluate(tab.heading, this.bindingContext, this.overrideContext);
            tab.active = this.expressionEvaluator.evaluate(tab.active, this.bindingContext, this.overrideContext);
            tab.if = this.expressionEvaluator.evaluate(tab.if, this.bindingContext, this.overrideContext);

            if (tab.if === false) {
                tabs.splice(i, 1);
                viewFactories.splice(i, 1);
            }

            if (tab.active === true) {
                activeTab = i;
            }
        }

        this.tabs = tabs;
        this.viewFactories = viewFactories;

        if (this.tabs.length > activeTab) {
            this.selectTab(activeTab);
        }
    }

    selectTab(i)
    {
        this.activeTab = i;

        //Remove view if a tab is already shown
        if (this.view) {
            this.view.unbind();

            this.viewSlot.remove(this.view, true, true);
        }

        //Create new view with current context
        let viewFactory = this.viewFactories[i];

        this.view = viewFactory.create(this.container);
        this.view.bind(this.bindingContext, this.overrideContext);

        this.viewSlot.add(this.view);
    }
```

**Comment by Alexander-Taran** [comment]
Stale
