### ISSUE TITLE
Nested repeat.for loops are calling content compose twice

### ISSUE THREAD

**Issue by jsobell** [aurelia/templating#427]
An example gist.run is here:
https://gist.run/?id=0fc9051c8c266c89d15c60b1abda030b

When two repeat loops are nested, once the total number of inner iterations exceeds about 80 we start to get duplicate content rendered when a compose is present.

Reported by @gregdouglas

**Comment by jsobell** [comment]
Actually, this is unrelated to nested loops.
```
<template>
    <table>
        <span repeat.for="i of 111">
            <compose view-model.bind="{ data : i+','+x }"  view="./html-only-template.html"></compose>
        </span>
    </table>
</template>
```
demonstrates that the same thing happens as soon as the loop exceeds 99 items.

**Comment by CasiOo** [comment]
Same issue as here https://github.com/aurelia/templating-resources/issues/240
Think I found the problem(s) :)

**Comment by EisenbergEffect** [comment]
closing as duplicate
