### ISSUE TITLE
Please add an afterBind view engine hook

### ISSUE THREAD

**Issue by glen-84** [aurelia/templating#429]
I want to use a view engine hook to initialize various jQuery plug-ins, but I've realized that `afterCreate` is not suitable because at this stage, the data has not yet been bound to the elements.

Would it be possible to add an `afterBind` hook for this purpose?

**Comment by EisenbergEffect** [comment]
Use `attached` for that. That's the best time for jQuery plugins to initialize.

**Comment by glen-84** [comment]
@EisenbergEffect,

I see two ways to use attached:

1. In a custom element: I don't want to create a custom element just for this. Maybe later.
2. In the page VM: This will be done on multiple pages, so all page VMs would have to inherit from a base VM that applies all of the plug-ins. This doesn't seem ideal. IDK.

I added `afterBind` myself a few minutes ago, and it seems to work. :disappointed:

**Comment by EisenbergEffect** [comment]
You should keep dom manipulation out of page VMs. Use a custom attribute. It's easy:

``
@inject(Element)
export class FooCustomAttribute {

  constructor(element) {
   this.element = element;
  }

  attached() {
    $(this.element).foo();
  }
}
```

**Comment by glen-84** [comment]
Unfortunately, I'm working with an existing (purchased) theme, which makes use of a bunch of different plug-ins. It's not pretty. So instead of just being able to invoke their existing initialization functions, I'll now have to pretty much throw away their JS and re-write it as custom attributes. This means that any changes that they make to this code will not take effect in my application. Happy days. (=

**Comment by EisenbergEffect** [comment]
I don't see how that's related at all. It's no different from what you were doing in your view model. You are just abstracting it so you have a clean architecture now.

If you want some other approach you can use a view engine hook to apply behaviors to a view generally speaking.

**Comment by glen-84** [comment]
> I don't see how that's related at all. It's no different from what you were doing in your view model. You are just abstracting it so you have a clean architecture now.

Using a custom attribute or element means that I have to apply the initialization to a specific element. Using a view engine hook allows me to execute existing code from the theme with `view.fragment` as context (like [this](https://github.com/aurelia/framework/issues/354#issuecomment-223576986)).

> If you want some other approach you can use a view engine hook to apply behaviors to a view generally speaking.

This is exactly what the issue is about. `afterCreate` doesn't work when a plug-in performs initialization based on the bound state of the element though, like a switch control that renders differently if the checkbox is checked. Hence the request for `afterBind`.

Anyway, if the suggestion doesn't make sense for the framework, then I'll just have to work with what I have. Thanks for your input.

**Comment by EisenbergEffect** [comment]
We can't really add any more hooks to the framework at this point, especially not the week before 1.0 release. There are a number of ways to accomplish this, so I would use those for now.

**Comment by nisargrthakkar** [comment]
Any update on this. Please suggest new hook or Alternet way to bind this.
