### ISSUE TITLE
Syntax suggestion for the change handler of a select

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating#43]
This is just a suggestion for handling the `onchange` of a select element.
This is how i would do it in html:
```
<select onchange="onChange(this.value)">
```

It would make sense then that the following would also work in aurelia:
```
<select change.delegate="onChange(this.value)">
```
(in the spirit of keeping things like html)

But as i understand it you would need to use a `ref` attribute to make this scenario work in aurelia, because the `this.value` would not work to pass the value of the select as an argument to the function.
Or you could use `value.bind` to bind to a model.

I was just wondering if also making the above syntax work would make sense ?

**Comment by jdanyow** [comment]
there's also `<select change.delegate="onChange($event)">` which has the target, etc

**Comment by Aaike** [comment]
i did not think about that... thanks @jdanyow
