### ISSUE TITLE
Question: Include external html view, without compose container ?

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/templating#430]
When using `compose` to include the external html `view.html` segment:
```html
<div style="display: flex; background: red;">
    <compose view="./view.html"></compose>
</div>
```
the compose creates an element around the included view, breaking the css style and more css required to fix that.

Is it possible to include the external html directly, as innerHTML of the element, and how?

**Comment by EisenbergEffect** [comment]
Try this

```
<div style="display: flex; background: red;">
    <compose view="./view.html" containerless></compose>
</div>
```

**Comment by bsrdjan** [comment]
I actually tried exactly that, before posting question and the result was that the container, with the included view.html probably, is removed, no content. I was not sure if it possibly a bug ?

<ui-navbar class="navbar au-target ui-row" au-target-id="479">

</ui-navbar>

**Comment by EisenbergEffect** [comment]
We'll take a look at it.

**Comment by bsrdjan** [comment]
Hi Rob,
sorry, it happens with the custom element only, perhaps only when inline view used.
Please find the gist https://gist.run/?id=8914354f532d1daba33f095fa8bb7e79
Thanks and regards,
srdjan
