### ISSUE TITLE
Require from looks for js, css and html only

### ISSUE THREAD

**Issue by atul221282** [aurelia/templating#431]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32
* **Browser:**
all

* **Language:**
TypeScript 1.3

**Current behavior:**
<require from="nav-bar"></require> looks for nav-bar.js
<require from="nav-bar.html"></require> looks for nav-bar.html

**Expected/desired behavior:**
<require from="nav-bar.cshtml"></require> looks for nav-bar.cshtml.js thought it should look for nav-bar.cshtml

* **What is the expected behavior?**
Look for provided extension not the defualt if not found which is .js

* **What is the motivation / use case for changing the behavior?**
Use server side view

**Comment by EisenbergEffect** [comment]
If you want to change the mapping, you need to configure that on the view locator. There is documentation on how to that here: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/9

**Comment by atul221282** [comment]
I am doing that and that is why I got normal class and views got working but when i use <require from="nav-bar.cshtml"></require> in my network tab it tried to get the nav-bar.cshtml.js file which is an issue
