### ISSUE TITLE
Relative to plugin viewStrategy

### ISSUE THREAD

**Issue by bas080** [aurelia/templating#435]
https://github.com/SpoonX/aurelia-view-manager/issues/7

For the aurelia-view-manager plugin I would like to define paths that are relative to the plugin's base directory.

Consider the following directory tree.

```
├── aurelia-form.js
├── component
│   ├── entity-form.js
│   ├── form-field.html
│   ├── form-field.js
│   ├── form-fields.html
│   ├── form-fields.js
│   ├── framework
│   │   ├── actions.js
│   │   ├── bootstrap
│   │   │   ├── submit.html
│   │   │   └── textarea.html
│   │   ├── collection.js
│   │   └── entity.js
│   ├── schema-form.html
│   └── schema-form.js
├── config.js
├── entity-schema.js
└── form.js
```

And my view manager configurations look like this

```js
  viewManagerConfig.configureNamespace('spoonx/form', {
    framepath: '{{base}}/framework/{{framework}}', // framework path
    base     : './../component',
    location : '{{framepath}}/{{view}}.html',
    map      : {
      /* aurelia-form specific view are also overridable */
      'form-field'    : './form-field.html',
      'form-fields'   : './form-fields.html',
      'schema-form'   : './schema-form.html',
      'entity-form'   : './schema-form.html',

      /* custom elements with a view model do not end with .html */
      actions         : '{{framepath}}/actions',
      collection      : '{{framepath}}/collection',
      conditional     : '{{framepath}}/conditional',

      /* all input components */
      button          : '{{framepath}}/input.html',
      color           : '{{framepath}}/input.html',
      date            : '{{framepath}}/input.html',
      datetime        : '{{framepath}}/input.html',
      'datetime-local': '{{framepath}}/input.html',
      string          : '{{framepath}}/input.html',
      email           : '{{framepath}}/input.html',
      month           : '{{framepath}}/input.html',
      number          : '{{framepath}}/input.html',
      password        : '{{framepath}}/input.html',
      range           : '{{framepath}}/input.html',
      search          : '{{framepath}}/input.html',
      tel             : '{{framepath}}/input.html',
      time            : '{{framepath}}/input.html',
      url             : '{{framepath}}/input.html',
      week            : '{{framepath}}/input.html'
    }
  });
```

notice that the paths that are defined for the components are relative to the `component` path. f.e. the actions component's path in this config is `./framework/bootstrap/actions`. It would be better to have it in `./component/framework/bootstrap/actions`.

This is because the the form-field component's compose element makes it relative to the `component` directory.

This can cause some headache as it feels more untuitive for these configurations to be relative to the plugin path.

How would I go about to tell the compose element to see things not relative to it but relative to the plugins path.

[aurelia-view-manager](https://github.com/SpoonX/aurelia-view-manager)

**Comment by EisenbergEffect** [comment]
Please ask this of the developers working on SpoonX.

**Comment by EisenbergEffect** [comment]
You can't actually tell the compose element to change how it does that. That's part of it's basic behavior at present. I suppose we could add some new feature for that, but it would have to come through a community PR.

You might want to consider creating your own internal version of compose that suits your own needs.
