### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'nextSibling' .

### ISSUE THREAD

**Issue by kdmatrosov** [aurelia/templating#436]
```
Unhandled rejection TypeError: Cannot read property 'nextSibling' of null
at View.removeNodes (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:1504:23)
```
I move to new route by using 
```
this.router.navigateToRoute('index');
``` 
Then I press "back" button , route changes but app catches this error.

Also I catch this error trying to set route (for example 'localhost:9000/#/welcome") directly in address line

**Comment by EisenbergEffect** [comment]
Please update to the latest version of the templating library.

**Comment by kdmatrosov** [comment]
Thx
