### ISSUE TITLE
string interpolation/computedFrom not updated on array modification

### ISSUE THREAD

**Issue by Thanood** [aurelia/templating#438]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-rc.1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 8

* **Node Version:**
6.2.2

* **NPM Version:**
3.10.5

* **JSPM OR Webpack AND Version**
JSPM 0.16.15

* **Browser:**
Chrome 49
* **Language:**
all

**Current behavior:**

See: https://gist.run/?id=be83622cb000a4b8f4d2047955b7301a

The output of `${data}` is not populated/changed, while `${data.length}` gets updated..
The original intent has been to use `@computedFrom` to retrieve single `title` properties from an object array. This is not used but has the same issues.

Inserting a `repeat.for` binding works.

**Expected/desired behavior:**

The output of `${data}` should be populated every 500ms.

If you uncomment the `concat` line and comment the `push` line, both string interpolation and `computedFrom` work.

**Comment by jdanyow** [comment]
@Thanood I updated your gist to the latest aurelia which has the fix for this bug.

https://gist.run/?id=7e10e25a51926fb22227dc4bd8d1c1aa

**Comment by Thanood** [comment]
@jdanyow Thanks, that works. Apart from the `computedFrom` part, though: https://gist.run/?id=82c48de63159f1b1d39c2658ab748bf7

What exactly does "the latest" aurelia mean in this context? Is it `1.0.0-rc.1.0.3` as mentioned in the intro of this issue? Or the upcoming release version?

Because if it's `1.0.0-rc.1.0.3` I might have another error in my code. :smile:

**Comment by jdanyow** [comment]
computedFrom deals with property changes.  In the gist, the data property never changes, it remains the same array instance.  This is why the dataTitles binding is never updated.

By latest I was referring to the RC, not the upcoming RTM that's being rolled out today.

**Comment by Thanood** [comment]
@jdanyow Is it expected behavior that string interpolation (no `@computedFrom`) is not updated when using valueConverters?
https://gist.run/?id=82c48de63159f1b1d39c2658ab748bf7
