### ISSUE TITLE
feature request: support for loading css through the es6 module loader

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating#44]
It would be nice to be able to use module names in link tags to refer to stylesheets inside installable packages, or just to be able to use the config.js to map paths to css files. i.e. :
```
<link href="modulename/style.css!">
```

maybe this can be added to the `<require>` element

This can then also be used to load in less or other formats using the systemjs plugins.

**Comment by Aaike** [comment]
I have tried to put a link tag within a custom element and i get this error.
`HTML element <link> is ignored in shadow tree`

Am i correct to assume that link tags do not work for element that make use of shadow dom ?
and could the `<require>` element fix that ?

**Comment by EisenbergEffect** [comment]
The `require` element now supports this. You can import css files with require. if you want them to be scoped to the shadow dom, then you do it like this:

```
<require from="./my.css" as="scoped"></require>
```

Otherwise

```
<require from="./my.css"require>
```
