### ISSUE TITLE
Requiring same CSS in multiple views fails in Firefox

### ISSUE THREAD

**Issue by woble** [aurelia/templating#443]
**I'm submitting a bug report**

* **Library Version:**
```
"aurelia-animator-css": "npm:aurelia-animator-css@^1.0.0-rc.1.0.0",
"aurelia-bootstrapper": "npm:aurelia-bootstrapper@^1.0.0-rc.1.0.0",
"aurelia-event-aggregator": "npm:aurelia-event-aggregator@^1.0.0-rc.1.0.0",
"aurelia-fetch-client": "npm:aurelia-fetch-client@^1.0.0-rc.1.0.0",
"aurelia-framework": "npm:aurelia-framework@^1.0.0-rc.1.0.0",
"aurelia-history-browser": "npm:aurelia-history-browser@^1.0.0-rc.1.0.0",
"aurelia-loader-default": "npm:aurelia-loader-default@^1.0.0-rc.1.0.0",
"aurelia-logging": "npm:aurelia-logging@^1.0.0-rc.1.0.1",
"aurelia-logging-console": "npm:aurelia-logging-console@^1.0.0-rc.1.0.0",
"aurelia-pal-browser": "npm:aurelia-pal-browser@^1.0.0-rc.1.0.0",
"aurelia-router": "npm:aurelia-router@^1.0.0-rc.1.0.0",
"aurelia-templating": "npm:aurelia-templating@^1.0.0-rc.1.0.1",
"aurelia-templating-binding": "npm:aurelia-templating-binding@^1.0.0-rc.1.0.0",
"aurelia-templating-resources": "npm:aurelia-templating-resources@^1.0.0-rc.1.0.0",
"aurelia-templating-router": "npm:aurelia-templating-router@^1.0.0-rc.1.0.0",
"aurelia-testing": "npm:aurelia-testing@^1.0.0-beta.1.0.3"
```

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.5

* **JSPM OR Webpack AND Version**
JSPM 0.16.39

* **Browser:**
Tested in:
Firefox 47.0.1 (stable)
Firefox 48.0 (beta channel)

Chrome and other major browsers seem to be doing fine.

* **Language:**
TypeScript

**Current behavior:**
Requiring the same CSS file from multiple views sometimes causes an empty style tag being injected in the head. The file is loaded correctly; http response does contain the correct content every time. The behaviour is random after every page refresh.

e.g. this line in more than one view
```
<require from="foo/bar.css"></require>
```

**Expected behavior:**
A style tag always being injected with the content of the required CSS file.

**Comment by dstroyrofworlds** [comment]
I seem to get the same issue in chrome.
I might require some static Semantic CSS in one html template and importing it in another removes it again.
I have to comment out my import for it to work.

My versions are 1.0.0 for aurelia.
I use webpack with typescript.

**Comment by jdanyow** [comment]
possibly related: https://github.com/aurelia/templating-resources/issues/239

**Comment by EisenbergEffect** [comment]
Closing as duplicate.
