### ISSUE TITLE
enhance a <require from=....>

### ISSUE THREAD

**Issue by tzimmerer** [aurelia/templating#444]
Hi guys,

I would like to know if we can enhance a <require from=....> ? 
Here is what I would like to do : 

https://gist.run/?id=2d00b06ba86c518db9f219ca917846f3

When you click on the enhance button, I want to display the <red-square></red-square> element.

Is there a way to do this ?

**Comment by EisenbergEffect** [comment]
You can't include the require elements in there no. All resources for enhance have to be either global or registered with the ViewResources instance you pass to enhance.

**Comment by tzimmerer** [comment]
Thanks for your answer
So I saw there is a viewResources.registerElement function to add an element to the viewResource, but I can't figure out how to get the HtmlBehaviorResource.
Is that the good way to do it ? Can I have a little help for that ?
