### ISSUE TITLE
Template Engine returning undefined when binding data with innerhtml and running enhance.

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/templating#445]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0

**Please tell us about your environment:**
Windows 10

**Node Version:**
NA

**NPM Version:**
NA

**JSPM OR Webpack AND Version**
NA

**Browser:**
all

**Language:**
all

**Current behavior:**
Returning undefined after being compiled
- **What is the expected behavior?**
  Return compiled html in place

https://gist.run/?id=70aa97833c5f5f7b6f4e83adb9267a28

**Comment by brandonseydel** [comment]
So.....any news on this?

**Comment by EisenbergEffect** [comment]
We haven't had an opportunity to look into this issue yet. If you track down the cause and want to submit a PR for the fix, we always welcome that.
