### ISSUE TITLE
register a custom element in viewResources

### ISSUE THREAD

**Issue by tzimmerer** [aurelia/templating#446]
I got a string containing the Html of a view, and I use the `templatingEngine.enhance` to enhance this view.
But when there is a `<require from=...>`, the element don't render because it is not in the viewResources.
How can I do to register the require element in the viewResources ? I search in the documentation and in the issues and find that I can do `viewResources.registerElement(tagName: string, behavior: HtmlBehaviorResource)` but I don't find how to get the behavior. 
Any idea ?

**Comment by levan-g** [comment]
@tzimmerer you need to globalize your element before calling ```templateEngine.enhance()```.

**Comment by EisenbergEffect** [comment]
The easiest way is to globalize it.
