### ISSUE TITLE
IE11 major performance issue

### ISSUE THREAD

**Issue by MikaelPorttila** [aurelia/templating#448]
**I'm submitting a performance issue report**

* **Library Version:**
aurelia-bootstrapper 1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows: 8, 8.1, 10

* **Node Version:**
4.2.1

* **NPM Version:**
3.10.5

* **Browser:**
IE 11 

* **Language:**
TypeScript 1.8

**Current behavior:**
We are having performance issues when displaying a list where every list-row contains multiple custom elements and bindings. Chrome, Firefox and Edge has no problem displaying the view right away, but IE11 takes almost a minute to display the same view.

I tried to use the IE-profiler and this is what I came up with:
majority of the time goes into insertBefore() and removeChild() (why is removeChild-called?)

This behavior should be the same on Firefox and Chrome, but it's done faster (14 times faster than IE11)

![horribleie11-performance](https://cloud.githubusercontent.com/assets/903468/17590840/aac6818a-5fdb-11e6-9452-eeb552e9a6a0.PNG)

At this state we can't deploy our application and 95% of our clients runs IE11.
Any tips on how we can speed up Aurelia on IE11?

We are already running bluebird for promise and replace our show.bind;s to if.bind;s.

**Comment by CasiOo** [comment]
It looks very weird indeed. Can you post any relevant code?

**Comment by MikaelPorttila** [comment]
I made this gistrun that demonstrates the the performance issue:
https://gist.run/?id=84b07a5e0b5d89289739839b8a8c4f5b

It's mostly nested custom elements in a list (10 custom elements per row).

I tried to find a good JS-run page that could handle the files and git.run was the only one that could manage multiple larger js-files without breaking...

Right now git.run seems to be missing Bluebird for IE11 Promise-support ( @jdanyow maybe could add the bluebird-package so the page works one IE11?).

**Comment by stsje** [comment]
Don't you have the unbundled version? Quite difficult to see what's going on inside the bundle.

**Comment by MikaelPorttila** [comment]
My bad - here is the complete source code for the test:
https://drive.google.com/file/d/0B4WpsVmNBfdERTRHel9MYlI1TU0/view?usp=sharing
Just unzip it, run npm install and use Aurelia CLI to build and run it

**Comment by jdanyow** [comment]
hey @MikaelPorttila - I downloaded your code and ran the application... definitely noticed the perf issue.

I could see that a significant amount of time was spent by bluebird capturing the stack trace information.

Adding `longStackTraces: false,` in main.js fixed the issue for me.

```js
(<any>Promise).config({
  longStackTraces: false,  // <----- I added this.
  warnings: {
    wForgottenReturn: false
  }
});
```

**Comment by MikaelPorttila** [comment]
@jdanyow Splendid! Your fix worked!  :+1:
 It was bluebird who killed the performance. 

It's worth pointing out that I ran into a bug in bluebird 3.4.1 (currently the latest package) where the debug-flag was set hard-coded true in this file: https://github.com/petkaantonov/bluebird/blob/v3.4.1/js/browser/bluebird.core.js#L539
so I was never able to override the longStackTraces-variable (if someone would run into the same issue as us)

Big thanks! :)

**Comment by jdanyow** [comment]
Excellent!

**Comment by suneelv** [comment]
@jdanyow Thank you for the fix. It would be good if you add this as a comment in skeleton navigation app. Our application used to take 9 seconds to start aurelia but after applying your fix, it came down to 1 second

**Comment by EisenbergEffect** [comment]
Maybe we should add that setting to the CLI generated app so that it only enables that in debug mode?

**Comment by EisenbergEffect** [comment]
Added: https://github.com/aurelia/cli/commit/bba08c321881f9bc5b9f02c4b597bde534440273

**Comment by fexdev** [comment]
Thanks so much!

**Comment by esnyder232** [comment]
@jdanyow  
Hi,

We are having this same issue with ie11, where insertBefore() and removeChild() are being constantly called and it takes ~45s for our page to load.

We are trying to turn longStackTrace off via script tag in our index.html:
    <script src="jspm_packages/system.js"></script>
    <script src="jspm_packages/npm/bluebird@3.5.0/js/browser/bluebird.min.js"></script>
    <script>
        Promise.config({ longStackTraces: false });
        Promise.setScheduler(function (fn) { setTimeout(fn); });
    </script>

I've been following another thread on how to do this as well, but we wanted to know how to gain visibility into the bluebird stack trace, mainly to confirm whether or not our script is doing anything. You said in the middle of the thread "I could see that a significant amount of time was spent by bluebird capturing the stack trace information." How did you do that? Is it in the profiler tab somewhere?

Any help would be greatly appreciated :).
Thanks!
