### ISSUE TITLE
Difference when using '@containerless' on VM and 'containerless' in HTML view on custom elements

### ISSUE THREAD

**Issue by Finlandia** [aurelia/templating#450]
I'm seeing weird behaviour when using containerless functionality. We're creating custom elements in a SVG container, which required us to use containerless tag to strip the custom element tags before adding it to the DOM as only SVGElements tags are allowed within a SVG container.
We're using Aurelia release version 1.0.0 and build our SPA with webpack.

Here you can find a gistrun example which displays the 2 implementation of containerless usage.
https://gist.run/?id=58ba6282ad54c1263eec3a141fe42183

In this example i've created 2 viewmodels and bind this to our custom elements. Using as-element="compose" to tell aurelia that i've created the viewmodel and that Aurelia shouldnt create a VM. The difference between these to custom elements are the containerless tag:
**1.** CustomElement doesnt have the @containerless tag in the Viewmodel but have 'containerless' in the HTML view.
**2.** withattr component does'nt have 'containerless' in the HTML view, but it does have the containerless tag in the Viewmodel. As described in the Aurelia HUB.

I expect in both situations that I would see a blue rectangle. customelement tags are stripped by Aurelia because of the containerless tag. however the @containerless tag doesnt seems to work, as in implementation 2.

Any clue why these implementation have different outputs?
Which is the correct one? I would expect 2, as stated in the Aurelia Docs that the @Containerless tag should be placed on the viewmodel.

**Comment by EisenbergEffect** [comment]
Ok, it works...but you've done some really strange things in your sample. I think you may have a bit of confusion over how things work. Essentially the `view-model.bind` only works on a compose element. When you do that other places it may be causing problems or not doing what you think. Also, it's strange to use a custom element in combination with `as-element`. That doesn't really make sense. If you remove the incorrect markup and instead just have your two custom elements, both of them actually work.

**Comment by EisenbergEffect** [comment]
All of these work:

```html
  customelement html containerless without @containerless:
  <strong>Working!</strong>
    <svg width="100%" height="150px">
      <customelement containerless />
  </svg>
  
  
    customelement with @containerless:
    <strong>Working!</strong>
    <svg width="100%" height="150px">
      <withattr />
  </svg>
  
  
  
  SVGElement svg:
  <svg width="100%" height="150px">
      <svg as-element="compose" view-model.bind="customElementViewModel"/>
  </svg>
  
   SVGElement g:
    <svg width="100%" height="150px">
      <g as-element="compose" view-model.bind="customElementViewModel"/>
  </svg>
```

**Comment by geertendoornenbal** [comment]
I'm a colleague of the topicstarter.

Please show me if I understand correctly now:
So if we want to use a custom element with a bindable view-model, you are saying the only way of doing this properly is as follows:
 `<compose view-model.bind="viewModel" view.bind="withattr.html" />`

**Comment by EisenbergEffect** [comment]
That is the purpose of the `compose` element, yes. It allows you to do dynamic UI composition. You don't necessarily need to specify the view. It can handle that by convention, just like for a custom element if you want. (Make sure not to use self closing tags because those aren't supported by html. They may work in svg though.)
