### ISSUE TITLE
@child and @children not working on nested components

### ISSUE THREAD

**Issue by reneolivo** [aurelia/templating#451]
**I'm submitting a bug report**
- **Library Version:**
  1.0.1

**Please tell us about your environment:**
- **Operating System:**
  Linux (Ubuntu 16.04 LTS)
- **Node Version:**
  5.10.1
  
  
- **NPM Version:**
  3.8.3
  
  
- **JSPM OR Webpack AND Version**
  Aurelia CLI?
  
  
- **Browser:**
  Chrome Version 51.0.2704.84 (64-bit)
- **Language:**
  all

**Current behavior:**
When I use **@child** and **@children** on a component inside another component I get _undefined_ 

**Expected/desired behavior:**
I expect a reference to the child element

Here's an example:
https://gist.run/?id=923920bcb56e0e4709954c93e5bece87

Please check the console. When I try to get a reference to **CustomTitle** from **CustomContainer** I get _undefined_

**Comment by tochoromero** [comment]
I'm having the same problem, but for me they don't work at all.

I have tried just selecting normal element like <h1> or <div> and I keep getting undefined. When I inspect the generated HTML code I can clearly see that the selector I'm using is a direct children of my custom element, but never the less the property does not get synced with the elements.

This is a VERY important feature for templating, specially when you are writing plugins that need to manipulate the DOM.

It could be that we are using it wrong, and on that case we need some good examples in the documentation, because right now they are just mentioned without no examples.

**Comment by reneolivo** [comment]
+1 for updating the docs. They just reference @child and @children briefly and they don't even explain this **selectorOrConfig** property.

**Comment by tochoromero** [comment]
I think I found what was going on. I was expecting the @child property to be populated when attached() happens, but it seems that is not the case. Instead, I listen for my property to be changed. For instance, if I have:
`@child('my-element') myChild;`
Then I would listen for it on:
`myChildChanged(newValue, OldValue){
//My child has a value here
}`

So it seems to be working as expected.

**Comment by reneolivo** [comment]
@tochoromero for me it still doesn't work. I tried these two things:

1. - created a *customTitleChanged* method, but it doesn't even fire.
2. - I went to the *custom-container.html* and added a `click.delegate="customTitleChanged()"` to the H3 in hopes that the title is attached at a later time but it doesn't work either.

**Comment by tochoromero** [comment]
@reneolivo I think I know what your problem is.
As far as I know the @children and @child annotations are only for CustomElements. In your case you are trying to use them in a normal ModelView, it seems you will have to wrap the whole thing into a Custom Element to have it work.

**Comment by ZoolWay** [comment]
I also have issues with `child` and `children` and I am not sure if I can follow you @tochoromero 

In the gist.run (rev 13) `@child('h2')` works to get the element `<h2>` inside of home.js which is a normal viewmodel, not a custom element. Inside the custom element `@child('custom-title')` does not work to get the sub-custom-element inside the custom element...

**Comment by ZoolWay** [comment]
Maybe there are typescript related issue with `child` and `children`:

Take a look at this gist: https://gist.run/?id=990d1f3289c5a790b3c75f3e3ebceae6
The `div` can be obtained through the `@child` decorator. 

Doing the same code as `app.ts` in a typescript skeleton does not work out...

**Comment by reneolivo** [comment]
@ZoolWay there's something weird here! I don't know if it's typescript or what, but when I use your index configuration everything seems to be working fine:

**This one:**
```
<!doctype html>
<html>
  <head>
    <title>Aurelia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body aurelia-app>
    <h1>Loading...</h1>
    
    <script src="https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.3/jspm_packages/system.js"></script>
    <script src="https://cdn.rawgit.com/jdanyow/aurelia-bundle/v1.0.3/config.js"></script>
    <script>
      System.import('aurelia-bootstrapper');
    </script>
  </body>
</html>
```

**Instead of this one:**
```
<!doctype html>
<html>
  <head>
    <title>Aurelia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  </head>
  <body aurelia-app="main">
    <h1>Loading...</h1>
    
    <script src="https://jdanyow.github.io/rjs-bundle/node_modules/requirejs/require.js"></script>
    <script src="https://jdanyow.github.io/rjs-bundle/config.js"></script>
    <script src="https://jdanyow.github.io/rjs-bundle/bundles/aurelia.js"></script>
    <script src="https://jdanyow.github.io/rjs-bundle/bundles/babel.js"></script>
    <script>
      require(['aurelia-bootstrapper']);
    </script>
  </body>
</html>

```

**Comment by reneolivo** [comment]
@ZoolWay I think the last one is the most up to date with the Aurelia. It seems some bug was introduced between version 1.0.0-beta.1.1.4 and rc1

**Comment by reneolivo** [comment]
side-note for documentation: @child and @children must point to a direct descendant (apparently)

```
@child('h1') title;
```

will grab 
```
<h1>Title</h1>
```

But not:
```
<header>
  <h1>Title</h1>
</header>
```

**Comment by EisenbergEffect** [comment]
Is anyone here having an issue with `child` or `children` when referencing a direct descendant of the element? That is the only scenario that is supported.

**Comment by ErikSchierboom** [comment]
I think I'm having the same problem. What I want to do is create custom elements to define a grid. My goal is to define this:

```html
<grid>
    <column name="ID"></column>
    <column name="Name"></column>
</grid>
```

which would then be rendered as:

```html
<table>
    <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
    </tr>
    </thead>
</table>
```

The first step is to define the custom components, starting with the `column.ts` element:

```typescript
import {noView, bindable} from 'aurelia-framework';

@noView
export class Column {
  @bindable name;
}
```

The `grid.ts` element looks like this:

```typescript
import {children} from 'aurelia-framework';

import {Column} from './column';

export class Grid {
  @children('columns') columns: Column[];

  attached() {
    console.log('columns', this.columns);
  }
}
```

Its corresponding `grid.html` file uses the bound `columns` field:

```html
<template>
  <table>
    <thead>
      <tr>
        <tr repeat.for="column of columns">
          <th>${column.name}</th>
        </tr>
      </tr>
  </table>
</template>
```

Finally (after having registered these components), I define my grid in my `app.html` file:

```html
<template>
  <h1>Aurelia parent/child/grandchild repro</h1>

  <grid>
    <column name.bind="ID"></column>
    <column name.bind="Name"></column>
  </grid>
</template>
```

Unfortunately, nothing is rendered. If I examine the log, I find that the `columns` field in the `Grid` element (which is marked with the `@children` decorator), is `undefined`.

If I manually add the columns, things are rendered correctly:

```typescript
export class Grid {
  columns: Column[] = [];

  constructor() {
    let column1 = new Column();
    column1.name = 'id';

    let column2 = new Column();
    column2.name = 'name';

    this.columns.push(column1);
    this.columns.push(column2);
  }

  attached() {
    console.log('columns', this.columns);
  }
}
```

It is quite likely that I am doing something wrong, but unfortunately the documentation didn't really help me here.

**Comment by EisenbergEffect** [comment]
On quick glance, I see you have a typo. It should be `@children('column')` so that the css selector matches the element name.

**Comment by ErikSchierboom** [comment]
@EisenbergEffect You are correct, that was indeed a typo (I used to have another custom element between `<grid>` and `<column>`). Unfortunately, fixing the typo does not fix the problem.

**Comment by EisenbergEffect** [comment]
@ErikSchierboom Next issue is that you need a `slot` element in your grid view or otherwise the the custom element doesn't know where to put the column elements. I recommend just adding one below the table and then make sure to have some css that matches the column element and makes it `display:none` since you are using that mostly as a data element.

**Comment by ErikSchierboom** [comment]
@EisenbergEffect One step further! Adding the `slot` element now ensures that the columns get populated, but the `<table>` is still not rendered anymore, even when I manually set the `columns` field to fixed values.

**Comment by EisenbergEffect** [comment]
Next issue I see is that the table markup is mal-formed.

**Comment by ErikSchierboom** [comment]
Valid point, but fixing that (by adding the closing `</thead>` element) doesn't help. That wasn't likely to be the problem, as rendering the elements directly (without the `<slot>` and with static values) already did work. Sorry to bug you about this.

**Comment by EisenbergEffect** [comment]
Can you repost your current version of the code?

**Comment by reneolivo** [comment]
Hello, sorry to interrupt. back to the original issue: during the weekend I'll try different scenarios using the latest Aurelia build (I'm not sure gist.run is up to date) and get back to this issue. I'll even help update the docs if necesary.

Side note: I believe that if @child and @children only access direct descendants then they are not that useful. I usually wrap my components in some sort of DIV, SECTION, TABLE tag depending on the scenario.

**Comment by EisenbergEffect** [comment]
They only locate direct content descendents. It doesn't matter where they are projected to.

**Comment by ErikSchierboom** [comment]
Sure.

`grid.html`:
```html
<template>
  <slot>
    <table>
      <thead>
        <tr repeat.for="column of columns">
          <th>${column.name}</th>
        </tr>
      </thead>
    </table>
  </slot>
</template>
```

`grid.ts`:
```typescript
import {children} from 'aurelia-framework';

import {Column} from './column';

export class Grid {
  @children('column') columns: Column[] = [];

  attached() {
    console.log('columns', this.columns.length);
  }
}
```

`column.ts`
```typescript
import {noView, bindable} from 'aurelia-framework';

@noView
export class Column {
  @bindable name;
}
```

`app.html`:
```html
<template>
  <h1>Aurelia parent/child/grandchild repro</h1>

  <grid>
    <column name="ID"></column>
    <column name="Name"></column>
  </grid>
</template>
```


@reneolivo Sorry to "hack" your issue

**Comment by EisenbergEffect** [comment]
Ok, there's your problem. The slot element is wrong. Use this:

```html
<template>
    <table>
      <thead>
        <tr repeat.for="column of columns">
          <th>${column.name}</th>
        </tr>
      </thead>
    </table>
  <slot></slot>
</template>
```

**Comment by ErikSchierboom** [comment]
@EisenbergEffect Perfect! Works like a charm. Thanks for all the help.

**Comment by EisenbergEffect** [comment]
@reneolivo Are you still having issues? Can you provide some sample code?

**Comment by reneolivo** [comment]
@EisenbergEffect I have prepared a very crude example using the latest Aurelia CLI's ES6 project:
https://github.com/reneolivo/aurelia-child-example

As you can see the only instances where @child and @children are working at this moment are when accessing slotted elements. 

I think the behaviour of @child and @children have been changing from version to version and it's not well documented.

**Comment by swalters** [comment]
@EisenbergEffect Please see this GistRun.  I have a parent and child custom element. Neither have a corresponding view.  The parent component's children is not populated.  I'm seeing this in an Aurelia adapter we are developing for ag-grid.

https://gist.run/?id=084df819ba204c3d5d6448674d8767b5

**Comment by EisenbergEffect** [comment]
The parent component needs to at least have a `<slot></slot>` element in its view or there's nowhere to project the the child elements. We may be able to improve that in the future. I realize it's a bit quirky in this case, since these elements have no view.

**Comment by elsebke** [comment]
Is it possible to work with dynamic slots? I tried several solutions with and without view for a column, but I could not make this work.

````
<template>
  <h1>Aurelia parent/child/grandchild repro</h1>
  <grid>
    <column name="ID">
       <div>[some HTML]</div>
    </column>
    <column name="Name">
       <div>[some other HTML]</div>
    </column>
  </grid>
</template>

**Comment by elsebke** [comment]
In fact I am trying to implement a stepper (kind of wizard with a flow of steps but within the same page). The steps are rendered correctly, except the dynamic slot (in the repeat.for). @EisenbergEffect Is this going to be supported?

```xml
<stepper finish.call="finish">
    <step title="First step">
      <div>Some HTML</div>
    </step>
    <step title="Second step">
      <div>Some other HTML</div>
    </step>
    <step title="Third step">
      <div>Still some other HTML</div>
    </step>
</stepper>
```
with stepper.js:

```js
import {children} from 'aurelia-framework';

export class Stepper {
  @children('step') steps = [];

  attached() {
    console.log("steps: %o", this.steps);
  }

  nextStep() {

  }

  previousStep() {

  }
  
  finish() {

  }
}
```

and stepper.html:

```xml
<template>
  <div class="stepper">    
    
    <div repeat.for="step of steps" class="step">
      <div class="step-badge">
        <i>done </i><span style="display: none;">1</span>
      </div>
      <div class="step-title text-bold">${step.title}</div>
      <div class="step-content" style="display: none;">
        <slot></slot> <!-- drop the HTML of each step here -->        
        <div class="step-actions" style="margin-top: 1rem; margin-left: -5px;">
          <button md-button click.delegate="stepper.nextStep()">CONTINUE</button>
          <button md-button click.delegate="stepper.previousStep()">BACK</button>
        </div>
      </div>
    </div>
    <slot></slot> <!-- in fact I don't need this -->
</template>
```

**Comment by elsebke** [comment]
I took my inspiration here:
[http://quasar-framework.org/components/tabs.html](http://quasar-framework.org/components/tabs.html)
[http://quasar-framework.org/components/stepper.html](http://quasar-framework.org/components/stepper.html)

Can this be implemented in Aurelia? I prefer working with custom elements rather than custom attributes like used in materialize bridge:
[http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/tabs](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/tabs)

**Comment by EisenbergEffect** [comment]
@elsebke We don't support dynamic slots. That repeat.for would create slots on the fly, all as default slots, which is invalid shadow dom.

**Comment by elsebke** [comment]
Thank you @EisenbergEffect. Is there another way to implement this stepper?

**Comment by RWOverdijk** [comment]
@EisenbergEffect 

> Is anyone here having an issue with child or children when referencing a direct descendant of the element? That is the only scenario that is supported.

Is there any other way to find children like this? I use it for aurelia-form, which has `<form-group />`'s. Now, if I wrap one, validation stops working because it can't find the element anymore.

**Comment by thinkOfaNumber** [comment]
A bit late to the party, but for the record @elsebke you can do the "stepper" you mentioned.  I've done the same with a "wizard" containing steps.

If you haven't solved it already, you're trying to do too much by repeating over the steps - this is already handled by the shadow dom implementation.

If you had a stepper element:

    <template>
      <ul>
        <li repeat.for="step of steps" click.delegate="selectStep(step)">${step.title}</li>
      </ul>
      <slot></slot> 
    </template>

    export class Stepper {
      @children("step") steps: Step[] = [];
      attached() {
        if (this.steps && this.steps.length > 0) this.steps[0].selected = true;
      }
      selectStep(step) {
        this.steps.forEach((t: Step) => t.selected = false);
        step.selected = true;
      }
    }

And a step element:

    <template show.bind="selected">
      <slot></slot>
    </template>

    export class Step {
      @bindable title: string;
      selected: boolean;
    }

Then you can use it as you described above. This is an amazingly small piece of code to do such a great custom element, thanks to Aurelia!

**Comment by Alexander-Taran** [comment]
@bigopon 
can be closed.

Amazing read on @child & @children
