### ISSUE TITLE
Creation Complete

### ISSUE THREAD

**Issue by Roustalski** [aurelia/templating#453]
**I'm submitting a feature request**

Hello,

I would like a way to respond in a view model when all rendering and lifecycle methods have completed for all children components and view/view-model pairs.

So, maybe another lifecycle method after `attached()`? `creationComplete()`? or `renderComplete()` or `complete()`?

**Comment by stoffeastrom** [comment]
Maybe you can use `CompositionTransaction` look at [this](https://github.com/aurelia/framework/issues/367) for more details

**Comment by jdanyow** [comment]
good call @stoffeastrom. @Roustalski there's no definitive end to the process from the perspective of the containing component- depending on the child component logic, their usage of `if`, `compose` etc.
