### ISSUE TITLE
Why bindable decorator is not respected when a custom element is rendered with compose

### ISSUE THREAD

**Issue by zakjan** [aurelia/templating#454]
It is possible to pass attributes to Aurelia custom element with `@bindable` decorator:

```
export class ItemCustomElement {
    @bindable model: Item;
}

<item model.bind="model"></item>
```

Why custom elements rendered by `<compose>` are treated differently, according to docs they need an `activate` method to pass data? `@bindable` is not respected.

```
export class ItemCustomElement {
    @bindable model: Item;

    activate(model: Item): void {
        this.model = model;
    }
}

<compose view-model="./item" model.bind="model"></compose>
```

From the custom element's point of view, currently it needs to know how it is going to be used, with `<compose>` or not. I believe a custom element should be isolated from this external decision.

Can we  make `<compose>` look for `@bindable` attributes and get rid of `activate` method?

(original question at SO https://stackoverflow.com/questions/38565024/why-bindable-decorator-is-not-respected-when-a-custom-element-rendered-with-comp)

**Comment by stsje** [comment]
It would then become unclear if you want the attributes attached to the `<compose>` or the custom element it is rendering.

I agree it would be nice with improvement in this area, but I don't have a suggestion atm.

**Comment by zakjan** [comment]
How about `<compose view-model="./item" view-model-attributes.bind="{...}"></compose>` where all properties in view-model-attributes (or another name) would be transferred to the rendered custom element?

**Comment by smajl** [comment]
+1 I was looking for some sort of this binding in composed elements too.

**Comment by stsje** [comment]
Another suggestion could be to extend the existing dot syntax with a `model-attribute` that only works for compose.
`<compose view-model="./item" item.model-attribute.bind="item"></compose>`

**Comment by jdanyow** [comment]
A composed view and view-model are not a custom element- compose is a separate, dynamic construct.

More info here: 

http://stackoverflow.com/questions/38886074/what-are-the-differences-between-using-compose-view-model-my-element-and/38920425#38920425

**Comment by stsje** [comment]
I still think it will be a big improvement, if we can find a way for it to support bindables.
My above suggestion could possibly be a solution.
