### ISSUE TITLE
expose container used to create behavior on controller

### ISSUE THREAD

**Issue by jdanyow** [aurelia/templating#457]
Will enable cleaning up this code in validation:

https://github.com/aurelia/validation/blob/b18c1b6dec53987334128714870df4925f869fd9/src/validate-binding-behavior.ts#L37-L54

In support of https://github.com/aurelia/validation/issues/288

**Comment by EisenbergEffect** [comment]
Got it in :)

**Comment by jods4** [comment]
@EisenbergEffect what's the change addition here? Can you point me out how a binding behavior can use this to grab the element it's created on, even in the case of a custom attribute?

**Comment by EisenbergEffect** [comment]
The `Controller` type now has a property named `container`. All HTMLElements that Aurelia sees as custom elements or that have custom attributes have an `au` property that you can use to get the `Controller`. So, you can now use that container to get access to any services related to behavior.

**Comment by jods4** [comment]
Just to be sure I understood correctly:
To get at the enclosing HTMLElement from a binding behavior I need to find the enclosing Controller (I do that already) and there is new `container` property there that is the `HTMLElement`?

**Comment by jdanyow** [comment]
@jods4 we'll have a full example for you in aurelia-validation tonight. In the meantime, it's `controller.container.get(Element)` to retrieve a custom element OR custom attribute's actual DOM element.

**Comment by EisenbergEffect** [comment]
Better to use `DOM.Element` :)

**Comment by jods4** [comment]
@EisenbergEffect does it make a difference if my code is only meant to run in browsers?

**Comment by EisenbergEffect** [comment]
Nope.

**Comment by jdanyow** [comment]
@jods4 https://github.com/aurelia/validation/blob/master/src/validate-binding-behavior.ts#L21-L39

**Comment by jdanyow** [comment]
@jods4 https://github.com/aurelia/validation/blob/master/src/validate-binding-behavior.ts#L21-L39

**Comment by jods4** [comment]
@jdanyow thanks! That's what I figured but nothing beats copy-paste 😉
