### ISSUE TITLE
@children not populated by the time `attached` is called

### ISSUE THREAD

**Issue by mbroadst** [aurelia/templating#459]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10] (all)

* **Node Version:**
6.3.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.45 | webpack 2.1.0-beta.17

* **Browser:**
works in Chrome 52.0.2743.116
appears to be broken in all other major browsers (mobile not tested)

* **Language:**
ESNext (potentially related to babel)

**Code Example:**
https://github.com/mbroadst/aurelia-children-issue

**Current behavior:**
This is a pretty involved component using the `AbstractRepeater` to provide a performant grid component. The grid displays three columns, and constantly changes data every 50ms after that.

**Expected/desired behavior:**
* **What is the expected behavior?**
The data displays and changes during the interval

* **What is actually happening?**
On chrome this works as expected. On any other tested browser - but specifically Firefox - the data never displays. The reason for this appears to be that the local variable decorated with `@children` is not populated by the time `attached` is called on the parent component. This method [here](https://github.com/mbroadst/aurelia-children-issue/blob/master/src/grid.js#L62) is the first function called in `attached` for the `Grid`, and you'll note that on Firefox the array is empty at the point the `console.log(this.columns)` is called. If you, on the other hand, put the contents of `scrapeColumnViewFactories` into a `setTimeout(() => { // stuff }, 50);`, the code works as expected. 

It is important to note that these issues do not occur in a `gist.run`, only when building completely from source using the webpack skeleton. I have not tested this with the same jspm skeleton.

* **What is the motivation / use case for changing the behavior?**
This might be expected behavior, but if it is I don't think it's properly documented. Otherwise, it might indicate an issue with the lifecycle, `@children`, or behavior of the task queue

**Comment by JeroenVinke** [comment]
Is this related to https://github.com/aurelia/templating/issues/403?

**Comment by mbroadst** [comment]
@JeroenVinke this does look very similar! Although I wasn't able to reproduce using a gist.run, so it might be slightly different. It looks the like the suggested approach moving forward is to manually find the child VMs since I'm not tracking future changes to the children, but rather scraping data from them once attached.

**Comment by mbroadst** [comment]
@JeroenVinke yep looks like the `getChildVMs` approach fixes my issue.. sorry for the noise here!
