### ISSUE TITLE
circular dependency problem with requirejs

### ISSUE THREAD

**Issue by cmichaelgraham** [aurelia/templating#46]
thanks to @colindembovsky, dragon slayer :smile:, for finding the issue causing the problem (the requirejs loader fails to load 0.10.0 and later aurelia apps)

we need help identifying a plan to resolve the issue.

in requirejs, [circular dependency injects are undefined](http://requirejs.org/docs/api.html#circular), which is the symptom here.

> If you define a circular dependency ("a" needs "b" and "b" needs "a"), then in this case when "b"'s module function is called, it will get an undefined value for "a". "b" can fetch "a" later after modules have been defined by using the require() method (be sure to specify require as a dependency so the right context is used to look up "a")

`view-engine` requires `module-analyzer`
`module-analyzer` requires `custom-element`
`custom-element` requires `view-engine`

so you see it's circular :smile:

**Comment by EisenbergEffect** [comment]
I will handle this by updating the compiler and building for the next release.

**Comment by cmichaelgraham** [comment]
:+1:

**Comment by EisenbergEffect** [comment]
Fixed in next release.
