### ISSUE TITLE
Unexpected binding behavior on input type="range"

### ISSUE THREAD

**Issue by jmzagorski** [aurelia/templating#461]
**I'm submitting a bug report**
Not sure if this is a bug or is the desired behavior
- **Library Version:**
  1.0.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  4.4.1
  
  
- **NPM Version:**
  2.14.20
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.45
  
  
- **Browser:**
  Chrome XX
- **Language:**
  ESNext

**Current behavior:**
If the value.bind appears before the min.bind or max.bind attributes, the range indicator does not work. 

Does Not Work
![rangenotworking](https://cloud.githubusercontent.com/assets/8404957/18488094/fa625972-79c5-11e6-9d8f-f786a3bef3ae.GIF)

```
<input type="range" id="countdown" value.bind="todaysDate & oneTime"  
             min="${requested & oneTime}" max="${required & oneTime}" disabled="disabled" 
             style="width:200px;float:right" />

```

**Expected/desired behavior:**

- **What is the expected behavior?**

Attribute order should not matter.

Works
![rangeworking](https://cloud.githubusercontent.com/assets/8404957/18488154/3d36fb22-79c6-11e6-9845-cef127cf5138.GIF)

```
<input type="range" id="countdown" min="${requested & oneTime}"
             max="${required & oneTime}" disabled="disabled" 
             value.bind="todaysDate & oneTime" style="width:200px;float:right" />


```
- **What is the motivation / use case for changing the behavior?**
  
  Might make it easier for future devs if order did not matter

**Comment by jdanyow** [comment]
I just hit the same issue.

The input type="range" elements ignore anything that is assigned to the `value` attribute that falls outside it's `min` and `max`. If the binding system assigns the `value` before assigning the `min` / `max` it's possible that your value will fall outside the element's default min and max, causing the assignment to be ignored.

A quick, reliable workaround is to set the min and max to some lower and upper limit values to ensure the binding order doesn't matter:

```html
<input type="range" min="0" max="10000"
       value.bind="myValue"
       min.bind="myMin"
       max.bind="myMax">

**Comment by jmzagorski** [comment]
thank you. In this particular app I use the range as an indicator for how close the programmer is getting to the due date. If today's date exceeds the due date I would want it to just stay at the max, so looks like I just need to remember order matters in that case.

**Comment by Alexander-Taran** [comment]
seems that it was fixed
https://gist.run/?id=e1dd951450d94cda711a622894ff41f9
