### ISSUE TITLE
Nested template elements not working in Internet Explorer 11

### ISSUE THREAD

**Issue by harrol** [aurelia/templating#465]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

npm list | grep templating
│ └─┬ aurelia-templating@1.1.0
│ ├── aurelia-templating-binding@1.0.0
│ ├── aurelia-templating-resources@1.0.0
│ └── aurelia-templating-router@1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
4.4.3

* **NPM Version:**
3.10.5

* **JSPM OR Webpack AND Version**
JSPM and RequireJS (Both projects from jspm skeleton as Aurelia CLI suffer from the same problem)
JSPM 0.16.32

* **Browser:**
IE 11

* **Language:**
TypeScript 1.8 | ESNext (issue manifested on both TypeScript and ESNext projects)

**Current behavior:**
When using nested _template_ elements, content is not rendered in Internet Explorer 11. In the supplied example only one _tr_ and all _td_ elements are generated but they have no content. Same example works on other browsers (tested Safari, Chrome, Firefox and Edge)

https://gist.run/?id=25f011c359c309f23e0a7e620597805a

(GistRun does not work on IE 11 however)

![screen shot 2016-09-19 at 15 27 17](https://cloud.githubusercontent.com/assets/883535/18633680/c107c1fa-7e7d-11e6-8852-7536adf07173.png)

**Expected/desired behavior:**

* **What is the expected behavior?**
Content is rendered in IE 11 just as in other browsers.

![screen shot 2016-09-19 at 15 28 16](https://cloud.githubusercontent.com/assets/883535/18633681/c3f9d772-7e7d-11e6-8adf-d8e7c3d065bc.png)

* **What is the motivation / use case for changing the behavior?**

**Comment by Thanood** [comment]
In the gist you didn't close the second template.

Please have a look here, it describes why this is invalid HTML (and how to work around it). That's probably the reason why IE doesn't render it:
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/4

**Comment by harrol** [comment]
Indeed it might be that Internet Explorer does not like my table structure. Unfortunately the actual project with the issue has a nesting of 3 deep. The the "as-element" trick does not work there. I guess I have to flatten my data structure.
