### ISSUE TITLE
When composing from multiple views and one model the refs inside the view do not work

### ISSUE THREAD

**Issue by len-ro** [aurelia/templating#467]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

* **Operating System:**
Linux (Ubuntu)

* **Node Version:**
6.2.0

* **NPM Version:**
3.10.6

* **JSPM Version**
JSPM 0.16.42

* **Browser:**
all

* **Language:**
all

**Current behavior:**
I am using <compose> to compose a single model with multiple view to provide different editors for th e same data. The binding works fine however I noticed that references from the view do not work. 
Check the following gist: https://gist.run/?id=ec85baf5daed86af838351f446820855

Click M1 to load the m1.html view then click Log. The ref is done correctly.
Click M2 to load the m2.html view then click Log. The ref is now null.

It would also be great to be able to handle the end of compose event. The change would be quite simple just send dispatch an event in https://github.com/aurelia/templating-resources/blob/master/src/compose.js after line 179.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this? Any chance this could also be connect with the task queue timing issue you were working on?

**Comment by jdanyow** [comment]
Initially I thought this was not a bug because the compose element had `model.bind="this"` instead of `$this`.

But once I fixed that issue and updated the gist to the latest aurelia bits, I found that the compose element binds the new view before unbinding the old view. When the old view finally does unbind, it clears the bound value of the property.

https://gist.run/?id=2b535b943d372602000a01298594bf1b

**Comment by jdanyow** [comment]
ok I'm back to thinking this is not a bug and just an unsupported scenario. The composition engine needs to bind the incoming view model before removing (and unbinding) the previous view model to enable transition scenarios.

1. bind incoming vm: https://github.com/aurelia/templating/blob/1.1.1/src/composition-engine.js#L202
2. unbind previous vm: https://github.com/aurelia/templating/blob/1.1.1/src/composition-engine.js#L205

@EisenbergEffect thoughts?

**Comment by EisenbergEffect** [comment]
I'm not sure what the best thing to do it. We could have the unbind of a ref not set the value to null, but I'm not sure if that would cause other problems.

**Comment by len-ro** [comment]
Thank you for the time to consider this. It is not a blocking bug for us, we managed to work around this problem. I think this is a very rare use-case.

**Comment by jdanyow** [comment]
Maybe we could make the ref unbind logic skip setting the property to null when the property's value is not the element associated with the ref:

```diff
 unbind() {
     if (!this.isBound) {
       return;
     }
     this.isBound = false;
+    if (this.sourceExpression.evaluate(this.source, this.lookupFunctions) === this.target) {
       this.sourceExpression.assign(this.source, null, this.lookupFunctions);
+    }
     if (this.sourceExpression.unbind) {
       this.sourceExpression.unbind(this, this.source);
     }
     this.source = null;
   }
}
```

**Comment by EisenbergEffect** [comment]
That sounds pretty reasonable.
