### ISSUE TITLE
Manipulating DOM in custom attribute

### ISSUE THREAD

**Issue by owlcode** [aurelia/templating#481]
**I'm submitting a bug report**
* **Library Version:**
1.0.0
* **Operating System:**
Windows10
* **Node Version:**
4.6.0
* **NPM Version:**
3.10.8
* **JSPM OR Webpack AND Version**
JSPM 0.16.34
* **Browser:**
all
* **Language:**
TypeScript 2.0

**Current behavior:**
I can't render properly appended DOM Elements via viewCompiler. Div is nested in a good way (when I console.log it) but it does not render

```
@templateController
@inject(Element, ViewSlot, ViewCompiler)
export class InputCrossCustomAttribute {
    el: HTMLInputElement;
    constructor(element, private viewSlot: ViewSlot,
                private viewCompiler: ViewCompiler) {
        this.el = element;
    }
bind(bindingContext, overrideContext) {
        let div = document.createElement('div');
        div.appendChild(this.el);
        let view = this.viewCompiler.compile(div);
        let x = view.create();
        x.bind(bindingContext, overrideContext);
        this.viewSlot.removeAll();
        return this.viewSlot.add(x);
    }
}
```

**Expected/desired behavior:**
By using custom attribute I would like to wrap my element into div.

**Comment by EisenbergEffect** [comment]
You are taking the wrong approach here. The bind hook is too late to do that. You will want to consider using a *template controller`. That is how `if`, `repeat` and `with` are implemented. It is an advanced tasks. What you are trying would be much simpler with a custom element. If really want to use an attribute, you should take a look at the source of `if` in the `templating-resources` repo. In the future, please ask questions first in the gitter channel.

**Comment by krostkowski** [comment]
We have already asked on gitter. Using 'if' component concept we've got:
```
constructor(private viewFactory: BoundViewFactory, private viewSlot: ViewSlot, private viewCompiler: ViewCompiler) {
}

bind(bindingContext, overrideContext) {
    let div = document.createElement('div');
    let viewFactory = this.viewCompiler.compile(div);

    let view = viewFactory.create();
    let elementView = this.viewFactory.create(view);

    view.bind(bindingContext, overrideContext);
    elementView.bind(bindingContext, overrideContext);

    this.viewSlot.add(view);
    this.viewSlot.add(elementView);
}
```
It works, adds two dom elements: fresh div and element on which we added custom attribute. The question is how to add elementView as a child of div view?
