### ISSUE TITLE
Odd behavior with nested Custom Elements

### ISSUE THREAD

**Issue by tochoromero** [aurelia/templating#483]
This is a weird one, I hope I can explain what is going on.

I'm creating some custom Elements on top of Bootstrap, among them is a tab custom elements. To create a new tabs you would do something like this:
```html
<tab-set>
   <tab>...</tab>
   <tab>...</tab>
</tab-set>
```
Behind the scenes the `tab` custom element register itself with the `tab-set` custom element.
To do this the `tab` injects a reference to the `tab-set` and then calls a register method passing `this` as an argument. The register method basically just adds the reference to the tab to an array. And finally the `tab-set` view iterates over the tabs array to display the tab navigation.

Here is the interesting part, if I call the register method in the `attached()` method of the `tab` custom element, for reasons I cannot explain, when the `tab-set` renders the view iterating over the tabs array, I end up with twice as many elements. But the extra elements don't have the right 'value reference' so I just end up with undefined stuff.

Now, if I call the register method in the `constructor()` of my `tab` custom element, then everything works as expected.

I believe this is some sort of regression. It was working just fine until I updated the project today.
I created a [gist run](https://gist.run/?id=6aca4fffdd4a653c2988b98c869dab20)  with a simplified example, and it is working just fine there since I couldn't find a newer Aurelia bundle.

So, maybe we are not supposed to do such things in the attached() method, but since it was working before I thought I should report it.

Regards.

**Comment by EisenbergEffect** [comment]
I wouldn't do this in attached. In fact, I would take a different approach and use the `@children` decorator. However, I'm concern about the regression. I don't think we changed anything that would affect this recently. What version were you updating from?

**Comment by tochoromero** [comment]
The problem with @children is that it doesn't work with @containerless and unfortunately  bootstrap is so picky about the html hierarchy. 

I'm sorry,  I don't really know the version I was updating from, I  need to pay more attention to that. I can tell you I wrote this code in August 24 and it was working, and I come back to it Monday and did the update and then it wasn't. 

Thank you Rob

**Comment by tochoromero** [comment]
I was able to reproduce the same issue using `@children`.
It seems the problem is when the parent custom element uses the array populated by `@children` on a `repeat.for` on its view.

Once again I created a gist run, but it works as expected there because it has an older version of Aurelia. But when running locally with the up to date ESNext navigation skeleton it fails in the same way I described before.

Here is the gist run, if you run this locally with the up to date framework it should show you the error https://gist.run/?id=c091747d47f9acc263174751a529c880

Thanks

**Comment by tochoromero** [comment]
I went back to my code and cleaned up my dependencies, it seems that I had some dependencies mismatches, some parts of the frameworks had newer versions but other parts had old version. I'm assuming that is what caused the odd behaviors. After cleaning it up and making sure all the parts are up to date the error went away. My apologies for raising a false alarm.

Thanks.
