### ISSUE TITLE
Define default binding behavior in @bindable

### ISSUE THREAD

**Issue by rsuter** [aurelia/templating#484]
Hi everyone, 

For my application I need to access the `Binding` object for a property in a component. I see two ways to do this: 

- Is there a way to inject a service object where I can ask for a `Binding` object for a property and the current component?
- Is there a way to specify a default binding behavior in the `@bindable` attribute (e.g. `@bindable({ bindingBehavior: MyBindingBehavior })`)? I want to avoid that the user of the component has to always specify the behavior. 

The `@bindable` attribute options are currently not defined in the `d.ts` file: 

    export function bindable(nameOrConfigOrTarget?: string | Object, key?: any, descriptor?: any): any;

Is there a place where I can find some documentation for the `@bindable` attribute and more advanced binding scenarios (i.e. get Binding expressions, manually add binding behaviors, etc)?

**Comment by CasiOo** [comment]
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/8 search for "Bindable Signature" it has what you are looking for.

**Comment by EisenbergEffect** [comment]
You can specify a default binding behavior. See the link above.
Can you tell me more about what you want to do with the Binding object? You can get at those through the View instance, which you can grab by implementing the `created` lifecycle hook.

**Comment by rsuter** [comment]
How can I set a default binding behavior on a @bindable property?

I'm currently building bootstrap bindings (it's my way of learning the insights of a framework). 

I currently can build a form like this: 

	<template>
		<h1>Create Event</h1>
		<form>
			<bs-textbox label="Title" value.bind="event.title & bsValidate"></bs-textbox>
			<bs-textbox label="Description" value.bind="event.description & bsValidate" rows="4"
						help="You can use the MarkDown syntax to format your description.">
			</bs-textbox>
			<bs-textbox label="Location" value.bind="event.location & bsValidate"></bs-textbox>

			<bs-textbox label="Start Date" value.bind="event.startDate & bsValidate"></bs-textbox>
			<bs-textbox label="End Date" value.bind="event.endDate & bsValidate"></bs-textbox>

			<bs-fileupload label="Image" value.bind="event.image & bsValidate" accept=".png,.jpg,.gif"></bs-fileupload>

			<bs-button click.trigger="cancel()">Cancel</bs-button>
			<bs-button primary="true"
					   click.trigger="submit()"
					   enabled.bind="controller.errors.length === 0">
				Create Event
			</bs-button>
		</form>
	</template>
	
The bs-textbox: 

	@containerless
	@customElement("bs-textbox")
	export class Textbox extends ValidationComponent {
		@bindable({ defaultBindingMode: bindingMode.twoWay })
		value = ""; // TODO: Add BsValidateBindingBehavior as default binding behavior
		
		...
	}
	
	export class BsValidateBindingBehavior {
		bind(binding: any) {
			var component = binding.target as ValidationComponent;
			var parent = binding.source.bindingContext;
			var parentPropertyName = binding.sourceExpression.expression.object.name;
			component.validatedObject = parent[parentPropertyName];
			component.propertyName = binding.sourceExpression.expression.name;

			// TODO: Recursively search parents
			for (var propertyName in parent) {
				if (parent.hasOwnProperty(propertyName) && parent[propertyName] instanceof ValidationController) {
					component.controller = parent[propertyName];
					break;
				}
			}
		}

		unbind() {
		}
	}

	export class ValidationComponent {
		controller: ValidationController;

		propertyName: string;

		validatedObject: any;

		isBound = false;

		bind() {
			this.isBound = true;
		}

		valueChanged() {
			if (this.isBound && this.controller) {
				if (!this.propertyName || !this.validatedObject)
					throw new Error("The ValidationComponent is not initialized properly: The property name or validated object could not be retrieved.");

				this.controller.validate({ object: this.validatedObject, propertyName: this.propertyName });
			}
		}

		// TODO: Disable dirty checking here
		get errors() {
			return this.controller ? this.controller.errors.filter(e => e.propertyName === this.propertyName) : [];
		}
	}
	
I only have two problems: 

- The Textbox.value should have an automatic binding behavior so that I dont have to define it in the form where the textbox is used. The binding lookup should also work with this declaration: `<bs-textbox label="Title" value.bind="event.title"></bs-textbox>`. To make the thing work, I need the binding object of the parent view and not the Textbox view (I cannot look it up in any views of the "created" method). 
- Declaring `@computedFrom('controller.errors')` on `get errors()` does not work and there is no `validating` event on the controller object... 

Btw: I'm working on a Swagger/Web API to TypeScript generator and just today added support for Aurelia: https://github.com/NSwag/NSwag/commit/5f89cd4149a2fa73f7cf2f3f31b9affa49cacb53

**Comment by echjordan** [comment]
@EisenbergEffect 
How exactly is the defaultBindable property in the bindable signature supposed to work? Is there more documentation on this? I want to override an undefined value coming from the parent but specifying an empty array as the default seems to have no effect -- the bindable still comes through as undefined. The use case is a form input, as the form starts blank all propagated values will be undefined, but to build a value property at the child level and two way bind it back up, I need to start with an empty array.

`@bindable({ defaultBindingMode: bindingMode.twoWay, defaultValue: [] }) value;`

**Comment by bigopon** [comment]
@echjordan May i know a bit about the html that is troubling you?

**Comment by echjordan** [comment]
@bigopon thanks for your response. I managed to figure out a workaround but I do just want to verify what I found: if a bound value from the parent is `undefined`, the default value in the child will not be set.

parent.js
`class Parent {
    array = undefined
}`

parent.html
`<child array.bind="array"></child>`

child.js
`class Child {
    @bindable(defaultValue: []) array;
    //this.array is undefined
}`

**Comment by bigopon** [comment]
@echjordan I see, it's the expected behavior. Default value specified in `Child` is always there, before binding system kicks in. The sequence is something like this:
```
1. create parent
2. create child <-- array = default value
3. bind child.array to parent.array <-- array = parent.array = undefined
```
so it's getting `undefined` from parent, which is what you are telling it to do in the html.

what you can do to make it easier is to handle it in a reactive way:

```js
class Child {
  @bindable({ defaultValue: [] }) array

  // add the bind() lifecycle hook if you want to stop initial change handler arrayChanged invocation
  // bind() {
  //   do something before doing this.arrayChanged(this.array) yourself
  // }

  arrayChanged(array) {
    if (Array.isArray(array)) {
      // here do the work
    } else {
      // maybe clean up something
    }
  }
}
```
