### ISSUE TITLE
Custom attribute not working on dynamic content

### ISSUE THREAD

**Issue by eliavmaman** [aurelia/templating#487]
I'm using w2ui grid, and the template column generated like so
```
{ field: 'TableCards', caption: 'Table cards', size: '10%', sortable: true ,
                render:function(record, index, column_index) {
                    let html = '';
                    if (record.TableCards) {
                           record.TableCards.forEach(function(card) {
                             html += `<div class="card-holder" style="width: 12%; display: inline-block; padding: 0.5%;">
                                        <div class="poker-card blah" poker-card data-value="${card.value}"
                                            data-color="${card.color}"
                                            data-suit="&${card.suit};"
                                            style="width: 30px;height: 30px">
                                        </div>
                                    </div>`;
                        });
                    }
                    return html;
                } 
            },
```

 **poker-card** as u can see is a custom attribute. and it's not get rendered in the grid.
any other way?

**Comment by eliavmaman** [comment]
any one?

**Comment by EisenbergEffect** [comment]
You would need to use the templating engine's `enhance` api to progressively enhance that content after it's in the DOM. This is necessary any time you create DOM using non-Aurelia APIs.

**Comment by eliavmaman** [comment]
ok, any sample?
, not sure  how to "use the templating engine's enhance api".

**Comment by EisenbergEffect** [comment]
@PWKad Would you be able to assist? This also sounds like a good topic for the documentation.

**Comment by eliavmaman** [comment]
I thought when aurelia-templating engine understand that the DOM has changed, it should look for custom attributes or custom elements innit?

**Comment by EisenbergEffect** [comment]
Aurelia doesn't arbitrarily watch the DOM. That would be extremely in-efficient. If you just change the DOM yourself, it doesn't know you did anything. (Same with all frameworks I know of.)

**Comment by PWKad** [comment]
@eliavmaman here's a post about enhance in general but focused on when not inside of an aurelia app - http://patrickwalters.net/enhance-an-existing-page-with-aurelia/ 

If you want to use `enhance` inside of an app after adding content to the DOM you can either pass an html element to enhance (if there is no binding context) or you can pass an `EnhanceInstruction`

Interface for `EnhanceInstruction` - 

https://github.com/aurelia/templating/blob/7693dbd65e59e428e4052922920145b76240f3cf/src/templating-engine.js#L15

Test example of the API usage for passing a binding context - 

https://github.com/aurelia/templating/blob/7693dbd65e59e428e4052922920145b76240f3cf/test/templating-engine.spec.js#L24

Source for reference - 

https://github.com/aurelia/templating/blob/7693dbd65e59e428e4052922920145b76240f3cf/src/templating-engine.js#L83


In a nutshell it would look like this - 

```es6
import {TemplatingEngine} from 'aurelia-framework';
export class MyViewModel {
  static inject = [TemplatingEngine];
  constructor(templatingEngine) {
    this.templatingEngine = templatingEngine;
  }
  attached() {
    // ...
     render:function(record, index, column_index) {
                    let html = '';
                    if (record.TableCards) {
                           record.TableCards.forEach(function(card, index) {
                             html += `<div class="card-holder" style="width: 12%; display: inline-block; padding: 0.5%;">
                                        <div class="poker-card blah" poker-card data-value="${card.value}"
                                            data-color="${card.color}"
                                            data-suit="&${card.suit};"
                                            style="width: 30px;height: 30px">
                                        </div>
                                    </div>`;
                        });
                    }
                    return html;
                } 
    // ...
  }
  someEventAfterYouKnowEverythingHasBeenRendered() {
    let myElementsToEnhance = document.querySelector('#my-poker-cards');
    this.templatingEngine.enhance(myElementsToEnhance);
  }
}
```

**Comment by eliavmaman** [comment]
10x will try that now.
