### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by rajajhansi** [aurelia/templating#488]
@AshleyGrant Although you have typed the "/" in the self-closing tag in .md file, it ignored it while generating HTML documentation. 

"This means that <secret-message /> will not work." is correctly typed in the .md file but the HTML documentation renders "This means that <secret-message> will not work" i.e., without "/" character.

**Comment by AshleyGrant** [comment]
@EisenbergEffect is this a bug in the code that renders the markdown, or do I need to fix the doc?

**Comment by EisenbergEffect** [comment]
Can someone provide some links?

**Comment by rajajhansi** [comment]
Here you go: http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-custom-elements/3

Screenshot: http://screencast.com/t/lcwZ6Ew89

**Comment by jdanyow** [comment]
Might be a docs app issue. The app is loading this file: 
https://cdn.rawgit.com/aurelia/templating/1.1.4/doc/article/en-US/templating-custom-elements.md

Which has:

>Custom elements are not allowed to be self-closing. This means that `<secret-message />` will not work. When using a custom element, you must provide a closing tag as shown in `app.html` below.

But it displays:

![issue](http://i.imgur.com/TuC1gvV.png)

**Comment by Alexander-Taran** [comment]
This one should really have a bounty attached to it (-:
Every time I pass it it seems like so minor issue to fix..

**Comment by bigopon** [comment]
Closing, as docs are vastly different now, and have been improved quite a lot
