### ISSUE TITLE
<template> inside an element using if.bind does not display in Chrome

### ISSUE THREAD

**Issue by kevmeister68** [aurelia/templating#489]
We have the following construct/pattern in some of our templates:

    <div if.bind="someExpression">
        <template replaceable part="partname">
        </template>
    </div>

The outer "div" might be other elements such as "li".

On IE 11 the above works perfectly. But on Chrome 53/54 the template content does not appear when the expression is true.

I looked at https://github.com/aurelia/templating/issues/299 but that example is where the if.bind is specifically *on* the template element itself, whereas mine encloses it. I nonetheless tried removing replaceable from the template and nothing changed.

For what it's worth, the use of if.bind is critical to me, because the if.bind construct is the only mechanic that I have in Aurelia that delays the Aurelia lifecycle of components within the template, and I need that behaviour because I am using this construct for a tab-control. I have discussed the general premise with Rob previously, but if you have 10 tabs that all load data, you don't want to make your page inefficient by loading data that a user may never click on, so you want that data (hence the Aurelia lifecycle in totality) to be deferred until the tab page becomes active.

I have written about 6 variations of my tab-control so far to work around various Aurelia or HTML/DOM limitations (eg. cannot use slots inside if.bind, and so forth), and I am running out of options to make my tab control work as expected. (Quite frankly, it shouldn't be this hard -- I challenge someone to write a tab control that delays the Aurelia lifecycle of its content). Hope someone can help me with this.

We are running with Aurelia RC 1.0.0.

**Comment by jdanyow** [comment]
@kevmeister68 I can take a look if you want to provide a gist: https://gist.run/?id=7542e061bc940cde506b

**Comment by Alexander-Taran** [comment]
Stale since 2016
and last i checked <template> inside flow bindings works as expected in chome
