### ISSUE TITLE
Custom Element without VM not working in CEF

### ISSUE THREAD

**Issue by tomasbonco** [aurelia/templating#495]
**I'm submitting a bug report**

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **JSPM OR Webpack AND Version**
JSPM

* **Browser:**
Chromium 49

* **Language:**
TypeScript

**Current behavior:**
It works in browser and Electron, in CEF I don't see any error message,, just debug:
```
DEBUG [templating] importing resources for file://location/to/my/file.html
```

When I create a class (VM) and change my code from:
```
<require "./file.html">
```
to:
```
<require "./file">
```

It works. Maybe it's a problem with a protocol.

**Comment by EisenbergEffect** [comment]
This is very odd. Please let us know if you are able to track down what is causing this more specifically.

**Comment by jdanyow** [comment]
@tomasbonco is this still an issue?

**Comment by tomasbonco** [comment]
I didn't had time to dig into it, but we're going to switch to https protocol, so I'll try it then, and let you know.

**Comment by tomasbonco** [comment]
After updating CEF, it works. Can be closed.
