### ISSUE TITLE
Method binding to VM in template

### ISSUE THREAD

**Issue by zakjan** [aurelia/templating#497]
**I'm submitting a feature request**

**Use case:** There is a method in VM, accessing `this`. If it is passed via `attribute.bind` to a custom element, calling it there throws an error because `this` is bound to the custom element instead of the parent VM.

**Example:**
```
export class TestViewModel {
    entities: Entity[];

    constructor(private dialogService: DialogService) {}

    entityClicked(entity: Entity): void {
        this.dialogService.open...
    }
}

<template>
    <template repeat.for="entity of entities">
        <entity-list-item entity.bind="entity" click-handler.bind="entityClicked"></entity-list-item>
    </template>
</template>

export class EntityListItemCustomElement {
    @bindable entity: Entity;
    @bindable clickHandler: (entity: Entity) => void;
}

<template>
    <button click.trigger="clickHandler(entity)">${entity.name}</button>
</template>
```

**Current possible solutions:**
- manually creating a bound method in the VM `clickHandlerBound = this.clickHandler.bind(this)` and passing it to `click-handler.bind`. I find this the most flexible solution, because it is the only possible solution working for input matcher attribute, which expects `(model1, model2) => boolean`, so I consistently use this solution.
- instead of `attribute.bind`, using DOM CustomEvents and `attribute.trigger`, it calls the function in the context of VM
- instead of `attribute.bind`, using `attribute.call`, but it means that in the custom element this function needs to have a different signature `(bindingContext: {...}) => void` according to https://github.com/aurelia/binding/issues/271

**Suggested change:**
Add `$this` or `$vm` to the template binding context to make possible such manual binding directly in the template with `click-handler.bind="clickHandler.bind($this)"` without creating a dummy property in the VM.

**Comment by EisenbergEffect** [comment]
Actually, `$this` should already be available. Have you tried it out?

**Comment by zakjan** [comment]
Oh, when it was added? But it still doesn't work. https://gist.run/?id=4b48d91c317374528aa9303ff3547f8a

**Comment by EisenbergEffect** [comment]
The correct way to handle this would be with `click-handler.call="itemClicked(item)"`

**Comment by zakjan** [comment]
@EisenbergEffect Yeah but it gets `item` from the app template, not from the custom element. Second example, with input matcher: https://gist.run/?id=58e940a5a2a75eed22c604984f29bec0 You say `$this` should be available in the template? Is it documented?

**Comment by jdanyow** [comment]
@zakjan @EisenbergEffect looks like it's documented but the latest bits haven't been deployed to the docs app:

https://github.com/aurelia/binding/blob/master/doc/article/en-US/binding-basics.md#contextual-properties

http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-basics/7

**Comment by zakjan** [comment]
@jdanyow Thanks, I haven't looked in master docs. I can see `$this` support was added in commit https://github.com/aurelia/binding/commit/31b081ee477543f140ca416af6702ca0165ef1e8#diff-6947033678b93d106e25614dd972e66fR315. See my follow-up bug report at https://github.com/aurelia/binding/issues/543
