### ISSUE TITLE
Configuration of global resources throws when we use export default more than once.

### ISSUE THREAD

**Issue by shaunluttin** [aurelia/templating#498]
**I'm submitting a bug report**

* **Library Version:**
```
"aurelia-fetch-client": "^1.0.0",
"aurelia-framework": "^1.0.6",
"aurelia-router": "^1.0.6",
"aurelia-cli": "^0.20.2",
```

**Please tell us about your environment:**
* **Operating System:** Windows 10
* **Node Version:** 6.9.1
* **NPM Version:** 3.10.8
* **Browser:** all
* **Language:** TypeScript 2.0.10

**Current behavior:**

If we write two (or more) resources that use `export default`, and if we register them both as global resources, then Aurelia will throw throw the following error: 

> Unhandled rejection Error: Attempted to register an Element when one with the same name already exists. Name: default.

Example: 
```
// my-resource-01.ts 
export default class MyResource01 {

}

// my-resource-02.ts
export default class MyResource02 {

}

// my-plugin.ts
export default function (config: FrameworkConfiguration) {
    config.globalResources([
        "./my-resource-01",
        "./my-resource-02",
    ]);
}
```

**Expected/desired behavior:**

* Allow the use of `export default` in multiple global resources.
* This will enable developers to follow the [TypeScript module export recommendations ](https://www.typescriptlang.org/docs/handbook/modules.html), which say that, "If you’re only exporting a single class or function, use export default."

**Comment by EisenbergEffect** [comment]
We can't change this as far as I know, due to the way that exports work.....IF you want to use conventions. But, if you use an explicit decorator, it should work since you would be providing the name.

**Comment by shaunluttin** [comment]
@EisenbergEffect Thank you for answering. What is an explicit decorator?

**Comment by EisenbergEffect** [comment]
It depends on what type of resources you are trying to export. You might want `@customElement('element-name')` or `@customAttribute('attribute-name')` or `@valueConverter('converterName') for example.
