### ISSUE TITLE
Content projection with slots does not work inside if bindings

### ISSUE THREAD

**Issue by fracz** [aurelia/templating#499]
**I'm submitting a bug report**

* **Library Version:**
templating: 1.1.2, Aurelia: 1.0.7

**Current behavior:**
When you use a component with content projection and the slot is conditionally visible with `if` binding, it does not work. In the following template you are not able to render anything in the slot:
```
<template>
  <div if.bind="something">
    <slot></slot>
  </div>
</temlpate>
```

Gist: https://gist.run/?id=30060f4165ccdf076d30bc8e77df8536

**Expected/desired behavior:**
Try changing the `if.bind` to `show.bind` in the `sample-component.html` in the provided Gist and see it working as expected.

**Comment by EisenbergEffect** [comment]
Yes, that is a documented known limitation. You cannot have the slots themselves be dynamic. They have to be statically present in the DOM.

**Comment by jemhuntr** [comment]
Are there any recent workarounds to this issue?

I can't create dynamic modals because of this, as well as dynamic popups, sidebars, etc. I can't use `show.bind` instead of `if.bind`, as I'm using the CSS Animator to animate the enter and leave of the components.
