### ISSUE TITLE
detect jspm app name configuration for html templates

### ISSUE THREAD

**Issue by olanod** [aurelia/templating#5]
I'm moving [this issue](https://github.com/aurelia/framework/issues/11) here from the framework repo.  
Here is my jspm custom configuration in my package.json.
```
{
  "jspm": {
    "name": "my-app",
    "directories": {
      "baseURL": "src",
      "lib": "src/app",
      "packages": "vendor"
    },
    "dependencies": {
      "aurelia-bootstrapper": "^0.9.1"
    }
  }
}
```
Application scripts are in the app folder(e.g. app.js) and when I want to import them they are prefixed with 'my-app', like `import {App} from 'my-app/app';`. So I had to add my app module to the `aurelia-app` attribute: `aurelia-app='my-app/app'` and it worked, my app script is being imported, the problem is with the associated template, it tries to download it from `/my-app/app.html` but it's in `/app/app.html`.  
I fixed it for now implementing `getViewStrategy` and returning an absolute path to my view but I think this should be considered.  
Now all my classes look like this: 
```
export class MyComponent {
    ...
    getViewStrategy() {
        return '/app/my-component/my-component.html';
    }
}
```
Do you have a better solution, this is kinda ugly.

**Comment by EisenbergEffect** [comment]
I'm thinking...if we just use System.normalize first, and then pass that result to our import loading code, that should work, right?

**Comment by EisenbergEffect** [comment]
We are working on improving the way we do template resolution and loading. Might be a bit before it's ready.One thing you can do is teach the framework about your organization convention. To do this import `ConventionalView`. Then do this:

```javascript
ConventionalView.convertModuleIdToViewUrl = function(moduleId){
    return moduleId + '.html';
}
```

In your implementation, you can basically append/remove whatever sub folders you want. All conventional view resolution will pass through here to transform the module id into its associated view url.

**Comment by Serhioromano** [comment]
To import ConventionalView?

    import {ConventionalView} from 'aurelia-templating'

Right?

To I do it in `app.js`?

**Comment by EisenbergEffect** [comment]
This is very much an app config type of thing. You want to do this before any of your views are loaded. So, you want to switch over to the more manual startup mechanism, using main.js. Take a look at the docs. You will see this setup. Most "real" projects will probably need this at some point to do some custom start up config. After you look at that, let me know if you have any questions.
