### ISSUE TITLE
Throw error/show warning if template expression throws error

### ISSUE THREAD

**Issue by afm-sayem** [aurelia/templating#500]
**I'm submitting a bug report**
* **Library Version:**
aurelia-templating 1.1.2

* **Operating System:**
Ubuntu 16.04

* **Node Version:**
7.0.0

* **NPM Version:**
3.10.8

* **Browser:**
Version 53.0.2785.143

* **Language:**
ESNext

**Current behavior:**
It's possible to write invalid javascript inside a template. Aurelia silently swallows the error and does not show anything in the console.
https://gist.run/?id=749f18b7cd3f0d07dfbe5b712eacc620

**What is the expected behavior?**
If the javascript expression inside a template is invalid, there should be an error/warning indicating so.

* **What is the motivation / use case for changing the behavior?**
debugging

**Comment by EisenbergEffect** [comment]
Technically. there's nothing wrong with that code since `undeclared` can be a property on your class. @jdanyow Did we ever implement the user settings to log/error when binding properties are undefined?

**Comment by afm-sayem** [comment]
While it's true a class property can be declared later on(i.e. on an event) when `undeclared` becomes available and the expression becomes valid, it's also possible that the developer made a mistake in declaring the property(for example a spelling mistake) and there'd be no pointer to catch that mistake. I have made a similar mistake recently where I've spent an hour chasing missing quotation marks.

**Comment by EisenbergEffect** [comment]
Some people want to allow undefined properties and others don't. We discussed adding a setting so you could set your preference. Let's wait until @jdanyow chimes in here on the current status of that.

**Comment by MattGiesa** [comment]
+1 This setting would be very useful. It's too easy to change a property name on a class in one place and miss a view somewhere else that is binding to it. If composing the view failed it would allow tests to pick this up without needing to test each and every binding. That's a big win.

**Comment by Alexander-Taran** [comment]
stale since 2016
AFAIK no setting was introduced

**Comment by EisenbergEffect** [comment]
We should handle this in vNext.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect added to vNext candidates list.
Can be closed
