### ISSUE TITLE
Polymer 2.0 integration

### ISSUE THREAD

**Issue by avizcaino** [aurelia/templating#502]
Hi!
This is not actually a bug report but more of an integration question (so I'm not sure if this is the place to put it).

I've been using Aurelia and Polymer together for the last year and I just been reading some of the Polymer 2.0 documentation and watching the Polymer Summit videos.

I was wondering if someone has already tested the Aurelia and Polymer 2.0 integration. I think it can be of a great use if you want to override some of the Polymer elements behavior/properties but actually I'm not quite grasping any more improvements over the Aurelia + Polymer 1 combination that I've been using till now.

A couple of months ago I was using a polymer-element that wasn't working as expected in some platforms and I had to fork the element code and override the problem with my own solution to solve the unexpected behavior. I think I could solve this now more easily now with Polymer 2, but I haven't tested yet.

Anyway, as I said, I was just wondering if someone has already tested it and if some of you can give some insight about the usefulness of this integration.

Thanks!

**Comment by EisenbergEffect** [comment]
I haven't tested myself. I'm a bit out of the loop with the latest Polymer news. I'd love it if you were able to provide us some information from any experiments you did with the new version :)

**Comment by avizcaino** [comment]
Yep, I'll experiment a bit and keep you posted. ;)

**Comment by avizcaino** [comment]
Hi! 
I know I said that I would try something but still been able to do so. Anyone did it already? 😜
