### ISSUE TITLE
TypeError: Cannot read property 'anchorIsContainer' of undefined

### ISSUE THREAD

**Issue by The-Dark** [aurelia/templating#503]
**I'm submitting a bug report**

* **Library Version:**
1.1.3

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.1

* **Node Version:**
6.8.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
N/A - Using Aurelia CLI

* **Browser:**
Chrome 54.0.2840.87

* **Language:**
TypeScript

**Current behavior:**
Console error thrown - TypeError: Cannot read property 'anchorIsContainer' of undefined when attempting to set class of repeated item.

**Expected/desired behavior:**
Class value should be set, and the rest of the page should load.

**Steps to reproduce**
Using Aurelia CLI, create a new TypeScript application with au new, then add the following lines to app.html

     <li repeat.for="contact of contacts" class="${contact.cls}">
        ${contact.name}
     </li>

It doesn't matter if contacts is defined in app.ts or not.

This works in 1.1.2 - the new line in 1.1.3 is checking for `(ins.elementInstruction !== null && !ins.elementInstruction.anchorIsContainer))` when elementInstruction can be undefined (it is passed in as undefined in line 374 (I think))

Changing it to `(ins.elementInstruction && !ins.elementInstruction.anchorIsContainer))` would fix (or perhaps just hide) the problem.

Gist with source and compiled bundles: 
https://gist.run/?id=f7e6488acaa251dc1262b8e9ee1797f3

**Comment by EisenbergEffect** [comment]
If you can submit a PR for that change, I can release it today.

**Comment by The-Dark** [comment]
Wow, that was fast, and a new release too! Thank you, and thanks for an excellent product.

**Comment by EisenbergEffect** [comment]
That was a pretty serious regression so we wanted to get a fix out fast.
