### ISSUE TITLE
class on a template does not propagate onto compose

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/templating#505]
**I'm submitting a feature request**

* **Library Version:**
1.1.4

* **Operating System:**
Windows 7

* **Node Version:**
5.11.1

* **NPM Version:**
3.10.10

* **JSPM Version**
JSPM 0.16.48

* **Browser:**
Chrome 55.0.2883.75 m

* **Language:**
TypeScript 2.0.10

**Current behavior:**
A class specified on the template does not propagate onto a `<compose>` element like it does on a `<custom-element>`.

This is non-working code but you should understand:

Source:
```html
<template class="my-component">
  <span class="my-component__foo">foo</span>
</template>
```

```html
<compose view="my-component" class="some-class"></compose>
<my-component class="some-class"></my-component>
```

**Current Output :**

```html
<!--Okay...-->
<my-component class="some-class my-component">
  <span class="my-component__foo">foo</span>
</my-component>
<!--Where's my class?-->
<compose class="some-class">
  <span class="my-component__foo">foo</span>
</compose>
```

**Desired Output:**
```html
<!--Okay...-->
<my-component class="some-class my-component">
  <span class="my-component__foo">foo</span>
</my-component>
<!--There it is!-->
<compose class="some-class my-component">
  <span class="my-component__foo">foo</span>
</compose>
```

* **What is the motivation / use case for changing the behavior?**
Make compose behave like custom-elements

**Comment by EisenbergEffect** [comment]
Compose and custom elements are not the same thing. All compose does is render the composed UI  inline. It doesn't work like a custom element, so it doesn't support surrogates, slots, template parts or any of the features of custom elements.

**Comment by AdamWillden** [comment]
@EisenbergEffect I know they aren't the same thing - I didn't suggest they were.

Saying you don't want it to support class propagation is fine (though questionable as to why not) but your response suggests I was asking for everything you described.
