### ISSUE TITLE
Bootstrap CSS loads last and overrides custom styles

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/templating#514]
@waywardz commented on [Fri Sep 16 2016](https://github.com/aurelia/bootstrapper/issues/47)

**I'm submitting a bug report**
- **Library Version:**
  major.minor.patch-pre
  aurelia-bootstrapper@1.0.0-beta.2.0.1 -> aurelia-bootstrapper@1.0.0

**Please tell us about your environment:**
- **Operating System:**
  RHEL
- **Node Version:**
  v4.2.5
- **NPM Version:**
  3.5.1
- **JSPM OR Webpack AND Version**
  JSPM 0.16.34
- **Browser:**
  all
- **Language:**
  ESNext

**Current behavior:**
Bootstrap overrides custom styles (see https://github.com/aurelia/skeleton-navigation/issues/659)

**Expected/desired behavior:**
Resources are loaded in the order they are required.

This is a duplicate of https://github.com/aurelia/skeleton-navigation/issues/659, however, through some trial and error I believe changes in this module are the cause, and the issue occurred between aurelia-bootstrapper@1.0.0-beta.2.0.1 and aurelia-bootstrapper@1.0.0.

---

@waywardz commented on [Mon Sep 19 2016](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-247971421)

I think these are also in play.  I noticed when I backed down the bootstrapper it also backed down the dependencies

"aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.2.0.2",
"aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.3.0.4",

---

@EisenbergEffect commented on [Tue Sep 27 2016](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-250060551)

@AshleyGrant Can you look into this?

---

@AssafDamari commented on [Thu Oct 06 2016](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-251889467)

Any news regarding this?
We can't use any custom themes due to this issue.

---

@EisenbergEffect commented on [Thu Oct 06 2016](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-251968122)

@AssafDamari As a work around, consider traditionally linking bootstrap in the head.

---

@EisenbergEffect commented on [Thu Oct 06 2016](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-251968173)

@AshleyGrant Ping.

---

@AshleyGrant commented on [Thu Oct 06 2016](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-252093678)

Looking in to it

---

@AshleyGrant commented on [Thu Oct 06 2016](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-252103569)

So the problem looks to be that this is all "promisified," and since it takes less time to load the smaller custom css file than the larger bootstrap css file, the custom css file wins the race to be added to the DOM. We would need to make sure the promises execute in order, or depromisify the loader code.

---

@waywardz commented on [Fri Jan 06 2017](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-270906870)

I took a look at 474 which is now closed, unfortunately I couldn't see jdanyow's suggestions as the links to the gitter didn't work for me.

Would it be possible to group priority loads together somehow?  I don't expect to personally have more than bootstrap, but maybe an attribute that tells the loader to create one or more groups based on the priority set?

In my case I have something like this:
```
<require from="font-awesome/css/font-awesome.min.css"></require>
<require from="bootstrap/css/bootstrap.css"></require>
<require from="styles/css/box-selector.css"></require>
<require from="styles/css/my-style-guide.css"></require>
<require from="styles/css/jquery-ui.min.css"></require>

<require from='top-header'></require>
<require from='side-bar'></require>
```

my issue is that my-style-guide.css loads before bootstrap.

Would it be possible to add something like
```<require loadorder="1" from="bootstrap/css/bootstrap.css"></require>```
to indicate I want bootstrap loaded first?

---

@waywardz commented on [Mon Jan 09 2017](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-271383136)

A possible workaround is to add another require with a nested require in it, allowing any overrides to be collected in one location.

in app.html
```
<require from='custom-css'></require>
```

in another file (that has an empty backing class)
```
<template>
    <require from="styles/css/my-style-guide.css"></require>
</template>
```

It looks like it loads the dependencies in groups, so it'll do the groups for app.html first, then the dependencies of custom-css.html.

---

@PWKad commented on [Thu Jan 12 2017](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-272370344)

Just switch to loading Bootstrap from CDN in the head of the index.html, it's a better solution anyways.

---

@AshleyGrant commented on [Fri Jan 13 2017](https://github.com/aurelia/bootstrapper/issues/47#issuecomment-272464880)

@EisenbergEffect could we move this issue to the templating repo?

**Comment by Expaso** [comment]
We have the same problems using imports in javascript.
For KendoUI to work for example, you need to first load jQuery, and then KendoUI.
When doing this:
'''javascript
import "jquery";
import "kendo.all.min";
'''
In most cases kendo.all.min.js is loaded before jquery.js.

Ofcourse we can workaround this (using ugly ways) but it would be nice if there would be first-class support for dependencies.

**Comment by AshleyGrant** [comment]
@Expaso javascript import order is outside of Aurelia's control. That's handled by the module loader. One tip in this specific instance though would be to move jQuery to the `prepend` section of your `vendor-bundle` config. jQuery will be a global object (which is really how it's meant to be used, since it's from "The Land Before Modules"). It would definitely be run before kendo is loaded.

**Comment by Alexander-Taran** [comment]
stale since march 2017

**Comment by EisenbergEffect** [comment]
Closing since this can be handled by bundling differently.
