### ISSUE TITLE
Inject associated View instance when available

### ISSUE THREAD

**Issue by davismj** [aurelia/templating#516]
**I'm submitting a feature request**

* **Library Version:**
1.2.0

**Current behavior:**
When `@inject(View)`, a new `View` is created with no arguments. This produces an error.

**Expected/desired behavior:**
If injected in an instance that has an associated `View`, the associated `View` should be injected.

**What is the motivation / use case for changing the behavior?**
This will allow an instance to handle its own lifecycle events.

**Comment by EisenbergEffect** [comment]
Have you tried implementing the `created` callback on your view model? That provides the view.

**Comment by bigopon** [comment]
@EisenbergEffect this can be close
