### ISSUE TITLE
Allow template literals in bound attributes

### ISSUE THREAD

**Issue by gpetrioli** [aurelia/templating#529]
**I'm submitting a feature request**

* **Library Version:**
1.0.8

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.9.4

* **NPM Version:**
4.1.2

**Current behavior:**
Related to https://github.com/aurelia/templating/issues/119 where the suggestion for passing dynamic urls to the `src` attribute of `img` is to use string concatenation. I tried to use a template literal ``<img src.bind="`/image/filter-icon-${category.icon}.png`" />`` and got

> ERROR [app-router] Error: Lexer Error: Unexpected character [\`] at column 0 in expression [\`/image/filter-icon-${category.icon}.png\`]

**Expected/desired behavior:**
Template literals be allowed in bound attributes.

**What is the motivation / use case for changing the behavior?**
Avoid the verbose and error-prone string concatenation. 
In the above scenario it would become `<img src.bind="'/image/filter-icon-' + category.icon + '.png'" />`.

**Comment by EisenbergEffect** [comment]
Just do this:

```
<img src="/image/filter-icon-${category.icon}.png" />
```

**Comment by gpetrioli** [comment]
@EisenbergEffect this will cause a 404 error (*as mentioned in the linked #119 issue*) before the binding evaluation.

**Comment by EisenbergEffect** [comment]
Yeah...I think that technically shouldn't happen if the browser supports HTMLTemplateElement natively. I don't see us adding an interpolation inside the bind any time soon though, since there's a reasonable workaround at present and this would probably be significant work in the parser.

**Comment by gpetrioli** [comment]
ok, thanks for answering.

**Comment by mertcankose** [comment]
Hey, I have exactly same problem. Do you find a solution? Thanks.

**Comment by mertcankose** [comment]
<Card
        class="card cat-card"
        v-for="card in 5"
        :key="card"
        imageUrl=`/src/assets/card-${card}.jpg`
      ></Card>

I got "Parsing error: unexpected-character-in-unquoted-attribute-value.eslint-plugin-vue"
What Can I do?

**Comment by mertcankose** [comment]
> ```
>   <Card
>     class="card cat-card"
>     v-for="card in 5"
>     :key="card"
>     imageUrl=`/src/assets/card-${card}.jpg`
>   ></Card>
> ```
> 
> I got "Parsing error: unexpected-character-in-unquoted-attribute-value.eslint-plugin-vue"
> What Can I do?

EDİT: I solved

      <Card
        class="card cat-card"
        v-for="card in 5"
        :key="card"
        :imageUrl="`/src/assets/card-${card}.jpg`"
      ></Card>
