### ISSUE TITLE
Documents (aurelia.io/hub.html) Templating> not working

### ISSUE THREAD

**Issue by ry8806** [aurelia/templating#536]
Going to the Aurelia hub and doing the following navigation does not work (none of the last steps work, "Named Slots" is merely an example)...

Templating > Content Projection > Named Slots

There is a warning in the console whilst navigating

![image](https://cloud.githubusercontent.com/assets/10958000/23949800/990f2470-0980-11e7-9213-0b783faedd11.png)

"Cannot read property 'code' of undefined"

If someone could point me in the direction of this file, then i could have a look 😄

**Comment by EisenbergEffect** [comment]
You can find this in the templating repo under the doc folder. The articles are there under a locale folder.

**Comment by bigopon** [comment]
@EisenbergEffect this can be close
