### ISSUE TITLE
Bug: "UseView" in view-strategy.js is undefined, preventing getViewStrategy from returning relative path strings for view selection

### ISSUE THREAD

**Issue by axefrog** [aurelia/templating#54]
This issue cropped up because I tried to dynamically select a view using a relative path string returned in my `getViewStrategy()` function. The erroneous code is here:

https://github.com/aurelia/templating/blob/master/src/view-strategy.js#L13

I suspect the code should actually read:

```
value = new UseViewStrategy(value);
```

**Comment by EisenbergEffect** [comment]
Will get this fixed and released today.
