### ISSUE TITLE
Question: creating a custom element and attaching it to the DOM at runtime

### ISSUE THREAD

**Issue by t03apt** [aurelia/templating#540]
**I'm submitting a question**

I am creating a custom element and attaching it to the DOM at runtime using templatingEngine.enhance.
See: https://gist.run/?id=dbf04191d963e2cc3a9021c924887c7e

Is there a better way to add a custom element dynamically and let aurelia to maintain its lifecycle?
Do you see anything wrong with this approach?

*Compose does not suit for my use case.*

**Comment by EisenbergEffect** [comment]
This would be a good question to ask in the gitter channel at gitter.im/aurelia/discuss
If you haven't tried using the `compose` element, I would look into that first.

**Comment by t03apt** [comment]
I have tried `compose`. I think it does not suit for my use case. Let's say I use compose instead of `my-container`.
a) I can't do this with compose: `date.bind="element.date"`
note: my-element has `@bindable` date property
b) I don't want to implement `activate` on `my-element`. Actually I am not really sure how `activate` fits into the custom element lifecycle.

**Comment by EisenbergEffect** [comment]
The activate does the same thing for compose as for routed view-models. In routing, the params are passed to activate, but with compose, the model is passed to activate.

There's no problem in using the enhance API though. If it meets your need, that's what it's there for. Just make sure to cleanup the view you get back from the enhance call by calling unbind and detach when you are done with it.

**Comment by t03apt** [comment]
> Just make sure to cleanup the view you get back from the enhance call by calling unbind and detach when you are done with it.

I think I did exactly that. So I should be good. See:
`my-containter.js`
```
    attached() {
        let childElement = DOM.createElement('my-element');
        childElement.setAttribute('date.bind', 'date');
        this.DOMElement.appendChild(childElement);
        this.childView = this.templatingEngine.enhance({ element: childElement, bindingContext: this });
        this.childView.attached();
    }

    detached() {
        this.childView.detached();
    }

    unbind() {
        this.childView.unbind();
    }
```

Thanks!

**Comment by EisenbergEffect** [comment]
Looks good!
