### ISSUE TITLE
<template repeat.for> not rendering with if.bind

### ISSUE THREAD

**Issue by VMBindraban** [aurelia/templating#542]
**I'm submitting a bug report**

* **Library Version:**
1.3.0

* **Operating System:**
Windows 10

* **Browser:**
Edge 10

* **Language:**
ESNext

**Current behavior:**
When using a `if.bind` together with a `repeat.for`, Edge is not rendering the template.

```js
<template repeat.for="value of values" if.bind="foo">
Bar
</template>
```

Looks like https://github.com/aurelia/templating/issues/22

**Expected/desired behavior:**
That is renders the template.

**Comment by RWOverdijk** [comment]
👍 very weird

**Comment by StrahilKazlachev** [comment]
You can not have 2 template controllers on the same element.

**Comment by RWOverdijk** [comment]
Why? It works in other browsers, right @VMBindraban ?

**Comment by VMBindraban** [comment]
This only happens in Edge.

**Comment by RWOverdijk** [comment]
@StrahilKazlachev, @jdanyow Could you please explain this a bit more?

**Comment by Thanood** [comment]
I've had the same problem a few months ago (didn't find the issue anymore). As far as I recall, it turned out the order in which browsers process attributes varies.

**Comment by CasiOo** [comment]
@Thanood Yes Firefox doesn't process them in the same order Chrome does (as an example). @StrahilKazlachev is correct in that you cannot have two template controllers on the same element.
