### ISSUE TITLE
bindable decorator breaks custom decorators

### ISSUE THREAD

**Issue by rsuter** [aurelia/templating#546]
I have implemented a custom decorator to automatically convert bound values (e.g. to number or boolean). The implementation is almost the same as in [this link](https://blog.rsuter.com/angular-2-typescript-property-decorator-that-converts-input-values-to-the-correct-type/). 

If I declare a field like this

    @bindable
    @convert(NumberConverter)
    number: number;

then the `NumberConverter` is never called. Somehow the `@bindable` decorator breaks my custom decorator and the property can no longer be intercepted. 

I've created a sample project: Just check the code in `subcomponent.ts` - if the `@bindable` decorator is removed, the `@convert` decorator is working as expected (but of course the binding is no longer working). 

[decoratortest.zip](https://github.com/aurelia/templating/files/905982/decoratortest.zip)

Even if this feature will be provided by the framework in the future (https://github.com/aurelia/templating/issues/96), we should still fix `@bindable` so that additional intercepting decorators are possible to implement...

**Comment by EisenbergEffect** [comment]
Questions are better asked on Gitter or SO.

**Comment by CasiOo** [comment]
@rsuter Here is a working example https://gist.run/?id=3af6abf72e2658a946701b9e466b0164

**Comment by rsuter** [comment]
@CasiOo the whole idea behind this is to avoid `foo.bind="5"` so that you can use `foo="5"` and the converter is still called.

**Comment by CasiOo** [comment]
@rsuter Sorry about that, I see that I messed it up haha
