### ISSUE TITLE
Shorter syntax for binding multiple properties with convention

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating#55]
A shorter version for binding multiple properties would be nice if you are using convention.
ie instead if doing:
```
@bindable("foo")
@bindable("bar")
@bindable("bla")
```

one could do it in one line if the bindable properties do not need any extra options.
```
@bindables("foo","bar","bla")
```

**Comment by EisenbergEffect** [comment]
I'm going to close this for now, since the decorator is rather complex as is. I think this is less of an issue when using ES7 or TypeScript since you can directly decorate the properties themselves.
