### ISSUE TITLE
Array modifications don't trigger bindings

### ISSUE THREAD

**Issue by gronostajo** [aurelia/templating#561]
**I'm submitting a bug report**

* **Library Version:**
aurelia-framework 1.1.2
aurelia-templating 1.4.2
aurelia-binding 1.2.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.2

* **NPM Version:**
4.6.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
Chrome 60.0.3112.113
Firefox 54.0.1

* **Language:**
TypeScript 2.1, ESNext

**Current behavior:**
Array modifications don't trigger bindings. [Demo](https://gist.run/?id=2cac8c024cac4c9b921bcbe7b9e0b115).

**Expected/desired behavior:**

* **What is the expected behavior?**
Bindings should be triggered when array is modified (not just replaced).

* **What is the motivation / use case for changing the behavior?**
It would be more intuitive.

**Comment by Alexander-Taran** [comment]
I think it is described as a note in docs
That changing the values in array won't trigger 'change' on array itself

might be closed

**Comment by Alexander-Taran** [comment]
can be closed
