### ISSUE TITLE
template tag doesn't work in tbody

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/templating#565]
@hobbit125 commented on [Mon Jun 01 2015](https://github.com/aurelia/html-template-element/issues/3)

In IE, if you attempt to place a template tag directly within a tbody tag, it appears to be ignored.

Use case:  Want all grandchildren of a collection to be shown in rows:

```
<table>
  <tbody>
    <template repeat.for="grp in data.rowGroups">
      <tr repeat.for="row in grp.Rows">
          <td>Test</td>
      </tr>
    </template>
  </tbody>
</table>
```

---

@EisenbergEffect commented on [Mon Jun 01 2015](https://github.com/aurelia/html-template-element/issues/3#issuecomment-107741190)

Doubtful we will be able to fix this, due to the way IE handles tables. We may be able to provide a comment-style workaround. Placing the repeat on the tr should be fine, but it's the presence of the template element inside the tbody that causes IE to strip it out before we can even read it.

---

@Ixonal commented on [Wed Nov 18 2015](https://github.com/aurelia/html-template-element/issues/3#issuecomment-157867851)

Just wanted to poke here, as I'm starting to run into this now. I'm wanting to add two rows for every item in a list inside of a table. Ex:

``` html
<table>
  <tbody>
    <template repeat.for="row of rows">
       <tr></tr>
       <tr></tr>
    </template>
  </tbody>
</table>
```

I can't really think of an alternate way to do this properly... I could put the repeat on the tbody, but that's not really right. Has there been any progress on the comment-style workaround? I'm assuming it'd be like comment bindings in Knockout. I found them helpful in various other circumstances as well, so they might be a nice generic addition.

Edit: I suppose one option for me could be to create a custom attribute similar to repeat.for, but that only repeats the inner html content, and leaves the containing element as-is. Kind of like how Knockout's foreach binding works. That way, I could just put it directly on the tbody.

---

@gavinaiken commented on [Tue Jan 12 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-170878884)

Anyone know what the status of this issue is?

---

@EisenbergEffect commented on [Tue Jan 12 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171041821)

It's not possible to make this work without native template support. It's literally impossible. However, we are considering some workarounds, such as potentially attributing elements with `template-start` and `template-end`. Perhaps like this:

``` html
<table>
  <tbody>
       <tr repeat.for="row of rows" template-start></tr>
       <tr template-end></tr>
  </tbody>
</table>
```

^^^Something like that. What do you think?

---

@Ixonal commented on [Tue Jan 12 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171045719)

Feels kind of odd... Maybe just because it's new or something.

Is the alternate repeat attribute i was contemplating not workable? I kind of gave up on it because I got told not to use Aurellia :(

---

@hobbit125 commented on [Tue Jan 12 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171149859)

I think the workaround suggested is fine.  It's a corner case and there's no normal way to handle it.

---

@Ixonal commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171286637)

True. 

Would those attributes have an effect on other binding constructs, or be limited to just repeats?

---

@Mordred commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171314901)

Based on http://stackoverflow.com/questions/3076708/can-we-have-multiple-tbody-in-same-table I end up with this:

``` html
<table>
  <tbody repeat.for="row of rows">
       <tr>1. line</tr>
       <tr>2. line</tr>
  </tbody>
</table>
```

---

@EisenbergEffect commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171318435)

@Ixonal The ideas is that the repeat-start, etc would affect all template controller attributes: repeat, if, with, etc. and any user defined behaviors as well.

---

@EisenbergEffect commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171319484)

@Mordred Cool! I didn't know that was possible. Very nice.

---

@Ixonal commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171328974)

@EisenbergEffect still feels a bit wonky to me, but if it works, it works.

@Mordred yeah, it's possible to do that, but the generated markup wouldn't really match the intent, and may cause issues with css frameworks. If those aren't relevant concerns, though, go for it :)

---

@EisenbergEffect commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171367201)

@Ixonal Do you have any alternate ideas? We are open to suggestions.

---

@Ixonal commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171379152)

@EisenbergEffect think i read the markup wrong the first time. Thought the repeat was on the table body. Having it on the row is a little better. Might let the attributes have an optional value to specify a sort of id to make it more obvious where a particular template starts and stops. My initial thought was that the repeat binding could be altered to give the option to only repeat its children, but you know better than me whether or not that's possible. Something like repeat.in="foo of bar" or repeat.for="foo in bar" to determine that the template should be composed of children only.

---

@EisenbergEffect commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171379716)

I think I would favor the `template-start` and `template-end` a bit more because we could bake that into the compiler and then enable the same thing to work with no only the repeat but also, if with, etc. automatically.

---

@Ixonal commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171381038)

Would that replace what the template tag does for those other cases, or would there just be two ways to have containerless control statements now?

---

@EisenbergEffect commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171381776)

It would basically be an alternative to the template element and could handle all containerless control scenarios.

---

@Ixonal commented on [Wed Jan 13 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171388856)

Sounds alright to me, then. 

---

@gavinaiken commented on [Fri Jan 15 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-171939891)

Would be great to have a work-around that would work with all the other templating keywords also, so I like the `template-start` / `template-end` idea for that reason.

---

@smithaitufe commented on [Sat Mar 05 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-192760212)

I had issue working tables today. I realized it is using template inside the table tag that caused my rows from been rendered. I think the template-start and template-end is better. Does it mean when we want to use nested component built with TR, we will not longer need to use template?

---

@jdanyow commented on [Thu Apr 14 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-210251625)

@EisenbergEffect can this be transitioned to an enhancment for the template-start / template-end feature?

---

@HenryKeen commented on [Fri Oct 21 2016](https://github.com/aurelia/html-template-element/issues/3#issuecomment-255427727)

Massive thanks for the template-start / template-end workarounds @EisenbergEffect, they work a treat!

I've run into a stumbling block though, have you got any idea how I could replicate a nested repeat like this?

```
<tr>
    <template repeat.for="item1 of items1">
        <template repeat.for="item2 of items2">
            <td></td>
        </template>
    </template>
</tr>
```

---

@nano2nd commented on [Thu Feb 09 2017](https://github.com/aurelia/html-template-element/issues/3#issuecomment-278694797)

Was template-start / template-end workaround ever added?

---

@davismj commented on [Sat Feb 11 2017](https://github.com/aurelia/html-template-element/issues/3#issuecomment-279174385)

I mean, I don't think we need it. Rob proposed this above:

```html
<table>
  <tbody>
       <tr repeat.for="row of rows" template-start>row 1</tr>
       <tr template-end>row 2</tr>
  </tbody>
</table>
```

You can achieve this with the following:

```html
<table>
  <tbody>
    <template repeat.for="row of rows" containerless>
       <tr>row 1</tr>
       <tr>row 2</tr>
    </template>
  </tbody>
</table>
```

---

@jdanyow commented on [Sat Feb 11 2017](https://github.com/aurelia/html-template-element/issues/3#issuecomment-279178490)

@davismj I think the template-start/end workaround is for IE.

IE doesn't have true template element support so it mangles the markup when you try to use template within a table.

---

@nano2nd commented on [Sat Feb 11 2017](https://github.com/aurelia/html-template-element/issues/3#issuecomment-279178526)

Thanks @davismj this works in Chrome, but my issue is specifically with tables in IE11 where my bindings are breaking down even with "containerless". I have yet to get code in this form to work in IE11...

```
<table>
  <tbody>
    <template repeat.for="row of rows" containerless>
      <tr if.bind="bool_expr">${row.SomeVal}</tr>
    </template>
  </tbody>
</table>
```

---

@nano2nd commented on [Sat Feb 11 2017](https://github.com/aurelia/html-template-element/issues/3#issuecomment-279178545)

oops we posted at the same time..is there no known workaround besides the repeating `<tbody>` implementation?

---

@lancegiles commented on [Mon Jun 12 2017](https://github.com/aurelia/html-template-element/issues/3#issuecomment-307781326)

I've just had a developer mention this issue to me for IE and the only work around he found is putting the template on the tbody (which I don't like since it messes up some of our css attributes when highlighting odd/even rows).  But we have to do what we have to do.  

Was the template-start / template-end ever designed?  I'd like to see if that resolves the issue.

---

@timfish commented on [Tue Jul 04 2017](https://github.com/aurelia/html-template-element/issues/3#issuecomment-312969765)

I can't have multiple `<tbody>` as I wanted to set max-height on it and have it scroll all the rows. I ended up having to change to flex layout rather than table!

---

@jamesond commented on [Fri Jul 21 2017](https://github.com/aurelia/html-template-element/issues/3#issuecomment-317080240)

Any one come up with a work around on this? Besides repeating tbody, seems pretty hacky.

---

@gavinaiken commented on [Mon Jul 24 2017](https://github.com/aurelia/html-template-element/issues/3#issuecomment-317378660)

Repeating `tbody` or using flexbox were the only work arounds we came up with in our project.

**Comment by Infuser** [comment]
Any updates on this?

I am currently putting the repeater on the tbody tag, but it's a bit of a nasty workaround.

**Comment by VMBindraban** [comment]
Bump. Placing the repeater on the `tbody` doesn't work for me in IE11. It doesn't repeat at all now.

**Comment by RomkeVdMeulen** [comment]
We had to hack around this recently with nested tables. :frowning_face:

**Comment by Alexander-Taran** [comment]
Have a nice read about containerles vs as-element that is very relevant to this topic about IE
https://discourse.aurelia.io/t/use-of-containerless/817/2

**Comment by RomkeVdMeulen** [comment]
@Alexander-Taran Thanks for your help, but I was aware of containerless and as-element (they also came up in [the original issue](https://github.com/aurelia/framework/issues/859)). As far as I know, those can't help get me multi-level nested repeaters in a table in a way that also works in IE.

**Comment by nenadvicentic** [comment]
Why isn't this stated in Aurelia documentation as a known issue in IE?  I guess that everyone who eventually ends up on this pages, spends LOT of time to figure where the issue actually is, same as I did, just to find out that it's well known problem.

**Comment by StrahilKazlachev** [comment]
@nenadvicentic like this [Invalid Table Structure When Dynamically Creating Tables](https://aurelia.io/docs/fundamentals/cheat-sheet#templating-basics)?

**Comment by nenadvicentic** [comment]
@StrahilKazlachev And why is is not in the section with the same name "Templating Basics" in normal documentation? There you have exact example of repeater on the template element `repeater-template.html`.

Unfortunately, I did not look at Cheat Sheet, since I was already reading templating documentation.

**Comment by StrahilKazlachev** [comment]
@nenadvicentic probably since the "cheat-sheet" was the first form of docs, during *pre-beta* and *beta*. Later was not transferred.
PRs were always welcomed from the community.

**Comment by nenadvicentic** [comment]
@StrahilKazlachev Unfortunately, right now I have to recover time lost on the project. Possibly I make PR at some later point.

**Comment by Alexander-Taran** [comment]
@bigopon PR to mention this in docs happened..
maybe can be closed.
