### ISSUE TITLE
aurelia-templating.js:1544 Uncaught TypeError: Cannot read property 'animatableElement' of undefined

### ISSUE THREAD

**Issue by Kukks** [aurelia/templating#574]
**I'm submitting a bug report**

* **Library Version:**
1.6.0

**Please tell us about your environment:**
* **Operating System:**
Win 10

* **Node Version:**
6.11.4

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 3.6.0

* **Browser:**
Chrome

* **Language:**
TS 2.5.3

**Current behavior:**
When removing an item from an array using splice, Aurelia throws an exception.
```
aurelia-templating.js:1544 Uncaught TypeError: Cannot read property 'animatableElement' of undefined
    at getAnimatableElement (aurelia-templating.js:1544)
    at ViewSlot.animateView (aurelia-templating.js:1583)
    at ViewSlot.removeAt (aurelia-templating.js:1785)
    at Repeat.removeView (repeat.js:263)
    at ArrayRepeatStrategy._runSplices (array-repeat-strategy.js:189)
    at ArrayRepeatStrategy.instanceMutated (array-repeat-strategy.js:158)
    at Repeat.handleCollectionMutated (repeat.js:151)
    at Repeat.call (repeat.js:95)
    at ModifyArrayObserver.callSubscribers (aurelia-binding.js:304)
    at ModifyArrayObserver.call (aurelia-binding.js:917)
```

* **What is the expected behavior?**
To work as it does on this gist:
https://gist.run/?id=0849daa54f6804e2ea378945da8b9f33

**Comment by StrahilKazlachev** [comment]
Can not reproduce, please provide a repro we can test with.
Tested:
- chrome@62
- `aurelia-templating@1.6.0`, `aurelia-templating-resources@1.5.3`
- setup used
  - aurelia-cli - requirejs/babel - copied the main.js/html contents from the provided *working* gist
  - aurelia-cli - webpack/ts - copied the main.js/html contents from the provided *working* gist

**Comment by Kukks** [comment]
package lock and bumping the versions was the issue

**Comment by AshleyGrant** [comment]
I'm currently seeing this error in my project on `aurelia-templating` 1.7.0 and `aurelia-templating-resources` 1.6.0.

It only seems to happen when I use splice to remove the only item in an array with `length === 1`. But it is repeatable for me.

**Comment by AshleyGrant** [comment]
It also happens if I simply overwrite the bound property holding the array with a new array.

**Comment by AshleyGrant** [comment]
The LOC throwing the error seems to be here: https://github.com/aurelia/templating/blob/7f96b42c28ee3399b3c5de4752d552b6b29db6a1/src/view-slot.js#L6

But that isn't the source of the problem. The source of the problem is that somewhere along the line, array observation is spitting out two mutations for the one mutation. So the view is removed (and animation is attempted), and then it is removed again.

cc/ @EisenbergEffect @jdanyow

**Comment by AshleyGrant** [comment]
I'm currently unable to duplicate this in a simple repro, but I can show this in client code.

**Comment by AshleyGrant** [comment]
I would recommend we add a null check here: https://github.com/aurelia/templating/blob/7f96b42c28ee3399b3c5de4752d552b6b29db6a1/src/view-slot.js#L279

**Comment by AshleyGrant** [comment]
This is an issue that continues to pop up, but is rather difficult to repro and thus continues to get closed:

https://github.com/aurelia/templating-resources/issues/165
https://github.com/aurelia/templating/issues/470
https://github.com/aurelia/templating/issues/518
https://github.com/aurelia/templating/issues/525

and is affecting public tooling built on Aurelia:

https://github.com/monterey-framework/monterey/issues/263

**Comment by StrahilKazlachev** [comment]
Wouldn't that be a breaking change? The method is expected to return the removed `view`.

**Comment by AshleyGrant** [comment]
The code is currently broken. When I add the null check in my app it doesn't throw an error.

**Comment by AshleyGrant** [comment]
I've tried to find where the duplicated mutations get created but haven't been able to figure that out.

**Comment by StrahilKazlachev** [comment]
I'm arguing that with the current implementation of `ViewSlot.prototype.removeAt` it's responsibility of the caller not to call with non-existent `View`s.

**Comment by AshleyGrant** [comment]
This is the error message I get 

```
aurelia-task-queue.js?2bf4:43 Uncaught TypeError: Cannot read property 'animatableElement' of undefined
    at getAnimatableElement (VM29765 aurelia-templating.js:1628)
    at ViewSlot.animateView (VM29765 aurelia-templating.js:1667)
    at ViewSlot.removeAt (VM29765 aurelia-templating.js:1873)
    at Repeat.removeView (VM29779 repeat:272)
    at ArrayRepeatStrategy._runSplices (VM29782 array-repeat-strategy.js:193)
    at ArrayRepeatStrategy.instanceMutated (VM29782 array-repeat-strategy.js:162)
    at Repeat.handleCollectionMutated (VM29779 repeat:160)
    at Repeat.call (VM29779 repeat:104)
    at ModifyArrayObserver.callSubscribers (VM29771 aurelia-binding.js:398)
    at ModifyArrayObserver.call (VM29771 aurelia-binding.js:1011)
    at TaskQueue._flushQueue (VM29772 aurelia-task-queue.js:90)
    at TaskQueue.flushMicroTaskQueue (VM29772 aurelia-task-queue.js:141)
    at MutationObserver.eval (VM29772 aurelia-task-queue.js:66)
```

**Comment by AshleyGrant** [comment]
>I'm arguing that with the current implementation of ViewSlot.prototype.removeAt it's responsibility of the caller not to call with non-existent Views.

`removeAt` doesn't take a view as a parameter, it takes an index and then the ViewSlot is in charge of finding that specific view.

**Comment by StrahilKazlachev** [comment]
I corrected myself.

**Comment by AshleyGrant** [comment]
The only thing the docs mention regarding a return value is "May return a promise if the view removal triggered an animation." I know that the typings say that it can return `View | Promise<View>` but the fact is that if someone is currently relying on that, then their code will be having the error thrown at it. 

I agree that it could be considered a breaking change. But in the absence of a simple, repeatable repro, I'm not sure what else to do. I thought I had a simple repro, but then I managed to fix it. I tried the same fix in my app code and it didn't fix the problem.

**Comment by AshleyGrant** [comment]
Also, I'm not really sure how the caller can be expected to know that the view doesn't exist when it calls the API given all it is required to know is an index for the view it wants to remove.

**Comment by AshleyGrant** [comment]
I have a feeling the issue is caused by having two template controllers one inside the other (if.bind with a repeat.for inside it).

**Comment by AshleyGrant** [comment]
I have a feeling the issue is caused by having two template controllers one inside the other (if.bind with a repeat.for inside it). 

https://github.com/aurelia/templating/issues/590
https://github.com/aurelia/templating/issues/596

In this case, given the async nature of Aurelia's binding engine, I don't think it can be expected that a template controller can know that a view it wants to be removed won't exist at the time it requests its removal.

I'm able to get rid of my problem removing an `if.bind` on my `table` element just above the `repeat.for` on the `tr` element. I had put the `if.bind` there to deal with a *different* bug in the repeater implementation (similar to #590 linked above). So I'm chasing my tail a bit here.

**Comment by Kukks** [comment]
I've also started getting this frustrating bug as part of the new templating versions. In some places where I append items to an array the repeater completely breaks and starts rendering superficial items.
For example
```
<ul>
  <li repeat.for="x of y">
    ${x} at index ${$index}
  </li>
  <li click.delegate="y.push('blah')">+</li>
  <li>${y.length}</li>
</ul>
```
would render 
```
<ul>
  <li>blah at 0</li>
  <li>null at 1</li>
  <li>null at 2</li>
  <li>null at 3</li>
  <li click.delegate="y.push('blah')">+</li>
  <li>1</li>
</ul>
```

**Comment by classicalConditioning** [comment]
y = [1, 2];
Template: `<div repeat.for="i of y">${i}</div>`
**Steps to repro:** 
1) Problem with `array.shift()`:

call `y.shit()`
you will get the error described in this thread.

2) Problem with `array.unshift()`:

call `y.unshift(3)`
`y` shows proper value in the console: [3, 1, 2]
but in the view - a bizarre value is rendered: 31212

**Comment by VagyokC4** [comment]
I'm also getting this issue.  I simply push into the array and while the array looks right, the repeat.for is drawing extra items. and the above error shows up in the browser.

**Comment by stuartbale** [comment]
I'm experiencing the same behaviour as @VagyokC4 
Will investigate further for possible cause.

**Comment by michaelsmithson** [comment]
I had some issues with the repeater rendering superficial items today. This was caused by me accidentally getting two different versions of the binding library imported. Left a more detailed comment on #575

**Comment by huochunpeng** [comment]
See https://github.com/aurelia/templating/issues/575#issuecomment-407920042

All the weird bugs (this and few others github issues) (highly) probably caused by duplicated aurelia-binding in webpack bundle.

**Comment by huochunpeng** [comment]
There is a temporary solution for duplicated aurelia-binding in webpack. Please check it to see whether it solve some weird issue of yours.

aurelia/binding#702

**Comment by johanbasson** [comment]
I got this bug today, here is the stack trace:

`
Uncaught TypeError: Cannot read property 'animatableElement' of undefined
    at getAnimatableElement (aurelia-templating.js:1847)
    at ViewSlot.animateView (aurelia-templating.js:1886)
    at ViewSlot.removeAt (aurelia-templating.js:2088)
    at Repeat.removeView (repeat.js:292)
    at ArrayRepeatStrategy._runSplices (array-repeat-strategy.js:194)
    at ArrayRepeatStrategy.instanceMutated (array-repeat-strategy.js:163)
    at Repeat.handleCollectionMutated (repeat.js:180)
    at Repeat.call (repeat.js:115)
    at ModifyArrayObserver.callSubscribers (aurelia-binding.js:383)
    at ModifyArrayObserver.call (aurelia-binding.js:997)
    at TaskQueue._flushQueue (aurelia-task-queue.js:99)
    at TaskQueue.flushMicroTaskQueue (aurelia-task-queue.js:150)
    at MutationObserver.<anonymous> (aurelia-task-queue.js:75)
`

Here is the aurelia plugins we use:

`		"aurelia-auth": "^3.0.5",
		"aurelia-bootstrap-datetimepicker": "^1.3.2",
		"aurelia-bootstrapper": "^2.3.0",
		"aurelia-chart": "^0.2.7",
		"aurelia-dialog": "^2.0.0-rc.3",
		"aurelia-fetch-client": "^1.6.0",
		"aurelia-google-maps": "^2.2.1",
		"aurelia-http-client": "^1.3.0",
		"aurelia-i18n": "^2.3.2",
		"aurelia-resize": "^1.1.2",
		"aurelia-templating": "^1.10.1",
		"aurelia-validation": "^1.3.0"
`
also aurelia-cli: 0.35.1

This happens when I clear an array and add an item to the array. This array is used in the view.

Any help appreciated.

**Comment by johanbasson** [comment]
@bigopon Here is the code which updates the array:

```typescript
private selectSingle(team: TeamSummary) {
		this.selectedTeams = [];
		this.selectedTeams.push(team);
		this.publishMessage(new TeamsSelectedMessage(this.selectedTeams));
	}
```
As you can see it is a very simple clear and append to the array.

And here is a sample of the view code:

```html
			<li repeat.for="team of teams | teamFilter:'OTHER'" class="mouse-cursor-link ${selectedTeams.length > 0 && isSelected(team) ? 'active' : ''}" click.delegate="selectTeam(team, $event)">
                <span class="none">
					<svg class="wh-16 auto-active hide fill-aqua">
						<use xlink:href="images/sprites.svg#icn-auto-activate-outline"></use>
					</svg>
                </span>
...
```

**Comment by StrahilKazlachev** [comment]
Try
```ts
private selectSingle(team: TeamSummary) {
        const selectedTwams = [team];
	this.publishMessage(new TeamsSelectedMessage(selectedTeams));
        this.selectedTeams = selectedTeams;
}
```
*or*
```ts
private selectSingle(team: TeamSummary) {
        const selectedTwams = [team];
        this.selectedTeams = selectedTeams;
	this.publishMessage(new TeamsSelectedMessage(this.selectedTeams));
}
```
if it must be assigned before dispatching the event.
In general try to keep the mutations to the arrays used in bindings to a minimum - on perf side.

**Comment by bigopon** [comment]
I think we have already tried to patch for this issue. My guess is there is some different version of aurelia binding inside your app. Can you try 
```js
 alias: {
  'aurelia-binding': path.resolve(__dirname, 'node_modules/aurelia-binding')
}
```
in your webpack configuration?

**Comment by johanbasson** [comment]
@bigopon I'm using the aurelia-cli with requirejs. I have also checked my node_modules directory and the aurelia-binding version is on 2.1.6

**Comment by bigopon** [comment]
@johanbasson Thanks. I think this is hard to reproduce and it's a result of some weird combination of modules, could be core, could 3rd party. We'd really need a reproduction to fix this. I'm doing what you do to remove / add stuff all the times and haven't run into it. I'll try again but please share if you can reproduce it.

**Comment by johanbasson** [comment]
@bigopon Thank you for your help. I investigated the code where the issue occurs and manged to simplify the code which somehow fixes the issue. The code changes does not have anything to do with Aurelia but somehow it does not give the stack trace. I'm at a loss to explain why the code changes fixes the problem, but at least it is sorted now.

**Comment by Truffula** [comment]
Saw another instance of this error which was caused by core-js being loaded after aurelia-binding (instead of before) and replacing the `array.push` method. core-js includes a fix for an old browser bug, [the check for which](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.array.push.js#L9-L24) is apparently tripped up by the aurelia-binding override.

**Comment by bigopon** [comment]
> Saw another instance of this error which was caused by core-js being loaded after aurelia-binding (instead of before) and replacing the `array.push` method. core-js includes a fix for an old browser bug, [the check for which](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.array.push.js#L9-L24) is apparently tripped up by the aurelia-binding override.

Thanks for the info @Truffula 👍
