### ISSUE TITLE
Repeat binding iterates an extra time for each item in array

### ISSUE THREAD

**Issue by Kukks** [aurelia/templating#575]
**I'm submitting a bug report**

* **Library Version:**
1.6.0

**Please tell us about your environment:**
* **Operating System:**
Win 10

* **Node Version:**
6.11.4

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 3.6.0

* **Browser:**
Chrome

* **Language:**
TS 2.5.3

**Current behavior:**
When adding an extra item to an observed array, the bindings on the repeat seem to break. 
an array with length 2  would repeat 4 times, with the last two items being null.
```
<div repeat.for="item of items">
${$index} -- ${item}
</div>
``` 
```
<div>0 -- a</div>
<div>1 -- b</div>
<div>2 -- </div>
<div>3 -- </div>
```

* **What is the expected behavior?**
To work as it does on this gist:
https://gist.run/?id=0849daa54f6804e2ea378945da8b9f33

My current workaround is ugly:
`if.bind="$index<items.length"`

**Comment by bigopon** [comment]
It's working as expected for me. Can you describe how to reproduce the error ?

**Comment by Kukks** [comment]
@bigopon I wish I could, it only started happening on my colleague's workstation from a  fresh npm install.  Our solution is a bit too massive to easily dissect and find what makes it break like this. 
Seems like the repeat binding breaks on splices. Possible related error here: https://github.com/aurelia/templating/issues/574

**Comment by StrahilKazlachev** [comment]
@Kukks were there any lock files prior to the clean install?

**Comment by Kukks** [comment]
package lock and bumping the versions was the issue. Thanks for the help!

**Comment by Kukks** [comment]
This has started appearing again. Tried all sorts of annoying tactics with package locks and version bumping.. 
https://github.com/aurelia/templating/issues/574#issuecomment-396849762

**Comment by bigopon** [comment]
Hmm it's not easy to track down, I have updating through many version and haven't gotten into that bad state of the repeat. Can you please share a repro or some more info @Kukks  ?

**Comment by Kukks** [comment]
Just an example of using .push on the array, with a .length print at the bottom:
https://gyazo.com/f5def4c9e4d8897e866a26f48b904309

**Comment by bigopon** [comment]
Maybe the specific block that updating the array should do

**Comment by Kukks** [comment]
```
<table class="table">
          <thead>
            <th t="name">Name</th>
            <th></th>
          </thead>
          <tbody>
          <resource-data-source resource="TranslationCultures"
                                view-model.ref="translationCulturesDS"></resource-data-source>
          <tr repeat.for="chosenTranslation of chosenTranslations">
            <td class="d-flex">
              <h-options
                class="col-md-6"
                read-only.bind="!editMode"
                if.bind="translationCulturesDS && translationCulturesDS.metadata"
                translate.bind="false"
                value-identifier.bind="chosenTranslations[$index]"
                allow-clear.bind="false"
                load-remote-options.bind="translationCulturesDS.loadSelectRemoteData"
                load-single-option.bind="translationCulturesDS.loadSingleRemoteData"
                prop-display.bind="translationCulturesDS.metadata.optionSettings.name"
                prop-id.bind="translationCulturesDS.metadata.optionSettings.id"></h-options>
            </td>
            <td class="text-right">
              <button class="btn-sm btn-link text-danger" h-button click.delegate="chosenTranslations.splice($index, 1)" if.bind="editMode">
                <h-icon name="trash-o"></h-icon>
                <span t="remove">Remove</span>
              </button>
            </td>
          </tr>
          <tr>
            <td>
              <h-spinner show.bind="loading"></h-spinner>
            </td>
            <td class="text-right">
              <button class="btn-link text-dark" h-button click.delegate="chosenTranslations.push(null)" if.bind="editMode">
                <h-icon name="plus-circle"></h-icon> ${'add' & t}
              </button>
            </td>
          </tr>
          </tbody>
          <tfoot>
            <tr>
              <td>${chosenTranslations.length}</td>
            </tr>
          </tfoot>
        </table>
```

**Comment by bigopon** [comment]
How you are adding element to `chosenTranslations` ?

**Comment by Kukks** [comment]
`chosenTranslations.push(null);` straight from the html
I have other scenarios where I get the same effect from a view model  x.push

**Comment by VagyokC4** [comment]
I'm experiencing this problem as well...    Can we get this issue escalated and resolved?

[Animated GIF](https://i.imgur.com/4EZv6d3.gifv)

**Comment by Kukks** [comment]
It's a bug in Aurelia, i did some further  debugging and had posted in the
gitter along with a nasty hack where you override the prototype with a
dangerous patch. It really is a crazy bad issue and seems to be very hard
to replicate but keeps popping up every time you try to update Aurelia.

**Comment by doktordirk** [comment]
@Kukks  hard to find anything on gitter. can you repost here or in discourse?

**Comment by michaelsmithson** [comment]
We had something similar happening in our project today, where the push was causing duplicate items. Looking at the final compiled code it appears we have ended up with two different versions of the binding library imported in our solution (1.6.0 and 2.1.0). 

The binding library patches the push method on the array prototype with a version that adds a change record. With two versions of the library this being patched twice, it resulting in two changes being recorded for every push.

**Comment by stuartbale** [comment]
@michaelsmithson - when you say "binding library" do you specifically mean aurelia-binding (https://www.npmjs.com/package/aurelia-binding) or something else?

**Comment by huochunpeng** [comment]
Here is my guess.

Probably this is the way how webpack works, it tries to mimic nodejs behaviour.

Previous @EisenbergEffect released new parser in aurelia-binding v2 to make it a safe opt-in. But since then, aurelia core libs have been updated to depend on v2.

But if you have some 3rd party plugin (very likely) still asks aurelia-binding ^1.x.x in the package.json, you end up with 2 versions of binding in your node_modules (one direct, another one under the plugin folder).

webpack tries to respect the plugin's dependency, thence bundled 2 versions of aurelia-binding.

This also answers why I didn't see this nasty issue, as I use cli+requirejs built, it only bundles one version of every libs.

**Comment by stuartbale** [comment]
Ah yes, i see that my:
aurelia-plugins-google-recaptcha
'requires' aurelia-binding ^1.7.1
I will see if I can fix it somehow.

**Comment by michaelsmithson** [comment]
@stuartbale yep, I do mean the aurelia-binding library.
To find this I was stepping through the code in the chrome debugger, and noticed this weird behaviour inside the binding library push function. I then stuck a breakpoint before it patched the push method and noticed that when I inspected the current Array.prototype.push method that it was not the native function (push() { [native code] }) but rather appeared already to be the aurelia patched version. At this point I hunted around and found that there were two versions of aurelia-binding being included by jspm.

**Comment by huochunpeng** [comment]
Reference

https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin

https://github.com/zillow/webpack-stats-duplicates

**Comment by huochunpeng** [comment]
The new resurgence of this isssue, is apparently different from the original issue created by @Kukks.
The original issue was demonstrated in gistrun, which is an aurelia bug. It has been fixed.

The resurgence is caused by which I guess the webpack packed two versions of aurelia-binding.

**It's confirmed.**

I can reproduce this issue with cli+webpack, just use plugin aurelia-plugins-google-recaptcha (which requires aurelia-binding ^1.7.1).

Not only the repeat bug appear, but also `DuplicatePackageCheckerPlugin` complains
```
WARNING in aurelia-binding
  Multiple versions of aurelia-binding found:
    1.7.1 ./~/aurelia-plugins-google-recaptcha/~/aurelia-binding
    2.1.2 ./~/aurelia-binding
```

Bingo.

**Comment by stuartbale** [comment]
@huochunpeng I concur. I installed DuplicatePackageCheckerPlugin and saw the same result as you.

**Comment by fkleuver** [comment]
Yep, this will keep happening as long as these 3 conditions are met:
- `aurelia-binding@^2.0.0` is pulled in as a result of any main dependency allowing it (which is approximately the whole framework at least)
- `aurelia-binding@^1.0.0` is pulled in as a result of another dependency disallowing it (which is a large portion of the plugin landscape)
- `webpack` and `jspm` not offering a means to override the dependency resolution tree

At the moment, the best thing to do I believe is to try and get all those plugins updated. They can be found by looking at https://www.npmjs.com/package/aurelia-binding / `dependents`. I'll start sending some PRs early next week. Anyone feel free to chime in and help out.

**Comment by huochunpeng** [comment]
FYI
Temporary solution: Update webpack.config.js using alias to force one version of binding

```js
module.exports = ({production, server, extractCss, coverage, analyze} = {}) => ({
  resolve: {
    extensions: ['.js'],
    modules: [srcDir, 'node_modules'],

// add alias for aurelia-binding
    alias: {
      'aurelia-binding': path.resolve(__dirname, 'node_modules/aurelia-binding')
    }
  },
```
