### ISSUE TITLE
Can't get Signalable Value Converters to work

### ISSUE THREAD

**Issue by nashwaan** [aurelia/templating#578]
**I'm submitting a bug report**

* **Library Version:**
1.1.5

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.6.0

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
webpack v3.8.1

* **Browser:**
Chrome

* **Language:**
ESNext

**Current behavior:**
Signalable value convertor doesn't work

**Expected/desired behavior:**
Trying to follow documentation about [Signalable Value Converters](http://aurelia.io/docs/binding/value-converters#signalable-value-converters) but can't get it to work.

Calling `signalBindings('shout');` causes error:
`Uncaught TypeError: (0 , _aureliaFramework.signalBindings) is not a function`.

Also tried this possible workaround `this.bindingSignaler.signal('shout')` and has no effect.

Check this gist:
https://gist.run/?id=e7be9424900100c8085e7a50c56fa5d6

**Comment by bigopon** [comment]
The gist used an old version if Aurelia binding, which creates `signalBindings is not a function`. @jdanyow I remember the gist bundle is always up to date ? Should we also link `BindingSignaler` to `signalBindings` now ?

**Comment by nashwaan** [comment]
@bigopon I am using latest aurelia-framework v1.1.5 via webpack and I still get this error message.
BTW, does it work for you?

> Should we also link BindingSignaler to signalBindings now ?

Sounds like a good idea.

In fact, I don't think the difference is clear between `signalBindings('shout')` and `bindingSignaler.signal('shout')`. If they are redundant or largely similar, then one of them should be deprecated.

**Comment by StrahilKazlachev** [comment]
@nashwaan And are you using the latest of `aurelia-binding?`

**Comment by nashwaan** [comment]
@StrahilKazlachev after installing `aurelia-binding`, `signalBindings('shout')` worked! Thanks for your help.

But this is strange. Although I am importing `signalBindings` **from** `aurelia-framework` which I have it installed and updated to latest version, I still need to install `aurelia-binding` for this!!!
```js
import {signalBindings} from 'aurelia-framework';
```

And again, what do we have two things that looks so similar:
`signalBindings('shout')` and `bindingSignaler.signal('shout')`?

**Comment by StrahilKazlachev** [comment]
@nashwaan Do bear in mind that Aurelia is a mudular framework. This allows for independent releases of the modules(most of the time). When you install `aurelia-framework` you get the latest versions at that time. Later on a new versions of the dependencies can be published without affecting the version of `aurelia-framework` itself. Also the majority of the *exports* of `aurelia-framework` are actually *reexports* from its dependencies - `export * from 'aurelia-binding';`.

**Comment by nashwaan** [comment]
Can someone please explain why there two similar api calls? this thing doesn't look to me a good api design.

`signalBindings('shout')` and `bindingSignaler.signal('shout')`?

**Comment by EisenbergEffect** [comment]
The `bindingSignaler` is deprecated. If you use it, it will tell you that. We can't just remove it without it causing a breaking change. We didn't want to do that, so we added the new API, forwarded the old API to it and added a deprecation message.

**Comment by nashwaan** [comment]
@EisenbergEffect thanks for this important clarification.

Now this means I should replace all the existing `bindingSignaler.signal('shout')` with the new API `signalBindings('shout')`.

**Comment by EisenbergEffect** [comment]
Yes. We'll remove the old API in the next Major release. So, this keeps you ahead of that, if you want to.

**Comment by nashwaan** [comment]
@EisenbergEffect 
Currently, `signalBindings('shout')` doesn't replace the functionality of `bindingSignaler.signal('shout')`.

For example, in a view template:
```html
<div>${result | json & signal:'shout'}</div>
```

Calling `bindingSignaler.signal('shout')` will cause the update in the view, but calling `signalBindings('shout')` has no effect. I am now using both of them in the application for different scenarios. This is not good.

cc: @jdanyow

**Comment by obedm503** [comment]
same experience as @nashwaan here. with aurelia-framework@1.1.5 (the latest) the `signalBindings` function exists but it doesn't actually refresh the bindings. also, using `BindingSignaler#signal` doesn't warn about it being deprecated

**Comment by bigopon** [comment]
@obedm503 It's working fine for me https://gist.run/?id=54a95aca25b9df101aaa03df0ae4c9bd

**Comment by obedm503** [comment]
@bigopon  ![error](https://user-images.githubusercontent.com/9118707/35178587-d567e168-fd50-11e7-963f-8d6c101cfc8d.png)

**Comment by bigopon** [comment]
@obedm503 I think you need to enable cookie / cache / whatever it takes to enable service worker
