### ISSUE TITLE
Passing a URL to the Primary Property on Custom Attribute Confuses the Engine.

### ISSUE THREAD

**Issue by SuricateCan** [aurelia/templating#583]
**I'm submitting a bug report**

* **Library Version:**
1.6.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.1

* **NPM Version:**
5.5.1

* **Browser:**
Chrome 62.0.3202.94

* **Language:**
TypeScript >=1.9.0-dev || ^2.0.0

**Current behavior:**
When using a primary property on a custom attribute that is meant to receive an URL, the simple syntax does not pass the value to the property.
My guess is that the `:` on the URL confuses the parser to think I'm setting a property called http.
The behavior can be seen here: https://gist.run/?id=c1d96d1d33ac50eb1fd3ab1a3007e049

**Expected/desired behavior:**
The engine should recognize the value as a valid URL/URI and set the primary property with it.

* **What is the expected behavior?**
The engine should recognize when the attribute value is set to a valid URI and set the primary property accordingly.

* **What is the motivation / use case for changing the behavior?**
In my case, I'm trying to write an attribute that remotely load options to a select element. The attribute should receive an URL as value so the request can be made.

**Comment by SuricateCan** [comment]
The attribute for debug purposes is as simples as this:
```
import {bindable, inject} from 'aurelia-framework';

@inject(Element)
export class RemoteSourceCustomAttribute {
  @bindable value: string;
  @bindable({ primaryProperty: true }) url: string;

  constructor(elem) {
    this.elem = elem;
  }

  attached(){
    this.elem.innerText = `someProperty: ${this.value} | color: ${this.color}`;
  }
}

```
It is used on the view as this:
```
<template>
  <require from="./remote-source"></require>
  
  <div remote-source="/relative/path/works"></div> 
  <div remote-source="https://absolute.paths.does/not"></div>
  <div remote-source="url:https://only.using.full/syntax;"></div>
  
</template>
```

**Comment by bigopon** [comment]
The syntax of custom attributes follow standard syntax you see in html style attribute:

```html
<div style="rule: value; rule: value; rule: value"></div>
```

Checking for url to parse correctly is unexpected. I think this is a won't fix issue.

@EisenbergEffect

**Comment by SuricateCan** [comment]
@bigopon you are right, but even the style attribute accepts url by doing `url()`, maybe that can be a way to implement this?
I'm thinking maybe something like:
`
<div remote-source="url(https://absolute.paths.now/works)"></div>
`

Then the view model would receive the URL string.

What do you think?

**Comment by bigopon** [comment]
For me, I would only pass the part after `https:`, so it still feels invalid to me (it looks like `url(https = //...`). Also I'm not sure how to distinguish between what you describe and standard syntax in the parser.

**Comment by Alexander-Taran** [comment]
@SuricateCan can you provide a use case for that value being a sting literal?
if you use a variable instead I assume everything will work fine.
So what's your "edge case"?

**Comment by SuricateCan** [comment]
@Alexander-Taran you are correct. If I bind the default value to a variable, the value gets passed correctly. This behaviour only happens when using a string literal that represents a "protocol". I assume any other protocol will fall in the same issue.
Where this would be useful is, for example, a component that can receive only a URL to function properly, like a remote source for a static list, or something like this.
Here in the company I work, we have lots of components that receive a URL in the HTML so handle the calls. I don't think this is a good idea, but in some cases can be useful.
PS.: I've updated the Gist https://gist.run/?id=c1d96d1d33ac50eb1fd3ab1a3007e049

**Comment by Alexander-Taran** [comment]
@SuricateCan that I understood.. why is it in markup though? Is it server-rendered? or just like that in code base?

**Comment by SuricateCan** [comment]
Not server rendered. It fetches data to list, in my use case.

**Comment by Alexander-Taran** [comment]
I mean why url is statically defined in markup?
why it's not dynamic?

**Comment by SuricateCan** [comment]
Because the content is kind of static. It fetches a list from the server, that may or may not change. The source is always the same.

**Comment by SuricateCan** [comment]
I found this issue when creating a component that fills a `<select>` element with `<option>`s from the server, where the list is built from an enumeration.

**Comment by Alexander-Taran** [comment]
well obvious workaround is.. to have url defined in vm
Highly unlikely this will be modified in v1

**Comment by Alexander-Taran** [comment]
@bigopon and the question is kinda answered?

**Comment by bigopon** [comment]
This is a won't fix for now. Unless it's really desirable. There' many ways to work around it, simplest is with let as an example. Changing the attr parser in v1 isn't a high priority unless someone wants to take on that.
