### ISSUE TITLE
Au property missing on containerless custom elements, makes child and children not find viewmodels on containerless elements.

### ISSUE THREAD

**Issue by ielcoro** [aurelia/templating#588]
I'm not sure if this is a bug or not, so first I want to confirm with you if this is expected, or there are any workarounds.

When using containerless decorator or containerless attribute on elements, the au property is missing on the root element. So there is no way to access the viewmodel reference from the DOM. This also changes the behaviour of child and children, as they cannot locate the viewmodel for the specified selector, and they inject HtmlElements. 

Removing the containerless decorator creates the "custom element" element in the DOM that has the au property correctly fullfilled. 

Is there another way of accessing the au element's property? Could be posible to add the au property when using containerless custom elements so other framework funcionality (child, children...) work as intented?

**Comment by bigopon** [comment]
I think it's hard to work around mutation observer, containerless elements and comments. If you don't wanna see the custom element wrapper, I suggest you to use `as-element`. Example:

Instead of:

```html
<!-- parent.html -->
<template>
  <child repeat.for="record of records"></child>
</template>
```

You can do

```html
<!-- parent.html -->
<template>
  <div as-element="child" repeat.for="record of records"></div>
</template>
```

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 solutionOffered()
 let response = await getResponseFromOP( { timeout : veryLong } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by EisenbergEffect** [comment]
I don't think we can fix this since with a containerless element, there really is no parent.
