### ISSUE TITLE
Potentially unhandled rejection [1] ReferenceError: childContainer is not defined

### ISSUE THREAD

**Issue by davismj** [aurelia/templating#6]
Issue occurs when using the <compose> element with only a view attribute, as follows:

```html
<compose view="views/start.html"></compose>
```

Stack trace from DevTools:
> Potentially unhandled rejection [1] ReferenceError: childContainer is not defined
>    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.8.4/system/composition-engine.js:147:47
>    at O (http://localhost:9000/jspm_packages/es6-module-loader.js:7:7462)
>    at K (http://localhost:9000/jspm_packages/es6-module-loader.js:7:7094)
>    at y.7.y.when (http://localhost:9000/jspm_packages/es6-module-loader.js:7:10248)
>    at v.7.v.run (http://localhost:9000/jspm_packages/es6-module-loader.js:7:9284)
>    at a.3.a._drain (http://localhost:9000/jspm_packages/es6-module-loader.js:7:1763)
>    at 3.a.drain (http://localhost:9000/jspm_packages/es6-module-loader.js:7:1417)
>    at MutationObserver.b (http://localhost:9000/jspm_packages/es6-module-loader.js:7:3325)

**Comment by EisenbergEffect** [comment]
Fixed in f87668da917b9fe2ddc0dfa944c29ae9fdd66a4a

**Comment by virenderkverma** [comment]
Any idea about "Potentially unhandled rejection [2] ReferenceError: Error loading "github:aurelia/bootstrapper@0.9.3" at " in safari. Application working fine on chrome and IE.

**Comment by davismj** [comment]
which version of safari? what operating system?

**Comment by virenderkverma** [comment]
Safari 5.1.7 (7534.57.2) , OS - Windows 8.1

**Comment by EisenbergEffect** [comment]
Safari on Windows hasn't been updated in years. It's not a supported browser.
