### ISSUE TITLE
Proposal: Include annotation that causes customElements to inherit from SVGElement

### ISSUE THREAD

**Issue by SeanWykes** [aurelia/templating#60]
*Problem:* Unable to create customElements that play well inside an SVG canvas.

*Example:* I created two components, `<x-canvas>` and `<x-node>`, each with their own template. The `<x-canvas>` has an `<svg> </svg>` pair, and instantiates multiple `<x-node>`s inside, using an Aurelia `repeat.for=` on a `<g>` tag.

Unfortunately, it would appear that SVG does not recognise custom elements that don't inherit from SVGElement. Thus the `<x-node>` tags and their contents are not displayed.

*Suggestion:* a new annotation `@svgElement` that, when used alongside `@customElement`, causes the new element to be registered with `extends: "SVGElement"` in the `options` parameter to `document.registerElement()`. 

BTW: I used  a `<g>` tag, since an inner `template` tag for the `repeat.for` raised a `RangeError: Maximum call stack size exceeded` during view compilation. This may be a bug, stack trace follows:

```
    at ViewCompiler.compile (http://localhost:8080/jspm/github/aurelia/templating@0.10.3/view-compiler.js:90:18)

    at ViewCompiler.compileElement (http://localhost:8080/jspm/github/aurelia/templating@0.10.3/view-compiler.js:159:34)

    at ViewCompiler.compileNode (http://localhost:8080/jspm/github/aurelia/templating@0.10.3/view-compiler.js:102:29)

    at ViewCompiler.compile(...)   etc  
```

**Comment by Aaike** [comment]
This could possible be fixed with this: https://github.com/aurelia/templating/issues/65

**Comment by EisenbergEffect** [comment]
Unfortunately, you can't really inherit from SVGElement unless you have native Web Components, which is the only way to get them to work at all inside of SVG. Unfortunately, even with native WC it doesn't work that great because you MUST inherit from a known SVG element in order for it to work and then you have to use the "is" designator, which is much less elegant.

I need to think about this much more because it's not pretty even with web components.

**Comment by slundberg** [comment]
I also ran into this issue trying to combine Aurelia with D3 (motivated by separation of concerns, where D3 never touches the DOM). The solution I ended up with was using `@containerless` with a template:
```html
<template>
  <svg>
    ...
  </svg>
</template>
```
 
When the component loads it strips the `<svg>` element to become part of the parent `<svg>` DOM:

```javascript
attached() {
    $(this.element.previousElementSibling.childNodes).unwrap();
}
```

This is my first week with Aurelia, so I may be missing something important. But it seems like this kind of functionality would be easy enough to add as a decorator if desired. The approach is working in the latest versions of Chrome, Firefox, and Safari for use cases such as:

```html
<series-xaxis series-xaxis.ref="xaxis" width="500" height="20"></series-xaxis><br>
<series-plot xaxis.bind="xaxis" width="500" height="100">
  <series data.bind="dataTrack1"></series>
  <series data.bind="dataTrack2"></series>
</series-plot>
```

**Comment by EisenbergEffect** [comment]
Intersted in sending a PR? Perhaps we should have a new decorator `customSVGElement` that will differentiate this use case? Is it only a matter of needing to add the code you have in attached plus the containerless option?

**Comment by slundberg** [comment]
- I'll need to look into custom decorators but depending on the time needed I could send a PR once I have a good feel for how it should be implemented.
- Would it be best for `customSVGElement` to add the `<svg>` into the template or assume it is present?
- Yes. Those are the only two things I changed in the `<series>` custom element.

**Comment by EisenbergEffect** [comment]
@slundberg Is there any reason why you have to have the svg tag in your template at all? Couldn't  you just put the svg children directly in the template and then add the containerless option?

**Comment by slundberg** [comment]
When I did that the children were not interpreted as "svg" tags by the
browser. Hence the need to wrap them in the template.

**Comment by EisenbergEffect** [comment]
Interesting...really interesting. Ok, let me keep thinking about this. We are introducing some new capabilities to compilation, etc soon. So, I'm revisiting this to see how we can make it work as seamelessly as possible.

**Comment by EisenbergEffect** [comment]
I think we've got this solved. Latest docs explain.

**Comment by Todberg** [comment]
What is the solution to this problem? @EisenbergEffect Where is this described?
