### ISSUE TITLE
Custom Element: Binding to id and for doesn't select the checkbox when the label is clicked

### ISSUE THREAD

**Issue by codedbypaul** [aurelia/templating#600]
**I'm submitting a bug report**

* **Library Version:**
aurelia-cli 0.31.3

**Please tell us about your environment:**
* **Operating System:**
CentOS 7

* **Node Version:**
6.2.1

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
Chrome 56

* **Language:**
ESNext

**Current behavior:**
I have a simple checkbox and label component. If I set `id` and `for` directly I can click the label to select the checkbox. However if I use binding with `id` and `for`, the values are set correctly but the browser doesn't see them as being linked. If you inspect the input's properties the labels array is empty.

**Expected/desired behavior:**

* **What is the expected behavior?**
That the checkbox would be selected when clicking on the label.

* **What is the motivation / use case for changing the behavior?**
So I can bind a different value for the id for each checkbox component.

**Comment by Alexander-Taran** [comment]
Can you create a gist.run to reproduce the issue?
for me it works
https://gist.run/?id=974bda5669a029fa7965701c6d1ad92d

**Comment by codedbypaul** [comment]
Sorry should have added this is inside a custom element.

I.e `<my-radio id="foo"></my-radio>`

[Gist here](https://gist.run/?id=5c3730c981b2000a400e4f6256be46c1)

**Comment by michaelbull** [comment]
This is not an issue with Aurelia. The issue is that you are setting two elements with the same ID, which is not valid HTML.

![example](https://i.imgur.com/0N3bmP3.png)

In the picture above you can see `<my-checkbox>` has an `id` attribute of `my-checkbox`, but so does the `<input>` inside of it.

The solution is to not use the name `id` as a `@bindable` attribute name.

Below are the fixed files:

### `my-checkbox.html`

```html
<template>
  <input type="checkbox" id.bind="id" />
  <label for.bind="id">${label}</label>
</template>
```

### `my-checkbox.js`

```js
import {bindable} from 'aurelia-framework';

export class MyCheckbox {
  @bindable label;
  @bindable labelId;
}
```

**Comment by Alexander-Taran** [comment]
can be closed then

**Comment by codedbypaul** [comment]
I see that `<my-checkbox id.bind="binding"></my-checkbox>` works too. I'll rename it to checkboxId for now as that's more descriptive.
