### ISSUE TITLE
[Feat. Req] Custom Element class

### ISSUE THREAD

**Issue by Aedaeum** [aurelia/templating#61]
In the view of a custom element, we currently put:
```html
<template>
    ...
</template>
```

The template element is embedded and replaced with the name of the view-model. Let's assume I have a custom element named `message` for example. The embedded object would look like the following:
```html
<message class='au-target'>
    ...
</message>
```

It would be nice if we could also apply a class directly on this embedded object. Currently we would have to `@inject(Element)` and programmatically add the class. It would be nice to have the much simpler and more logical convention as follows:

**View**
```html
<template class='message'>
    ...
</template>
```
**Embedded As**
```html
<message class='au-target message'>
    ...
</message>
```

**Comment by PWKad** [comment]
You can currently add the class or w/e in your main view -
```html
<message class="message"></message>
```
for now.  I know in my cases this has solved the issue but I definitely think there are strong uses for adding the class to the template itself so you can reduce what the `message` custom element actually needs to know about the `template`'s implementation.

**Comment by jdanyow** [comment]
@Aedaeum you can do as @PWKad suggested, especially if you need the class to be dynamic via data-binding.  If your goal is to target all instances of the `message` custom element, you do not need a css class, you can target the node type directly:

``` css
.message {
  text-decoration: blink;
}
```

becomes:

``` css
message {
  text-decoration: blink;
}
```

**Comment by PWKad** [comment]
Excellent point @jdanyow

**Comment by cmichaelgraham** [comment]
awesome !!

**Comment by Aedaeum** [comment]
The only issue with referencing the node is that it throws up an error in css that it's not valid. However, I didn't think about just assigning the class directly, thanks @PWKad

**Comment by EisenbergEffect** [comment]
There may be some value to this as a more generatl request to possible copy all template attributes over to the custom element itself during template compilation of containing views. For example, if you wanted to provide default aria roles, you would have to grab the element in JS code and add those, but we could change the compiler so that when an element is created it just copies all attributes off of the template element over to the custom element. This would naturally include any classes.

What do you all think?

**Comment by PWKad** [comment]
I think we should, I noticed this when wanting to have certain classes that they had to be on every instance instead of in the template when working with modals. :+1:

**Comment by Aaike** [comment]
i like it , have brought it up in the past actually :) good job @Aedaeum

**Comment by zewa666** [comment]
I'd definitely like to have that in as well :+1:

**Comment by Aedaeum** [comment]
Haha thanks @Aaike 
I'm loving that this can be useful in other scenarios :smile:

**Comment by EisenbergEffect** [comment]
There are a bunch of interesting scenarios now that I've though about this issue a bit. I think what we need is something a bit more flexible. Here's what I'm proposing. In your view template, you should be allowed to place attributes and bindings on the template element itself. At runtime, these bindings will be on the custom element, but bound to the element's view model. So, the template element is like a stand-in for the custom element itself and the bindings on template are in the same binding scope as the rest of the template's bindings. This allows setting static properties, but also binding classes and aria attributes to the state of the element itself. Here's an example of a theoretical progress bar's template:

```html
<template aria-role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow.bind="percent">
  <div class="bar-container">
    <div class="bar" css="width: ${percent}%"></div>
  </div>
</template>
```

What do you all think of this?

**Comment by csaloio1** [comment]
@EisenbergEffect Yes, that's exactly what I would like to see. It would reduce the amount of code and DOM manipulation inside of many custom elements.

**Comment by forest** [comment]
:+1:

**Comment by Aedaeum** [comment]
Excellent :)
