### ISSUE TITLE
useShadowDOM decorator not working

### ISSUE THREAD

**Issue by olanod** [aurelia/templating#62]
I have a custom element class and I want it to render with shadowDOM
```
@customElement('my-element')
@useShadowDOM
export class MyElement {
}
```
The rendered element should have a shadowRoot but it doesn't.  
##### Curious facts
```
@customElement('my-element')
@useShadowDOM
export class MyElement {
    static beforeCompile(template) {
        console.log(this) // an object with property 'targetShadowDOM: false' when before decorator was true
    }
}
```
Adding a break-point in the decorator's code 
```
function useShadowDOM(target) {
    var deco = function deco(target) {
        var resource = Metadata.on(target).firstOrAdd(HtmlBehaviorResource);
        // resource has usesShadowDOM: false
        resource.useShadowDOM = true;  // note the name is different
    };

    return target ? deco(target) : deco;
}
```

**Comment by jdanyow** [comment]
@Aaike ^^^

**Comment by Aaike** [comment]
thank you , was about to start an issue for this lol :+1:

**Comment by jdanyow** [comment]
additional troubleshooting details- thanks @olanod  + @Aaike  :

[April 23 2015 12:42 PM](https://gitter.im/Aurelia/Discuss?at=553920ff1c7f609d3d25872a)

**Comment by olanod** [comment]
As I mentioned [here](https://gitter.im/Aurelia/Discuss?at=553921c9dcf9be9c3da28bff) I think the `Metadata.on(target).firstOrAdd(HtmlBehaviorResource)` doesn't return the instance of the resource it should return. Having changed `resource.useShadowDOM = true;` to `resource.usesShadowDOM = true;` when I add a breakpoint in the `html-behavior.js#create` method, `this.usesShadowDOM` is still false which means the decorator didn't change the right instance.

**Comment by Aaike** [comment]
i have applied the fix this morning , it still doesn't seem to work for me.
As a confirmation, when i use `@useShadowDOM` i am supposed to see a `#shadow-root` in the DOM without manually creating one right ?

**Comment by EisenbergEffect** [comment]
You are. I will investigate further.

**Comment by zewa666** [comment]
Well the shadow-root is created, but new elements aren't attached to it.

**Comment by Aaike** [comment]
Right... i finally i understand my issue with this.
It was simply not working when using in combination with `@noView`...
I know it is easy enough to create manually when using that.
But i guess i just expected it would create an empty shadow root for me in that case, but it only does that for custom elements that have an html template...
Most of my custom elements that i am creating are ones without an html actually... so i guess i was confused about that...

**Comment by EisenbergEffect** [comment]
@Aaike How can we make this more intuitive? How should we change this? Thoughts?

**Comment by Aaike** [comment]
i have a comment [here](https://github.com/aurelia/templating/pull/42#issuecomment-96451711) that kind-off ties into this issue.

i think the @useView should create the empty shadow root for me.
that would at least confirm that the @useShadowDOM is working and did something.

if not it should throw an error or a warning saying that `useShadowDOM` cannot be used in combination with `noView`

But i do think allowing it to be used in combination with `noView` makes sense, it would helpful used in combination with a @useStyle as noted in the other issue.

**Comment by Aaike** [comment]
a solution for the `noView` and `useShadowDOM` use case can now be tracked here : https://github.com/aurelia/templating/issues/66

**Comment by schernichkov** [comment]
`useShadowDOM `directive still does not create shadow root. Could anybody explain what current purpose of it?

**Comment by EisenbergEffect** [comment]
There isn't any browser that supports Shadow DOM v1 yet. It will start working once the browsers release their implementations.

**Comment by PaulHMason** [comment]
Will there be no polyfill or "shady dom" support, like Polymer (mainly for IE11)?
