### ISSUE TITLE
ViewResources and generated .d.ts file does not implement `valueConverters` property

### ISSUE THREAD

**Issue by PWKad** [aurelia/templating#627]
**I'm submitting a bug report**

* **Library Version:**
1.7.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
8.9.3

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
all

* **Language:**
TypeScript 2.3

**Current behavior:**

When using `aurelia.resources.valueConverters` as identified in this blog post - https://aurelia.io/blog/2017/03/17/combining-value-converters-with-i18n-in-aurelia/ - client reported that `valueConverters` property was not defined in the build, however the property exists (it is hydrated in the constructor)

**Expected/desired behavior:**

If the property is part of the public API it should be added to the Type definition.

* **What is the motivation / use case for changing the behavior?**

To not have to use `aurelia.resources['valueConverters']` in a TypeScript project

**Comment by bigopon** [comment]
That's interesting doc, and we probably need to fix it. This is the public API part for it https://github.com/aurelia/templating/blob/master/src/view-resources.js#L481-L483 and it should be used that way as it works with `ViewResources` hierarchy too.

**Comment by bigopon** [comment]
ping @zewa666 @EisenbergEffect for i18n doc fix

**Comment by zewa666** [comment]
Im not sure this is even part of the official docs. I think it was only part of the linked blog post

**Comment by PWKad** [comment]
Ah perfect thanks!
