### ISSUE TITLE
Updating aurelia-templating to 1.8.0-rc.1 results in error during startup

### ISSUE THREAD

**Issue by jmezach** [aurelia/templating#629]
**I'm submitting a bug report**

* **Library Version:**
1.8.0-rc.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.5

* **Node Version:**
8.11.2

* **NPM Version:**
5.10.0 (same with 6.1.0)

* **JSPM OR Webpack AND Version**
webpack 3.12.0

* **Browser:**
Chrome 67

* **Language:**
TypeScript 2.8.1

**Current behavior:**
Updating only aurelia-templating to version 1.8.0-rc.1 results in the following error when starting our application:

```
bluebird.js:5256 Error: Unable to find module with ID: aurelia-templating-router/router-view.html
    at WebpackLoader.<anonymous> (aurelia-loader-webpack.js:197)
    at step (aurelia-loader-webpack.js:41)
    at Object.next (aurelia-loader-webpack.js:22)
    at aurelia-loader-webpack.js:16
    at Promise._execute (bluebird.js:971)
    at Promise._resolveFromExecutor (bluebird.js:3249)
    at new Promise (bluebird.js:2845)
    at webpackJsonp../node_modules/aurelia-loader-webpack/dist/native-modules/aurelia-loader-webpack.js.__awaiter (aurelia-loader-webpack.js:12)
    at WebpackLoader.webpackJsonp../node_modules/aurelia-loader-webpack/dist/native-modules/aurelia-loader-webpack.js.WebpackLoader._import (aurelia-loader-webpack.js:162)
    at WebpackLoader.<anonymous> (aurelia-loader-webpack.js:262)
    at step (aurelia-loader-webpack.js:41)
    at Object.next (aurelia-loader-webpack.js:22)
    at aurelia-loader-webpack.js:16
    at Promise._execute (bluebird.js:971)
    at Promise._resolveFromExecutor (bluebird.js:3249)
    at new Promise (bluebird.js:2845)
```

**Expected/desired behavior:**

Our application starts normally without an error.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
I'm trying to figure out if a change made in this new version solves a problem we're seeing, but I'm unable to verify this due to the error above. Since this is a released version of the package I was expecting it would just work.

I have also tried updating other aurelia packages to their latest versions, but that doesn't help. Removing package-lock.json, node_modules and all of that doesn't help either.

**Comment by doktordirk** [comment]
yeah, i never understood why they don't use peerDepebdecies to avoid such issues. anyways, meanwhile use yarn and add to your package.json

```js
  "dependencies": {
    "aurelia-binding": "^2.1.0",
    "aurelia-bootstrapper": "^2.2.0",
    "aurelia-framework": "^1.3.0-rc.2",
    ...
  },
  "resolutions": {
    "**/aurelia-framework": "^1.3.0-rc.2",
    "**/aurelia-templating": "^1.8.0-rc.1",
    "**/aurelia-binding": "^2.1.0"
  },
``

**Comment by EisenbergEffect** [comment]
@doktordirk We'd be welcome to PRs to improve how the packages are configured to make these scenarios work better. Once upon a time (quite some time ago now) when we originally set this stuff up...I'm not even sure if NPM supported peer dependencies....and I don't think we anticipated the challenges at that time. Since then, we just haven't changed much in the package configuration. We're certainly open to improvements, esp. from community members that have experienced the downsides of the current configuration and can make recommendations to smooth that out.

**Comment by jmezach** [comment]
After reading [this](https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/) I think I tend to agree with @doktordirk and it would probably solve this issue. Having two distinct versions of the same package at runtime usually breaks stuff.

I have also since verified that [this fix](https://github.com/aurelia/templating/commit/b4abe6e) solves my original problem. We are currently seeing a memory leak in our application that is solved by this.

Unfortunately we can't currently upgrade due to this issue. Is there anything we can do to get this fixed short term? I don't really want to switch to yarn right now, since that will have quite some impact on my team.

**Comment by doktordirk** [comment]
@jmezach switching to yarn is zero effort. anyways, npm shrinkwrap also should do the job

**Comment by jmezach** [comment]
@doktordirk While I agree that it's not that much of an effort, it is a lot of effort if you have a team that suddenly need to use yet another tool. Additionally we'll need to do some modifications to our build pipeline as well.

Not sure how npm shrinkwrap will help us though. I just tried running it, but as far as I can tell it doesn't solve our problem. It only renames the package-lock.json with npm-shrinkwrap.json, but I still have duplicate packages.

**Comment by doktordirk** [comment]
@EisenbergEffect 
The issue here comes from the users need to use a release candidate. -rc and -beta are not in the normal version range and are quiet rightly only included if the parent package also is rc or beta. Using peerDependencies actually wouldn't change that. I don't know anything which would make mixing rc and non rc modules easier for the users on your side. Using yarn (as above) or shrinkwrap-lock.json (as bellow, much more work) seems to be the way to go

 @jmezach 
to make it work you'd have to edit it. 

of the aurelia module entries: (for aurelia-templating 1.8.0-rc.1. same would need to be done for other RCs)
* replace all `"aurelia-templating": "1.7.0"` with  ` "aurelia-templating": "1.8.0-rc.1"` (of the requires field)
* remove all `dependencies` entries
* make sure to publish your shrinkwrap-lock.json 
* in case of a previous installation, delete all aurelia folders in node_modules (not needed for remote builds as they start clean anyways)
* run `npm i `

**Comment by doktordirk** [comment]
good question. a quick view  only did show https://github.com/aurelia/templating/commit/e7da973. however, given the title (aurelialess aurelia) it sounds like it's needed for the new features of the blog today(?), in which case it certainly would need to drop the -rc tag.  that was a quick view only, however.

**Comment by doktordirk** [comment]
@EisenbergEffect I did some forking and testing with peerDependencies. while eg aurelia-path, aurelia-route-recognizer are side effect free and could remain direct dependencies. my guess is, that it'll be easier for future fixes to have modules like that included as well and also easier for users to use their own forks if so desired. 

So, some structure could be following, with only two core modules having dependencies and everything else using peerDependencies.  

aurelia-boostrapper:
```
    "dependencies": {
      "aurelia-event-aggregator": "^1.0.0",
      "aurelia-framework": "^1.0.0",
      "aurelia-history": "^1.1.0",
      "aurelia-history-browser": "^1.1.0",
      "aurelia-loader-default": "^1.0.0",
      "aurelia-logging-console": "^1.0.0",
      "aurelia-pal-browser": "^1.1.0",
      "aurelia-polyfills": "^1.0.0",
      "aurelia-router": "^1.5.0",
      "aurelia-templating-binding": "^1.0.0",
      "aurelia-templating-resources": "^1.0.0",
      "aurelia-templating-router": "^1.0.0",
      "aurelia-route-recognizer": "^1.0.0"
    },
```

aurelia-framework:
```
    "dependencies": {
      "aurelia-binding": "^1.0.0  | ^2.0.0",
      "aurelia-dependency-injection": "^1.0.0",
      "aurelia-loader": "^1.0.0",
      "aurelia-logging": "^1.0.0",
      "aurelia-metadata": "^1.0.0",
      "aurelia-pal": "^1.0.0",
      "aurelia-path": "^1.0.0",
      "aurelia-task-queue": "^1.0.0",
      "aurelia-templating": "^1.0.0",
      "aurelia-task-queue": "^1.0.0"
    },

**Comment by bigopon** [comment]
@jmezach @doktordirk I think the main issues described have been resolved, and it feels safe to close this to me. If you have any other issues related to this, please reopen/ open another.
