### ISSUE TITLE
Possible bug of premature `automate` call in `CompositionEngine._createControllerAndSwap`

### ISSUE THREAD

**Issue by bigopon** [aurelia/templating#632]
https://github.com/aurelia/templating/blob/90087a0dd4af40a6305ebd3810a40e39b8c362ed/src/composition-engine.js#L110-L118

@EisenbergEffect while chasing this issue, that appears recently, (https://discourse.aurelia.io/t/using-require-breaks-router/1411/17), I noticed that it's always calling `automate` before `waitForCompositionComplete()`, which could potentially be wrong. Should it be like the following: moving `automate` inside promise and right before calling `_swap`

```js
    return this.createController(context).then(controller => {

      if (context.compositionTransactionOwnershipToken) {
        return context
          .compositionTransactionOwnershipToken
          .waitForCompositionComplete()
          .then(() => {
            controller.automate(context.overrideContext, context.owningView);
            return this._swap(context, controller.view);
          })
          .then(() => controller);
      }

      controller.automate(context.overrideContext, context.owningView);
      return this._swap(context, controller.view).then(() => controller);
    });
```

cc @huochunpeng

**Comment by huochunpeng** [comment]
Did it solve the weird timing bug with bluebird?

BTW, I think you can dry it to
```js
return this.createController(context).then(controller => {
      if (context.compositionTransactionOwnershipToken) {
        return context
          .compositionTransactionOwnershipToken
          .waitForCompositionComplete();
      }
}).then(() => {
      controller.automate(context.overrideContext, context.owningView);
      return this._swap(context, controller.view);
}).then(() => controller);
```

**Comment by bigopon** [comment]
Yes, you can solve bluebird bug with following patch

```js

import { CompositionEngine } from 'aurelia-templating';

CompositionEngine.prototype._createControllerAndSwap = function(context) {
    return this.createController(context).then(controller => {
      if (context.compositionTransactionOwnershipToken) {
        return context
          .compositionTransactionOwnershipToken
          .waitForCompositionComplete();
      }
    }).then(() => {
      controller.automate(context.overrideContext, context.owningView);
      return this._swap(context, controller.view);
    }).then(() => controller);
  }
```

**Comment by huochunpeng** [comment]
Any update on this fix?
More people are affected by this nasty bug.

https://stackoverflow.com/questions/51348676/aurelia-nav-bar-not-showing-up-any-more

**Comment by EisenbergEffect** [comment]
@bigopon Do we have a PR for the suggested fix? We could merge that and get it out Monday or Tuesday. I've got another bug fix in binding that's planned to go out then too. Let me know.

**Comment by bigopon** [comment]
@EisenbergEffect I can create a PR from the snippet above. We will have 2 choices:

1. Keep the old behavior of repeat, by reverting my old PR https://github.com/aurelia/templating-resources/pull/349
2. Apply the above fix, keep the repeat fix.

1 will solve no bug, but it will bring back the long "stable" behavior
2 will solve both bugs, but i'm not certain what this fix implies for existing applications. It seems to have been like that since the start https://github.com/aurelia/templating/commit/b8e51df0c2d94254172eca53b66031a37664bc91#diff-4bfd9a6641ba63793471805ad54f3324

**Comment by huochunpeng** [comment]
To me,
Option 2 is needed anyway to normalise native/bluebird promises, there might be more edge cases if not fixed.
Option 1 is for future. After @fkleuver implemented changeQueue in vNext, all rendering will be processed when model is not mutating. aurelia/templating-resources#349 will be unnecessary by the time.

**Comment by fkleuver** [comment]
@huochunpeng Yeah about that, the concept I had in mind is starting to manifest itself in an almost complete rewrite of `binding` as well as a large amount of small changes in `templating`.

The changes are too fundamental for a "quick backport" and our current test coverage isn't nearly high enough to confidently release something like that. It would probably have to come in the form of a "backwards-compatible version of vNext". I don't see it happening in this code base.

**Comment by davismj** [comment]
@bigopon Did @huochunpeng 's version fix the issue as well?

**Comment by bigopon** [comment]
@davismj What version is it ?

**Comment by EisenbergEffect** [comment]
@bigopon I can't think of a reason why waiting to call `automate` until after the transaction is complete would be a problem. Can you submit a PR for this change? I can get it merged and released today or tomorrow.

**Comment by bigopon** [comment]
K, i'll push it up soon.
