### ISSUE TITLE
<template> without custom attributes is rendered incorrectly

### ISSUE THREAD

**Issue by rmja** [aurelia/templating#634]
**I'm submitting a bug report**

* **Library Version:**
1.8.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.2.1

* **NPM Version:**
6.1.0

* **JSPM OR Webpack AND Version**
webpack 3

* **Browser:**
all

* **Language:**
all

**Current behavior:**
The following renders correctly, being that the `template` is removed such that all the `li`s are children of the `ul`:

```
<template>
    <ul>
        <li>An item</li>
        <template if.bind="backingProperty">
            <li class="divider"></li>
            <li>A conditional item</li>
        </template>
    </ul>
</template>
```

However, if the condition on `template` is removed such that we have the similar example:

```
<template>
    <ul>
        <li>An item</li>
        <template>
            <li class="divider"></li>
            <li>A conditional item</li>
        </template>
    </ul>
</template>
```

Then the resulting dom becomes:

![image](https://user-images.githubusercontent.com/2112306/42831087-b29ac748-89ed-11e8-9ee7-f76d3731f828.png)

**Expected/desired behavior:**

* **What is the expected behavior?**
The expected behaviour is that the `li`s would be children of the `ul` in both cases.

* **What is the motivation / use case for changing the behavior?**

**Comment by StrahilKazlachev** [comment]
Can you provide a use case? I find the current behaviour quite correct.

**Comment by rmja** [comment]
I dont have a particular use case, I found it by accident and thought that
the behaviour was strange.

tir. 17. jul. 2018 21.34 skrev StrahilKazlachev <notifications@github.com>:

**Comment by bigopon** [comment]
This is the expected behavior. What `if` custom attribute does is "turning" `<template/>` into a view factory, which later will be rendered without the `<template/>` element. Without the `if` custom attribute, it's just a normal element like any other element, any Aurelia doesn't do anything with it.

**Comment by rmja** [comment]
Ok, I will close since I don't have any particular need for this to actually work:-) Thanks for clarifying.
