### ISSUE TITLE
@bindable with default value of {} fails to bind properly

### ISSUE THREAD

**Issue by mbroadst** [aurelia/templating#64]
See code [here](http://plnkr.co/edit/Fe9kUyrd7VZVJYZuMlN6).

In this example, the "my-element-form" custom component has an attribute called "mydata" which is bound to an object that looks like:

```javascript
{
  one: { value: "test1" },
  two: { value: "test2" }
}
```

When the attribute definition omits a default value, this works fine and you can see that the list to the right lists two entries "one" and "two" respectively. When the attribute definition specifies ```@bindable mydata = {}``` the list is always empty.

**Comment by EisenbergEffect** [comment]
I think we've got this fixed now in master. Will push out an update this evening.
