### ISSUE TITLE
HTMLBehavior Pipeline Hooks

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating#65]
It would be nice if we can hook into certain events in the HTMLBehavior pipelines to allow custom behaviors to be created.

One use case could be to create some new decorators for handling various scenarios  for working with css, [example proposal here](https://github.com/aaike/aurelia-css)

I think a hook for the `analyze`, `load` , and `create` phases of the html-behaviours should do it, perhaps there is also some hooks needed in the composition engine.

The hooks could be used for various other cases in the future.

**Comment by EisenbergEffect** [comment]
In brief, here's the idea I am toying with:

* **view generation hooks** - Implement a new type of view resource which can be registered with `resources.registerViewGenerationHooks()`. The resource is a class with any of the following methods, which hook into view compilation and instantiation `beforeCompile(template, resources)`, `afterCompile(viewFactory)`, `beforeCreate(viewFactory)` and `afterCreate(view)`. These hooks can be imported like any other view resource, using the `require` element. They can also be globalized, meaning the hooks would apply to *all* views. It might be possible to also let these be configured through decorators on the class. There are a couple of important scenarios this enables:
	* Some css frameworks need their behaviors activated programmatically when dynamic DOM is created. This would allow a global hook to make that work seamlessly across all views.
	* This would make it easy to provide scoped styles. We could use a view resource like this:
	`<require from="./my-element.css!scoped"></require>`. The "scoped" loader plugin could load the css file dynamically (or get it from a bundled resource). It could then generate a view hook resource dynamically for the styles. The view hook could then use the `beforeCompile` step to inject a `style` tag into the template with the css content. This would set up properly scoped styles for shadow dom. A more advanced version could possibly detect shadow dom presence, and if not present it could alter the css classes to simulate scoping. Note that all this would happen only one time as part of the compilation of the custom element's template. This also solves an additional problem with scoped styles in general...that of re-use. The resource would be cached by normalized id and would thus serve as a way to share scoped styles across shadow dom boundaries. Note that this also gives us a well-known usage pattern for per-view css and would enable us to handle bundling automatically. It could also be implemented as a plugin. We could similarly allow global css through a loader plugin. Basically this lets us write es6 loader plugins that can return classes that interact with the resource loading pipeline as well as the view compilation and creation lifecycle.

**Comment by EisenbergEffect** [comment]
@Zoltu @Aaike Please see above.

**Comment by Zoltu** [comment]
It sounds like it handles my desired use-case, which is styles inside of shadow-dom and/or scoped styles.

**Comment by Aaike** [comment]
it sounds like some very good solutions , seems like a lot of areas are covered by this , very nice

**Comment by EisenbergEffect** [comment]
Going out in tomorrow's release we now have support for css via the require element. So, from a view, you can do this:

```
<template>
  <require from="./my-styles.css"></require>

  ...
</template>
```

That will ensure that the styles are loaded as part of the view load process. It uses the module loader's text plugin so that the css can also be bundled. When used in this way the css will be added to the head of the document. You can also do this though:

```
<template>
  <require from="./my-styles.css" as="scoped"></require>

  ...
</template>
```

In this case, if the element is rendering to ShadowDOM, the styles will be injected into the ShadowDOM root. If the component is not using ShadowDOM, the styles will be injected into the custom html element's view and the `scoped` attribute will be applied to the style element.

**Comment by omidkrad** [comment]
This is great, but why not have styles scoped by default? Also what are the other options for the `as` attribute?

**Comment by EisenbergEffect** [comment]
There aren't any other options for "as". If you can think of other scenarios, let me know. I wasn't confident that making scoped styles the default was a good idea when it's not really natively supported across all browsers.

**Comment by omidkrad** [comment]
I didn't know there was such a limited browser support for the [scoped](http://caniuse.com/#feat=style-scoped) attribute. It's still only supported in FireFox. Can we polyfill this with something like the [jQuery Scoped CSS plugin](https://github.com/thingsinjars/jQuery-Scoped-CSS-plugin)?

I also like how stylesheets encapsulation is done in [GWT UiBinder](http://www.gwtproject.org/doc/latest/DevGuideUiBinder.html#Hello_Stylish_World) that will also allow programmatic access to styles. I think it can give some inspiration for Aurelia.
