### ISSUE TITLE
Custom element creation is confusing

### ISSUE THREAD

**Issue by code-chris** [aurelia/templating#674]
**I'm submitting a bug report**

* **Library Version:**
1.10.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.15.3

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
webpack 4.27.0

* **Browser:**
Chrome 77

* **Language:**
TypeScript 3.1.2

**Current behavior:**
I created a repro for our problem:
https://github.com/code-chris/aurelia-templating-issue

We define child-views as custom-elements (without CustomElement suffix or annotation). In all of our applications this works as expected (using with <require> tag or global registration).

Our current problem is, that the child-views are not initialized correctly (shown in the repro with the CommentItem and SolutionItem views.)
In the repro this only works with the customElement-Attribute. In one of our projects where this issue appears now, it works correctly if the Attribute is located on the SolutionItem, the DefaultItem seems not to need this...
I also had the issue that both item-views have switched their VM-Implementation if the Attribute were not set. So The SolutionItem.html was bound against the DefaultItem.ts and the other way round...

**Expected/desired behavior:**
It works as normal without the need of custom elements

**Comment by bigopon** [comment]
With a very quick glance at the code, I'm guessing you miss a metadata-generating decorator in derived classes. This is a requirement for bindable - inheritance. Could you please help try and confirm it?

**Comment by bigopon** [comment]
What i meant is: in either `CommentItem` or `SolutionItem`, decorate it with `@bindable`, or `@customElement`, just one is enough, so it has the right metadata. This is a legacy issue that we traverse to the root metadata holding class definition, because there was no intention to support inheritance at first. We can fix it, but the potential breakage is unknown.

**Comment by bigopon** [comment]
Yes
```ts
class A {} // no issue
class B extends A {} // using class A metadata without its own metadata holder
class C extends A { @bindable c } // using class C metadata
```

**Comment by code-chris** [comment]
okay, thanks for your quick response.
Then I think we can close this issue. It was only a bit weird 😃
