### ISSUE TITLE
Upgrading electron caused <compose> to hide other parts of UI

### ISSUE THREAD

**Issue by anthonyborell** [aurelia/templating#689]
### I'm submitting a bug report

**Library Version:**
aurelia-templating 1.10.3

### Please tell us about your environment:

**Operating System:**
Windows 10 1903

**Node Version:**
12.13.0

**NPM Version:**
6.12.0

**Webpack Version**
4.38.0

**Browser:**
Electron 7.3.3
Chromium 78.0.3904.130

**Language:**
TypeScript 3.5.3

### Current behavior:

After upgrading my Electron app from 3.0.2 to 7.3.3, pages/views which have`<compose>` elements hide other parts of the UI. 

Originally I thought this might of been a CSS issue, however the pages with the `<compose>` elements on them are the only ones affected. No code was changed besides upgrading electron.

How the UI should look: toolbar, sidebar, content
![image](https://user-images.githubusercontent.com/4422171/94651182-635e2480-033b-11eb-9aa1-399d30d3d3e2.png)

The page with the `<compose>` element hides the toolbar
![image](https://user-images.githubusercontent.com/4422171/94651149-55a89f00-033b-11eb-9403-2e5c356d32b6.png)

Setting the container of the `<compose>` element to `display: none;`
![image](https://user-images.githubusercontent.com/4422171/94651253-85f03d80-033b-11eb-992b-37d05002adde.png)

Toolbar is visible again:
![image](https://user-images.githubusercontent.com/4422171/94651305-9dc7c180-033b-11eb-87d3-4e20840b8130.png)

### Expected/desired behavior:

`<compose>` elements work as they previous did, but I'm not entirely sure it's a `<compose>` issue.

### Solution

I solved it by changing

```ts
<compose view-model="./xyz"></compose>
```

to this

```ts
<div as-element="compose" view-model="./xyz"></div>
```

**Comment by bigopon** [comment]
@anthonyborell can you help paste some template html here? and the final rendered html as well? It's quite hard to guess what is rendered and what's not based on just a few lines of html

**Comment by anthonyborell** [comment]
@bigopon The vagueness was due to this being propitiatory software. However I will do my best to help you as much as I can. I am going to try and recreate the bug outside of the code base.

**Comment by anthonyborell** [comment]
Upon further investigation, the problem isn't related to `<compose>`. Between Electron 3.0.2 and 7.3.3, the behaviour of CSS overflow has changed. There also seems to be issues with Chromium's implementation of flexbox and overflow since v72
The reason it only affected the pages with the `<compose>` elements were because those pages had content that exceeded the containers height.

**Comment by bigopon** [comment]
I remember having these issues in one of my apps as well, and it was painful to resolve. Thanks for the updates.
