### ISSUE TITLE
can't bind value in child VM to top level setter

### ISSUE THREAD

**Issue by mbroadst** [aurelia/templating#69]
I'm pretty sure the title of this issue could use some work, but the problem is expressed in this [plunkr](http://plnkr.co/edit/Fe9kUyrd7VZVJYZuMlN6). 

Basically, I have two elements: my-element, and my-other-element. my-other-element is a widget which provides a text box that modifies a single @bindable "myotherattr". my-element contains a my-other-element, and binds its local setter "something" to my-other-element's "myotherattr", and then below that displays the context of "myattr". Something simply sets the value of "myattr".

I understand this seems very contrived, but I believe it should be expected to work? My expectation was that a letters were typed into the text box, they would show up in the "Value" display.

**Comment by EisenbergEffect** [comment]
@mbroadst You have two issues. First, you either need to declare that `myotherattr` has a default binding mode of twoWay by default, or you need to use the .two-way binding on it in html. The other issue is that your string interpolation binding is incorrect. It should be `${myattr}`
