### ISSUE TITLE
In aurelia template, it shows "Cannot read properties of null (reading 'insertBefore')" error.

### ISSUE THREAD

**Issue by leonidpaslavskyi** [aurelia/templating#709]
**I'm submitting a bug report**

* **Library Version:**
1.10.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
14.17.4

* **NPM Version:**
6.14.14

* **JSPM OR Webpack AND Version**
webpack 4.44.2

* **Browser:**
Chrome 106.0.5249.119

* **Language:**
TypeScript 4.0.3 | ESNext

**Current behavior:**
In aurelia template, I used multiple if.bind expressions for view elements. If I switches the condition value, it shows "Cannot read properties of null (reading 'insertBefore')" error like following:
![image](https://user-images.githubusercontent.com/102751559/198190161-fefb5479-8d8d-45cf-9c5c-64c1f75c34c4.png)

![image](https://user-images.githubusercontent.com/102751559/198190327-891299a0-a909-4fe7-ba88-a65b5a0f37c9.png)

**Expected/desired behavior:**

* **What is the expected behavior?**
Is should be processed without above error.

* **What is the motivation / use case for changing the behavior?**

**Comment by bigopon** [comment]
Please follow the main discussion at https://github.com/aurelia/framework/issues/1003
Linked issue in the html spec change that causes this https://github.com/whatwg/dom/pull/819

**Comment by jded76** [comment]
@bigopon are you sure it's the same thing? The issue here says Chrome and doesn't mention Safari 16+ anywhere.

**Comment by bigopon** [comment]
Thanks @jded76 , I looked too quick and only saw `insertBefore ... null`.
@leonidpaslavskyi sorry for closing too quickly, can you provide a repro?
