### ISSUE TITLE
A method to get the markup for a template

### ISSUE THREAD

**Issue by csaloio1** [aurelia/templating#72]
In angular there is a $templateCache service that can be used to request the markup for a specific template:
```
var markup = $templateCache.get(templateName);
```
Is there a way to accomplish the same thing for a view in Aurelia? If not could this be added? I have some situations where I wish to read some data- attributes from a view prior to in being rendered in the DOM.

**Comment by csaloio1** [comment]
I think I see now that this can be done via the DefaultLoader.

**Comment by zewa666** [comment]
@csaloio1 It would be a big help for others if you could provide a gist or even better an example repo, otherwise those questions might appear again

**Comment by csaloio1** [comment]
Here's an example of how I think it might be accomplished. Not sure if this is the *correct* way though
https://gist.github.com/csaloio1/b9a13c882937319a0f37
