### ISSUE TITLE
@bindable's defaultBindingMode property don't work.

### ISSUE THREAD

**Issue by andrevlins** [aurelia/templating#73]
If you specify a default binding mode in `@bindable` decorator It will not be used when you bind you attribute throught `.bind`.

```html
<my-custom-element  my-attribute.bind="foo"></my-custom-element>
```

if my-attribute is defined as 
```javascript
@bindable({ name: 'myAttribute', attribute: 'my-attribute', defaultBindingMode: TWO_WAY})
```

foo will not be updated.... but if you use:
```html
<my-custom-element  my-attribute.two-way="foo"></my-custom-element>
```

then foo will be updated as expected.

I'll make a repro on top of skeleton-nav later...

**Comment by jods4** [comment]
The syntax has changed, now it's `defaultBindingMode: bindingMode.twoWay` but it is still not working...

**Comment by andrevlins** [comment]
@jods4 you have to import `import {bindingMode} from 'aurelia-framework';`

**Comment by jods4** [comment]
I know and I did (I am using TypeScript so that would have been an error otherwise). Does it work for you now?

I have a customAttribute with bindable properties, like so:
```javascript
export class SomethingCustomAttribute {
  @bindable({ defaultBindingMode: bindingMode.twoWay })
  public x: string = null;
}
```

But when I use it so: `<input something='{ x.bind = yada }' />` yada does not update but when I use it like this: `<input something='{ x.two-way = yada }' />` it does.

**Comment by EisenbergEffect** [comment]
Ok, I think this is a confusion about how to use custom attributes. A simple custom attribute that wants two-way binding to be the default should be declared like this:

```javascript
@customAttribute('my-attr, bindingMide.twoWay)
export class MyAttr {
  valueChanged(newValue, oldValue) {
    //do stuff
  }
}
```

For simple attributes, you don't define the properties, the framework provides on automatically...and so the binding mode need to be declared on the class. You only declare it on properties if you have an attribute that maps to multiple properties (an options attr).

**Comment by jods4** [comment]
@EisenbergEffect I am not sure I understand fully.

As my example shows, I'm trying to have an options attribute. I only used `x` in the example, but of course I actually have a bunch of attributes.

Something more like this just an example, mind you:
`<input auto-complete='src.one-time: suggestions, selected.bind: value' />`

In this case `selected.bind` would not be two-way, even tough the field in the custom attribute is declared with `@bindable({ defaultBindingMode: bindingMode.twoWay }) selected;`.

**Comment by EisenbergEffect** [comment]
Ok, I may have misunderstood. I'll re-open this and investigate further.
