### ISSUE TITLE
Compile linked stylesheets of shadowDOM custom elements

### ISSUE THREAD

**Issue by olanod** [aurelia/templating#8]
When I have a `<link rel='stylesheet' href='...' />` inside a template of a custom element using shadowDOM I expect it to be fetched and in-lined inside the shadow root just like polymer does.

**Comment by EisenbergEffect** [comment]
That is a good idea.

**Comment by EisenbergEffect** [comment]
Can you show me the markup you want to write and then also show me what you want the output to be? I think I understand, but want to be sure.

**Comment by olanod** [comment]
Something like this:
```
<template>
    <link rel='stylesheet' href='...' />
    <h1>Hello World</h1>
</template>
```
And produces:
```
#shadow-root
    <style>
    ....
    </style>
    <h1>Hello World</h1>
```

**Comment by EisenbergEffect** [comment]
Gotcha. I think we can make that happen ;)

**Comment by Hendrixer** [comment]
:+1:

**Comment by yelvert** [comment]
Wonder if this could be automatically included, at least in Behaviors? Something like `Behavior.useStyle(optionalPath)`, and that loads and attaches the stylesheet, same as the template.

**Comment by EisenbergEffect** [comment]
The `require` element now supports this. You can import css files with require. if you want them to be scoped to the shadow dom, then you do it like this:

```
<require from="./my.css" as="scoped"></require>
```
