### ISSUE TITLE
Potentially unhandled rejection [1] t@http://localhost:9000/public/bundle-core.js:3:29910

### ISSUE THREAD

**Issue by changgvash** [aurelia/templating#83]
Potentially unhandled rejection [1] t@http://localhost:9000/public/bundle-core.js:3:29910
when calling subscribe() in constructor, for working with eventAggregator.

**Comment by EisenbergEffect** [comment]
Can you provide more information than this? I really can't determine anything from this. What is bundle-core.js? What does the code in your constructor look like?

**Comment by changgvash** [comment]
I got the solution thanks,
