### ISSUE TITLE
Add support for inheritance in custom elements.

### ISSUE THREAD

**Issue by donald-slagle** [aurelia/templating#84]
I have some custom elements for different types of modal windows, (delete confirmation, editor windows, etc..), that all share common code and have a common bindable property. All of the inherited code works except for the bindable property. The first modal that is loaded will be the only modal that is initialized for the lifetime of the app. Here is an example of my base class:
```javascript
import $ from 'jquery';
import {bindable} from 'aurelia-framework';

export class BaseModal {
	@bindable config;
	
	static inject = [Element];
	constructor(element) {
		this.element = $(element);
	}
	
	attached() {
		this.config.element = this.element.find('.modal');
	}
}
```

**Comment by xandervdm** [comment]
I'm working on a UI widget library and created a BaseField base class and then a TextBox VM + Template that extends BaseField which renders and works fine. 

I then created a Checkbox VM + Template that extends BaseField and that caused the TextBox to be incorrectly rendered as a Checkbox. 

Sounds like it could be related to the above?

**Comment by EisenbergEffect** [comment]
I don't think we're going to add this for now. I'm not sure it's a good idea. However, we have provided some options to use mixins to share behavior.
