### ISSUE TITLE
Dynamically specifying views for custom elements

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating#85]
I would like to be able to specify the view that will be used for my custom element through the templating.
for example:
```markup
<dialog view="foundation-modal.html"></dialog>
```

Or when not specified it would use a default setting which should be configurable through the plugin for the dialog
ie:
```
.plugin('my-dialog',config=>{
    config.view = "foundation-modal.html";
  })
```

At which point the dialog can be used without specifying a view for it every time.
```markup
<dialog></dialog>
```

The default view can normally be specified by the developer by using the `@useView` decorator.

But specifying it in the plugin would allow the user of my plugin to have control over the default view to be used.

The `<compose>` does something similar to all this but it wouldn't allow the user to specify a default view through plugin configuration.

another reason for not using `<compose>` is that is takes away the coolness of a custom element, which is letting a developer use it's custom tag in the code and specify options for it and add custom attributes to it.

consider something like :
```
<dialog view="foundation-modal.html" width.bind="width" some-custom-attribute="foo:bar"></dialog>
```

Another not unrelated issue is the ability to actually add `view` and `view-model` attributes to all elements used inside the custom elements markup.
consider something like this without having a bunch of compose tags in my markup and resulting DOM:

```
<dialog view="foundation-modal.html">
    <title class="special-title">Foo</title>
    <article view-model="welcome"></article>
    <footer view="dialog-footer.html"></footer>
</dialog>
```

Which would ideally keep the resulting tags/markup the same as it is above.
only the contents of the elements would be filled in.

Note that i'm actually using something similar to `ContentSelectors` to put the resulting contents of `title`, `article` and `footer` into the `foundation-modal.html` template into designated elements that have the `select` attribute.
I am deviating from the standard here by allowing any element to have the `select` attribute.
experimental implementation of that here : https://github.com/gooy/aurelia-dialog/blob/master/src/element-selectors.js

Below is an abstract example of the dynamic template that would be used with the dialog.

The contents and attributes of the original tags inside the `<dialog>` element
are applied to the elements in the dynamic template that have a matching `select` attribute.

```
<template>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header"><h4 class="modal-title" select="title"></h4></div>
        <div class="modal-body" select="article"></div>
        <div class="modal-footer" select="footer"></div>
      </div>
    </div>
</template>
```

A working example of all this can be seen here : http://gooy.github.io/aurelia-dialog/demo/#/demo

You would have to look at how the DOM of the dialogs look like before and after they are opened for the first time to see the effect i am describing.

One last reason for not using compose is i don't want the views or view models that will be used for the body of the dialogs (or even the template of the dialog) to be all preloaded when the page opens.
Those should only start loading when the dialog is opened for the first time.
and ideally it should be easy to show a loading indicator while the dynamic views are loading.

**Comment by Aaike** [comment]
A lot of the functionality used in the dialog custom element uses the experimental functions in my [aurelia-compiler](https://github.com/gooy/aurelia-compiler) repo.

The ability to swap views dynamically at at given moment for a view model is done with the [swapView](https://github.com/gooy/aurelia-compiler/blob/master/src/index.js#L27) method.

Which is used [here](https://github.com/gooy/aurelia-dialog/blob/master/src/dialog.js#L99) in the dialog.

That function also allows the dynamically loaded template to be transformed before it is compiled.
That is used in this case to allow the template and the dialogs inner markup to use the `self.` keyword in the templating to refer to the dialog's execution context rather than the one of the VM where the dialog is created.

Right after the template is ready [the dialog uses](https://github.com/gooy/aurelia-dialog/blob/master/src/dialog.js#L123) the [processBehavior](https://github.com/gooy/aurelia-compiler/blob/master/src/index.js#L94) function 
which basically creates a new ViewFactory and creates a new View from the new contents of the element and swaps it with the one in the current ViewSlot.

**Comment by jdanyow** [comment]
closing- @Aaike please re-open in the dialog plugin repo if further work is needed
