### ISSUE TITLE
Add base animator methods for integrating with JS based animators.

### ISSUE THREAD

**Issue by Aaike** [aurelia/templating#88]
A couple of functions should be added to the base animator to allow full use of JS based animators and some extra methods that make sense for CSS based animators as well.
```javascript
animate(element,className,options)
```

This can trigger a single event or callout like "bounce" or "shake".
For css animators this is a class that will be added to the element and removed right after the animation is done.
For JS based implementations the `className` is used as the `effectName` or as an object that specifies the properties to be animated.

```javascript
runSequence(sequence)
```

The sequence is an array of `effectNames` of `classNames` that represent animations to be animated with the `animate` method one after another.

```javascript
registerEffect(effectName,properties)
unregisterEffect(effectName)
```

Register and unregister an effect with the animator (for JS based animators)

**Comment by Aaike** [comment]
An implementation of a JS based animator using velocity can be seen here : https://github.com/gooy/aurelia-animator-velocity/

**Comment by zewa666** [comment]
@EisenbergEffect as mentioned in the PR issue, that one looks great and is ok to merge :+1: 
I'd also like to highlight @Aaike's implementation of the VelocityAnimator, very nice work and adds now even more flexibility to the Aurelia-EcoSystem. Great work !!!

**Comment by Aaike** [comment]
A basic implementation and demo for GSAP Animator can now be found at : https://github.com/gooy/aurelia-animator-greensock

**Comment by EisenbergEffect** [comment]
Sweet! I think a guest blog post is in order soon :)

**Comment by Aaike** [comment]
last and perhaps also least this time, the TinyAnimate Animator : https://github.com/gooy/aurelia-animator-tinyanimate

**Comment by EisenbergEffect** [comment]
Nice! Very nice work. Do you think you'll be able to address the browser issues that people in the gitter have discovered?

**Comment by Aaike** [comment]
thx ! Yes i have a pretty good idea on how to fix them ;)

However one of those issues is because of Aurelia i think, and that is when switching pages in IE11 : https://github.com/aurelia/templating/issues/86

**Comment by Aaike** [comment]
One more thing
when using the animator somewhere, one would have to import it like this:
`import {VelocityAnimator} from "blabla"`
or as
`import {CSSAnimator} from "blabla"`
and then inject it.

So you would have either `VelocityAnimator` or `CssAnimator` references in all your pages and VM's etc...
Which makes it not so easy to swap one with the other..

is there a way we can avoid declaring exactly what animator implementation to use in our VMs ?

I talked about it with @zewa666 and he suggested something like `Animator.getInstance` would be good to get the **current**' animator , whether that is `VelocityAnimator`, `GreensockAnimator`, `CssAnimator` or something else.

**Comment by shanonvl** [comment]
@Aaike, you could use `withSingleton` or `withInstance` to avoid this, assuming that `VelocityAnimator` and `CssAnimator` have a common parent class `Animator`:

In assuming plugin ( put the `.plugin(...)` before any animation dependencies ):
```
import {Animator, CssAnimator, VelocityAnimator} from '...';

export function configure(aurelia) {

   // set the default animator... 
   let animatorImpl;

   // do whatever logic you want to discern which animator you want to use
   // here animationType is 'velocity' | 'css' ...  
   switch(animationType) {
       case 'css':         
          animatorImpl = CssAnimator;
          break;
       case 'velocity':
          animatorImpl = VelocityAnimator;
          break;
       default: 
          throw new Error(`Unknown animator type: ${animatorType}`);
   }
   aurelia.withSingleton(Animator,animatorImpl);
}
```

Then in all view models, etc, you just inject the Animator and it will be the impl that you registered.

```
import 'Animator' from '..';

@inject(Animator)
export class Foo {
 ...
}
```

Or you can grab it from the container directly:

```
import 'Animator' from '..';
import 'Container' from 'aurelia-framework';

@inject(Container)
export class Foo {

   constructor(container) {
       this.animator = container.get(Animator);
   }
}
```

**Comment by shanonvl** [comment]
>I talked about it with @zewa666 and he suggested something like Animator.getInstance would be good to get the current animator , whether that is VelocityAnimator, GreensockAnimator, CssAnimator or something else.

I'd personally recommend using the above method/DI vs. a static accessor/factory pattern.  

The `withSingleton` and `withInstance` provides a nice way to swap out the impl w/out any dependent objects knowing/caring while also keeping things idiomatic:  you want an animator?  Just inject `Animator` like you inject everything else and move along...

**Comment by zewa666** [comment]
There are multiple problems related to that. First of all the Animator is Opt-in as it's delivered as custom plugin. This is one of the reasons having BaseAnimator as a placeholder. Another one is that by making the concrete Animators inherit from Animator we'd introduce another JSPM dependency for the plugin which is not really necessary.

Your proposed solution is ok but looks like a lot of work, so instead of having to all of that why not simply expose one simple method returning right instance of the concrete implementation? Ultimately there isn't also a lot difference between that method and the second approach with the container you've shown.

**Comment by shanonvl** [comment]
Thanks for the reply; I read through some of the code since last post... 

>This is one of the reasons having BaseAnimator as a placeholder.

Just to clarify, you're referring to Animator from aurelia-templating right?  I can't find  BaseAnimator?

>Another one is that by making the concrete Animators inherit from Animator we'd introduce another JSPM dependency for the plugin which is not really necessary.

The animate-css plugin is already dependent on `aurelia-templating`'s Animator; since these are, in fact, Animator impls doesn't it make sense for them to extend it ?

>Your proposed solution is ok but looks like a lot of work, so instead of having to all of that why not simply expose one simple method returning right instance of the concrete implementation? Ultimately there isn't also a lot difference between that method and the second approach with the container you've shown.

Sure you can expose a property to get the *right* instance... I was mainly focused on the process for *wiring* the right instance.

**Comment by EisenbergEffect** [comment]
You can already simply inject `Animator`. Assuming your animation plugin uses the proper animation configuration mechanism anyone asking for `Animator` from the DI should get the concrete version. Here's what the plugin configure function looks like from the CssAnimator:

```
export function configure(aurelia){
  Animator.configureDefault(aurelia.container, new CssAnimator());
}
```

The concrete version does not need to inherit from `Animator`.

**Comment by shanonvl** [comment]
Thanks for clarification @EisenbergEffect.  My apologies, I was confused about the architecture...
