### ISSUE TITLE
Add pre-compile hook to custom elements 

### ISSUE THREAD

**Issue by olanod** [aurelia/templating#9]
Custom elements(or behaviors in general?) should have a `preCompile` hook that gives them access to the raw template element before it is compiled.  
E.g.
```
import style form './super-button.css!text';

export class SuperButtonCustomElement {
    ...
    beforeCompile(template) {
        var styleSheet = document.createElement('style');
        styleSheet.appendChild(document.createTextNode(style));
        template.content.appendChild(styleSheet);
        // return template;  // necessary?
    }
}
```

**Comment by EisenbergEffect** [comment]
Can this be a one time thing? In other words, alter template once, then it is uses for all instances of the element?

**Comment by olanod** [comment]
Yes I think that would be fine, something like the compile function in angular directives where you alter the template before it gets linked and repeated.

**Comment by EisenbergEffect** [comment]
I think this would be a static function on the class. Since we run compilation before any instances are ever created. So, something like this:

```javascript
import style form './super-button.css!text';

export class SuperButtonCustomElement {
    static beforeCompile(template) {
        var styleSheet = document.createElement('style');
        styleSheet.appendChild(document.createTextNode(style));
        template.content.appendChild(styleSheet);
        return template;
    }
}
```

Thoughts?

**Comment by EisenbergEffect** [comment]
Implemented as above. You now have a `static beforeCompile(template)` hook you can add to a custom element.

**Comment by EisenbergEffect** [comment]
FYI. I think we're going to have to change this. Mainly, I think we will need to change the name of the callback method. Basically, we want to support a `compile` callback hook on all behaviors that happens during compilation. So, this is the per-view compilation hook that gets called when you use a behavior in a view. The hook above is the one-time callback when you are about to compile a custom element's template. The name might still work....but need to think about it. Maybe `compilingTemplate` instead? Feedback is welcome.
