### ISSUE TITLE
View lifecycle hook naming

### ISSUE THREAD

**Issue by heikkilamarko** [aurelia/templating#91]
About the detached() lifecycle hook. The documentation says it is invoked when the view that contains the extension is detached from the DOM. Is the view still part of the DOM when detached() is invoked? If it is, detaching() might be a better name for the hook.

**Comment by EisenbergEffect** [comment]
It is fired after it is removed from the DOM. We have selected this naming based on the Web Components spec. I agree that it would be nice to have a detaching callback as well perhaps, but we want to stick with the WC callbacks as a basis for our behaviors at the moment.
