### ISSUE TITLE
doing something when a custom element bindable property changes

### ISSUE THREAD

**Issue by lukeapage** [aurelia/templating#93]
Sorry if I am missing something obvious.. I am using code mirror in a aurelia app and am wrapping the functionality. Getting binding from code mirror to the element works fine...

```
@customElement("cmeditor")
export class cmeditor {
  @bindable readonly;
  @bindable value;

  attached() {
    console.log(this.value);
    const codeMirror = CodeMirror.fromTextArea(this.cmTextarea, {
      lineNumbers: true,
      matchBrackets : true,
      mode: "text/x-less",
      theme: "cobalt",
      readOnly: this.readonly
    });
    codeMirror.on('change', (codeMirror, changeObj) => {
      const newValue = codeMirror.getValue();
      if (newValue !== this.value) {
        this.value = newValue;
      }
    });
  }
}
```

However now I need to bind the other way - I tried making a setter for `value`, but that is what `@bindable value'` does.. So how do I run some code when `this.value` changes (and the change is coming from outside the element).

It seems like a pretty normal use-case for someone adapting from an existing event based component into an aurelia custom element?

**Comment by EisenbergEffect** [comment]
You can add a method to your class called `valueChanged(newValue, oldValue)` and that will run any time the value property changes. Is that what you are asking?

**Comment by lukeapage** [comment]
Thanks,  i can work with that.

**Comment by gregoryagu** [comment]
To expand a little bit on Rob's answer, if you add a `<bindablePropertyName>Changed(newValue,oldValue)` to a view-model, Aurelia will call the method every time the value changes.

So if your bindable property name is "selectedDate", then add a `selectedDateChanged(newValue, oldValue)` to your viewmodel and it will automatically get called by the framework.

**Comment by kurtjmeyoung** [comment]
hello, i would like to expand this question a little bit further. in my case i got a customElement with a bindable property "propertyInCustomElement". Also, I got a "propertyInCustomElementChanged" in the corresponding customElement view-model, which is correctly fired everytime i change the value of the custom element.

in the view in which the customElement is used, the bindable property "propertyInCustomElement" is two-way bound to a second bindable property "propertyInViewModel". In the corresponding view-model I also got a "propertyInViewModelChanged" method, but this method is never called.

Is there a way of doing this? Executing some code outside of an custom element, whenever a property in the custom element has changed?

**Comment by EisenbergEffect** [comment]
We will need to see your full source sample to see if you've got it all set up correctly.

**Comment by kurtjmeyoung** [comment]
customElement view:
```html
<template>
     <select value.two-way="propertyInCustomElement">
         <option if.bind="placeholder != null" model.bind="null"></option>
         <option repeat.for="option of options" value="${option.value}">${option.text}</option>
     </select>
</template>
```


customElement view-model:
```typescript
@customElement('customElement')
export class CustomElement {

    @bindable
    public propertyInCustomElement: any;

    public attached(): void {
        $("#" + this.name).select2().on("change", event => {
            this.selected = (<HTMLInputElement>event.currentTarget).value;
        });
    }

    public detached(): void {
        $("#" + this.name).select2('destroy');
    }

    //following method works as expected
    public propertyInCustomElementChanged(newValue: string): void {
        console.log(newValue);
    }
}
```
view where the custom element is used:
```html
<template>
  <customElement propertyInCustomElement.two-way="propertyInViewModel" options.bind="options"></customElement>
</template>
```

view-model:
```typescript
export class ViewModel {

    @bindable
    public language: string;

    public options: {value: string, text: string}[] = [];

    // following method is never called
    public languageChanged(newValue: string): void {
        console.log(newValue);
    }
}
```

**Comment by atsu85** [comment]
@kurtjmeyoung, I've helped @axwalker to document several observer/communication patterns [here](https://github.com/axwalker/aurelia-observer-patterns/wiki/Observer-patterns-in-Aurelia) - You might find the answer to Your question with exact code examples :)

**Comment by atsu85** [comment]
This 
> `propertyInCustomElement.two-way="propertyInViewModel"`

should probably be replaced with
`property-in-custom-element.two-way="propertyInViewModel"`

**Comment by EisenbergEffect** [comment]
Good catch!
@kurtjmeyoung HTML is case agnostic (and usually erases case info) so all bindables become attributes with their names "kebab cased" (lower cased and hyphenated)

**Comment by kurtjmeyoung** [comment]
i updated the source to shorter property names

**Comment by kurtjmeyoung** [comment]
thanks, for the responses so far, great tips! any further advices?

**Comment by AWoelfel** [comment]
i'm experiencing a similar problem in the moment using aurelia-binding (1.0.0-beta.1.3.0)
in detail: i do not get any "changeHandler" notifications of bound custom-element properties this property is bound to the value of an input control.

my custom element 
-ts
```typescript
@customElement('custom')
export class Custom {
    @bindable
    public value: string = "";

    @bindable
    public testValue: string = "";

    public valueChanged(newValue: string, oldValue: string): void {
        console.log(`inner custom element ${oldValue} => ${newValue}`);
        this.testValue = newValue;
    }
}
```

-html
```html
<template>
    <input type="text" value.two-way="value"/>
</template>
```


usage of custom element:
-ts 
```typescript
    @bindable
    public inputValue: string;

    @bindable
    public delegatedValue: string;
    
    public inputValueChanged(newValue: string, oldValue: string): void {
        console.log(`outer custom element (direct) ${oldValue} => ${newValue}`);
    }

    public delegatedValueChanged(newValue: string, oldValue: string): void {
        console.log(`outer custom element (delegated) ${oldValue} => ${newValue}`);
    }
```

-html
```html
<template>
    <custom test-value.two-way="delegatedValue"></custom>
</template>
```


when i start typing inside the displayed input control it get this console output : 
```
inner custom element  => d
outer custom element (delegated) undefined => d
inner custom element d => dd
outer custom element (delegated) d => dd
inner custom element dd => ddd
outer custom element (delegated) dd => ddd
inner custom element ddd => ddd2
outer custom element (delegated) ddd => ddd2
```
where i would expect 
```
inner custom element  => d
outer custom element (direct) undefined => d
outer custom element (delegated) undefined => d
inner custom element d => dd
outer custom element (direct) d => dd
outer custom element (delegated) d => dd
inner custom element dd => ddd
outer custom element (direct) dd => ddd
outer custom element (delegated) dd => ddd
inner custom element ddd => ddd2
outer custom element (direct) ddd => ddd2
outer custom element (delegated) ddd => ddd2
```

it is worth mentioning that the code of "usage of custom element:" itself is within another custom element. 


thanks in advance
Alex

**Comment by EisenbergEffect** [comment]
Try using `bindable()` with the parents. I *think* this may be a quirk of TypeScript. Let me know.

**Comment by atsu85** [comment]
@EisenbergEffect, I haven't found a case where the parens after `@bindable` would make anything work better with TypeScript (there are some other decorators tough where this matters), so I don't think it will make anything better, but maybe I'm wrong.

**Comment by eliranmal** [comment]
@atsu85 have you tried adding an `@observable` decorator to the property? (the brute force approach)

**Comment by atsu85** [comment]
@eliranmal, did I understand You correctly, that Your comment was a reply to this:
> I've helped @axwalker to document several observer/communication patterns [here](https://github.com/axwalker/aurelia-observer-patterns/wiki/Observer-patterns-in-Aurelia)

and You suggested documenting another observer pattern [here](https://github.com/axwalker/aurelia-observer-patterns/wiki/Observer-patterns-in-Aurelia)? If so, I guess @axwalker will gladly accept a PR :)

**Comment by ERobishaw** [comment]
It appears that @bindable and @observable do not invoke propertyChanged when it is a lambda expression.  I.e.,  the following will not get invoked:
```
   namechanged = (oldval,newval)=>{
       //this does not get called
   }
   
```

**Comment by reeddunkle** [comment]
If all I want to do is access the new property value, is there a reason to use the `newVal` parameter passed into the method over accessing the property directly?

e.g.

```
@bindable name;

nameChanged() {
  console.log(this.name);
}
```

vs.

```
@bindable name;

nameChanged(newValue) {
  console.log(newValue);
}
```

**Comment by EisenbergEffect** [comment]
You can use either.

**Comment by PoDaC** [comment]
@EisenbergEffect there is a way to capture changes for two bindable properties in a single method? using the upper example:  
@bindable
    public inputValue: string;

    @bindable
    public delegatedValue: string;

    public inputValueDelegatedValueChanged(){Do Something}
Thank you

**Comment by StrahilKazlachev** [comment]
@PoDaC 
```
bindable({changeHandler: 'nameOfChangeHandler'})
```
But you'll get only the values again, no property name. So if differentiating is important you'll have to manage only by the value type.
You can check the signature of `@bindable` in the *Hub*.

**Comment by PoDaC** [comment]
@StrahilKazlachev behaviour is exactly as you described and in my case will not work due to differentiation. Anyway I learned something new, which is great. Thank you!

**Comment by Malexion** [comment]
@EisenbergEffect Are we able to modify the bindable change before it is set with getter/setter? Or do setters/getters not play well with @bindable()? Like so:
```javascript
@bindable()
get myprop() {...}
set myprop(value) {...}
```
