### ISSUE TITLE
custom element delegate custom event

### ISSUE THREAD

**Issue by jus101** [aurelia/templating#94]
After I upgraded to 0.12, I noticed that delegation of custom events dispatched from my custom elements no longer worked. Changing to to trigger works.

E.g. app.html
```
<widget start.delegate="widgetStart()" stop.trigger="widgetStop()" />
```

app.js
```
widgetStart() {
 console.log("Widget start");
}

widgetStop() {
 console.log("Widget stop");
}
```

widget.html
```
<template>
  <button click.delegate="start()">Start</button>
  <button click.delegate="stop()">Stop</button>
</template>
```

widget.js
```
start() {
  let e = new CustomEvent('start');
  this.element.dispatchEvent(e);
}

stop() {
  let e = new CustomEvent('stop');
  this.element.dispatchEvent(e);
}
```

In this contrived example, clicking the widget start does nothing, but clicking widget stop works fine.

**Comment by maxgrv** [comment]
We have the same problem with latest release..

**Comment by elitecoder74** [comment]
Same problem here. Any movement on this issue?

**Comment by EisenbergEffect** [comment]
Are you all using shadow DOM for your custom elements? If so, does it work correctly in Firefox or IE?

**Comment by elitecoder74** [comment]
Yes my custom elements are in shadow DOM.  Both delegate and call do not work.   I believe my last test showed everything works correctly in the light DOM.  I've only tested with Chrome.  I will test I.E. and Firefox this evening.

**Comment by EisenbergEffect** [comment]
Ok, I understand the problem then.

**Comment by maxgrv** [comment]
We are not using shadow DOM, and we are having the issue on Chrome. We did not test it in other browser though.

**Comment by maxgrv** [comment]
Trigger works fine for us.

**Comment by elitecoder74** [comment]
Trigger, also, works in shadow DOM.

**Comment by derekpitt** [comment]
any word on this? this is an issue for us as well!

**Comment by EisenbergEffect** [comment]
The good news is that I understand the problem and believe I have a solution. It relates to shadow dom boundaries. I hope to get a fix out by tomorrow.

**Comment by maxgrv** [comment]
But we are having the issue without Shadow DOM actually...

**Comment by EisenbergEffect** [comment]
@maxgrv I'm going to need more information on that. (The fix I have in mind might fix you as well, but I don't know for sure because I don't know how to reproduce your scenario...whatever that is.)

**Comment by maxgrv** [comment]
Ok we will try with the fix, this is not a very serious issue for us as we can use trigger for now.

**Comment by maxgrv** [comment]
In case this fix does not work, we can try to pull together a repro based on the navigation skeleton.

**Comment by derekpitt** [comment]
@maxgrv do you have a cancelBubble or stopPropagation anywhere in the dom chain?

**Comment by shanonvl** [comment]
Hi all -- I just hit the same thing where trigger worked and delegate did not.   Reading into the [Event API](https://developer.mozilla.org/en-US/docs/Web/API/Event/Event), I noticed this:  
```
 event = new Event(typeArg, eventInit);
```
and that the `eventInit` map has a `bubbles` property:

> "bubbles", optional and defaulting to false, of type Boolean, indicating if the event bubbles or not.

After changing my code as follows, I'm able to use delegate successfully:
```
let e = new CustomEvent('hidden', {
  bubbles: true
});
this.element.dispatchEvent(e);
```

Not sure if you've tried this already ?

**Comment by derekpitt** [comment]
my issue was a cancelBubble that I had forgot that I had in there... We hadn't updated aurelia in a while and when they fixed direct/delegate binding in https://github.com/aurelia/binding/commit/11e364936b4726f34bf15268a112fc62d154b920 our code "broke", but it turns out that we had it wrong this whole time :)

**Comment by EisenbergEffect** [comment]
I've just pushed a fix that introduces the concept of DOMBoundary into the component model. This is used to properly scope delegated event handlers and with this fix, I am seeing the correct behavior for delegated events from within the shadow dom. The release will be out later this week.

**Comment by maxgrv** [comment]
@shanonvl Thanks, it was the missing ```bubbles: true```.

**Comment by tonypee** [comment]
It seems that we still need to use bubbles: true - is this desired? Was quite confusing for quite a while
